### ISSUE TITLE
When using AsyncIOScheduler in version 3.11, decorators cannot be used.

### ISSUE THREAD

**Issue by SaucePlum** [agronholm/apscheduler#1003]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.11

### What happened?

When using AsyncIOScheduler in version 3.11, decorators cannot be used.
error message:runtimeerror  event loop is closed

<img width="737" alt="b2bcb272e8a89401d1c1e9b3410fa30" src="https://github.com/user-attachments/assets/66dc0a0d-da64-4bfa-a481-08e3107821b0" />

### How can we reproduce the bug?

file1.py
<img width="737" alt="b2bcb272e8a89401d1c1e9b3410fa30" src="https://github.com/user-attachments/assets/f36b02e2-03ab-4440-8e15-f8179db44613" />
file2.py
![image](https://github.com/user-attachments/assets/6c6f19df-01fb-40e7-9706-d48b12931d57)

**Comment by agronholm** [comment]
Please provide a minimal working example that demonstrates the issue. I'm not going to type the code from a screenshot.

**Comment by SaucePlum** [comment]
> Please provide a minimal working example that demonstrates the issue. I'm not going to type the code from a screenshot.

I don't think changing `get_event_loop` to `get_running_loop` can fix the problem that `AsyncIOScheduler` inadvertently creates an invalid event loop when starting up, which makes the scheduler not work at all.

**Comment by agronholm** [comment]
That change makes sure the scheduler does not create an event loop, period. Again, please provide a minimal working example so I can look at the issue.

**Comment by SaucePlum** [comment]
> That change makes sure the scheduler does not create an event loop, period. Again, please provide a minimal working example so I can look at the issue.

# -*- coding: utf-8 -*-
import asyncio

from apscheduler.schedulers.asyncio import AsyncIOScheduler

scheduler = AsyncIOScheduler()
async def start_scheduler():
    print(111)
    scheduler.start()

asyncio.run(start_scheduler())


@scheduler.scheduled_job(
    "cron",
    hour=1,
    minute=30,
    id="group_vip_equity",
    next_run_time = "2024-12-19 17:10:00"
)
async def test():
    print("test")
while True:
    pass

**Comment by SaucePlum** [comment]
> That change makes sure the scheduler does not create an event loop, period. Again, please provide a minimal working example so I can look at the issue.

`
# -*- coding: utf-8 -*-
import asyncio

from apscheduler.schedulers.asyncio import AsyncIOScheduler

# 启动调度任务
scheduler = AsyncIOScheduler()
async def start_scheduler():
    print(111)
    scheduler.start()

asyncio.run(start_scheduler())


@scheduler.scheduled_job(
    "cron",
    hour=1,
    minute=30,
    id="group_vip_equity",
    next_run_time = "2024-12-19 17:10:00"
)
async def test():
    print("test")
while True:
    pass
`

**Comment by agronholm** [comment]
You're trying to add a job after you've closed the event loop. The asyncio scheduler can't work without a running event loop.

**Comment by SaucePlum** [comment]
> That change makes sure the scheduler does not create an event loop, period. Again, please provide a minimal working example so I can look at the issue.

This change actually has a change to the interface, which belongs to breaking chang, which will cause an error in the schedule_job decorator that took effect in the past.

**Comment by agronholm** [comment]
Your example doesn't even work on the previous release.

**Comment by SaucePlum** [comment]
> Your example doesn't even work on the previous release.

```
# -*- coding: utf-8 -*-
import asyncio

from apscheduler.schedulers.asyncio import AsyncIOScheduler

# 启动调度任务
scheduler = AsyncIOScheduler()

async def start_scheduler():
    scheduler.start()



@scheduler.scheduled_job(
    "cron", hour=1, minute=30, id="test", next_run_time="2024-12-19 18:07:00"
)
async def test():
    print("test")


asyncio.run(start_scheduler())


while True:
    pass


```
The above example cannot be scheduled either.

**Comment by agronholm** [comment]
Even though you get no error from this on 3.10.4, it doesn't actually run either, for the reason I mentioned above. You need a running event loop in order to make the scheduler actually work. This is the reason I made this change: to explicitly fail when you're using the scheduler wrong.

**Comment by agronholm** [comment]
The following example works as expected:
```py
import asyncio

from apscheduler.schedulers.asyncio import AsyncIOScheduler

scheduler = AsyncIOScheduler()


@scheduler.scheduled_job("cron", second="*")
async def test():
    print("test")


async def main():
    scheduler.start()
    await asyncio.sleep(float("inf"))

asyncio.run(main())
```

**Comment by SaucePlum** [comment]
> The following example works as expected:
> 
> ```python
> import asyncio
> 
> from apscheduler.schedulers.asyncio import AsyncIOScheduler
> 
> scheduler = AsyncIOScheduler()
> 
> 
> @scheduler.scheduled_job("cron", second="*")
> async def test():
>     print("test")
> 
> 
> async def main():
>     scheduler.start()
>     await asyncio.sleep(float("inf"))
> 
> asyncio.run(main())
> ```

  Thanks for the help, I should use `asyncio.get_event_loop().create_task (...)` to run
