### ISSUE TITLE
Skipped executions should be events

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#112]
Originally reported by: **Łukasz Jernaś (Bitbucket: [deejay1](http://bitbucket.org/deejay1), GitHub: [deejay1](http://github.com/deejay1))**

----------------------------------------

When the scheduler skips execution of a job because of the maximum number of running instances it should generate an event, so it can be reacted upon (for example for monitoring)

----------------------------------------
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/112

**Comment by backbord** [comment]
+1

**Comment by agronholm** [comment]
Implemented in bb67d0899d235479b32450315a683b42af435f73.
