### ISSUE TITLE
Feature request: Job is submitted to executor --> event

### ISSUE THREAD

**Issue by backbord** [agronholm/apscheduler#117]
I would like to be informed via an event as soon as a job is submitted to an executor.

**Comment by agronholm** [comment]
What's the use case?

**Comment by backbord** [comment]
My use case is that I have a (currently rough and tiny) web interface where I show for each job
- successful runs with scheduled run times (and how long each took)
- failed runs with scheduled run times (and how long each took)
An event like "EVENT_JOB_STARTED" (or "EVENT_JOB_SUBMITTED") allows to show
- active runs with scheduled run times (and how long each is running)

**Comment by agronholm** [comment]
Implemented in bb67d0899d235479b32450315a683b42af435f73.
