### ISSUE TITLE
'tuple' object has no attribute 'public' in __init__ 

### ISSUE THREAD

**Issue by ajain352** [agronholm/apscheduler#123]
As i can see the commit which added this piece of code in constructor was added just 3 days back. So I am just curious if its a bug or I am doing something wrong here ?
Trace:
      2 parsed_version = __import__('pkg_resources').get_distribution('APScheduler').parsed_version
----> 3 version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
      4 version = parsed_version.base_version
      5 release = __version__ = parsed_version.public

AttributeError: 'tuple' object has no attribute 'public'

**Comment by backbord** [comment]
Hi, for me this caused problems too, when I was using setuptools 18.x.y.
With a current version of setuptools (20.6.7), it works fine.

**Comment by agronholm** [comment]
Damnit, I had no idea this would break on older setuptools.

**Comment by agronholm** [comment]
@ajain352 what exact version of setuptools are you using? What about you @backbord ? I couldn't reproduce this even with setuptools 9.1.

**Comment by backbord** [comment]
Hi, I've had the same exact problem as ajain352 with setuptools 0.9.1 and 18.3.2.

**Comment by agronholm** [comment]
I just installed setuptools 18.3.2 and "import apscheduler" works fine. Please verify.

**Comment by backbord** [comment]
Oops. Wrong branch. 18.3.2 worked fine. 0.9.1 didn't work. 20.6.7 works. Haven't tried versions other than those.

**Comment by wowkin2** [comment]
The same problem (Windows 7 x64, Python 3.4.3, APScheduler 3.1.0):
`Traceback (most recent call last):
  File "....../main.py", line 10, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "............\venv\lib\site-packages\apscheduler\__init__.py", line 3, in <module>
    version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
AttributeError: 'tuple' object has no attribute 'public'`

**Comment by agronholm** [comment]
Not sure why you're commenting this in a closed issue. A fix has been made and will appear in the next release that will be out soon.

**Comment by agronholm** [comment]
Meanwhile upgrade your setuptools manually and it will work fine.

**Comment by agronholm** [comment]
An alternative fix has been committed which does not require setuptools to be upgraded.

**Comment by kalman770** [comment]
I have the same problem too when I execute isyhelper.py in Python 2.7.9 shell using Raspian (Jesse) for OS
I get:
Traceback (most recent call last):
  File "/home/pi/isyhelper/ISYHelper/isyhelper.py", line 24, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/__init__.py", line 3, in <module>
    version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
AttributeError: 'tuple' object has no attribute 'public'.
How do I update Setuptools to version (20.6.7), I am a newbie.

**Comment by agronholm** [comment]
pip install -U --user setuptools
