### ISSUE TITLE
'tuple' object has no attribute 'public'

### ISSUE THREAD

**Issue by paviro** [agronholm/apscheduler#124]

**Comment by paviro** [comment]
Sorry did not see there way already a closed issue with this. But shouldn't it be fixed then?

**Comment by agronholm** [comment]
Indeed. Are you sure you're getting this with a new setuptools? If so, can you give me instructions to reproduce it?

**Comment by paviro** [comment]
I completely uninstalled apscheduler with `pip` and the reinstalled it. I tried updating `setup tools` with `pip` as well but it did not help.

**Comment by agronholm** [comment]
So starting from creating a new virtualenv, please describe the steps to reproduce this problem.

**Comment by paviro** [comment]
I do not use a virtualenv.

**Comment by agronholm** [comment]
Please run this script with apscheduler installed:
```python
print(__import__('setuptools').__version__)
import apscheduler
```
And tell me what comes out.

**Comment by paviro** [comment]
`5.5.1`

**Comment by agronholm** [comment]
You told me you were using setuptools 20.6.7, not 5.5.1.

**Comment by paviro** [comment]
Thought so, sorry my bad...
```
Installing collected packages: setup tools
  Found existing installation: setup tools 5.5.1
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed setup tools
```
Overlooked the `Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS` part... Thanks for your amazing library!

**Comment by agronholm** [comment]
The fix I committed was to require setuptools >= 11 in setup.py. To install the development version you need to install with `pip install git+https://github.com/agronholm/apscheduler.git`. That is, before I make a new release.

**Comment by agronholm** [comment]
Also, I hope you're installing with the --user option so as not to mess up your system libraries.

**Comment by paviro** [comment]
Yeah sorry... Looks like I was a bit stupid.

**Comment by agronholm** [comment]
Don't worry about it, it happens to everyone :)

**Comment by paviro** [comment]
:)
