### ISSUE TITLE
Schdulers across processes

### ISSUE THREAD

**Issue by sum12** [agronholm/apscheduler#129]
This is more of a behaviour question. If there are multiple processes(A and B) each running a scheduler  with `sqlalchemy` based job store using the same database. And an `interval`(-trigger) based job is submitted to only scheduler from ProcessA. Will the scheduler from a ProcessB be able to schedule its execution to its own executor?

My understanding after digging the code:
If scheduler from ProcessB `wakesup` (for any reason) only then it will be able to schedule it. 

This seems more like a race condition (?)

**Comment by agronholm** [comment]
APScheduler does not support redundant schedulers or sharing of job stores. This will lead to problems. Instead, both processes should communicate with a single scheduler process using RPC or HTTP or a similar mechanism. APScheduler 4.0 *may* get support for redundant schedulers, but that's not certain.

In the future, only post bug reports and feature requests here. The Google group, the IRC channel (#apscheduler) and StackOverflow are the proper channels for asking questions, as indicated in the documentation.
