### ISSUE TITLE
3.1.0 no longer works with centos7

### ISSUE THREAD

**Issue by pabelanger** [agronholm/apscheduler#130]
After 3.1.0, native support for centos7 has been dropped.  Since the minimal version of setuptools shipped in packages is: 

python-setuptools.noarch                0.9.8-4.el7                    @base    

File "/usr/lib/python2.7/site-packages/apscheduler/__init__.py", line 3, in <module>
  version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
AttributeError: 'tuple' object has no attribute 'public'

Please consider reverting 72181ef732c6b4b5f493f4374057b1f663277ea3

**Comment by pabelanger** [comment]
I recommend using PBR: https://github.com/openstack-dev/pbr

It is very easy to use, and provides the functionality you are looking for.

**Comment by agronholm** [comment]
PBR does a lot of things I don't want. I'll find another way to provide this information in the top level package until I can remove it altogether.

**Comment by agronholm** [comment]
Just to be sure: are you a CentOS packager? The only plausible reason for working around this (instead of upgrading setuptools) is if APScheduler is packaged with rpm.

**Comment by pabelanger** [comment]
Yes: https://admin.fedoraproject.org/pkgdb/package/rpms/python-APScheduler/

I haven't upgrade to 3.1.0 yet, as I only noticed the new release just now testing nodepool on centos7.

**Comment by agronholm** [comment]
I will be releasing 3.2.0 soon due to a compatibility problem with FlexGet. FlexGet uses APScheduler in ways it was not intended to be used, though the mistake was understandable. The new API additions will cover their use case and I have a PR ready to launch when I'm done with the release.

Expect 3.2.0 this weekend. I will revert the problematic version info change as well.

**Comment by pabelanger** [comment]
Great, thanks for helping out!
