### ISSUE TITLE
pyinstaller fails to ship apscheduler

### ISSUE THREAD

**Issue by janscas** [agronholm/apscheduler#131]
When using pyinstaller to distribute an application it fails to add apscheduler.

It raises a DistributionNotFound error.

I have checked all the posibilites and it seems that the apscheduler code is making some "on the run imports" and therefore pyinstaller does not found the packages it needs to integrate.

However the pyinstaller distribution package can be made succesfully using a "hook file" (https://pythonhosted.org/PyInstaller/#understanding-pyinstaller-hooks) but I can't found the tweaks I need to do inside the hook to let pyinstaller know which imports are needed and where to find them...

I have tested this running python 2.7 on windows 7.

Can anyone help?

![error](https://cloud.githubusercontent.com/assets/7224106/14739908/141200b8-088b-11e6-97f0-a9f1061d98d6.png)

**Comment by janscas** [comment]
I've been able to skip this error by changing the __init__.py file and simply setting "version='3.1.0'.

Now the exe is generated without errors but when executed it raises LookupError: No trigger by the name "interval" was found.

It has something to do with the imports done by pyinstaller because when working with the .py program it works like a charm.

![error2](https://cloud.githubusercontent.com/assets/7224106/14741196/deba83b8-0894-11e6-81a0-836c0bd16cbf.png)

**Comment by janscas** [comment]
I've found the solution for this problem here:

https://groups.google.com/forum/#!searchin/apscheduler/lookuperror/apscheduler/OR3MSBHwd8Q/0BzP3xpuGmAJ

The solutions consists on importint the trigger and setup directly.

from apscheduler.triggers.interval import IntervalTrigger

trigger = IntervalTrigger(hours=24, start_date=start_date)

**Comment by jainmehul** [comment]
Hi, I am having the same issue, as the first one. which init.py did you modify?

**Comment by janscas** [comment]
Just modify the appscheduler/__init__.py

and set it to:

```
version_info = (3, 1, 0)
version = '3.1.0'
release = '3.1.0'
```

**Comment by thebeancounter** [comment]
still not working

**Comment by agronholm** [comment]
@thebeancounter Have you tried the workaround proposed by janscas?

**Comment by iamliamc** [comment]
This issue is still pertinent. 

 I'll mention if the workaround still works with: 
APScheduler==3.6.3
pyinstaller==4.5.1

Python >= 3.9

On Debian 9/10 armv7l architecture BeagleBone/RasberyPi

Shortly...!

**Comment by agronholm** [comment]
It might be a good idea to open a separate ticket for this.
