### ISSUE TITLE
EVENT_JOB_BEFORE_REMOVE callback feature needed

### ISSUE THREAD

**Issue by saadqc** [agronholm/apscheduler#138]
Hi,
Currently there is no way to apply filter on apscheduler get jobs method. So, i am trying to implement
my own logic and for that there is a need of EVENT_JOB_BEFORE_REMOVE method.

Regards,
Saad

**Comment by agronholm** [comment]
Please elaborate. What is this filter for and why do you need this event?

**Comment by saadqc** [comment]
See the situation is i have multiple users who can schedule multiple jobs. (users are in thousands and each can schedule hundreds of job). For that, currently, i am passing a user_id parameter to each job.  So, when the user hits an endpoint to get only his running jobs. I simply call scheduler.get_jobs() method to get all jobs then iterate through them to get only requesting user's job. 

```
something like this

jobs = scheduler.get_jobs()
[scheduler.get_job(job.id) for job in jobs if job.args[0] == user_id]
```

that's a bad approach if application scales.
So, i maintain another redis entry like 
```
user_id: [job_ids....., ....]
```
but for that i need two callback handlers 
JOB_ADDED (which is there), and JOB_GOING_TO_REMOVE (which isn't)

in the JOB_ADDED handler, i can get the job and then get the user_id arg and add an entry in my own collection 

```
def callback_job_added(event):
      job = scheduler.get_job(event.job_id)
      redis.rpush('user_%s' % user_id, job.id)
```


```
def callback_job_before_removing(event):
      job = scheduler.get_job(event.job_id)
      redis.lrem('user_%s' % user_id, job.id)
```

I hope you have a better solution than above. 

Another issue is apscheduler is taking too much memory on production environment.
Although the process pool and threads depend on machine capability(no. of cores) but
What are the reasonable parameters for executors in case of apscheduler with 
above 2000-3000 jobs running ? 

(Note: I am using BlockingScheduler in flask app)

I am using executors something like this
```
executors: {
 'default': ThreadPoolExecutor(12),
 'processpool': PoolProcessExecutor(10)
}
```

**Comment by agronholm** [comment]
Why can you not use EVENT_JOB_REMOVED? You didn't really explain that part.

This new event doesn't seem generally useful outside of your particular use case. Not that your use case is odd – it seems reasonable but the way it's implemented is not. If this is to be solve in the mainstream implementation, there should be some way to efficiently filter the jobs based on some metadata, but in a way that's compatible with the underlying mechanisms of the job stores.

**Comment by saadqc** [comment]
@agronholm Apology for the late reply.

You are right, the way i am trying to filter is not a good approach. I wanted to change minimal code possible. That's i came up with above approach. 
BTW, i am using the above approach and it did speed up the time of getting user specific jobs.

The 2nd approach can be grouping or group name field in APScheduler. 
So, we can get jobs using that group

e.g:

```
# Schedule a job
scheduler.add_job(group_name='user1',
                              ....) # Other fields                          

# Get all jobs a specific user
user1_jobs = scheduler.get_jobs(group_name='user1')
```

**Comment by agronholm** [comment]
I think it might be best if you created your own job store implementation, possibly subclassing some of the existing job store class. That way, you could add whatever metadata you need and you can directly query the jobs from the job store. No scheduler modifications needed.

**Comment by saadqc** [comment]
JobStore is used for persistency of jobs. (There is currently no implementation of any type of filter in any job store, AFAIK).  Subclassing jobstore just to add another field and filtering is surely not a good approach too. 

Whereas by adding listeners, if we can achieve a better filteration method. IMO, there shouldn't be any issue.

**Comment by agronholm** [comment]
You say it is not a good approach but you don't justify this claim in any way. The event you want to add does not help in any way to reduce the amount of data coming from the job store. Remember, this is a very specialized use case. Some job store backends are not even capable of general filtering of jobs. This BEFORE_REMOVE event caters only to your specialized way to work around this problem. It is not a real solution. Besides, you STILL haven't explained why EVENT_JOB_REMOVED is not good enough for you.

**Comment by saadqc** [comment]
Pardon me, I think i haven't explained well. 

Subclassing: 
By subclassing, i have to re-implement remove_job method like you did. 

I agree with your point "some job store backends are not even capable of general filtering of jobs".
and i did explained how EVENT_JOB_BEFORE_REMOVE reduce time significantly in my comment above(see 2nd comment).

Although if you want me to add another field(group or something) which helps in filtering implementation(in all backends).
Kindly let me know. I will come up with another design.

How EVENT_JOB_REMOVED is not good enough for me?

Answer:
Currently, a user who schedules a job, i assign the user_id in args when scheduling(apscheduler add_task(args=[user_id,...], ....).  And also add another entry of keyvalue pair (user_id, job_id) in db. After the job is removed how can i get id(or any other unique key) of user who scheduled the job in order to remove job_id from my own defined list? 

my own hash entry in redis:

user_id      [job_id1, job_id2, job_id3 ....]

after removal of job_id1,
data will be
user_id [job_id2, job_id3, ....]

The above design has nothing to do with apscheduler. I just needed an extra event in apsheduler
which will help me in implementing my design.

**Comment by agronholm** [comment]
I cannot understand why you can't use the job_id property in the existing job removal event for this.

**Comment by agronholm** [comment]
You would have a hash that maps every job id to its owner. So when EVENT_JOB_REMOVED is fired, you look up the user id from that.

**Comment by saadqc** [comment]
Suppose, the callback for EVENT_JOB_REMOVED is below

def callback_job_removed(event):
      #After job is removed, the line below will give None instead of job. So, i am unable to get user_id
      job = scheduler.get_job(event.job_id)
      redis.lrem('user_%s' % user_id, job.id)

**Comment by saadqc** [comment]
hash mapping is as follows in redis collection

key: user_id
value: [job_id1, job_id2, job_id3,...., job_idn]

If i don't know the user_id then how can i remove job_id from a list

**Comment by agronholm** [comment]
Did you read my last message? This is solved by having a job_id -> user_id hash in redis.

**Comment by saadqc** [comment]
So, you meant to say, i should create another job_id <--> user_id hash mapping in redis. 
Don't you think there is too much data redundancy and data manipulation in this?

job_id <--> user_id
user_id <--> [job_id1, job_id2, .... ]

now, if i want to remove job_id1 in EVENT_JOB_REMOVED callback

```
def callback_job_removed(event):
      user_id = redis.get(event.job_id)   # get user_id from job_id <--> user_id
      redis.delete(event.job_id)   # delete job_id <--> user_id key value pair
      redis.lrem('user_%s' % user_id, job.id)
```

BTW, thanks for the above solution. It works, but still performance-wise the old solution is better. 
(less redis hits, less redundancy and less managing data)

**Comment by agronholm** [comment]
I think the extra redis hits are acceptable. Use a multiexec pipeline to make it a redis transaction.

I will keep in mind this use case and requirements.

**Comment by saadqc** [comment]
Thank You.

For now, i am closing this PR and please don't close issue. And also i am hoping that there will be some fast builtin filtering in next versions.

**Comment by agronholm** [comment]
How would I accomplish that with redis?

**Comment by agronholm** [comment]
Or should I just declare that certain things aren't available with certain job stores?

**Comment by saadqc** [comment]
No, this feature can be implemented with all job stores

Workaround: 
You can add another field "group" or "group_name" in each job which has some value by default. 

Adding a task:

task = scheduler.add_job(group="user defined group",
                                         ....)

in Redis or other NoSQL, an entry will be created:

keyvalue pair: apscheduler.groups:group_%s <--> [list of job_ids]

Retrieving job using group_name:

tasks = scheduler.get_jobs(group="user defined group", limit=30) # By default limit will be -1

Redis Query behind:

job_ids_list = redis_store.lrange("user defined group",
                                 limit)

As you retrieve job_ids_list just lookup in particular jobstore and get job
for job_id in job_ids_list:
     list_jobs.append(scheduler.get_job(job_id))

**Comment by agronholm** [comment]
Ok, you were thinking of a different solution than I was. I was thinking about filtering on arbitrary metadata but that certainly won't work with Redis.

**Comment by agronholm** [comment]
So do you still require this feature?

**Comment by saadqc** [comment]
@agronholm : I managed to make change in my branch. So, it would be great if you add filtering (whatever method you wish) in upcoming versions.

If you need a hand, let me know. I would love to help

**Comment by saadqc** [comment]
@agronholm And you can close this issue if you want
