### ISSUE TITLE
pause & resume failure: AttributeError: 'NoneType' object has no attribute 'timezone'

### ISSUE THREAD

**Issue by jackemuk** [agronholm/apscheduler#140]
APScheduler-3.0.5

This seems to be located in  _lookup_job in schedulers/base.py

Once I have my scheduler, I'm then getting the job object for a particular job:
jobObject = scheduler.get_job(jobID)

When I pause the job using jobObject.pause(), an "AttributeError: 'NoneType' object has no attribute 'timezone'" is produced inside apscheduler/job.py/_modify():

AttributeError: "'NoneType' object has no attribute 'timezone'"
-> apscheduler/job.py(192)_modify()
-> approved['next_run_time'] = convert_to_datetime(value, self._scheduler.timezone, 'next_run_time')

Even though I'm passing a jobObject where I have actually set the _scheduler manually, the Job class in turn calls the the scheduler to pause_job, which then inside modify_job it again calls _lookup_job and gets a new Job object but the _scheduler is set to None, which then fails inside job._modify().

One solution is inside of schedulers/base.py set the scheduler before the Job object is returned.

        for job, alias, replace_existing in self._pending_jobs:
            if job.id == job_id:
                job._scheduler = self
                return job, None

        # Look in all job stores
        for alias, store in six.iteritems(self._jobstores):
            if jobstore_alias in (None, alias):
                job = store.lookup_job(job_id)
                if job is not None:
                    job._scheduler = self
                    return job, alias

The solution above seems to work with the current code, but may not elegant... A better solution might be to figure out how to not have to call lookup job again. Job.pause() calls the scheduler with just the job id, so all that information is already available

**Comment by agronholm** [comment]
Are you trying to pause the job before the scheduler has started? #68 has an open ticket for that.

**Comment by jackemuk** [comment]
No, the scheduler is starting and working normally. I call the scheduler to give me a list of the jobs that are current. The issue happens when calling schedulers\base.py\_lookup_job, the job object that is returned does not have _scheduler set.

**Comment by agronholm** [comment]
I just checked the code and `_scheduler` is indeed set by the job stores. Could you give me a minimal script to reproduce this?

**Comment by jackemuk** [comment]
jobObject = scheduler.get_job(<add a job ID here>)
jobObject.pause()

set a breakpoint in schedulers/base.py at line 382, inside modify_job():

382:    import pdb; pdb.set_trace()
383:    with self._jobstores_lock:
384:        job, jobstore = self._lookup_job(job_id, jobstore)

This job object that is returned from self._lookup_job(job_id, jobstore) is returning _scheduler set to "None".

**Comment by agronholm** [comment]
I mean a standalone script I could execute, which reproduces the problem on your end.

The job store is responsible for setting job._scheduler.

**Comment by jackemuk** [comment]
Not at present, the jobstore is a MongoDB.
> .../apscheduler/schedulers/base.py(687)_lookup_job()
-> return job, alias
(Pdb) p store
<MongoDBJobStore (client=MongoClient('mongo', 27017))>

**Comment by jackemuk** [comment]
When we initialize the jobstore, are we not setting something properly? 

cls.jobstore = MongoDBJobStore(client=MongoConnection.client)

**Comment by jackemuk** [comment]
When the document is reconstituted, the jobObject._scheduler is set to None.

apscheduler/jobstores/mongodb.py
 59  ->     def lookup_job(self, job_id):
 60             document = self.collection.find_one(job_id, ['job_state'])
 61             return self._reconstitute_job(document['job_state']) if document else None

**Comment by agronholm** [comment]
That only happens if `self._scheduler` is None. But that can't happen since the scheduler calls `MongoDBJobStore.start()` with the scheduler itself as the argument and `self._scheduler` gets set there.

**Comment by agronholm** [comment]
This is why I wanted you to write a minimal example script -- so I could see what goes wrong in your case.

**Comment by jackemuk** [comment]
I'm looking into the initialization and call to starting the scheduler to make sure it's set correctly. Thanks for the quick feedback!

**Comment by jackemuk** [comment]
In our configuration, we have a task scheduler process that is running with the jobstore in MongoDB. In another application I need to connect to that scheduler to modify the jobs that are scheduled. So what I'm doing in my application, is configuring the BackGroundScheduler in this fashion:

jobstores = {'default': MongoDBJobStore(client=MongoConnection.client)}
bgScheduler = BackgroundScheduler(jobstores=jobstores)

Since the scheduler is actually running in the other application, we are not starting the scheduler in this application. So the above bgScheduler can list the jobs and such, but since the scheduler is never actually started in this application, the self._scheduler is not set. 

Does that make more sense?

**Comment by agronholm** [comment]
Don't do this. If you do, the actual running scheduler has no way of knowing the job store has been altered and cannot thus adjust its sleeping time. A better way is to connect to your actual scheduler instance via some form of RPC, like execnet, rpyc, zeromq or similar.

And I guess you know now why `_scheduler` is None in the jobs. As the job store has not been started, it doesn't have a scheduler reference to put in the Job instance.

**Comment by jackemuk** [comment]
Now it makes sense... I'll bring this to the attention of the senior architect. 

Thanks!
