### ISSUE TITLE
a background scheduler run in a systemd service does not output to log file

### ISSUE THREAD

**Issue by bradburydoom** [agronholm/apscheduler#142]
Hello,

I have a background scheduler setup very similar to the example. A single job run every minute. I also imported logging and set level=logging.INFO. When run from the command line the log file is populated as expected. When the same file is run from a systemd service the log file is not populated. Any ideas?

Thanks!

**Comment by agronholm** [comment]
Use StackOverflow, the Google Group or IRC to ask questions. The Github issue tracker is not the correct channel for that. Also, I have no idea why this would happen with systemd.

**Comment by bradburydoom** [comment]
Sorry for mistake.

**Comment by bradburydoom** [comment]
Even though this issue is closed, and wasn't a valid issue, I thought I might offer an update. The issue was python logging tries to write the logging file to the directory the python file is located in. When run from a systemd service python logging tries to write the logging file to a directory it does not have permission to write to. So not an issue at all with apscheduler. Sorry for the mistake!

And thank you for all of the hard work on apscheduler. It's great and super easy to use!
