### ISSUE TITLE
misfire_grace_time not serialized to sqlite?

### ISSUE THREAD

**Issue by MaxNoe** [agronholm/apscheduler#147]
Following up on issue #146: Could it be that the misfire_grace_time is not saved and restored when using a sqlite jobstore?

On the next program start the misfire grace time is `1` for most jobs.

**Comment by agronholm** [comment]
There is nothing jobstore specific about serialization. I checked the code and misfire_grace_time is saved and restored to/from the serialized state properly. Could you write a small script to demonstrate the issue?

**Comment by MaxNoe** [comment]
Yes, you're right. It works. I had old jobs with the wrong time in the database.
