### ISSUE TITLE
Update docs page

### ISSUE THREAD

**Issue by jarekwg** [agronholm/apscheduler#148]
Docs @ https://apscheduler.readthedocs.io/en/latest/index.html show latest version as 3.1 and all links go to bitbucket.

**Comment by agronholm** [comment]
The builds are stuck at RTD and there is nothing I can do about it on my own. I will try to raise the RTD admins to reset the builds.

**Comment by agronholm** [comment]
It was my bad, I hadn't updated the repository URL. Works now.
