### ISSUE TITLE
Does scheduled_job decorator actually work?

### ISSUE THREAD

**Issue by jarekwg** [agronholm/apscheduler#150]
I know this sounds like a stackoverflow question, but I believe I've stumbled upon a bug.

The following code doesn't seem to work.

```
@scheduler.scheduled_job(...)
def somefunction():
   pass
```

The following code (which is what the tests actually test for) does:

```
def somefunction():
   pass
scheduler.scheduled_job(...)(somefunction)
```

The issue with the former case is that when it serialises the function location (`func_to_ref`), it does a quick check to ensure that it's worked by attempting to import the function back from the newly-generated ref. The problem is that at this stage, the function is not yet visible to the module as it hasn't finished being declared, so the 'quick check' fails to reimport it.

Currently, I'm not sure how to fix this and have had to resort to using the undecorated form `scheduler.add_job`.

**Comment by agronholm** [comment]
Sorry for the late reply. Yes, you're right in that this does not work if persistent job stores or ProcessPoolExecutor are involved. Perhaps I should modify obj_to_ref() to instead do the check in some other manner?

**Comment by jarekwg** [comment]
Yep, or:
- check at a later/delayed point in runtime, after the function has been bound to the module.
- simply trust obj_to_ref to be reliable.

**Comment by agronholm** [comment]
The second option is not acceptable. There are several cases where it will not produce a reproducible result:

1. Inner classes (detecting this requires `__qualname__` which is not available on Python 2)
1. Nested functions (ditto)
1. Lambdas (detectable in any Python version)
