### ISSUE TITLE
Scheduling Tornado Coroutines

### ISSUE THREAD

**Issue by anirbanroydas** [agronholm/apscheduler#152]
I have been following the issues and the code. So in light of those, is there any trick as of yet to actually schedule `tornado coroutines` using `apscheduler` or do I have to wait till **3.3**? 

Or what would be a _**quickfix**_ to do it? Should I plugin my own `Executer` subclassing the `BaseExecuter`? Or, will `GeventExecuter` any good if I convert all by `Tornado coroutines` to normal functions?

Or is there anyway to mimic the functionality of scheduling my `tornado coroutines`?

**Comment by agronholm** [comment]
This is the same issue as #98 and relates to the same problem as #96. I'm going to close this as duplicate; I will answer your question in the comments section of #98.

**Comment by anirbanroydas** [comment]
@agronholm Thanks for responding so quickly.

You can answer in the comment section of #98 .

By far as a quickfix I found this, [stackoverflow link](http://stackoverflow.com/a/29351054).

Have a look and let me know, is that a plausible solution or if there are other better alternatives?

**Comment by agronholm** [comment]
That answer only covers how to run code in the IOLoop thread. It does not work with coroutines and has other problems too (like exceptions never triggering scheduler events). I will post a better solution in #98's comments.

**Comment by anirbanroydas** [comment]
@agronholm As a matter of fact, the answer is authored by you itself.

**Comment by anirbanroydas** [comment]
Okay. Thanks. Please post a better solution. Need a quickfix around this. 👍

**Comment by anirbanroydas** [comment]
@agronholm As a humble request, it would be great if you could post the answer within today, only if you have a solution by any chance. As I mentioned I am in need of a real quick fix.

**Comment by agronholm** [comment]
See #98 for the code.
