### ISSUE TITLE
Add Consul support?

### ISSUE THREAD

**Issue by gkze** [agronholm/apscheduler#156]
Just wondering if it's on the roadmap at all 😄

**Comment by agronholm** [comment]
What is Consul?

**Comment by gkze** [comment]
It's a distributed k/v store from the folks at HashiCorp... similar to
Zookeeper in some ways -- http://consul.io

**Comment by agronholm** [comment]
Then I'm saying...if someone contributes a job store with tests then I'll merge. That's how it happened with ZooKeeper too.

**Comment by gkze** [comment]
Thank you! I'm currently using this for a small internal framework I'm developing, it's super useful. Considering writing a consul backend if it grows :)
