### ISSUE TITLE
func must be a callable or a textual reference to one

### ISSUE THREAD

**Issue by smarttang** [agronholm/apscheduler#161]
e,,,i don't know WHY...

`
class schedule_worker:

	def __init__(self):
		self.Lapi = apisec(username,password)
		self.Lapi.account()

	def checknode(self):
		self.Lapi.nodecheck()

	def runtask(self):
		self.Lapi.taskdo()

if __name__ == '__main__':
	scheduler = BackgroundScheduler()
	scheduler.start()
	k = schedule_worker()
	scheduler.add_job(k.checknode(),'interval',seconds=5)

`

`➜  schedule git:(master) ✗ python schedule.py
[*] Login successful!
Traceback (most recent call last):
  File "schedule.py", line 54, in <module>
    scheduler.add_job(k.checknode(),'interval',seconds=5)
  File "/Library/Python/2.7/site-packages/APScheduler-3.2.0-py2.7.egg/apscheduler/schedulers/base.py", line 422, in add_job
    job = Job(self, **job_kwargs)
  File "/Library/Python/2.7/site-packages/APScheduler-3.2.0-py2.7.egg/apscheduler/job.py", line 44, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
  File "/Library/Python/2.7/site-packages/APScheduler-3.2.0-py2.7.egg/apscheduler/job.py", line 165, in _modify
    raise TypeError('func must be a callable or a textual reference to one')
TypeError: func must be a callable or a textual reference to one`

**Comment by agronholm** [comment]
Please ask on the Google group or StackOverflow if you have questions. This issue tracker is for bug reports and feature requests.

You're calling `k.checknode()` and passing the return value (`None`) to `add_job()`.

**Comment by smarttang** [comment]
return None to add_job() ?

is k.checknode() ??

**Comment by agronholm** [comment]
Sorry, but you're making no sense at all. If you want help, ask a colleague to translate for you.
