### ISSUE TITLE
How to stop the task of cron 

### ISSUE THREAD

**Issue by lookcat** [agronholm/apscheduler#162]
First, I create a task of cron, jobstore was  used to memory. then  I need to delete the task of cron,
I forgot  the jobid. how to get the content of task ? how to stop the task?

**Comment by agronholm** [comment]
Please, use either the Google group or StackOverflow to ask questions. This issue tracker is for reporting bugs and requesting enhancements.

That said, you can get all jobs using `scheduler.get_jobs()`. Just find the job you're looking for by iterating over the returned list and remove the job when you find it.
