### ISSUE TITLE
APScheduler Job Next Executions

### ISSUE THREAD

**Issue by anoopkhandelwal** [agronholm/apscheduler#163]
Is there any way to fetch the next 5 executions time of the job?
Currently,I am able to get only 1 next execution time.
Getting only next execution time is not sufficient for the use-case,so I need few more subsequent executions time.

**Comment by agronholm** [comment]
Please ask questions only on the Google group, StackOverflow or the IRC channel. This issue tracker is for bug reports and feature requests.

You can use the `get_next_fire_time()` method on the job's `trigger` to calculate more run times.
See the code for [Job._get_run_times()](https://github.com/agronholm/apscheduler/blob/master/apscheduler/job.py#L118) for an example.

**Comment by anoopkhandelwal** [comment]
Hi,
Thanks for the info.I got the solution from it.
