### ISSUE TITLE
CronTrigger Constructor: 'str' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by andrewjli** [agronholm/apscheduler#164]
In the docs for `CronTrigger`, it says `start_date` and `end_date` can be passed as `datetime` or `str` values. But when you attempt to pass a string to the constructor:

``` python
trigger = CronTrigger(year='*', month='*/2', week='*', day='1',
    day_of_week='*', hour='0', minute='0', second='0',
    start_date='2016-11-01 12:15:00')
```

You end up with:

``` python
  File "/Library/Python/2.7/site-packages/apscheduler/triggers/cron/__init__.py", line 51, in __init__
    elif start_date and start_date.tzinfo:
AttributeError: 'str' object has no attribute 'tzinfo'
```

Which makes sense because a string does indeed not have a `tzinfo` attribute. There should probably be a check to see if `start_date` is a `datetime` before checking if it has a `tzinfo` attribute.

The easiest workaround is probably to pass in the local timezone in via `timezone`.

Note: I'm constructing a trigger instance manually here because my application needs to be compiled using PyInstaller, and correct me if I'm wrong, but this is the solution you suggested [here](https://groups.google.com/forum/#!searchin/apscheduler/lookuperror/apscheduler/OR3MSBHwd8Q/0BzP3xpuGmAJ).

**Comment by agronholm** [comment]
Yes, this is a bug. You can, however, provide your own datetime instances for `start_date`/`end_date` to circumvent this problem.
