### ISSUE TITLE
Scheduler: Scheduler._event is None when calling modify_job

### ISSUE THREAD

**Issue by briansan** [agronholm/apscheduler#165]
```
  File "myvenv/lib/python3.4/site-packages/apscheduler/schedulers/base.py", line 391, in modify_job
    self.wakeup()
  File "myvenv/lib/python3.4/site-packages/apscheduler/schedulers/blocking.py", line 32, in wakeup
    self._event.set()
AttributeError: 'NoneType' object has no attribute 'set'
```

i am writing a routine to sync up the intervals that are specified in a file with the jobs inside my apscheduler instance. my call looks like the following:

```
self.blocking_scheduler.modify_job( my_job_id, trigger=IntervalTrigger(seconds=new_interval) )
```

and end up with the attribute error shown above. any suggestions/diagnoses??

**Comment by agronholm** [comment]
I can't diagnose this unless I see the code that produced this. Do the examples work for you?

**Comment by briansan** [comment]
hi @agronholm, thanks for the quick reply. here's the code that created the job:
```
        self.blocking_scheduler.add_job(self.my_delayed_method, "interval",
                               seconds=10,
                               start_date=datetime.datetime.now() + datetime.timedelta(0, 5),
                               replace_existing=True,
                               misfire_grace_time=60,
                               id=schedule_id)
```

**Comment by briansan** [comment]
and here's the code that instantiates the blocking scheduler:
```
        client = "mongodb://localhost:27017/apscheduler"
        jobstore = MongoDBJobStore(client=client, database=client.get_default_database().name)
        self.blocking_scheduler = BackgroundScheduler(jobstores={"default": jobstore})
```

**Comment by agronholm** [comment]
This isn't helping. I don't want bits and pieces, I want to see the whole picture. I'm asking again: do the examples work for you? If they do, how does your code differ?

**Comment by briansan** [comment]
i'm sorry, but the company i work for that is using this library operates under a pretty heavy curtain of IP entitlement so i'm can only give bits and pieces..

i can't seem to find any examples that use the `modify_job` method

**Comment by agronholm** [comment]
Well did you try any of the examples anyway? There is no reasonable explanation for `self._event` being `None`, as there is no code that assigns `None` there. So could you modify an existing APScheduler example script (from``examples/``) to exhibit this behavior? I have no way to diagnose this problem otherwise.

**Comment by briansan** [comment]
i lied, it works just fine :)
