### ISSUE TITLE
GeventScheduler throws gevent.hub.LoopExit: This operation would block forever exception

### ISSUE THREAD

**Issue by jnpr-allenliu** [agronholm/apscheduler#167]
I try to create a geventScheduler instance in __init__ and add jobs later dynamically. 
Below is my code: apschedule.py

```
from apscheduler.schedulers.gevent import GeventScheduler
from apscheduler.executors.gevent import GeventExecutor
from datetime import datetime
import time
import os
import gevent

class Scheduler():
	def __init__(self):
        	self.scheduler = GeventScheduler()
        	self.g = self.scheduler.start()  # g is the greenlet that runs the scheduler loop
		try:
        		self.g.join()
        	except (KeyboardInterrupt, SystemExit):
        	     pass
	def add_job():
		self.scheduler.add_job(self.tick, 'interval', seconds=3)			

	def tick():
		print('Tick! The time is: %s' % datetime.now())




if __name__ == '__main__':
	try:
		scheduler = Scheduler()
		scheduler.add_job()	
        except (KeyboardInterrupt, SystemExit):
                pass
```

I am getting the following error when I execute the file
python apschedule.py

```
Traceback (most recent call last):
  File "apschedule.py", line 27, in <module>
    scheduler = Scheduler()
  File "apschedule.py", line 13, in __init__
    self.g.join()
  File "/home/allenliu/hapi-setup/csp-job-service/job-service-core/.venv/share/local/lib/python2.7/site-packages/gevent/greenlet.py", line 290, in join
    result = self.parent.switch()
  File "/home/allenliu/hapi-setup/csp-job-service/job-service-core/.venv/share/local/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: This operation would block forever

```

Did I miss anything? Thanks in advance for your help

**Comment by agronholm** [comment]
Where are you starting the scheduler?

**Comment by jnpr-allenliu** [comment]
Inside the __init__, after I create the scheduler instance
self.scheduler = GeventScheduler()
self.g = self.scheduler.start()

**Comment by agronholm** [comment]
Sorry, I wasn't looking properly. Though `__init__` is not a proper place for such code.

**Comment by agronholm** [comment]
Does the Gevent scheduler example work for you? I mean `examples/scheduler/gevent_.py`.

**Comment by jnpr-allenliu** [comment]
Yes, the example works for me. 
But I would need  to add the job dynamically by other function after I create the scheduler. 
Is there a way to do that?

**Comment by agronholm** [comment]
Maybe if you don't try to join the scheduler's greenlet?

**Comment by jnpr-allenliu** [comment]
If I remove the join statement, the program would exit directly.

**Comment by agronholm** [comment]
Well aren't you doing something else with Gevent? I mean, if you aren't, you should be using BlockingScheduler, right?

**Comment by agronholm** [comment]
So maybe spawn a task that adds another job?

**Comment by jnpr-allenliu** [comment]
I am modifying a program that uses Gevent. If I use BlockingScheduler, would it block other functions from executing?

**Comment by agronholm** [comment]
That it would. But your example looked like nothing else was going on.

**Comment by jnpr-allenliu** [comment]
I am still trying to figure out how to get the geventScheduler to work by writing some simple class/function.
I will need to add the code to my project once it's working.

Do you have any advice how I can fix the geventScheduler issue?

**Comment by agronholm** [comment]
I don't use gevent myself so there is not much advice I can give you. Did you try out my previous tip?

**Comment by jnpr-allenliu** [comment]
spawn a task that adds another job? 
Could you give me an example? I don't think I get it

**Comment by agronholm** [comment]
Look, I'm not going to teach you Gevent here. That's your task. If you can point out a bug in APScheduler's GeventScheduler class, file it here. This issue tracker is for bugs and feature requests, not for coding assistance. For that you can use StackOverflow or the apscheduler Google group.
