### ISSUE TITLE
rescheduling a paused job resumes the job

### ISSUE THREAD

**Issue by SyedElec** [agronholm/apscheduler#170]
Hi,

I had a quick question, is it a normal behavior to have a job resumed when it is rescheduled ?

I needed to reschedule a simple job into my scheduler to make it run later but still stay in its current state (paused in my case).

I just wanted to notify this issue (or not), and know if it is the normal behavior so I can modify my code to take into account this behavior.

I cannot find in the documentation info related to this behavior, maybe I missed it.

Thank you.

**Comment by agronholm** [comment]
It is. A job having `None` as its next run time means it's paused. Rescheduling assigns it a new run time.

BTW, do you happen to know where in Github I could put a notice to people posting issues, informing them to send questions to the Google group instead?

**Comment by SyedElec** [comment]
Ok, did not know if it was an issue or not. Please update documentation. Thanks anyway.

BTW, you can define a template for new issues and specify to ask questions on Google group instead of here : [example](https://github.com/OpenSC/OpenSC/issues/new)
