### ISSUE TITLE
Compatiability with Python 3.5, Pip 9.0.1

### ISSUE THREAD

**Issue by impguard** [agronholm/apscheduler#173]
On a fresh install of Python 3.5.0, APScheduler errors with:

```
---------------------------------------------------------------------------
DistributionNotFound                      Traceback (most recent call last)
<ipython-input-1-01ae27199cce> in <module>()
----> 1 import apscheduler

/Users/kwu/.pyenv/versions/3.5.0/envs/ruigi/lib/python3.5/site-packages/apscheduler/__init__.py in <module>()
      1 # These will be removed in APScheduler 4.0.
----> 2 release = __import__('pkg_resources').get_distribution('APScheduler').version.split('-')[0]
      3 version_info = tuple(int(x) if x.isdigit() else x for x in release.split('.'))
      4 version = __version__ = '.'.join(str(x) for x in version_info[:3])
```

I haven't used pkg_resources before and I'm not completely attuned with the intricacies of package installation, but it seems that `pkg_resources` doesn't seem to carry distribution information anymore?

I'm running on the latest version of pip, so I'm sure I'm installing things properly. Every other package I've installed works fine, and I've tried a fresh install with just APScheduler.

**Comment by agronholm** [comment]
How did you manage to get this error? Does it happen without IPython? Not for me at least. I've tried a couple times now and it installs just fine. No one else has reported any problems.

**Comment by impguard** [comment]
Using pyenv I installed 3.5.0. Then installed a virtualenv based off of it. Started the environment and installed apscheduler, seemed to break things.

I can try a fresh fresh install of 3.5.0 since my version had things like ipython installed in the base version.

I installed 3.0.6 and everything is good since it used a different method for determining version and release. My best guess right now is that the issue has something to do with virtualenv, since pyenv simply uses virtualenv under the hood, so I might test that later.

**Comment by agronholm** [comment]
I installed APScheduler in a virtualenv too and I had no problem importing it.

May I ask which version of setuptools you had installed?

**Comment by impguard** [comment]
```
setuptools 30.2.0 from /Users/kwu/.pyenv/versions/3.5.0/envs/ruigi/lib/python3.5/site-packages (Python 3.5)
```

**Comment by agronholm** [comment]
I don't know how to advise you, as I cannot reproduce the problem.

**Comment by impguard** [comment]
Cool, I'll work on reproducing it here again.

**Comment by agronholm** [comment]
So were you able to reproduce it?

**Comment by agronholm** [comment]
4 months and no response – closing.
