### ISSUE TITLE
The reschedule job function can not find the job id which has been in the job store

### ISSUE THREAD

**Issue by bg1szd** [agronholm/apscheduler#174]
I use SQLite as the jobstore.
I used get_jobs to query all the jobs in the job_store. The following job id in bold is there.
[root@apschedulerlq apschedule]# python query_jobs.py
run_cmd (trigger: date[2016-12-10 10:48:05 CST], next run at: 2016-12-10 10:48:05 CST)
run_cmd (trigger: date[2016-12-12 11:00:05 CST], next run at: 2016-12-12 11:00:05 CST)
run_cmd (trigger: date[2016-12-07 21:59:05 CST], paused)
[<Job (id=80b8e3c01539472f857c89e90802176f name=run_cmd)>, <Job (id=**7831f05b5c9c4652a123052bb3310603** name=run_cmd)>, <Job (id=809dbcd6830142a3b7770ec49ec5cc80 name=run_cmd)>]

However, if I tried to use reschedule_job to set another trigger time of the job as the following:
job=reschedule_job('7831f05b5c9c4652a123052bb3310603','date',run_date= '2016-12-10 15:15:05',timezone='Asia/Shanghai')

It will report the following error as:
Traceback (most recent call last):
  File "reschedule_job.py", line 50, in <module>
    job=conn.root.reschedule_job(jobid_value,'date',run_date=TargetTime,timezone='Asia/Shanghai')
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
rpyc.core.vinegar/apscheduler.jobstores.base.JobLookupError: No job by the id of 7831f05b5c9c4652a123052bb3310603 was found

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "server.py", line 64, in exposed_reschedule_job
    return scheduler.reschedule_job(job_id, jobstore, trigger, **trigger_args)
  File "/usr/lib/python2.7/site-packages/APScheduler-3.3.0-py2.7.egg/apscheduler/schedulers/base.py", line 502, in reschedule_job
    return self.modify_job(job_id, jobstore, trigger=trigger, next_run_time=next_run_time)
  File "/usr/lib/python2.7/site-packages/APScheduler-3.3.0-py2.7.egg/apscheduler/schedulers/base.py", line 474, in modify_job
    job, jobstore = self._lookup_job(job_id, jobstore)
  File "/usr/lib/python2.7/site-packages/APScheduler-3.3.0-py2.7.egg/apscheduler/schedulers/base.py", line 808, in _lookup_job
    raise JobLookupError(job_id)
JobLookupError: u'No job by the id of 7831f05b5c9c4652a123052bb3310603 was found'

Why could it not find the job id which is already available in the job store? Thanks!

**Comment by agronholm** [comment]
Could you construct a script that reproduces this problem? Thanks.

**Comment by bg1szd** [comment]
Below is the server.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
import time
import os
import sys
import commands
import subprocess
import logging
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.executors.pool import ThreadPoolExecutor, ProcessPoolExecutor
from datetime import datetime, timedelta

import pytz
from pytz import timezone

import rpyc
from rpyc.utils.server import ThreadedServer

def run_cmd(cmd):
    #status, output = commands.getstatusoutput(cmd)
    handle = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)

class SchedulerService(rpyc.Service):
    def exposed_add_job(self, func, *args, **kwargs):
        return scheduler.add_job(func, *args, **kwargs)

    def exposed_modify_job(self, job_id, jobstore=None, **changes):
        return scheduler.modify_job(job_id, jobstore, **changes)

    def exposed_reschedule_job(self, job_id, jobstore=None, trigger=None, **trigger_args):
        return scheduler.reschedule_job(job_id, jobstore, trigger, **trigger_args)

    def exposed_pause_job(self, job_id, jobstore=None):
        return scheduler.pause_job(job_id, jobstore)

    def exposed_resume_job(self, job_id, jobstore=None):
        return scheduler.resume_job(job_id, jobstore)

    def exposed_remove_job(self, job_id, jobstore=None):
        scheduler.remove_job(job_id, jobstore)

    def exposed_get_job(self, job_id):
        return scheduler.get_job(job_id)

    def exposed_get_jobs(self, jobstore=None):
        return scheduler.get_jobs(jobstore)


if __name__ == '__main__':
    scheduler = BackgroundScheduler()
    url = sys.argv[1] if len(sys.argv) > 1 else 'sqlite:///bug_repro.sqlite'
    jobstore=scheduler.add_jobstore('sqlalchemy', url=url)
    scheduler.start()
    protocol_config = {'allow_public_attrs': True}
    server = ThreadedServer(SchedulerService, port=12345, protocol_config=protocol_config)
    try:
        server.start()
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        scheduler.shutdown()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Below is the client.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from time import sleep

import rpyc
import os
import sys


cmd = 'ls -lrt /opt'
conn = rpyc.connect('localhost', 12345)
job = conn.root.add_job('server:run_cmd', 'date', run_date='2016-12-20 11:00:05', timezone='Asia/Shanghai', args=[cmd])
jobid_value=job.id

print("New Job has been added, the jobid is", jobid_value)

print("Query all jobs")
joblist = conn.root.get_jobs()
print(joblist)
newjob = conn.root.reschedule_job(jobid_value,'date',run_date='2016-12-12 12:00:05', timezone='Asia/Shanghai')

print("After the reschedule, view the job")
print(newjob)

#sleep(10)
#conn.root.remove_job(job.id)
conn.close()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Run `python server.py` in a console to make the server is in listening mode,
then run `python client.py` to reproduce the issue.

**Comment by bg1szd** [comment]
Here is the output after I run the python client.py

[root@apscheduler apschedule]python client.py
('New Job has been added, the jobid is', '3e7ba96bf66a4cc384edf19f21ffd900')
Query all jobs
[<Job (id=3e7ba96bf66a4cc384edf19f21ffd900 name=run_cmd)>]
Traceback (most recent call last):
  File "bug_client.py", line 18, in <module>
    newjob = conn.root.reschedule_job(jobid_value,'date',run_date='2016-12-12 12:00:05', timezone='Asia/Shanghai')
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
rpyc.core.vinegar/apscheduler.jobstores.base.JobLookupError: No job by the id of 3e7ba96bf66a4cc384edf19f21ffd900 was found

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "bug_repro_server.py", line 30, in exposed_reschedule_job
    return scheduler.reschedule_job(job_id, jobstore, trigger, **trigger_args)
  File "/usr/lib/python2.7/site-packages/APScheduler-3.3.0-py2.7.egg/apscheduler/schedulers/base.py", line 502, in reschedule_job
    return self.modify_job(job_id, jobstore, trigger=trigger, next_run_time=next_run_time)
  File "/usr/lib/python2.7/site-packages/APScheduler-3.3.0-py2.7.egg/apscheduler/schedulers/base.py", line 474, in modify_job
    job, jobstore = self._lookup_job(job_id, jobstore)
  File "/usr/lib/python2.7/site-packages/APScheduler-3.3.0-py2.7.egg/apscheduler/schedulers/base.py", line 808, in _lookup_job
    raise JobLookupError(job_id)
JobLookupError: u'No job by the id of 3e7ba96bf66a4cc384edf19f21ffd900 was found'

**Comment by bg1szd** [comment]
@agronholm , have you reproduced this issue in your local env?

**Comment by agronholm** [comment]
I have not had time to look into it yet.

**Comment by yangzhen868** [comment]
I hava the similar problem.
In django project,first job is started,and will start second job. Two jobs will run twice,and three jobs will run three times
Back job don't know scheduler is running and must be start. 

code like this：
    def tick():
        print('Tick! The time is: %s' % datetime.now())
    def tick2():
        print('Tick2! The time is: %s' % datetime.now())

    def __init__(self):
        self.sched = BlockingScheduler()
    def _addjob(self, appname,dic):     #dic is time set
        dic['jobstore'] = appname
        dic['trigger'] = 'cron'
        self.sched.add_job(eval(appname), **dic)
        print(self.sched._executors)
        print(self.sched._jobstores)
        print(self.sched._listeners)
        print(self.sched._pending_jobs)
        print(self.sched.state)
        self.sched.start()

Result like this
[17/Feb/2017 11:25:54] "GET /job/set/?n=tick HTTP/1.1" 200 7462
[17/Feb/2017 11:25:54] "GET /favicon.ico HTTP/1.1" 200 5297
{}
{'tick': <DjangoJobStore>}
[]
[(<Job (id=ea36abf21c9f4e61ae07fcc092fb1835 name=tick)>, 'tick', False)]
0
Tick! The time is: 2017-02-17 11:26:00.015659
[17/Feb/2017 11:26:00] "GET /job/list/ HTTP/1.1" 200 6934
[17/Feb/2017 11:26:01] "GET /favicon.ico HTTP/1.1" 200 5297
[17/Feb/2017 11:26:02] "GET /job/set/?n=tick2 HTTP/1.1" 200 7464
[17/Feb/2017 11:26:03] "GET /favicon.ico HTTP/1.1" 200 5297
Tick! The time is: 2017-02-17 11:26:05.034746
{}
{'tick2': <DjangoJobStore>}
[]
[(<Job (id=d82556686b1e4adeb1961be2d2f5092c name=tick2)>, 'tick2', False)]
0
Tick2! The time is: 2017-02-17 11:26:06.014696
Tick2! The time is: 2017-02-17 11:26:09.025060
Tick! The time is: 2017-02-17 11:26:10.026191
Tick! The time is: 2017-02-17 11:26:10.028289
Tick2! The time is: 2017-02-17 11:26:12.028191
Tick2! The time is: 2017-02-17 11:26:12.028898
Tick2! The time is: 2017-02-17 11:26:15.026958
Tick2! The time is: 2017-02-17 11:26:15.032247
Tick! The time is: 2017-02-17 11:26:15.042909
Tick! The time is: 2017-02-17 11:26:15.045914
Tick2! The time is: 2017-02-17 11:26:18.041688
Tick2! The time is: 2017-02-17 11:26:18.046075

**Comment by agronholm** [comment]
@bg1szd Sorry for taking so unbelievably long with this! But in case you hadn't figured it out, this happens because you call `reschedule_job()` while passing "date" for the jobstore parameter. There is no job store named "date" of course, which is why rescheduling fails.

**Comment by agronholm** [comment]
@yangzhen868 I can barely understand you, but if you still have a problem, please post a different issue and describe the problem with code that I can run to reproduce it.
