### ISSUE TITLE
Support cron expression directly?

### ISSUE THREAD

**Issue by sinall** [agronholm/apscheduler#176]
I would like to see a CronTrigger constructor which tasks a whole cron expression directly.
User scenario:
It will be very easy to have the trigger configured in a config file.

BTW, cron expression is a standard DSL. Don't know why people not using it directly.

**Comment by agronholm** [comment]
Sorry, I will not support this in the foreseeable future. Feel free to write your own library for that though.

**Comment by sinall** [comment]
Do you mind if I create a PR or you don't like the idea at all :)

**Comment by agronholm** [comment]
I don't like the idea in the first place.

**Comment by sinall** [comment]
Cool, will do it in my application then, thanks.
