### ISSUE TITLE
ImportError: RedisJobStore requires redis installed

### ISSUE THREAD

**Issue by lookcat** [agronholm/apscheduler#181]
I use the APScheduler==3.3.0 and install redis on the window7.
I set the jobstore to use the redis , got some error:

    from apscheduler.jobstores.redis import RedisJobStore
  File "C:\Python27\lib\site-packages\apscheduler\jobstores\redis.py", line 19, in <module
>
    raise ImportError('RedisJobStore requires redis installed')
ImportError: RedisJobStore requires redis installed

I sure that redis is workingfor me , how to deal with the error ?
reinstalled the redis or the others?
can you give me some tips?

Thanks, have a nice day!

**Comment by agronholm** [comment]
You don't have the redis driver installed.
`pip install redis` will fix it.
