### ISSUE TITLE
Job was missed

### ISSUE THREAD

**Issue by sinall** [agronholm/apscheduler#182]
```
        scheduler = BackgroundScheduler()
        scheduler.add_job(self._new_stock_purchase_job, APCronParser.parse('30 */1 9-15 mon-fri * * * *'))
        scheduler.start()
        print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))

        try:
            while True:
                time.sleep(1)
        except (KeyboardInterrupt, SystemExit):
            scheduler.shutdown()
```

> 2017-01-16 11:35:01,380 WARNING Run time of job "NewStockPurchaseJob (trigger: cron[year='*', month='*', day='*', week='*', day_of_week='mon-fri', hour='11', minute='35', second='0'], next run at: 2017-01-16 11:35:00 CST)" was missed by 0:00:01.209054

Why my job was missed? How to avoid this?

**Comment by agronholm** [comment]
It was executed late due to other system load. You may want to change the `misfire_grace_time` setting which defaults to 1 second.
