### ISSUE TITLE
Is this a bug?(TornadoScheduler with AsyncHTTPClient)

### ISSUE THREAD

**Issue by avayayu** [agronholm/apscheduler#183]
I am using windows7 and python3.5.When I tried interval job,everything runs well,but When I change interval job to cron job,http_client failed with no error,no exception. What's wrong?

from tornado.httpclient import AsyncHTTPClient
from tornado.httpclient import HTTPRequest
import tornado.ioloop
import tornado.web
from tornado.ioloop import IOLoop
from apscheduler.schedulers.tornado import TornadoScheduler
import pytz
application = tornado.web.Application()

def handle_request(response):
    if response.error:
        print("Error:", response.error)
    else:
        print(response.body)
        print('\n=====================================================================')

def crawl():
    print('crawl start')
    url = 'http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/Market_Center.getHQNodeData?page=' + \
        str(0 + 1) + '&num=80&sort=changepercent&asc=0&node=hs_a&symbol=&_s_r_a=setlen'
    req = HTTPRequest(url, request_timeout=100000)
    http_client = AsyncHTTPClient()
    http_client.fetch(req, handle_request)
    http_client.close()
    print('crawl end')

if __name__ == "__main__":
    application.listen(8222)
    sh = pytz.timezone('Asia/Shanghai')

    scheduler = TornadoScheduler(timezone=sh)
    scheduler.add_job(crawl,  'cron',
                      hour=11, minute=23, replace_existing=True)
    scheduler.start()

    try:
        IOLoop.instance().start()
    except (KeyboardInterrupt, SystemExit):
        pass

**Comment by agronholm** [comment]
If you feel like there's a bug somewhere, would you please dig deeper and provide some more information? Try setting the log level to `DEBUG` for the `apscheduler` logger (see the documentation for the `logging` module in the stdlib docs if you don't know how logging works in Python) and find out what it outputs.

**Comment by avayayu** [comment]
Fri, 03 Feb 2017 18:56:43 base.py[line:431] INFO Adding job tentatively -- it will be properly scheduled when the scheduler starts
Fri, 03 Feb 2017 18:56:43 base.py[line:865] INFO Added job "crawl" to job store "default"
Fri, 03 Feb 2017 18:56:43 base.py[line:158] INFO Scheduler started
Fri, 03 Feb 2017 18:56:43 base.py[line:924] DEBUG Looking for jobs to run
Fri, 03 Feb 2017 18:56:43 base.py[line:1004] DEBUG Next wakeup is due at 2017-02-03 18:57:00+08:00 (in 16.203927 seconds)
Fri, 03 Feb 2017 18:57:00 base.py[line:924] DEBUG Looking for jobs to run
Fri, 03 Feb 2017 18:57:00 base.py[line:123] INFO Running job "crawl (trigger: cron[hour='18', minute='57'], next run at: 2017-02-03 18:57:00 CST)" (scheduled at 2017-02-03 18:57:00+08:00)
crawl start
Fri, 03 Feb 2017 18:57:00 base.py[line:1004] DEBUG Next wakeup is due at 2017-02-04 18:57:00+08:00 (in 86399.999000 seconds)
crawl end
Fri, 03 Feb 2017 18:57:00 base.py[line:135] INFO Job "crawl (trigger: cron[hour='18', minute='57'], next run at: 2017-02-04 18:57:00 CST)" executed successfully
Error: HTTP 599: Timeout

thanks for your reply. I can't get useful information from logs.It seems that scheduler does well. But the callback does not work. But when I add a interval job like this
```
def signal():
    print('scheduler alive')
scheduler.add_job(signal,  'interval',
    seconds=2, replace_existing=False)
```
then the callback works well.

**Comment by agronholm** [comment]
Did the `HTTP 599: Timeout` not come from the callback?

**Comment by avayayu** [comment]
Yes.
But when I add the signal job,there is no error and get the right json data.

**Comment by avayayu** [comment]
```
scheduler.add_job(IOLoop.instance().add_callback,  'cron',
                      hour='20', minute='14', replace_existing=False, args=[crawl])
```
I change the add_job to the above code,then everything seems Ok.
