### ISSUE TITLE
Timezone error when timezone is specified

### ISSUE THREAD

**Issue by randywreed** [agronholm/apscheduler#186]
I got an error saying : 'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).

But the datetime object has a timezone attached.
```
tz=timezone('America/New_York')
attendanceEnd=datetime.datetime.now(tz=tz)+datetime.timedelta(hours=int(h), minutes=int(m), seconds=int(s))
scheduler.add_job(func=closeAttendance, trigger='date', run_date=attendanceEnd )
```
print_jobs() shows

> closeAttendance (trigger: date[2017-02-22 17:24:52 EST], next run at: 2017-02-22 17:24:52 EST)

Is this an error? This is running on at centos machine.

**Comment by agronholm** [comment]
CentOS, combined with an old version of tzlocal will manifest this problem. I suggest you upgrade to the latest tzlocal version.

**Comment by randywreed** [comment]
tzlocal is up to date (1.3) but the error still happens. Is there any other package that might affect this?

**Comment by agronholm** [comment]
Sorry to hear that. I was under the impression that the latest tzlocal would finally work with CentOS. If not, then you have to manually specify your timezone as the message says.
