### ISSUE TITLE
Thread not killed after successful job execution

### ISSUE THREAD

**Issue by shawnpg00** [agronholm/apscheduler#190]
I'm executing a job ever minute, 

```
sched.add_job(function1, 'interval', minutes=1, id='Job1', args=['arg1'])


def function1(arg1):
       print "hi"
       return
```

The scheduler starts a new thread for every execution of the job, which is expected. However, after successful execution of the job, it does not kill the thread it was running on. That means every minute I've a new thread running on my machine which is never closed. How to solve this? I want the scheduler to kill the thread after successful execution of the function.

Here is the debug log,

INFO:apscheduler.scheduler:Added job "function1" to job store "default"
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2017-03-21 08:56:02.773109+00:00 (in 59.999213 seconds)
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2017-03-21 08:57:02.773109+00:00 (in 59.999567 seconds)
INFO:apscheduler.executors.default:Running job "function1 (trigger: interval[0:01:00], next run at: 2017-03-21 08:57:02 UTC)" (scheduled at 2017-03-21 08:56:02.773109+00:00)
INFO:apscheduler.executors.default:Job "function1 (trigger: interval[0:01:00], next run at: 2017-03-21 08:57:02 UTC)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "function1 (trigger: interval[0:01:00], next run at: 2017-03-21 08:57:02 UTC)" (scheduled at 2017-03-21 08:57:02.773109+00:00)

**Comment by agronholm** [comment]
The thread pool executor, which is the default, does not stop threads after being started. It will start up to N threads where N is the configured maximum. After that it starts to reuse the threads. Is this a problem?

**Comment by shawnpg00** [comment]
I want to keep the number of threads to the minimum possible at a given time. Is there a way to kill a thread after finishing it's use? Say when the allotted function returns?

**Comment by agronholm** [comment]
Not sure why you feel this is important, but you will need to implement your own pooling or other threading algorithm in a custom executor then. The default executor works this way because the standard library ThreadPoolExecutor works like that.

**Comment by shawnpg00** [comment]
okay, thanks for clearing things out!
