### ISSUE TITLE
get_job was stoped by "with self._jobstores_lock"

### ISSUE THREAD

**Issue by chenli0906** [agronholm/apscheduler#192]
i use django to build a web-app and apscheduler to add a job when start the server
and call `get_job` beore `add_job` to check exists
unfortunately, server cant start, no exception, no warning
then i use pdb to track what happened
it was stucked in get_job function by the code `with self._jobstores_lock`

the last time runserver i press CTRL + C to quit, maybe that moment apscheduler was accessing data through sqlite database, and database was locked

is there any method to release the lock of database before `get_job`?

thx a lot : )

**Comment by agronholm** [comment]
The lock is supposed to be part of the internal implementation details of the scheduler, so it is not to be touched. Why *do* you call `get_job()` before `add_job()` anyway?

**Comment by chenli0906** [comment]
call get_job() before add_job() in order to check job exists, it was locked at time of django service start when i put add_job startup code in wsgi.py. but use RESTapi to call add_job is OK, maybe add_job need some delay to release lock.
Anyway, i use scheduled_job decorator to solve this, seems work : )
