### ISSUE TITLE
zombie process 

### ISSUE THREAD

**Issue by lookcat** [agronholm/apscheduler#193]
logging.basicConfig()
scheduler = BackgroundScheduler(daemon=True)
scheduler.add_job(clean_hour_Values, 'cron', minute=0, second=30)
scheduler.add_job(clean_day_Values, 'cron', hour=23, minute=55)

'''
Jobstore default:
    clean_hour_Values (trigger: cron[minute='0', second='30'], next run at: 2017-03-29 17:00:30 CST)
    clean_day_Values (trigger: cron[hour='23', minute='55'], next run at: 2017-03-29 23:55:00 CST)
'''
print (scheduler.get_jobs())
scheduler.print_jobs()

scheduler.start()
try:
    # This is here to simulate application activity (which keeps the main thread alive).
    while True:
        time.sleep(2)
except (KeyboardInterrupt, SystemExit):
    scheduler.shutdown()  # Not strictly necessary if daemonic mode is enabled but should be done if possible

############################################################################
I use the centos 6.5, apscheduler3.3, python2.7.8
I make a cron task as Daemon，I ran the it yesterday on the time. 
Today, I saw the result of the log file.
I found the scheduler is running at 08:00:30, 09:00:30,12:00:30. what's the matter with 10:00:30 11:00:30?
Can you give me some advice ? 
                                                                                                                             Have a fun day.

**Comment by agronholm** [comment]
Your question boils down to: "Scheduler is not working. Please help."
Could you at least dig a little deeper before asking?

**Comment by lookcat** [comment]
Oh,I'm sorry .  I did not how to improve some tip for you, I just found the  script is running at first day and  is stopping at second day. 
I have not to get useful imformation .
