### ISSUE TITLE
How to add Authentication to MongoDBJobStore

### ISSUE THREAD

**Issue by n3xus** [agronholm/apscheduler#197]
Can we add mongodb authentication to MongoDbJobStore ?

**Comment by agronholm** [comment]
See the [MongoClient](http://api.mongodb.org/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient) documentation for that. As the docs say, any leftover configuration not consumed by `MongoDBJobStore` is sent to `MongoClient` directly.
