### ISSUE TITLE
help: could not import module

### ISSUE THREAD

**Issue by itchenyi** [agronholm/apscheduler#201]
#### My Env:
```
apscheduler==3.3.1

$ python --version
Python 3.6.0
```

#### My Code:

```
#: add job
klass = JobUtils.import_class(req_data['job_type'])
func = getattr(klass, 'execute')

scheduler.add_job(
    func=func,
    trigger='cron',
    ...
)

#: JobUtils.import_class
def import_class(cls, name):
    spec = import_module.spec_from_file_location(name, os.path.join(cls.absolute_path(), "%s.py" % name))
    mod = import_module.module_from_spec(spec)
    spec.loader.exec_module(mod)

    return getattr(mod, name.capitalize())
```
                
#### Logger Info for Add Job 

```
INFO:apscheduler.scheduler:Added job "test" to job store "default"
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
```

#### Databases:
```
*************************** 1. row ***************************
           id: 098f6bcd4621d373cade4e832627b4f6
next_run_time: NULL
    job_state: ...
```

#### i try resume the job, but the error:

```
code:
scheduler.get_job(job_id="098f6bcd4621d373cade4e832627b4f6").resume()

error msg:
File "/$PATH/.env/lib/python3.6/site-packages/apscheduler/util.py", line 270, in ref_to_obj
    raise LookupError('Error resolving reference %s: could not import module' % ref)
LookupError: Error resolving reference scan:Scan.execute: could not import module
```

#### source code 

```
    try:
        obj = __import__(modulename, fromlist=[rest])
    except ImportError:
        raise LookupError('Error resolving reference %s: could not import module' % ref)
```

**Comment by itchenyi** [comment]
Looking forward to your reply 😊

**Comment by agronholm** [comment]
Well, it says it cannot import the `scan` module. So what do you need?

**Comment by itchenyi** [comment]
i am using `__import__` the function and resume this job:

```
code:
scheduler.get_job(job_id="098f6bcd4621d373cade4e832627b4f6").resume()

log:
INFO:apscheduler.scheduler:Removed job 098f6bcd4621d373cade4e832627b4f6
```

**Comment by itchenyi** [comment]
@nikolas   i want to import from the absolute path, but the `__import__` function default from the `sys.path` ...

**Comment by agronholm** [comment]
I do not see how that is going to help. The error it gives you tells me that you have added a job for the `execute()` method on the `Scan` class in the `scan` module, but that there is no module named `scan`. I don't know what else to tell you, and I have absolutely no idea why `__import__()` is involved here or what you're saying about `absolute paths`.

**Comment by itchenyi** [comment]
@agronholm  ok, I understand

**Comment by itchenyi** [comment]
thank you , you can see this code:

```
code:
scheduler.get_job(job_id="098f6bcd4621d373cade4e832627b4f6").resume()

log:
INFO:apscheduler.scheduler:Removed job 098f6bcd4621d373cade4e832627b4f6

why is that?
```

**Comment by agronholm** [comment]
When attempting to restore jobs, the job stores will delete any jobs for which they cannot resolve the target function. This is so that obsolete job states get automatically cleared away. Since your `scan` module was not found, I can only guess that it automatically removed the stored job state from the job store.

**Comment by itchenyi** [comment]
ok thanks
