### ISSUE TITLE
Apscheduler add_job can't run successfully for cron type?

### ISSUE THREAD

**Issue by easytrader** [agronholm/apscheduler#202]
My github project: 
https://github.com/easytrader/Apscheduler_for_django

My Apscheduler's code:
```
from apscheduler.schedulers.background import BackgroundScheduler
scheduler = BackgroundScheduler()
scheduler.start()

def test_3():
    print("test3")
    print('Tick! The time is: %s' % datetime.now())

def test3(request):
    print("test3 ")
    scheduler.add_job(test_3, 'cron',id='my_test_job3', day_of_week='0-5', hour='16', minute='28')
    return render_to_response('hello_world.html',{},context_instance = RequestContext(request))
```
My test1 and test2 work fine for testing Apscheduler's interval function.

But it can't work on cron type.

How to fix this issue.

Thank you very much.

**Comment by agronholm** [comment]
When writing a bug report, it would be helpful to describe the actual problem you're having. "Doesn't work" is totally unhelpful. It's as if nobody else was using cron style jobs and I should immediately understand that cron does not work for anybody.

**Comment by agronholm** [comment]
Have you tried the examples? If the examples work, the problem is in your own code. A minimal script that reproduces the issue would shed light on the problem.

**Comment by easytrader** [comment]
Hello agronholm,
Thanks for give me a feedback. I will open the bug report more carefully.

The below script run cron type successfully. 
But I don't know what difference between the below script and my github project.
I really can't figure it out . I really want to use cron type in django project.
Thank you so much.
```
# coding=utf-8

from datetime import datetime
import time
import os

from apscheduler.schedulers.background import BackgroundScheduler


def tick():
  print('Tick! The time is: %s' % datetime.now())

def test_3():
    print("test3")
    print('Tick! The time is: %s' % datetime.now())

if __name__ == '__main__':
  scheduler = BackgroundScheduler()
  scheduler.start()
  #scheduler.add_job(tick, 'interval', seconds=3)
  #scheduler.add_job(tick, 'date', run_date='2016-02-14 15:01:05')
  scheduler.add_job(test_3, 'cron', id='my_test_job3',day_of_week='0-5', hour='19', minute='19')
  
  print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))

  try:
    # This is here to simulate application activity (which keeps the main thread alive).
    while True:
      time.sleep(2)  #其他任務是獨立的線程執行
      print('sleep!')
  except (KeyboardInterrupt, SystemExit):
    # Not strictly necessary if daemonic mode is enabled but should be done if possible
    scheduler.shutdown()
    print('Exit The Job!')
```

**Comment by agronholm** [comment]
Could you construct a minimal example that **does** reproduce the problem you're seeing? I don't know how else to help you.

**Comment by easytrader** [comment]
I create a minimal django project for reproduce the problem.
https://github.com/easytrader/Apscheduler_for_django_test

You can use git clone https://github.com/easytrader/Apscheduler_for_django_test.git.
And `python manage.py runserver` to run the project.
I add scheduler.add_job in the index page.
You should refresh the http://127.0.0.1:8000/ in your browser and it will trigger the scheduler.add_job's cron.
You can see the cron doesn't run.
Thank you so much.

The cron django code is below:
```
from django.shortcuts import render,render_to_response
from django.template import RequestContext
import sys
import os

from datetime import datetime
import time
import os

from apscheduler.schedulers.background import BackgroundScheduler
scheduler = BackgroundScheduler()
scheduler.start()


def test_3():
    print("test3")
    print('Tick! The time is: %s' % datetime.now())

# Create your views here.
def hello_world(request):
    print("add_job")
    scheduler.add_job(test_3, 'cron', id='my_test_job3', day_of_week='0-5', hour='19', minute='42')

    return render_to_response('hello_world.html',{},context_instance = RequestContext(request))
```

**Comment by agronholm** [comment]
You still have not told me what problem you're seeing.

**Comment by easytrader** [comment]
I can't see print "test3" on my setting time(19:42).
This is my problem.

**Comment by agronholm** [comment]
What I suggest is to enable logging output for the `apscheduler` logger on the `DEBUG` level, so you can see what the scheduler is doing. Can you do that?

**Comment by easytrader** [comment]
I use https://groups.google.com/forum/#!topic/apscheduler/EA91eKGl8tM to save log.
The log is below:
```
[2017-04-27 12:07:08,264]: DEBUG : Next wakeup is due at 2017-04-27 20:07:00+00:00 (in 28791.735664 seconds)
[2017-04-27 12:08:56,066]: INFO : Scheduler started
[2017-04-27 12:08:56,067]: DEBUG : Looking for jobs to run
[2017-04-27 12:08:56,067]: DEBUG : No jobs; waiting until a job is added
[2017-04-27 12:09:00,107]: INFO : Added job "test_3" to job store "default"
[2017-04-27 12:09:00,108]: DEBUG : Looking for jobs to run
[2017-04-27 12:09:00,108]: DEBUG : Next wakeup is due at 2017-04-27 20:10:00+00:00 (in 28859.891952 seconds)
[2017-04-27 12:09:00,108]: WARNING : /usr/local/lib/python2.7/dist-packages/django/shortcuts.py:45: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
  using=using)

```
So the problem is django's time?
[2017-04-27 12:09:00,108]

**Comment by easytrader** [comment]
Thank you so much Agronholm.

**Comment by agronholm** [comment]
Django does not have its own time. Your development machine just has a different timezone than what you expected.
