### ISSUE TITLE
A server has installed, another I wan't install

### ISSUE THREAD

**Issue by Jeyha** [agronholm/apscheduler#203]
A server has installed, another I wan't install; So I transfer this package to this server;
But it does't work, the problem is:
```
Traceback (most recent call last):
  File "flow_py3.py", line 24, in <module>
    import cron
  File "/data/server/git/cron.py", line 12, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/data/server/zlibs/apscheduler/__init__.py", line 2, in <module>
    release = __import__('pkg_resources').get_distribution('APScheduler').version.split('-')[0]
  File "/usr/local/python35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 557, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/python35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/python35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/python35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'APScheduler' distribution was not found and is required by the application
```

Python：3.5.3
apscheduler：3.3.1【installed by easy_install】

**Comment by agronholm** [comment]
You only transferred the package, not the related `.egg-info` directory which is created on install. Couldn't you just have reinstalled it on the new server?

**Comment by Jeyha** [comment]
I don't want to reinstall it on the new server, So I only transferred the package;
I try only transferred the package, Also I related .egg-info directory; But not work!

**Comment by agronholm** [comment]
Reinstalling it shouldn't be so difficult. Could you try that and see if it fixes the problem?

**Comment by Jeyha** [comment]
I reinstall it on a new sever, can work!
But I don't want to reinstall it, like the green software！

**Comment by agronholm** [comment]
What "green software"? I have no idea what you're talking about.

**Comment by Jeyha** [comment]
Thank you for your reply!
A server install the python package; So I collect these into a libs directory;
When I deploy my project on a new server, I just deploy the project code and the python pacage I collected,
And I config the linux sys path, So that the python can find the libs in my own libs directory; Then my project can running;
So another new sever do!

**Comment by agronholm** [comment]
I cannot understand you, but it sounds like you're doing something you're not supposed to do. If you feel APScheduler has a bug, create a script that reproduces the problem when APScheduler has been correctly installed. I do not support nonstandard ways of installing it.

**Comment by Jeyha** [comment]
It is not the bug of APScheduler, I just don't want to install on a new server!
Before, I use Pyhton is 2.6.6, and the APScheduler is 2.1.2, It can work like this way!
Now I update the Python version to 3.5.3, and the APScheduler version update to 3.3.1, But it can not work!

**Comment by agronholm** [comment]
Why not?

**Comment by agronholm** [comment]
Also, what prevents you from installing an older version of APScheduler?

**Comment by Jeyha** [comment]
I use easy_install to install the APScheduler; It's OK!

**Comment by agronholm** [comment]
Easy_install should not be used anymore (use pip instead) but `easy_install apscheduler==2.1.2` should work.

**Comment by Jeyha** [comment]
OK, Thank you!
