### ISSUE TITLE
relationship between job_id and func

### ISSUE THREAD

**Issue by yzfshuijing** [agronholm/apscheduler#209]
hi, i want to ask a question 
How the database jobstore achieves id and func mapping relationship
for example:
if i made a scheduler and i made some jobs with different func, then i exit the program and restart it 
how the store knows which job id belongs to which func
looking forward for your answer
thanks

**Comment by gilbsgilbs** [comment]
See (Getting Help)[https://github.com/agronholm/apscheduler#getting-help] section in the README. It's better to use GitHub issues for bug reports or new features discussions only.

AFAIK, APScheduler uses the qualified name of the function independently of the job store. This also means that you wont be able to wrap jobs when adding them.
```
scheduler.add_job(my_wrapper(my_callback), 'interval', minutes=2, id='my_job_id')  # Gotcha: this does not work.
```

**Comment by yzfshuijing** [comment]
i see, thanks
