### ISSUE TITLE
why BlockingScheduler does not execute on start

### ISSUE THREAD

**Issue by junneyang** [agronholm/apscheduler#215]
from apscheduler.schedulers.blocking import BlockingScheduler
scheduler = BlockingScheduler()
scheduler.add_job(tick, 'interval', hours=24)
scheduler.start()

it does not execute on start, but wait for 24 hours

**Comment by fir5** [comment]
please read the document.

**Comment by agronholm** [comment]
This is how the interval trigger works. If I changed it, a lot of code in production would break. I will probably do it in the next major release though, whenever that might be.
