### ISSUE TITLE
Jobs not added to Heroku Postgres

### ISSUE THREAD

**Issue by SamuelNLerner** [agronholm/apscheduler#216]
I have a background scheduler set up as such:

`scheduler = BackgroundScheduler()`

`url = os.environ["DATABASE_URL"]`
`scheduler.add_jobstore(SQLAlchemyJobStore(url=url))`

`scheduler.start()`

Every time I add a job, with the line:

` scheduler.add_job(job, 'date', run_date=run_date, id=job_id)`

 it indicates that it occurred successfully. However, the jobs do not run and when I go to the Heroku Postgres console, and run

`select * from apscheduler_jobs;`

it indicates that no rows exist.

**Comment by agronholm** [comment]
Can you reproduce this without Heroku?

**Comment by agronholm** [comment]
27 days and no response – closing.
