### ISSUE TITLE
high resolution timer (nanoseconds)

### ISSUE THREAD

**Issue by blaisezzz** [agronholm/apscheduler#219]
Hello,

I have been experimenting around the scheduler to see if it is possible to use within the micro-controller environment. I am interest in modifying the internal timer to have higher resolution than milliseconds, in the range of microseconds, even perhaps nanoseconds. 

I am looking to use high-precision linux timer to get down to the timing I need, then I would like to use these timing inside your apscheduler. Where in the repository should I start to experiment with these changes. Would it be possible to give me some pointer to achieve this.

Thank you in advance!

**Comment by agronholm** [comment]
I honestly don't think Python's scheduling is reliable enough for this. But as I recall, the scheduler would indeed accept highly accurate timestamps. And if the trigger classes don't support it, you would need to add support to each one of them separately.
