### ISSUE TITLE
Add a job: job with an argument isn't possible ?

### ISSUE THREAD

**Issue by skawm** [agronholm/apscheduler#220]
hello, 
I would like to know if it possible to make a job that call my job function with an argument, like this for example: 
`scheduler.add_job(tick("tickk"), 'cron', second=15)`

As you can see I would like to pass the "tickk" argument to my job tick but I can't. So, have you any ideas of what I can do? 

Thanks!

**Comment by skawm** [comment]
Hi, after some research, just found that using a lambda function make the things happen!
like this : `scheduler.add_job(lambda: tick("tickk"), 'cron', second=15, timezone="Europe/Paris")`

hope it will help somes!

**Comment by agronholm** [comment]
Why do you not simply do `scheduler.add_job(tick, 'cron', second=15, args=['tickk'])` as indicated in the API documentation?

**Comment by skawm** [comment]
Ho, I was not able to get it working.. I didnt understood exactly what should be done.. Thanks
