### ISSUE TITLE
    PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

### ISSUE THREAD

**Issue by kitianFresh** [agronholm/apscheduler#221]
why error when i use apscheduler.add_job() in a thread? It can not use in multithreading environment?

**Comment by agronholm** [comment]
This has nothing whatsoever to do with threading. Please edit your issue to include code to reproduce the problem.

**Comment by kitianFresh** [comment]
@agronholm 
`    def post_create(self, user_cred, owner_cred, data):
        '''
        After persisting a cron job, sync to apscheduler.
        '''
        sched = cronscheduler.get_scheduler()

        if data['action']['name'] == self.CALL_SERVICE_ACTION_TYPE:
            cronjob = cronscheduler.call_service_job
        elif data['action']['name'] == self.HTTP_REQUEST_ACTION_TYPE:
            cronjob = cronscheduler.notify_job
        else:
            raise Exception('Not supported action type')

        sched.add_job(cronjob, id=self.id, trigger='cron', args=[self.action, None, None], **self.trigger)
`
above code is a orm model function execute in a thread，the scheduler is a TornadoScheduler which is in cronscheduler module, following is cronscheduler.py:

`import logging
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.schedulers.base import STATE_STOPPED, STATE_PAUSED, STATE_RUNNING
from apscheduler.schedulers.tornado import TornadoScheduler
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
from tzlocal import get_localzone
tz = get_localzone()

jobstores = {}
executors = {}
job_defaults = {}

__scheduler = None

def get_scheduler():
    global __scheduler
    if __scheduler is None:
        __scheduler = TornadoScheduler(jobstores=jobstores, executors=executors, job_defaults=job_defaults, timezone=tz)

    return __scheduler

def init(options):
    global jobstores, executors, job_defaults
    jobstores.update(
        {
            'default': SQLAlchemyJobStore(url=options.sql_connection)
        }
    )
    executors.update(
        {
            'default': {'type': 'threadpool', 'max_workers': options.thread_pool},
            'processpool': {'type': 'processpool', 'max_workers': options.process_pool}
        }
    )
    job_defaults.update(
        {
            'coalesce': options.coalesce,
            'max_instances': options.max_instances
        }
    )

    sched = get_scheduler()
    if sched.state == STATE_STOPPED:
        sched.start()
    if sched.state == STATE_PAUSED:
        sched.resume()

def stop():
    global __scheduler
    if __scheduler is not None:
        if __scheduler.state == STATE_RUNNING:
            __scheduler.shutdown()


from clouds.cron.service_client_manager import get_service_client_mananger

def notify_job(action, succ_callback, fail_callback, *args, **kwargs):
    '''
        notify subscriber to execute cron job
    '''

    print '########### notify #########', action


def call_service_job(action, succ_callback, fail_callback):
    '''
    call other service to execute the cron job
    '''
    print '########## call service %s ########' % action['service'], action['url']
    try:
        ret = get_service_client_mananger().get_service_client(action['service']).\
            request(action['method'], action['url'], succ_callback, fail_callback, body=action['data'], sync=True)
        # call service cron job status succ log
    except Exception as e:
        logging.warning('Exception: Call Service %s %s failed: %s', action['method'], action['url'], str(e))
        # call service cron job status fail log
`

**Comment by agronholm** [comment]
Seems like one of the jobs you assign for the process pool executor have unpickleable arguments. Could you simplify the code to the point where you reproduce the problem with only one job?

**Comment by kitianFresh** [comment]
@agronholm Thanks， I found that my self.action definition is     `action = Column(MutableDict.as_mutable(JSONEncodedDict), nullable=False)`,  It is unpickleable arguments. That is the reason.

**Comment by kitianFresh** [comment]
BTW, why apscheduler does not support custom define a job to store, it can only accept a callable?

**Comment by agronholm** [comment]
I don't understand. What do you mean by "custom define a job to store"?

**Comment by kitianFresh** [comment]
@agronholm , I mean why i can not customize a job's storage structure, for example, i can store more fields not just id, next_run_time and job_state.

**Comment by agronholm** [comment]
Would a `metadata` field suffice? A dict where you could place arbitrary data.

**Comment by agronholm** [comment]
Closing as the original question was resolved.

**Comment by kitianFresh** [comment]
@agronholm Sorry I am new for python, what did you mean for `metadata`,  could i inherit Job class？i found it doesn't work.
