### ISSUE TITLE
Virtual memory over consumed

### ISSUE THREAD

**Issue by zqy2084** [agronholm/apscheduler#223]
$ python --version
Python 2.7.9

$ pip freeze|grep APS
APScheduler==3.1.0

$ uname -a
Linux debian88 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

$ cat /tmp/asp.py

from apscheduler.schedulers.background import BackgroundScheduler
scheduler = BackgroundScheduler()

def f():
    print('func')

job = scheduler.add_job(f, trigger='interval', seconds=5)

if __name__ == "__main__":
    scheduler.start()
    import time;time.sleep(3000)

Run this simple apscheduler program by monitering the process in htop(better version of top), find the VIRT(virtual memory) used increased by about 70m per time that the job executed till it reach about 840M, it stop increasing.
Is this normal? Or any kind of "leaking"?
Hope someone can answer.

**Comment by agronholm** [comment]
It's the `ThreadPoolExecutor` that does it. Try limiting the maximum number of threads to 1 and you'll see VM consumption go down drastically. Note that resident memory usage (the one that really matters) stays constant in both cases.
