### ISSUE TITLE
runner  & manager applications

### ISSUE THREAD

**Issue by iAnanich** [agronholm/apscheduler#227]
Is it possible to have one host (application) as "job runner" and another one host (application) as "job manager"?

What I mean:
* "job runner" has defined jobs - functions to execute, and access to jobs store.
* "job manager" has only access to jobs store, and some user interface (web app for example).
Is it possible to change jobs triggers etc from "job manager" without having defined functions to execute?

**Comment by agronholm** [comment]
Yes, if the job manager accesses the job runner via some form of RPC. 
Examples here 
<https://github.com/agronholm/apscheduler/tree/master/examples/rpc>.


Illia Ananich kirjoitti 21.09.2017 klo 19:53:
