### ISSUE TITLE
Unrecognized expression  for field when compile 

### ISSUE THREAD

**Issue by kitianFresh** [agronholm/apscheduler#229]
when i pass an hour expression "0-2, 4-6" there will be an error Unrecognized expression  " 4-6" for field. But I think the redundant spaces should not be an error, I check your code, I found that you firstly strip spaces, split the expression by comma, then compile every segment, but when compile each segment, you just do not strip the spaces, it leads to error! 

    def compile_expressions(self, exprs):
        self.expressions = []

        # Split a comma-separated expression list, if any
        exprs = str(exprs).strip()
        if ',' in exprs:
            for expr in exprs.split(','):
                self.compile_expression(expr)
        else:
            self.compile_expression(exprs)

    def compile_expression(self, expr):
        for compiler in self.COMPILERS:
            match = compiler.value_re.match(expr)
            if match:
                compiled_expr = compiler(**match.groupdict())
                self.expressions.append(compiled_expr)
                return

        raise ValueError('Unrecognized expression "%s" for field "%s"' % (expr, self.name))

why not add a strip() just like this?

    def compile_expressions(self, exprs):
        self.expressions = []

        # Split a comma-separated expression list, if any
        exprs = str(exprs).strip()
        if ',' in exprs:
            for expr in exprs.split(','):
                self.compile_expression(expr)
        else:
            self.compile_expression(exprs)

    def compile_expression(self, expr):
        expr = str(expr).strip()
        for compiler in self.COMPILERS:
            match = compiler.value_re.match(expr)
            if match:
                compiled_expr = compiler(**match.groupdict())
                self.expressions.append(compiled_expr)
                return

        raise ValueError('Unrecognized expression "%s" for field "%s"' % (expr, self.name))

**Comment by agronholm** [comment]
Yeah, I suppose I could just remove spaces altogether. Not a big issue either way.
