### ISSUE TITLE
add_jobs function with parameters fails with error

### ISSUE THREAD

**Issue by antani** [agronholm/apscheduler#230]
I am on apscheduler-3.3.1, with a simple add_jobs example, I keep getting 
   ` ValueError: The list of positional arguments is longer than the target callable can handle (allowed: 1, given in args: 2)`

The code is:
```
scheduler = BlockingScheduler()
     scheduler.add_job(process_live_calls,'interval',args=[today_list,exchange],minutes=3,start_date=_start_date)
     scheduler.start()

```
I have tried all variations of different parameters as per docs but with every variation, this error keeps popping up

**Comment by agronholm** [comment]
Could you at least include the signature of `process_live_calls()` here?

**Comment by Keramatfar** [comment]
Similar problem.

**Comment by agronholm** [comment]
@Keramatfar not helpful. If you think there is a bug, please do a little bit of investigation and create a ticket with details that will let me resolve the problem.
