### ISSUE TITLE
[Question] Multiple application instance accessing the same Job Store

### ISSUE THREAD

**Issue by Code-ReaQtor** [agronholm/apscheduler#231]
Hi,

I just want to know what will be the behavior of APScheduler when I have multiple application instances with a BackgroundScheduler on each instance and accessing a single central Job Store (database). ***Are the jobs going to be executed on each instance or will it be "atomic" and will only be executed on one instance?***

Just checking if APScheduler is a good candidate for "distributed" applications.

Thanks a lot.

**Comment by agronholm** [comment]
This is not going to work. You must not share a job store between two schedulers. There is no built-in way to notify the other scheduler if one scheduler has added a job. Even if you had that, you would have to use distributed locks instead of in-process locks which are currently used by APScheduler.

**Comment by agronholm** [comment]
So to soften the blow, the gist is: It's theoretically possible but is not currently supported.

**Comment by Code-ReaQtor** [comment]
@agronholm Thanks a lot!

Will there be any chance that this will be added to future releases? The use case is to make it distributed or to create microservices out of it so that if some of the instances (machines) goes down there will still be other instances running - horizontally scalable.

**Comment by pranav93** [comment]
@Code-ReaQtor , I'm using `TornadoScheduler` with `SQLAlchemyJobStore`. We are having different table for each running app.
sample code
```
jobstores = {
    'default': SQLAlchemyJobStore(
        url=config.SQLALCHEMY_DATABASE_URI,
        tablename=os.environ.get('PROCESS_TABLE_NAME'),
    )
}

scheduler = TornadoScheduler(
    jobstores=jobstores,
    executors=config.EXECUTORS,
    job_defaults=config.JOB_DEFAULTS,
    replace_existing=config.REPLACE_EXISTING
)
```
Here you can see that we are having same DB but each of the app has its own table provided through config.

**Comment by agronholm** [comment]
@Code-ReaQtor not in the near future at least. I have little personal interest in this and I don't easily see anyone else taking on such a major task.

**Comment by Code-ReaQtor** [comment]
@pranav93 thanks for the idea. It doesn't fit though on our use case - scaling. I'll check if this will help as a workaround.

@agronholm I see. Thanks a lot.

**Comment by navwork** [comment]
@agronholm Do you expect any issues with using the same Redis DB with multiple schedulers while using unique `jobs_key` and `runtime_times_key` values per scheduler handling separate jobs. I tool a quick look at the code and it seems fine to me. What do you say?

**Comment by agronholm** [comment]
That should isolate the schedulers from each other, but why not use separate dbs to begin with?

**Comment by dariosm** [comment]
@agronholm I'm using a single instance of `apscheduler` with a mongodb backend setup in an application. 
Thing is, probably related to the original post here, I'm running multiple replicas of my application and my expectation was to share the same backend for the scheduler created by the each app.
I wonder if this is still not in the roadmap, or if is there any workaround to handle scenarios like this. Thanks in advance.

**Comment by agronholm** [comment]
You should track #256 and #465.

**Comment by dariosm** [comment]
Will do, thanks @agronholm
