### ISSUE TITLE
Help for scheduling a new job while async main function is running

### ISSUE THREAD

**Issue by dhmk815** [agronholm/apscheduler#232]
Hello.
This is a question about using AsyncScheduler. Actually, this is not an issue. I thought it would be faster to get reply from here than asking in other communities. Hope you give me some advice to use it.

Here is my original code, actually pseudo code.

```
import asyncio

urls = ['http://blabla1', 'http://blabla2']

async def fetchDataUsingHttpReqeust():
    data = await apiCallLib.fetchData()
    return data
    
async def async_main():
    while True:
            try:
                futures = [asyncio.ensure_future(fetchDataUsingHttpReqeust(url)) for url in urls]
                results = await asyncio.gather(*futures)

                ### doing something with the results from async http requests

               
            except Exception as e
                await asyncio.sleep(4)
            
        
loop = asyncio.get_event_loop()
ret = loop.run_until_complete(async_main())
```

The main function, `async_main`, is running forever with no specific period. It can't be scheduled using your library, because we don't know when fetching tasks(`fetchDataUsingHttpRequest()`) finish. As you can see `while true:` in `async_main()` function, this coroutine task is running forever on an event loop.

**While this main function is running, I'd like to schedule a job which runs every 2 seconds to check some other variables.**

At first, I considered to implement this job using `BackgroundScheduler' which runs in a different thread.
But, I am not sure that approach works efficiently.

So, I am considering to use `AsyncScheduler`, but I don't know how to use the `AsyncScheduler` and how it works in my main coroutine `async_main()`.

In your example sources, I found that the new event loop should be generated.
Could you explain how to integrate `AsyncScheduler` into my async process?

**Comment by agronholm** [comment]
Have you looked at [this ](https://github.com/agronholm/apscheduler/blob/master/examples/schedulers/asyncio_.py) example?

**Comment by dhmk815** [comment]
@agronholm Yes I have saw it. But, I don't know how to integrate with my code.... Actually, I am not sure how asyncscheduler is working and what's the relation between it and event loop.

**Comment by agronholm** [comment]
The [asyncio scheduler](https://github.com/agronholm/apscheduler/blob/master/apscheduler/schedulers/asyncio.py) uses the event loop to wake it up in time to process the next job. Also, its default executor, [AsyncIOExecutor](https://github.com/agronholm/apscheduler/blob/master/apscheduler/executors/asyncio.py), uses the event loop to run any coroutine based jobs.

**Comment by agronholm** [comment]
@dhmk815 do you still require help with this?
