### ISSUE TITLE
BUG!! Apscheduler modify do not work when you update a cron job from later to early

### ISSUE THREAD

**Issue by kitianFresh** [agronholm/apscheduler#234]
I found a bug that, if you firstly add a cron style job which will be scheduled at tomorrow, such as     `notify_job (trigger: cron[day_of_week='0-6', hour='0-2', minute='0-59', second='0-59'], next run at: 2017-10-25 00:00:00 CST)`

then if you modify it by early, such as `notify_job (trigger: cron[day_of_week='0-6', hour='*/', minute='*/5', second='*/20'], next run at: 2017-10-25 00:00:00 CST)`
 
it will think hour  is tomorrow; it does not work!!! following is my code snippet, it is dangerous！

    task1 = scheduler.add_job(job_func, trigger='cron', day_of_week='0-6', hour='19,21', minute='*/5', second='0,10,20,30,30,40,40,50', args=[action, 'disk1', 'disk1'], end_date='2017-12-30')
    job_func = clouds.cron.jobs.notify_job
    task2 = scheduler.add_job(job_func, trigger='cron', day_of_week='0-6', hour='0-2', minute='0-59', second='0-59', args=['disk2', succ_callback, fail_callback])
    task3 = scheduler.add_job(job_func, trigger='interval', seconds=20, args=['disk3', succ_callback, fail_callback])

    scheduler.print_jobs()

    time.sleep(5)
    scheduler.remove_job(task3.id)

    scheduler.print_jobs()

    time.sleep(5)

    from apscheduler.triggers.cron import CronTrigger
    trigger = CronTrigger(day_of_week='0-6', hour='*', minute='*/5', second='*/20', end_date='2017-10-31')
    # import pdb
    # pdb.set_trace()
    scheduler.modify_job(task2.id, trigger=trigger, args=[action, succ_callback, fail_callback], coalesce=True)
    # scheduler.reschedule_job(task2.id)

    print scheduler.get_job(task2.id)

    time.sleep(10)
    print 'pausing......'
    scheduler.pause()

    time.sleep(5)
    print 'resuming......'
    scheduler.resume()

        
output：

    The job 2119531081404a19bf9366df356a9688 added
    The job bb46475c58684677971a43d39541006e added
    The job 544f0b1203e74f68be3c3b0af3c18d7b added
    Jobstore default:
        notify_job (trigger: interval[0:00:20], next run at: 2017-10-24 19:58:47 CST)
        job (trigger: cron[day_of_week='0-6', hour='19,21', minute='*/5', second='0,10,20,30,30,40,40,50'], next run at: 2017-10-24 21:00:00 CST)
        notify_job (trigger: cron[day_of_week='0-6', hour='0-2', minute='0-59', second='0-59'], next run at: 2017-10-25 00:00:00 CST)
    The job 544f0b1203e74f68be3c3b0af3c18d7b removed
    Jobstore default:
        job (trigger: cron[day_of_week='0-6', hour='19,21', minute='*/5', second='0,10,20,30,30,40,40,50'], next run at: 2017-10-24 21:00:00 CST)
        notify_job (trigger: cron[day_of_week='0-6', hour='0-2', minute='0-59', second='0-59'], next run at: 2017-10-25 00:00:00 CST)
    The job bb46475c58684677971a43d39541006e modified
    notify_job (trigger: cron[day_of_week='0-6', hour='*', minute='*/5', second='*/20'], next run at: 2017-10-25 00:00:00 CST)
    pausing......
    resuming......

I also query mysql database to make sure it is, and the time in next_run_time always keep the same in tomorrow!

**Comment by agronholm** [comment]
It's not clear whether you are actually calling `scheduler.reschedule_job(...)`. If you're not, you should not expect it to work correctly.

**Comment by kitianFresh** [comment]
@agronholm  But even though i use reschedule_job, it do not work either！

    job_func = clouds.cron.jobs.notify_job
    task2 = scheduler.add_job(job_func, trigger='cron', day_of_week='0-6', hour='10,13,14', minute='0-59', second='0-59', args=['disk2', succ_callback, fail_callback], end_date='2017-11-01 13:38:00')
    # task3 = scheduler.add_job(job_func, trigger='interval', seconds=20, args=['disk3', succ_callback, fail_callback])

    scheduler.print_jobs()

    # time.sleep(5)
    # scheduler.remove_job(task3.id)

    # scheduler.print_jobs()


    time.sleep(5)

    from apscheduler.triggers.cron import CronTrigger
    trigger = CronTrigger(day_of_week='0-6', hour='13,14,15', minute='*/2', second='*/20', end_date='2017-11-01 13:57:00')
    scheduler.reschedule_job(task2.id, trigger=trigger, args=[action, succ_callback, fail_callback], coalesce=True,misfire_grace_time=600,
                        max_instances=256)

    print scheduler.get_job(task2.id)

    from tzlocal import get_localzone
    tz = get_localzone()
    now = datetime.datetime.utcnow()

    t = time.strptime("2017-10-24T12:36:18Z", "%Y-%m-%dT%H:%M:%SZ")
    dt = datetime.datetime.fromtimestamp(time.mktime(t))
    print type(trigger.end_date), type(now)
    if dt < now:
        print dt,now
    time.sleep(10)
    print 'pausing......'
    scheduler.pause()   

    time.sleep(5)
    print 'resuming......'
    scheduler.resume()

following is the output, and i check database, next_run_time is null; I use UTC timezone not local

    /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/kiki/PycharmProjects/async/main.py
    Asia/Shanghai
    The job 018e88080a2b4a8eb793d94fe29b128c added
    Jobstore default:
        notify_job (trigger: cron[day_of_week='0-6', hour='10,13,14', minute='0-59', second='0-59'], paused)
    The job 018e88080a2b4a8eb793d94fe29b128c modified
    notify_job (trigger: cron[day_of_week='0-6', hour='13,14,15', minute='*/2', second='*/20'], paused)
    <type 'datetime.datetime'> <type 'datetime.datetime'>
    2017-10-24 12:36:18 2017-11-01 13:39:32.472049
    pausing......
    resuming......

**Comment by kitianFresh** [comment]
I think reschedule  and modify job is very buggy!

**Comment by agronholm** [comment]
Where are you starting the scheduler? No tasks are scheduled until the scheduler is running.

**Comment by kitianFresh** [comment]
@agronholm resume is not restart? so you mean i need resume and start

**Comment by kitianFresh** [comment]
I use a TornadoScheduler, and I put above code in a callback function in tornado loop. 

    tz = get_localzone()
    print tz
    from pytz import UTC
    scheduler = TornadoScheduler(jobstores=jobstores, executors=executors, job_defaults=job_defaults, timezone=UTC)
    scheduler.add_listener(my_listener,
                                EVENT_JOB_ADDED | EVENT_JOB_SUBMITTED | EVENT_JOB_EXECUTED | EVENT_JOB_ERROR | EVENT_JOB_REMOVED | EVENT_JOB_MODIFIED | EVENT_JOB_MISSED)

    from clouds.cron.models import tornado_sched

    scheduler._ioloop.add_callback(tornado_sched.callback)

    scheduler.start()

    scheduler._ioloop.start()

and in the callback in tornado_sched module, i started a thread to add some job.

    def callback():

        def add_job(*args):
            succ_callback = clouds.cron.jobs.succ_callback
            fail_callback = clouds.cron.jobs.fail_callback
            job_func = clouds.cron.jobs.job
            # task1 = scheduler.add_job(job_func, trigger='cron', day_of_week='0-6', hour='19,21', minute='*', second='0,10,20,30,30,40,40,50', args=[action, 'disk1', 'disk1'], end_date='2017-10-31T21:25:00Z')
            job_func = clouds.cron.jobs.notify_job
            task2 = scheduler.add_job(job_func, trigger='cron', day_of_week='0-6', hour='2,3,4', minute='0-59', second='0-59', args=['disk2', succ_callback, fail_callback], end_date='2017-11-02 02:39:00')
            # task3 = scheduler.add_job(job_func, trigger='interval', seconds=20, args=['disk3', succ_callback, fail_callback])

            scheduler.print_jobs()

            # time.sleep(5)
            # scheduler.remove_job(task3.id)

            # scheduler.print_jobs()


            time.sleep(5)

            from apscheduler.triggers.cron import CronTrigger
            trigger = CronTrigger(day_of_week='0-6', hour='2,3,4', minute='*/2', second='*/20', end_date='2017-11-02 02:57:00')
            # import pdb
            # pdb.set_trace()
            # scheduler.modify_job(task2.id, trigger=trigger, args=[action, succ_callback, fail_callback], coalesce=True)
            scheduler.reschedule_job(task2.id, trigger=trigger, args=[action, succ_callback, fail_callback], coalesce=True,misfire_grace_time=600,
                            max_instances=256)

            print scheduler.get_job(task2.id)

            from tzlocal import get_localzone
            tz = get_localzone()
            now = datetime.datetime.utcnow()

            t = time.strptime("2017-10-24T12:36:18Z", "%Y-%m-%dT%H:%M:%SZ")
            dt = datetime.datetime.fromtimestamp(time.mktime(t))
            print type(trigger.end_date), type(now)
            if dt < now:
                print dt,now
            time.sleep(10)
            print 'pausing......'
            scheduler.pause()

            time.sleep(5)
            print 'resuming......'
            scheduler.resume()
            scheduler.start()



        t = threading.Thread(target=add_job)
        t.start()

**Comment by agronholm** [comment]
You are checking before the scheduler start if a job has been scheduled. But that won't do anything as the scheduler needs to be started before any job gets their first scheduled run time.

**Comment by agronholm** [comment]
You should not start TornadoScheduler in a thread, but in the Tornado I/O loop thread.

Also, did you read my previous message? I told you that the scheduling only happens when the scheduler is running, so trying to check the next run time before that is pointless.

**Comment by kitianFresh** [comment]
@agronholm  I FOUND reschedule_job function can not modify job's function args parameter, right?

    sched.reschedule_job(self.id,
                         name=self.name,
                         misfire_grace_time=options.misfire_grace_time,
                         max_instances=options.max_instances,
                         coalesce=options.coalesce,
                         trigger=trigger,
                         func=cronjob,
                         args=[data['action'],None,None])

just trigger is valid, other do not! so if i want to modify and take effective  immediately， I must first use modify and then use reschedule

**Comment by agronholm** [comment]
It's not a bug, this is how it's supposed to work. The keyword arguments are meant for instantiating the trigger. Had you read the documentation for [reschedule_job()](http://apscheduler.readthedocs.io/en/latest/modules/schedulers/base.html#apscheduler.schedulers.base.BaseScheduler.reschedule_job), you would have known this.
