### ISSUE TITLE
Memory leak when worker raises an exception

### ISSUE THREAD

**Issue by meowcakes** [agronholm/apscheduler#235]
Hello,

If a worker raises an exception and it isn't handled, the memory used by the worker will not be released.

This can be reliably reproduced by the following code snippet:

```python
from apscheduler.schedulers.background import BlockingScheduler

def bar():
    a = [{i: i + 2} for i in range(10000000)]
    for (k, v) in a.items():
        a[k] = v + 5

def foo():
    scheduler = BlockingScheduler({
        'apscheduler.executors.default': {
            'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
            'max_workers': '20'
        },
        'apscheduler.job_defaults.coalesce': 'false',
        'apscheduler.job_defaults.max_instances': '1',
        'apscheduler.timezone': 'UTC'
    })

    scheduler.add_job(bar, trigger='cron', minute='*')
    scheduler.start()

foo()
```

Thanks

**Comment by agronholm** [comment]
How did you determine that there is a memory leak? Does the amount of resident memory keep rising without end?

**Comment by agronholm** [comment]
Also, just to make sure we're on the same page, that script does not call `foo()`. Is there anything else besides the call missing?

**Comment by meowcakes** [comment]
Sorry, I overlooked the missing call to `foo()` and have updated my comment to put it in. Yes, it was the only thing missing and the snippet alone is enough to reproduce the issue.

In order to show that there is a memory leak I closed all open programs, ran the script and observed memory usage. Resident (and then swap) memory kept rising without end, displaying a pattern of step changes at 60 second intervals consistent with the cron setting in my code snippet. Here is a screenshot:

![a](https://user-images.githubusercontent.com/3435150/32130090-239a0cb8-bbdd-11e7-8eb8-f98718188c6f.png)

**Comment by agronholm** [comment]
I can reproduce the leak, even with a single worker thread. It's probably a reference loop somewhere.

**Comment by agronholm** [comment]
Hm, strange. Now I'm stumped. Can't reproduce it anymore. Here's the code I was using:

```python
import logging
from apscheduler.schedulers.background import BlockingScheduler
from pympler import muppy, summary

def bar():
    all_objects = muppy.get_objects()
    sum1 = summary.summarize(all_objects)
    summary.print_(sum1)

    a = [{i: i + 2} for i in range(100000)]
    for (k, v) in a.items():
        a[k] = v + 5


def foo():
    scheduler = BlockingScheduler({
        'apscheduler.executors.default': {
            'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
            'max_workers': '1'
        },
        'apscheduler.job_defaults.coalesce': 'false',
        'apscheduler.job_defaults.max_instances': '1',
        'apscheduler.timezone': 'UTC'
    })
    logging.basicConfig()

    scheduler.add_job(bar, trigger='cron', second='*/10')
    scheduler.start()

foo()
```

**Comment by agronholm** [comment]
Memory usage stabilizes within the first minute. According to pympler, the number of objects does not grow either. Can you verify?

**Comment by meowcakes** [comment]
I also get stable memory usage when running your code.

I'm assuming `muppy.get_objects` performs a garbage collection at some point, because the memory usage stabilises after it alone is added to `bar`, and I can produce the same results by adding a `gc.collect()` to the beginning of `bar`.

Also, when performing a garbage collection, the memory usage caps out at a level that is proportional to the value of `max_workers`.

**Comment by agronholm** [comment]
Ok, I nailed it. I just had to delete the traceback object in `run_job()`. That fixes the problem. Patch is coming once I figure out how to add a meaningful test for this.

**Comment by agronholm** [comment]
Nope, that only solved the problem for Python 2. I'm still seeing a steady grow in memory use on Python 3.

**Comment by gilbsgilbs** [comment]
I also experienced this issue. I noticed SQLAlchemy connection leaks and it turned out it was a GC issue (cyclic references in traceback objects) caused by some APScheduler jobs raising exceptions.

@agronholm For what it's worth: in py3, tracebacks are also emebedded in the exception object. I managed to fix the leak by calling `traceback.clear_frames(exc.__traceback__)` in addition to deleting the traceback object.

```python
@@ -134,4 +137,10 @@ def run_job(job, jobstore_alias, run_times, logger_name):
                                             retval=retval))
             logger.info('Job "%s" executed successfully', job)
 
-    return events
+    try:
+        return events
+    finally:
+        if six.PY3:
+            traceback.clear_frames(exc.__traceback__)
+        del tb
```

If we need a clean `__traceback__` later on (which I don't think because it's unsupported on PY2 anyways), it's still possible to override `__del__` method from `JobExecutionEvent` and delete instances manually in `_run_job_success`. Hope that helps.

There's the same kind of potential leak in `_do_submit_job` callback. Everytime a traceback object is referenced (or an exception in PY3), it should be deleted manually.

**Comment by agronholm** [comment]
When using `traceback.clear_frames(tb)`, the problem seems gone on Python 3 but persists on Python 2. I'm stumped. A traceback object that should have been gc'd is still seen by the garbage collector.

**Comment by agronholm** [comment]
Nailed it. I was just missing the `sys.exc_clear()` call.

**Comment by agronholm** [comment]
@gilbsgilbs Can I get your real name so I can give you credit in the changelog? Your patch helped me get to the right solution.

**Comment by gilbsgilbs** [comment]
@agronholm Please, call me `gilbsgilbs` in the changelog if you don't mind putting nicknames in it.

**Comment by agronholm** [comment]
Okay.
