### ISSUE TITLE
No job by the id of { job_id } was found

### ISSUE THREAD

**Issue by HarveyJiang** [agronholm/apscheduler#237]
hi，
i get a apscheduler.jobstores.base.JobLookupError if i use date trigger and jobstores use MongoDBJobStore, if use MemoryJobStore no error.

use this  code , now you open four shell type python demo.py. 
a shell is ok
a shell is error, process crash
two shell not work

`
import datetime
import logging
import sys
import time

from apscheduler.executors.pool import ProcessPoolExecutor, ThreadPoolExecutor
from apscheduler.jobstores.memory import MemoryJobStore
from apscheduler.jobstores.mongodb import MongoDBJobStore
from apscheduler.schedulers.blocking import BlockingScheduler
from pymongo import MongoClient

logging.basicConfig()

jobstores = {
    # 'default'      : MemoryJobStore(),
    'default': MongoDBJobStore(
            collection='job',
            database='test',
            client=MongoClient('127.0.0.1', 27017))}
executors = {
    'default'    : ThreadPoolExecutor(10),
    'processpool': ProcessPoolExecutor(3)
}
job_defaults = {
    'coalesce'     : False,
    'max_instances': 10
}
scheduler = BlockingScheduler(
        jobstores=jobstores,
        executors=executors,
        job_defaults=job_defaults)

def my_job():
    print 'begin ', datetime.datetime.now()
    time.sleep(5)
    print 'end ', datetime.datetime.now()
run_date = datetime.datetime.now() + datetime.timedelta(seconds=20)
job = scheduler.add_job(my_job, 'date', run_date=run_date, id='my_test', replace_existing=True)
print job.trigger

try:
    scheduler.start()
except SystemExit:
    sys.exit(0)
`

**Comment by agronholm** [comment]
Would you mind pasting the code in a properly formatted manner?

**Comment by HarveyJiang** [comment]
i'm sorry.
[apscheduler_demo.zip](https://github.com/agronholm/apscheduler/files/1415149/apscheduler_demo.zip)

**Comment by agronholm** [comment]
I ran it and did not get an error. Could you post the traceback?

**Comment by HarveyJiang** [comment]
I guess maybe the two process is going to delete job at the same time。


```   
λ  python .\test_demo.py
date[2017-10-26 19:51:00 CST]
begin  Traceback (most recent call last):
  File ".\test_demo.py", line 47, in <module>
2    017-10-26 19:51:04.298000scheduler.start()

  File "D:\portable\Python27\lib\site-packages\apscheduler\schedulers\blocking.py", line 19, in start
    self._main_loop()
  File "D:\portable\Python27\lib\site-packages\apscheduler\schedulers\blocking.py", line 30, in _main_loop
    wait_seconds = self._process_jobs()
  File "D:\portable\Python27\lib\site-packages\apscheduler\schedulers\base.py", line 985, in _process_jobs
    self.remove_job(job.id, jobstore_alias)
  File "D:\portable\Python27\lib\site-packages\apscheduler\schedulers\base.py", line 613, in remove_job
    raise JobLookupError(job_id)
apscheduler.jobstores.base.JobLookupError: u'No job by the id of my_test was found'
end  2017-10-26 19:51:09.305000
```

Change this is ok ,But I don't know if there are any other hidden dangers
```

        # schedulers\base.py line 613 
        # if jobstore_alias is None:
        #     raise JobLookupError(job_id)
        if jobstore_alias: 
            # Notify listeners that a job has been removed
            event = JobEvent(EVENT_JOB_REMOVED, job_id, jobstore_alias)
            self._dispatch_event(event)

            self._logger.info('Removed job %s', job_id)
```

**Comment by agronholm** [comment]
This cannot happen since the worker processes do not access the job database.

**Comment by agronholm** [comment]
Besides, you're not even using the process pool executor you defined in the script.

**Comment by agronholm** [comment]
Are you sure you are not running two schedulers against the same data store?

**Comment by HarveyJiang** [comment]
I have four docker run script, and same job store.

**Comment by agronholm** [comment]
You must **NEVER** run multiple schedulers against the same job store! This will cause huge problems.

**Comment by HarveyJiang** [comment]
Oh, Thanks. multiple crawler scheduling requires multiple job store。One-to-one correspondence 。

**Comment by agronholm** [comment]
Why not use a single scheduler to schedule all that, and have multiple worker processes to run that crawlers?

**Comment by HarveyJiang** [comment]
Because current environment it's deployed in four docker。

**Comment by agronholm** [comment]
Well, you need to find a way to run just a single scheduler, or use multiple job stores.
