### ISSUE TITLE
Feature: Enable creation of CronTrigger directly from cron-style string

### ISSUE THREAD

**Issue by luc-tielen** [agronholm/apscheduler#240]
Would it be possible to add a helper function somewhere that generates a CronTrigger directly from a cron-style string (possibly even for both 'traditional' and 'enhanced' formats as described at http://www.nncron.ru/help/EN/working/cron-format.htm)?

This could for example be done by adding a static method to the CronTrigger class and adding some parsing logic in there..

**Comment by agronholm** [comment]
What is the use case here that isn't covered by the usual means of creating cron-based jobs?

**Comment by luc-tielen** [comment]
Convenience? Would allow easier porting from a traditional crontab.
For now I do it using the current way via the named params; but previous system I'm working on used cronjobs (together with that syntax) so now I'm constantly converting from one format to the other (+ error checks etc).

**Comment by luc-tielen** [comment]
Very cool, thanks!
