### ISSUE TITLE
How to force execution of a periodic scheduler?

### ISSUE THREAD

**Issue by Stibbons** [agronholm/apscheduler#241]
Let's say I have a periodic task scheduled every day. I'd like to give the ability of the user of running it manually. It may be a long task so I would like to use the lock provided by `max_instances=1`. Is there an API to do so?

**Comment by agronholm** [comment]
There is not, unfortunately. If this is a requirement, consider using a lock within the target function.

**Comment by Stibbons** [comment]
Wouldn't be a legit feature? Something like `scheduler.force_start(job_id)` ?

**Comment by agronholm** [comment]
I'll think about it if you type it up as a feature request in a new issue.
