### ISSUE TITLE
Accessing a 'package' global variable from the inside the 'package:function'

### ISSUE THREAD

**Issue by sudhesam** [agronholm/apscheduler#243]
Hello,

I have this use case where I am using apscheduler -func <package:function> to be scheduled as a 'cron' job.

There are some routines within the package that runs in another thread and sets a global variable (in the background).

Now, when the scheduler schedules to run the function, I need to access a global variable that is set.  Is there a way to do this in apscheduler ?
Right now, when I print the value of the variable when the function is scheduled, it is empty (the global variable is a dictionary that I am accessing).
Any help appreciated.

**Comment by agronholm** [comment]
While this problem has nothing really to do with apscheduler, I'll try to help you anyway. Apparently the problem you have is a race condition. Have you considered using a `Future` (from the `concurrent.futures` standard library module) to coordinate between your threads? By waiting on the future you can ensure that the value won't be accessed before it's ready.

**Comment by sudhesam** [comment]
If I call the function (i.e. scheduled through the scheduler) from another function within the same file, it is able to get access to the global variable.

Example:
mydict = {'a':1}

def foo(myarg):
    ''' Schedule this function'''
   print(mydict)      <<<------ Returns {} when scheduled.  However, prints the value of mydict when called
                               <<<------ from within 'bar()'

def bar():
   foo(1)

**Comment by agronholm** [comment]
Are you saying that this is not a timing problem? If not, then I can't quite understand what you're saying. If your code looks like that and you set `mydict = {'a': 1}` on the module level already, then what code sets it to an empty dict then?

**Comment by sudhesam** [comment]
Thanks for your reply.

I think, I have proved that in my situation this method will NOT work.  This is  because the global dictionary variable address space is mapped different where it is accessed through the scheduler and where its value is set.  However, I am trying to create a small test scenario.  I will upload the scenario.  Appreciate if you can take a look at it and confirm, that will help.

Thanks again.

**Comment by sudhesam** [comment]
Sorry, I misspoke in my example.  myDict = {'a': 1} is initially set to empty dictionary and another function within the module will set the value.

**Comment by sudhesam** [comment]
Below is a small use case:

linux:/tmp/ssam # ls -l
total 8
-rw-r--r-- 1 root root    0 Nov 14 17:47 __init__.py
drwxr-xr-x 2 root root 4096 Nov 14 18:17 __pycache__
-rwxr-xr-x 1 root root 1235 Nov 14 18:17 foo.py
=====================================================
linux:/tmp/ssam # cat foo.py
#!/usr/bin/env python3

"""
Perform scheduling operations

"""
from __future__ import print_function
import datetime
import logging
from logging.handlers import RotatingFileHandler
from pySmg import apscheduler_wrapper

hw = ""

db_file = "/opt/samsung/scheduler/db/jobs.db"
log_file = "/var/log/samsung/sfm-sched.log"

def func_foo(myvar):
    print("Inside foo_func")
    print("ID of hw in FUNC_FOO() = ", id(hw))
    print("hw = ", hw)
    print(hw)

def func_bar():
    global hw
    hw = "Hello World!!!"
    print("In bar()...")
    print("ID of hw in FUNC_BAR() = ", id(hw))
    print(hw)

def sched_start():

    try:
        logger = logging.getLogger("apscheduler.executors.default")
        my_handler = RotatingFileHandler(log_file, maxBytes=10*1024*1024)

        logger.addHandler(my_handler)
        logger.setLevel(logging.INFO)

        scheduler = apscheduler_wrapper.apscheduler_class(db_file, keepalive=10)

        # Start processing registered jobs and wait
        scheduler.start()

    except (KeyboardInterrupt, SystemExit):
        print("\n")
        pass

    scheduler.close()
    print("Done.")

    return


# Start program
if __name__ == "__main__":
    func_bar()
    # func_foo(1)
    sched_start()
linux:/tmp/ssam #

=====================================================

Running foo.py, to set the global variable and then start the scheduler:
------------------------------------------------------------------------
linux:/tmp/ssam # python3 foo.py
In bar()...
ID of hw in FUNC_BAR() =  139949844188976
Hello World!!!
SCHEDULER: Open...
SCHEDULER: Started...
SCHEDULER: Running...
...
...
...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Below is how I am scheduling the job in the database.

We have a 'CLI' to accept the arguments and create a job in the database.

linux:/tmp/ssam # /opt/samsung/scheduler/bin/apscli add -type cron -func 'foo:func_foo' -fargs 1 -id 1 -seconds 10 -start_date '2017-11-14 18:24:00' -end_date '2017-11-14 18:24:00'


SCHEDULER: Open...


SCHEDULER: Added:
JOB:    cron
        func:           <function func_foo at 0x7f6bcde19d90>
        args:           1
        id:             1
        name:           func_foo
        max_instances:  1
        year:           *
        month:          *
        week:           *
        day_of_week:    *
        day_of_month:   *
        hour:           *
        minute:         *
        second:         *
        start_date:     2017-11-14 18:24:00
        end_date:       2017-11-14
        apjob:          func_foo (trigger: cron[], next run at: 2017-11-14 18:24:00 UTC)

SCHEDULER: Job count = 1
SCHEDULER: Closed.
Done.
linux:/tmp/ssam # date
Tue Nov 14 18:23:53 UTC 2017
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Below is the output when the scheduler picks up the job @ 18:24:00 and runs the func_foo().

linux:/tmp/ssam # python3 foo.py
In bar()...
ID of hw in FUNC_BAR() =  139949844188976
Hello World!!!
SCHEDULER: Open...
SCHEDULER: Started...
SCHEDULER: Running...
Inside foo_func
ID of hw in FUNC_FOO() =  139949845796936
hw =

**Comment by sudhesam** [comment]
I also tried the following : 

1.  Separate func_foo() and func_bar() into 2 different files (foo.py and bar.py)
2.  Create settings.py and define hw = ""
3.  Import settings.py in both files
4.  Set the value of 'hw' (to 'Hello World') in func_foo (foo.py) and start the scheduler
    (to read the job from the database)
5.  Run 'apscli' (our wrapper script to add jobs to database) to add "-func bar:func_bar" to jobs db
6.  Print the value of 'hw' in func_bar (bar.py).

This prints empty string for 'fw' and id(hw) is different in foo.py (where the value is set) and bar.py (where the value is printed).

**Comment by agronholm** [comment]
Would you mind wrapping your code in a code block so github doesn't mess up the indentation?

**Comment by sudhesam** [comment]
`#!/usr/bin/env python3

"""
Perform scheduling operations

"""
from __future__ import print_function
from datetime import datetime
import logging
from logging.handlers import RotatingFileHandler
from pySmg import apscheduler_wrapper

hw = ""

db_file = "/opt/samsung/scheduler/db/jobs.db"
log_file = "/var/log/samsung/sfm-sched.log"

def func_foo(myvar):
    print("Inside foo_func")
    print("ID of hw in FUNC_FOO() = ", id(hw))
    print("hw = ", hw)
    print(hw)

def func_bar():
    global hw
    hw = "Hello World!!!"
    print("In bar()...")
    print("ID of hw in FUNC_BAR() = ", id(hw))
    print(hw)

def sched_start():

    try:
        logger = logging.getLogger("apscheduler.executors.default")
        my_handler = RotatingFileHandler(log_file, maxBytes=10*1024*1024)

        logger.addHandler(my_handler)
        logger.setLevel(logging.INFO)

        scheduler = apscheduler_wrapper.apscheduler_class(db_file, keepalive=10)

        # Start processing registered jobs and wait
        scheduler.start()

    except (KeyboardInterrupt, SystemExit):
        print("\n")
        pass

    scheduler.close()
    print("Done.")

    return


# Start program
if __name__ == "__main__":
    func_bar()
    # func_foo(1)
    sched_start()
`

**Comment by sudhesam** [comment]
I did use 'insert code' in the menu above.  It seems like the indentation gets messed up even after I quote it.

**Comment by agronholm** [comment]
I just wanted you to edit your previous comment, not post a new one. This one didn't work either (as you can see). Use triple quotes with "python" after them, like this:
```python
def func_foo(myvar):
    print("Inside foo_func")
    print("ID of hw in FUNC_FOO() = ", id(hw))
    print("hw = ", hw)
    print(hw)
```

**Comment by sudhesam** [comment]
Sorry, this is the first time I am posting something on github asking for help.  So, please bear with me.

**Comment by agronholm** [comment]
The "Preview" tab is your friend here.

**Comment by sudhesam** [comment]
Got it.  Thanks and sorry for the mess up.

**Comment by sudhesam** [comment]
Here is another interesting finding (at least for me) when it comes to globals in python:

('In settings.py id of x ->', 17428848)          >>>> ID of a variable is different in settings.py.
====
('In subfile.py id of settings.x =>', 17428824)
====
1
----
('In main.py id of settings.x', 17428824)
----

**Comment by sudhesam** [comment]
```
# settings.py
x = 0
print("In settings.py id of x ->", id(x))

# subfile.py
import settings

settings.x = 1
print("====")
print("In subfile.py id of settings.x =>", id(settings.x))
print("====")

# main.py
import settings
import subfile

print(settings.x)
print("----")
print("In main.py id of settings.x", id(settings.x))
print("----")

**Comment by agronholm** [comment]
Why is this surprising? You're first calling `id(0)` and it gives you one number, and then you call `id(1)` twice and it gives you a different number twice.

**Comment by sudhesam** [comment]
copy-paste error.

**Comment by sudhesam** [comment]
Just curious to know your findings on my test case.  Thanks.

**Comment by agronholm** [comment]
I was already going to sleep at that time and I have a busy day today. I will check it when I can.

**Comment by sudhesam** [comment]
Thanks for the update.

**Comment by agronholm** [comment]
I looked at the code but since there are pieces that I cannot see, it's hard for me to figure out why the hw IDs are different. Could you write a script that exhibits the same problem but which I could run too? That would make this at least possible for me to solve.

**Comment by sudhesam** [comment]
Working on the script.  I will upload it soon.

**Comment by sudhesam** [comment]
Haven't had a chance to work on the script.  Hopefully, I will be able to work on it sometime today.  Will keep you updated.

**Comment by sudhesam** [comment]
Below is the version of how we are invoking the scheduler.  The order of execution is :  First add the job by running addjob2db.py and then run foo.py.

-Sudhe

**Comment by sudhesam** [comment]
```
#!/usr/bin/env python3
#
#  foo.py
#
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.executors.pool import ThreadPoolExecutor, ProcessPoolExecutor
from apscheduler.util import undefined
from pytz import utc
from datetime import datetime

import time

hw = ""

scheduler = None
db_file = 'jobs.db'

def func_a(myargs):
    print("func_a: myargs = ", myargs)
    print("Read value of hw = ", hw)

def func_b():
    global hw
    hw = "Hello World!"
    print("Set value of hw = ", hw)

if __name__ == "__main__":

    # Set global variable
    func_b()

    try:
        jobstores = {
            'default': SQLAlchemyJobStore(url='sqlite:///%s' % db_file)
        }

        executors = {
            'default': ThreadPoolExecutor(20)
        }

        job_defaults = {
            'coalesce': True,
            'misfire_grace_time':1,
            'max_instances': 1,
            'replace_existing':True,
        }

        #global scheduler
        scheduler = BackgroundScheduler(jobstores=jobstores, executors=executors, job_defaults=job_defaults, timezone=utc)

        # Start processing registered jobs and DO NOT wait
        print("Starting scheduler...")
        scheduler.start()

    except (KeyboardInterrupt, SystemExit):
        pass

    while True:
        time.sleep(1)

```

**Comment by sudhesam** [comment]
```
#!/usr/bin/env python3

"""
addjob2db.py

addjob2db: Perform scheduling operations

"""
from __future__ import print_function

import os
import argparse
import json
from pytz import utc
from datetime import datetime
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.executors.pool import ThreadPoolExecutor
from apscheduler.util import undefined

db_file = 'jobs.db'

def jobadd(scheduler, args):
    if args.func is None:
        print("ERROR: No system call specified.")
        return

    if args.type == 'cron':

        if args.id is not None:
            id = args.id

        if args.func is not None:
            func = args.func

            arg_list = args.fargs.split(' ')

        print(args)
        name     = "foo"
        max_instances = 1

        start_date = args.start_date
        end_date   = args.end_date

    else:
        print("ERROR: invalid type({}) found.".format(args.type))
        return

    print("\n")

    scheduler.add_job(func=func, args=arg_list, trigger=args.type, kwargs=None, id=id,
                      name=name, misfire_grace_time=1, coalesce=True, max_instances=1,
                      next_run_time=undefined, replace_existing=True,
                      start_date=start_date, end_date=end_date)

    print("SCHEDULER: job added")

    return


def main():
    print("\n")

    parser = argparse.ArgumentParser(description='Add jobs to JOBS DB CLI')

    parser.add_argument('cmd', help="[add]")
    parser.add_argument('-type', default='interval', help="[interval, cron, date]")

    parser.add_argument('-func', default=None, help="- interval, cron, and date")
    parser.add_argument('-fargs', default=None, help="- interval, cron, and date")

    parser.add_argument('-id', default=None, help="- interval, cron, and date")
    parser.add_argument('-name', default=None, help="- interval, cron, and date")
    parser.add_argument('-max_instances', type=int, default=1, help="- interval, cron, and date")

    parser.add_argument('-start_date', default=None, help="- interval and cron")
    parser.add_argument('-end_date', default=None, help="- interval and cron")

    args = parser.parse_args()

    print(args)

    try:
        jobstores = {
            'default': SQLAlchemyJobStore(url='sqlite:///%s' % db_file)
        }

        executors = {
            'default': ThreadPoolExecutor(20)
        }

        job_defaults = {
            'coalesce': True,
            'misfire_grace_time':1,
            'max_instances': 1,
            'replace_existing':True,
        }

        scheduler = BackgroundScheduler(jobstores=jobstores, executors=executors, job_defaults=job_defaults, timezone=utc)
        scheduler.start()

        if args.cmd == 'add':
            jobadd(scheduler, args)
        else:
            print("ERROR: Invalid cmd specified. ({})".format(args.cmd))


    except (KeyboardInterrupt, SystemExit):
        print("\n")
        pass

    scheduler.shutdown()
    print("Done.")

    return


# Start program
if __name__ == "__main__":
    main()
```

**Comment by sudhesam** [comment]
The order of execution is :  First add the job by running addjob2db.py and then run foo.py.

**Comment by sudhesam** [comment]
Output from my run:
-----------------------
localhost:/tmp/ssam # python3 addjob2db.py add -type cron -id 100 -start_date '2017-11-19 14:25:00' -end_date '2017-11-19 14:25:00' -func 'foo:func_a' -fargs '1'


Namespace(cmd='add', day_of_month=None, day_of_week=None, end_date='2017-11-19 14:25:00', fargs='1', func='foo:func_a', hour=None, id='100', max_instances=1, minute=None, month=None, name=None, second=None, start_date='2017-11-19 14:25:00', type='cron', week=None, year=None)
Namespace(cmd='add', day_of_month=None, day_of_week=None, end_date='2017-11-19 14:25:00', fargs='1', func='foo:func_a', hour=None, id='100', max_instances=1, minute=None, month=None, name=None, second=None, start_date='2017-11-19 14:25:00', type='cron', week=None, year=None)


Run time of job "foo (trigger: cron[], next run at: 2017-11-19 14:24:00 UTC)" was missed by 0:00:28.219276
SCHEDULER: job added
Done.

**Comment by sudhesam** [comment]
Hi Alex,  Appreciate any update on this.

**Comment by agronholm** [comment]
What is it exactly that you want me to comment on here?

**Comment by sudhesam** [comment]
As per your earlier comment, if you pick up my latest python code and run it 'as is' in the order mentioned you will be able to reproduce the issue (i.e. not able to read the value of the global variable) when scheduling a job through -func.

I wanted to know if it is possible at all.  If not, then I will use alternative way that I am trying to achieve.

**Comment by agronholm** [comment]
What arguments are you passing to addjob2db.py?

**Comment by sudhesam** [comment]
addjob2db.py add -type cron -func 'foo:func_a' -fargs 1 -name 'foo_test' -start_date <start_date> -end_date <end_date>
<start_date> & <end_date> in the format - 'YYYY-MM-DD hh:mm:ss'

**Comment by agronholm** [comment]
I will check this tomorrow.

**Comment by agronholm** [comment]
By the way, since you are not scheduling `func_b`, how do you expect the value of `hw` to be set in the first place?

**Comment by sudhesam** [comment]
func_b() is called when you run 'foo.py' and it will read the job added by add2jobsdb.py

**Comment by agronholm** [comment]
Ah, right, I missed that.

**Comment by agronholm** [comment]
Oh, BTW, I know what the problem is now. You have the code loaded twice, as the `__main__` and `foo` modules. The former sets the value of `hw`, and the latter does not. The latter is also where `func_a` runs as a scheduled job.

**Comment by sudhesam** [comment]
Sorry, I did not understand what you meant.

**Comment by agronholm** [comment]
When you do `python foo.py`, then `foo.py` is loaded as the `__main__` module, right? That's why you check `__name__`, right? Then what happens if you do `import foo`? The same module is loaded again, just with `foo` as its `__name__`. They are now two different, isolated modules in memory.

**Comment by sudhesam** [comment]
So, you mean the 2nd 'import foo' happens through -func 'foo:func_a'.

**Comment by agronholm** [comment]
The scheduler does that. Anyway, try putting your scheduled functions along with the variables in a separate module from the entry point module.

**Comment by sudhesam** [comment]
Thanks.  Will try that and update it.
