### ISSUE TITLE
Is it Ok to have multiple BackgroundSchedulers in different classes of Project?

### ISSUE THREAD

**Issue by MrBillium** [agronholm/apscheduler#245]
The reason I am asking is that my app always dies  sometime within 8 hours with the last log message being from  ApScheduler every time it crashes.  I suspect a race condition. Interestingly, this worked fine using  3.3.1 but showed up when I upgraded to 3.4 .  Here is the background.

I have an IOT app that stands up APsheduler.BackgroundScheduler from Main.py entry point which contains an endless loop. This has two housekeeping jobs every 1 and 15 minutes. The Main  code also instantiates another connection class that stands up its own ApScheduler.BackgroundScheduler to fire connection checker every minute.
Some time between 2 mins and 8 hours, the code will just stop and even though I have DEBUG level logging everywhere to catch the culprit, the last message logged is always the same:
WARNING:apscheduler.scheduler:Execution of job "MQTTConn._timer1 (trigger: interval[0:00:60], next run at: 2017-xxxxxx UTC)" skipped: maximum number of running instances reached (1)

Note that skipping this job does not cause bad things to happen but it is always the last log ( & console) message when my code stops

Q.  Should I be using just one scheduler  in main and calling the jobs in the other class from there or is my design ok and something else is going on?

Bill

**Comment by agronholm** [comment]
If you really want, you can have multiple schedulers running at the same time as long as they don't share a job store.

**Comment by MrBillium** [comment]
Through mtracing, the culprit appears to be another library updated at the same time as ApScheduler and I was able to produce one crash where ApScheduler was not the last logged entry - Why the other 10  crashes all ended the same way is still a head shaker!

Thanks for the feedback - I will will leave my design alone since I like to keep the modularity of a standalone connection class. Please close the issue.
