### ISSUE TITLE
How can I access previous job 's info / Pass some data to next execution of a job. 

### ISSUE THREAD

**Issue by eromoe** [agronholm/apscheduler#246]
Hello,

I want to schedule job with time limit (endtime) .  `apscheduler` miss one thing important I think. 

# 1.  Access previous job 's info

## For example

I have some users subscribe  different  dataset/information by some condition,  I say that : `order`.

I want a wroker scan order table by `last_scaned_time ` and `current_time` ,  in order to only read new orders .
Now I write `order_scan` with a while loop, and add job for different order.

```

scheduler = BackgroundScheduler()

def order_scan():
    # order_db_url = ''

    source = UBApi(config['source']['url'], config['source']['task'])
    starttime = 0
    while True:
        endtime = time()
        # only scan new order
        results = source.select(starttime=starttime, endtime=endtime)
        for i in results:
            if i['type'] == 'once':
                scheduler.add_job(order_job, id=i['id'])
            elif i['type'] == 'interval':
                scheduler.add_job(order_job, id=i['id'], args=[i], trigger='interval', seconds=i['interval'])

        starttime = endtime
        sleep(5)

def order_job(order):
    now = time()

    if now > order['endtime']:
        scheduler.remove_job(order['id'])
    else:
        pass
        #read db
        #call api
        #send email to user
```

The startup code :
```
scheduler.add_job(order_scan)
scheduler.start()
```

-------

## But I think it would be better to

```

def order_scan():
    source = UBApi(config['source']['url'], config['source']['task'])
    
    # here get previous job 's save data
    data = get_previous_job_data()
    starttime = data.get('starttime')
    
    endtime = time()
    # only scan new order
    results = source.select(starttime=starttime, endtime=endtime)
    for i in results:
        if i['type'] == 'once':
            scheduler.add_job(order_job, id=i['id'], save={'starttime': endtime })
        elif i['type'] == 'interval':
            scheduler.add_job(order_job, id=i['id'], args=[i], trigger='interval', seconds=i['interval'], save={'starttime': endtime })

```

The startup code :
```
scheduler.add_job(order_scan, 'interval', seconds=5)
scheduler.start()
```

----------------------------------

# 2. Is it safe to `scheduler.add_job(order_job)`  in a job ?

**Comment by agronholm** [comment]
1. It sounds like an infinite loop with `sleep(5)` would work better for you.
2. It should be, yes.

**Comment by eromoe** [comment]
For  1. 

Current problem is how to gracefully restart the job after  apscheduler restart/ die .

I know solution is simple,  may use a external db
```
def order_scan():
      starttime = get_last_runtime_from_db_or_file() or 0
      while True:
            ....

     set_last_runtime_from_db_or_file( time.time())
```


But I think it may be better to reuse the jobstore , save the extra infomation when job running .  In that way, can abandon infinite loop and use interval trigger happy.

**Comment by agronholm** [comment]
I've opened #265 to track this feature request.
