### ISSUE TITLE
how to add jobs during schedule is runing

### ISSUE THREAD

**Issue by spoock1024** [agronholm/apscheduler#247]
I am new to apscheduler. I have a problem.when the schdule is runing,I want to add jobs,but it seems that it does not work.Here is my code.
```Python
scheduler = BlockingScheduler()
scheduler.add_job(job,'cron',day_of_week='1-7',hour=20,minute=00)
scheduler.add_job(job3,'interval',seconds=5)
scheduler.start()
scheduler.add_job(job2,'interval',seconds=5)
````
the job2 seems not work,but I have to add jobs when the schedule is started.I think the scenario is very common, as the schedule is running,I have more and more jobs want to add to the scheduel.
so my question is is there any solution can solve this problem?Thanks

**Comment by agronholm** [comment]
That's because it's a *blocking* scheduler, and like the documentation says, it *blocks* at `start()`, so execution never reaches that last line.
