### ISSUE TITLE
How to get only the trigger time of a cron job?

### ISSUE THREAD

**Issue by morpheus65535** [agronholm/apscheduler#248]
I've been trying to display the trigger time of a cron job with APScheduler and I can't get it. The only way I have is this one but the result is not really user friendly for a UI:

```
for job in scheduler.get_jobs():
    print job.trigger.__str__()
```

It return this:

`cron[hour='4']`

I would like to display something like "0:04:00" or "4:00".

Someone got a hint for me?

Thanks!

**Comment by agronholm** [comment]
What's preventing you from formatting the value yourself by iterating through `job.trigger.fields`?
As an aside, `print str(job.trigger)` is the proper way to do this. You should almost never call the dunder methods directly.

**Comment by morpheus65535** [comment]
Of course, I can do this. Was just questioning if something was integrated in apscheduler to return this kind of information directly. No problem, I'm going to code it that way.
Thanks!
