### ISSUE TITLE
Question about  coalesce 

### ISSUE THREAD

**Issue by eromoe** [agronholm/apscheduler#249]
Hello ,

From code,
> coalesce: run once instead of many times if the scheduler determines that the job should be run more than once in succession

Does it mean:

When apsceduler run  a job with id  `1` , it would check its inner queue (pending_jobs) , to see if there are other jobs with id `1` .If they are ,  delete all of them , to make sure only run once ?

**Comment by agronholm** [comment]
When a job is run, its scheduled run times are calculated from the last run time, and if the calculation turns up more than one, the job is run several times unless coalescing is enabled.

**Comment by eromoe** [comment]
>  if the calculation turns up more than one

So, this only happen when `max_instances> 1` ?

**Comment by agronholm** [comment]
`max_instances` controls the max concurrent instances of the job. If this is 1 and coalescing is enabled and the calculation turns up more than one run time, then of course those extra runs cannot be done.

**Comment by eromoe** [comment]
Sorry , I just can't understand why calculation could turn up more than one run time even though there is only one job instance. 

Oh, wait.  I think I get the point, this may happen if the interval time is very small .Due to scheduler also need time to run other jobs,  may not have enough time to execute a job in time , which cause this situation , right ?

**Comment by agronholm** [comment]
What is so strange about this? If the last run time was at 10:00:00 and the job is being run with interval of 5 seconds and the executor is so busy it could only run the job at 10:00:50. How many 5 second intervals fit between 10:00:50 and 10:00:00?

**Comment by eromoe** [comment]
Yeah , I understand . Thank you!
