### ISSUE TITLE
Cron Rule with day="*/7" results in incorrect next run time

### ISSUE THREAD

**Issue by shehjart** [agronholm/apscheduler#252]
Hi Alex

I am trying to setup a rule that allows me to say:

Run Job every X days, at hour Y.

The output lines below are simply str(j) where j is the return value from add_job.

The job string looks like this when I try with "every 6 days rule":

TestJob (trigger: cron[day='*/6', hour='7'], next run at: 2017-12-01 07:00:00 IST)

Given that I am running this today on 25 Nov. This is the correct next run time date, considering I am running this at 5 PM so the next 7 am run will be 6 days away.

But the same scheme does not work when I try for 7 days:

TestJob (trigger: cron[day='*/7', hour='7'], next run at: 2017-11-29 07:00:00 IST)

Here, the next run time is setup to be just 4 days away.

Similar problem when I try with 5 day rule:

TestJob (trigger: cron[day='*/5', hour='7'], next run at: 2017-11-26 07:00:00 IST)

This one has the next run time tomorrow.

Am I using the cron trigger correctly?

**Comment by agronholm** [comment]
As we discussed on gitter, this is not correct. You need the new `CalendarTrigger` for this.
