### ISSUE TITLE
apschedular not running for long interval

### ISSUE THREAD

**Issue by anuj9196** [agronholm/apscheduler#253]
I'm using `apscheduler` to schedule cron task to run every hour. The script is hosted on `Heroku`
```
    from apscheduler.schedulers.blocking import BlockingScheduler
    sched = BlockingScheduler()
    
    @sched.scheduled_job('interval', minutes=60)
    def send_alert():
        # task logic
    
    sched.start()
```
**Procfile**
```
    clock: python telegram_alert.py
```
**But, it doesn't run. When I set `interval minutes` to `2` or `10`, it works fine. But setting it to a large value is not working.**

> Edit 2

I think cron is not running after 30 minutes. I changed duration to `minutes=10` to check how long does it run. It runs for 3 times only, means it run the task three times each on an interval of 10 minutes, after that It stopped running.

Is there some limitation with `scheduled_job`?

**Comment by agronholm** [comment]
Can you provide a trivial script that I can run where the job fails to run as expected?

**Comment by agronholm** [comment]
And are you sure this is not a Heroku limitation? Have you tried this locally?

**Comment by agronholm** [comment]
No feedback given in 2 weeks, closing.

**Comment by rnama22** [comment]
Reopening the ticket, as I see the same issue. I'm using the flask app along with apscheduler to run some processes every one hour. It was fine for first few times but wasn't running consistently. I'm using it currently in dev-prod mode and the last time scheduler worked was before 2 days despite every hour. I saw the same behavior earlier as well. Btw, it worked fine when the interval was 10 minutes. Not sure if the large interval is causing the issue.

Here is the code:
def start_scraping():
    service.scrape_all()
    print('time to scrape')

def start_scheduler():
     scheduler.add_job(start_scraping, 'interval',
                          seconds=3600)
    try:
        scheduler.start()
    except:
        scheduler.shutdown()

start_scheduler()

**Comment by agronholm** [comment]
Please at least provide a consistent way of reproducing the issue. Otherwise I cannot investigate.

**Comment by agronholm** [comment]
Also please enable debug logging as instructed in the [Troubleshooting](http://apscheduler.readthedocs.io/en/latest/userguide.html#troubleshooting) section of the docs.

**Comment by sasha00123** [comment]
@agronholm  I have the same issues. Didn't you find any solutions? I have enabled logging. Will send its output after the next startup.

**Comment by sasha00123** [comment]
@agronholm I found this in the log.
```
JobQueue - DEBUG - JobQueue thread stopped.

``` I suppose that Heroku just kills clock process after 30 minutes inactivity just like with web dynos.
I've found another solution with Heroku Scheduler: you can use as many daily schedules starting at different times as you need to imitate interval running.

**Comment by denny64** [comment]
@sasha00123  Do you know if there is a way to not let Heroku kill the clock process? I am on a paid tier but still run into this issue...

**Comment by sasha00123** [comment]
Hello! Unfortunately, I didn't find any way to fix it, but you can try to
contact paid support, maybe they'll help you. I started to use Heroku's
Task Scheduler addon for scheduled tasks.

**Comment by vvorlov** [comment]
Heroku puts your app to sleep after 30 minutes of inactivity to manage its resources. If you want to perform certain tasks irrespective of the traffic, this is a roadblock as the clock process will be put to sleep as well.


Fortunately, there is a workaround. There are services that ‘ping’ your app to wake it up after specified period of time. One such simple service is https://kaffeine.herokuapp.com/ You can specify your app name and it will give your app some ‘kaffeine’ every 30 minutes. Also, you need to specify what time it should not ping as there is a mandatory 6 hour sleep rule for Heroku free tier apps.

**Comment by Zayn-Rekhi** [comment]
```
from apscheduler.schedulers.background import BackgroundScheduler
from backgroundTask import script
from apscheduler.schedulers.blocking import BlockingScheduler

sched1 = BlockingScheduler()

@sched1.scheduled_job('interval', minutes=5)
def timed_job1():
    import datetime
    import time
    ts = time.time()
    st = datetime.datetime.fromtimestamp(ts).strftime('%H:%M')
    if st == "{time of different intervals}":
        script.main()
    else:
        print("ok")

sched1.start()
```

This was ultimately my solution. It works but it is not the most handsome. So the key to this process is to make sure that the time for the different intervals does not collide with minutes. 
Hope this helps!

**Comment by RichardMM** [comment]
https://stackoverflow.com/questions/34896705/python-apscheduler-not-consistent

perhaps this may help.
