### ISSUE TITLE
Any idea why exception 'NoneType' object has no attribute 'now' s appears occationally?

### ISSUE THREAD

**Issue by Sugeei** [agronholm/apscheduler#254]
I am using scheduler = BackgroundScheduler() to schedule my tasks.
locally run by pycharm. 
There are times no exception raised, but sometimes got below message:
`
2017/11/28 上午9:51:03Exception in thread APScheduler (most likely raised during interpreter shutdown):
2017/11/28 上午9:51:03Traceback (most recent call last):
2017/11/28 上午9:51:03  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2017/11/28 上午9:51:03  File "/usr/lib/python2.7/threading.py", line 754, in run
2017/11/28 上午9:51:03  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 30, in _main_loop
2017/11/28 上午9:51:03  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 925, in _process_jobs
2017/11/28 上午9:51:03<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'now'`

**Comment by agronholm** [comment]
Does this happen during interpreter shutdown? Python 2 in particular has some shutdown related quirks which can make this happen at that time.

**Comment by agronholm** [comment]
In particular, this happens if you're running a background scheduler and you don't shut it down cleanly. Is this what's happening?

**Comment by agronholm** [comment]
Don't bother asking questions if you don't want to follow up with answers.
