### ISSUE TITLE
AsyncIOExecutor -> RuntimeError: There is no current event loop in thread

### ISSUE THREAD

**Issue by dyus1983** [agronholm/apscheduler#255]
Hi,
My code use packages that employ asyncio. When AsyncIOScheduler runs scheduled functions which invoke coroutines, I get the following RuntimeError:
> 
2017-12-01 01:43:00,001 apscheduler.executors.default INFO Running job "rebalance (trigger: interval[0:02:00], next run at: 2017-11-30 14:43:00 EST)" (scheduled at 2017-11-30 14:43:00-05:00)
2017-12-01 01:43:00,361 apscheduler.executors.default ERROR Job "rebalance (trigger: interval[0:02:00], next run at: 2017-11-30 14:45:00 EST)" raised an exception
Traceback (most recent call last):
  File "/home/dias/anaconda3/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "<ipython-input-8-de72666ee5a6>", line 115, in rebalance
    self.algo(context, data)
  File "<ipython-input-8-de72666ee5a6>", line 68, in algo
    field='close')
  File "/home/dias/Dropbox/ibalgo/ibalgo.py", line 483, in history
    currdata_dict = self.current(sec, '', freq, parse=False)
  File "/home/dias/Dropbox/ibalgo/ibalgo.py", line 348, in current
    currdata = self.get_histdata_ib(req, return_df=True)
  File "/home/dias/Dropbox/ibalgo/ibalgo.py", line 325, in get_histdata_ib
    formatDate=histdatareq.formatDate)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/ib.py", line 686, in reqHistoricalData
    useRTH, formatDate, keepUpToDate, chartOptions))
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/ib.py", line 1080, in reqHistoricalDataAsync
    future = self.wrapper.startReq(reqId, bars)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/wrapper.py", line 60, in startReq
    future = asyncio.Future()
  File "/home/dias/anaconda3/lib/python3.6/asyncio/futures.py", line 155, in __init__
    self._loop = events.get_event_loop()
  File "/home/dias/anaconda3/lib/python3.6/asyncio/events.py", line 678, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/home/dias/anaconda3/lib/python3.6/asyncio/events.py", line 584, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread '<concurrent.futures.thread.ThreadPoolExecutor object at 0x7ff567af8c88>_1'.
> 

As you may have noticed from the traceback, the code runs function reqHistoricalData (from ib_insync package), which in its turn invokes reqHistoricalDataAsync. Since AsyncIOExecutor sees 'rebalance' as a blocking function it unloads it to ThreadPoolExecutor, which has no loop running.

Is there a way to solve this?

As a temporary solution, I use DebugExecutor to avoid unloading to a thread. It works for this particular case, but if there was a scheduled coroutine, this again would require AsyncIOExecutor.

**Comment by agronholm** [comment]
Couldn't you make the target function of the schedule job into a coroutine function? The asyncio executor handles plain functions via threads due to historical reasons.

**Comment by agronholm** [comment]
Also, how exactly are you calling coroutine functions from plain functions? That shouldn't be possible.

**Comment by dyus1983** [comment]
> Couldn't you make the target function of the scheduled job into a coroutine function? The asyncio executor handles plain functions via threads due to historical reasons.
> 
It is not a solution for me, because I use the functionality of ib_insync package, to be precise, I run reqHistoricalData function (from ib_insync), which has the following:


```
def reqHistoricalData(...):
        return self.run(self.reqHistoricalDataAsync(...))
```

```
    @staticmethod
    def run(*awaitables: List[Awaitable]):
        """
        By default run the event loop forever.
        
        When awaitables (like Tasks, Futures or coroutines) are given then
        run the event loop until each has completed and return their results.
        """
        loop = asyncio.get_event_loop()
        if not awaitables:
            result = loop.run_forever()
        else:
            if len(awaitables) == 1:
                future = awaitables[0]
            else:
                future = asyncio.gather(*awaitables)
            result = util.syncAwait(future)
        return result
```
> Also, how exactly are you calling coroutine functions from plain functions? That shouldn't be possible.
```
def reqHistoricalDataAsync(...):
        reqId = self.client.getReqId()
        bars = BarDataList()
        ...
        future = self.wrapper.startReq(reqId, bars)
        if keepUpToDate:
            self.wrapper.startLiveBars(reqId, bars)
        end = util.formatIBDatetime(endDateTime)
        self.client.reqHistoricalData(reqId, contract, end,
                durationStr, barSizeSetting, whatToShow,
                useRTH, formatDate, keepUpToDate, chartOptions)
        return future
```
I believe the way it is done is reqHistoricalDataAsync sends a request and expects the response in the 'future' variable, which is passed to asyncio loop.

**Comment by agronholm** [comment]
> It is not a solution for me, because I use the functionality of ib_insync package

What's keeping you from making a coroutine function that calls this?

> I believe the way it is done is reqHistoricalDataAsync sends a request and expects the response in the 'future' variable, which is passed to asyncio loop.

Coroutine functions don't return futures. Calling them gives you a coroutine object which has to awaited on, and you need another coroutine function to do that.

**Comment by dyus1983** [comment]
May be there is possibility to extend AsyncIOExecutor with the functionality of the DebugExecutor if the job is not a coroutine? Or, may it be possible to pass the event loop to the thread?

**Comment by agronholm** [comment]
Why not do as I suggested and create a coroutine function which calls that other function of yours? Coroutine functions are always executed on the event loop thread by AsyncIOExecutor.

**Comment by dyus1983** [comment]
> Why not do as I suggested and create a coroutine function which calls that other function of yours? Coroutine functions are always executed on the event loop thread by AsyncIOExecutor.
>
I will look into that. I'm new to asyncio, and didn't want to dig into it at this point, but I guess I will have to.
It seems to be implying stuff like callbacks, which means additional code.

**Comment by dyus1983** [comment]
Thank you for suggestions!

**Comment by agronholm** [comment]
> I will look into that. I'm new to asyncio, and didn't want to dig into it at this point, but I guess I will have to. It seems to be implying stuff like callbacks, which means additional code.

Uhh, why?

```python
async def target_func():
    your_plain_function()
```

**Comment by dyus1983** [comment]
Yes, I see now. Seems like all I had to do is just to wrap the function into a coroutine:
`task = asyncio.coroutine(func)`
Then it runs fine with AsyncIOScheduler (checked with ib_insync.reqHistoricalData)

Thank you again!
