### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#259]
As Django 2.0 dropped it, it might be a good time for APScheduler to drop Python 2 support too. This would open the possibility of adding native support for typing information directly into the source code, and to remove some awkward compatibility code. Python 2 users could still keep using 3.x, which should get bug fixes when possible but no new features.

**Comment by hugovk** [comment]
Here's the pip installs for apscheduler from PyPI for the last month (via `pypinfo --percent --pip --markdown apscheduler pyversion`)

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   70.9% |         68,543 |
| 3.6            |   17.8% |         17,164 |
| 3.5            |    7.4% |          7,175 |
| 3.4            |    3.6% |          3,448 |
| 2.6            |    0.2% |            189 |
| 3.7            |    0.1% |             62 |
| 3.3            |    0.0% |             43 |

**Comment by WesleyBlancoYuan** [comment]
I won't say drop Py2 is a good idea, I am with 2 too.

**Comment by agronholm** [comment]
@WesleyBlancoYuan Are you going to keep using it beyond 2020, when the PSF completely drops Python 2 support?

**Comment by WesternGun** [comment]
I will consider 3 definitely if it's a personal project, but the project is of my corporate, that's another story.

**Comment by agronholm** [comment]
The 3.x branch will still be installable on Python 2. If there are serious bugs found in it, I will probably fix those. But any new features will be py3 only. You can't expect to have the cake and eat it too.

**Comment by WesternGun** [comment]
Thanks for make that clear. Will take into consideration.

**Comment by hugovk** [comment]
You can always pin to the last one which fully supported 2.x.

A number of scientific projects are also dropping new features, if not also bug fixes, for 2.x next year. See http://www.python3statement.org/#sections40-timeline

**Comment by hugovk** [comment]
Just a note to show how Python 2 installs are dropping.

Here's the pip installs for apscheduler from PyPI for May 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  64.22% |         45,635 |
| 3.6            |  23.72% |         16,858 |
| 3.5            |   7.75% |          5,506 |
| 3.4            |   4.02% |          2,855 |
| 2.6            |   0.14% |             96 |
| 3.7            |   0.12% |             87 |
| 3.3            |   0.04% |             27 |
| 3.8            |   0.00% |              1 |
| Total          |         |         71,065 |

Source: `pypinfo --start-date 2018-05-01 --end-date 2018-05-31 --percent --markdown apscheduler pyversion`

**Comment by kaos** [comment]
What's the numbers like this year?

As those two tables you've shown, does not indicate a move to python 3, just a drop of installs from python 2..

**Comment by hugovk** [comment]
Here they are May 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  34.60% |   129,743 |
|      2.7 |  33.03% |   123,866 |
|      3.7 |  21.52% |    80,708 |
|      3.5 |   6.88% |    25,799 |
| null     |   2.07% |     7,752 |
|      3.4 |   1.83% |     6,864 |
|      2.6 |   0.05% |       188 |
|      3.8 |   0.01% |        48 |
|      3.3 |   0.00% |        14 |
|      3.2 |   0.00% |         4 |
| Total    |         |   374,986 |

Source: `pypistats python_minor APScheduler --last-month # pip install pypistats`

**Comment by agronholm** [comment]
This was discussed at Pycon 2019 and the conclusion was that the PyPI statistics were heavily skewed towards Python 2.7. They do not represent actual usage.
