### ISSUE TITLE
TypeError: _alarm() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by JulianMined** [agronholm/apscheduler#262]
Hello,
if my task triggered i got the following message:
> TypeError: _alarm() missing 1 required positional argument: 'self'

> from pytz import utc
> from apscheduler.schedulers.background import BackgroundScheduler
> from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
> 
> class AlarmManager:
>     scheduler = None
>     def __init__(self):
>         self.scheduler = BackgroundScheduler(jobstores={'default': SQLAlchemyJobStore(url='sqlite:///alarms.sqlite')})
>         self.scheduler.start()
> 
>     def _alarm(self, id):
>         print('Alarm')
> 
>     def set_alarm(self, scheduled_time, id):
>         self.scheduler.add_job(func=self._alarm, id=token, run_date=scheduled_time, args=[id])
>

**Comment by agronholm** [comment]
You need to pass it the function as an unbound function and then `self` as the first argument.
Like so:
```
self.scheduler.add_job(func=AlarmManager._alarm, id=token, run_date=scheduled_time, args=[self, id])
```

**Comment by JulianMined** [comment]
Thanks :) ,

now i got:
>  Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/media/usb/shares/alexa2/alexa/alarmmanager.py", line 16, in set_alarm
>     self.scheduler.add_job(func=AlarmManager._alarm, id=token, run_date=scheduled_time, args=[self, token])
>   File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/base.py", line 434, in add_job
>     self._real_add_job(job, jobstore, replace_existing)
>   File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/base.py", line 851, in _real_add_job
>     store.add_job(job)
>   File "/usr/local/lib/python3.5/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 92, in add_job
>     'job_state': pickle.dumps(job.__getstate__(), self.pickle_protocol)
> TypeError: can't pickle _thread.lock objects

**Comment by agronholm** [comment]
If `AlarmManager` is not pickleable then there's nothing you can do.

**Comment by agronholm** [comment]
You do understand that in order for the scheduler to call the method later, it will need to store all the arguments to `_alarm()` in the database, right? Including `self`.
