### ISSUE TITLE
OverflowError: timeout value is too large

### ISSUE THREAD

**Issue by puregod27** [agronholm/apscheduler#263]
schedtest.add_job(test, 'cron', month=1, day=1, hour=0, minute=0)
schedtest.start()

**After execution**

Traceback (most recent call last):
  File "C:/Users/YDS/PycharmProjects/untitled/main.py", line 55, in <module>
    schedtest.start()
  File "C:\Users\YDS\PycharmProjects\untitled\venv\lib\site-packages\apscheduler\schedulers\blocking.py", line 19, in start
    self._main_loop()
  File "C:\Users\YDS\PycharmProjects\untitled\venv\lib\site-packages\apscheduler\schedulers\blocking.py", line 28, in _main_loop
    self._event.wait(wait_seconds)
  File "C:\Python34\Lib\threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Python34\Lib\threading.py", line 293, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large

What's wrong

**Comment by puregod27** [comment]
I am using 3.4.0

**Comment by agronholm** [comment]
I will try this today on Windows. A couple of things I will need from you:

1. Are you running 32-bit or 64-bit Python?
2. Could you post a minimal script that reproduces the problem?

**Comment by puregod27** [comment]
using window 64bit

I made a schedule to work in the new year.

In the code below

----------------------------------------------------------------------------------------------------
from apscheduler.schedulers.background import BlockingScheduler


def test():
    print("scheduler run !!")


schedtest = BlockingScheduler()
schedtest.add_job(test, 'cron', month=1, day=1, hour=0, minute=0)
schedtest.start()
----------------------------------------------------------------------------------------------------

I change the date.

>> 2018-01-02

And Run Code
 
I get an error

I came to know one fact.

Date near the New Year does not cause an error

For example, 2017-12-29

**Comment by agronholm** [comment]
Wait, change what date? You don't have any dates in the code above.

**Comment by agronholm** [comment]
Hm, I can't reproduce this on my Windows with Python 3.4.4. Could you tell me the value of `threading.TIMEOUT_MAX` on your Python? What exact Python version are you running?

**Comment by puregod27** [comment]
Change operating system date

you change operating system date

2018-01-02

And Run Code

----------------------------------

python version 3.4.1

**Comment by agronholm** [comment]
Now that the year has rolled into 2018, I'm getting it too.

**Comment by Surflyan** [comment]
so，how to resolve this error？

**Comment by agronholm** [comment]
Update to the latest version?

**Comment by lzjun567** [comment]
so，how to resolve this error？

**Comment by agronholm** [comment]
@lzjun567 Did you not see my previous comment? It's already been fixed in the latest release. If not, please provide details.

**Comment by TaokyleYT** [comment]
After 4 years, a random guy is here to ask something you may rage about
So, how to fix this problem?
My school need me to use replit as a coding platform
And I don’t think replit let me update it

**Comment by TaokyleYT** [comment]
What I mean is
How can I fix this without updating?

**Comment by agronholm** [comment]
If you can't change the software then you can't fix the bug. I don't see a workaround.
