### ISSUE TITLE
Version 3.5.0 Release Availability

### ISSUE THREAD

**Issue by kyleaclark** [agronholm/apscheduler#264]
Hello,

I am trying to track down Version 3.5.0 through Conda Forge and the distribution is not yet listed.  The same also applies to PyPi.  Am I overlooking something or has the latest version not yet been formally released?  

I recognize it's only been a short time since the new version was released, and I certainly appreciate all of the hard work to make this library available.

EDIT: My apologies if this is not the appropriate channel for this question.  Please let me know if I should direct my question to a better place.  Thank you.

**Comment by agronholm** [comment]
It has not been released. There is no tag for 3.5.0 as there is for all previous releases, nor is there a version 3.5.0 on PyPI which is the authoritative source for Python packages. What made you conclude that 3.5.0 should be out?

**Comment by kyleaclark** [comment]
Thank you for the update.  The Version History page lists version 3.5.0.  I took that to mean the version is available.

http://apscheduler.readthedocs.io/en/latest/versionhistory.html

![screen shot 2017-12-22 at 9 44 39 am](https://user-images.githubusercontent.com/2191744/34305748-d2b89774-e6fc-11e7-9ed6-3b5466e1b78b.png)

**Comment by agronholm** [comment]
That will be the version history once 3.5.0 is out. You're looking at the documentation from the latest build. I fill in the changelog bit by bit which each new feature or bug fix I commit.

**Comment by kyleaclark** [comment]
Sounds good.  Thanks.

**Comment by agronholm** [comment]
I have released v3.5.0 now. Have fun!
