### ISSUE TITLE
get_jobs() doc and warning have conflicts

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [agronholm/apscheduler#266]
The docstring reads:

> Returns a list of pending jobs (if the scheduler hasn't been started yet) and scheduled jobs, either from a specific job store or from all of them.
> If the scheduler has not been started yet, only pending jobs can be returned because the
job stores haven't been started yet either.

And the warning in this method says:
```
warnings.warn('The "pending" option is deprecated -- get_jobs() always returns '
                          'pending jobs if the scheduler has been started and scheduled jobs '
                          'otherwise', DeprecationWarning)
```

As I read it, I think `pending jobs` means those scheduled but not run even once, and `scheduled jobs` means those running ones, right? So the docstring makes sense but the warning means the opposite, thus the confusion. You may miss a `not` in warning? I don't PR because I want to confirm that point.

**Comment by agronholm** [comment]
Pending jobs mean jobs that were added before the scheduler was started. Jobs can be scheduled only when the scheduler is running. But you are right – the warning ought to be fixed.
