### ISSUE TITLE
UTC offset ignored when creating datetimes from strings

### ISSUE THREAD

**Issue by darorl89** [agronholm/apscheduler#271]
It works properly for time with UTC+1 Timezone, while I put the same time but but in UTC timezone, it just starts immediately, e.g.:
start_date = '2018-01-03 18:00:00+00:00' Starts immediately
start_date = '2018-01-03 17:00:00+01:00' Starts properly

Also, there is an error thrown when I put datetime instead of string there:
AttributeError: 'datetime.timezone' object has no attribute '_utcoffset'
Thrown in pytz.
  
Have to use such fix...
dateStr = str(date + timedelta(hours=1))[0:-6] + '+01:00'

**Comment by agronholm** [comment]
You need to use pytz timezones (e.g. `pytz.utc`).

**Comment by agronholm** [comment]
As far as the text version goes, It seems that the UTC offset part is disregarded completely, and the local time zone is applied instead.

**Comment by darorl89** [comment]
Just to let you know, this lib is the most unreliable shit I have ever worked with...

**Comment by agronholm** [comment]
@darorl89 Just to let you know, if you ever feel like giving constructive input instead of potty mouthing, I'm all ears.

**Comment by darorl89** [comment]
Start date: 2018-01-03 23:48:00+01:00
printing (trigger: interval[0:01:00], next run at: 2018-01-03 17:48:25 EST)

This lib is just full of bugs. I'm struggling with it for 2 months now...

**Comment by agronholm** [comment]
You've pointed out one bug. What are the rest?

**Comment by agronholm** [comment]
Also, if you've been struggling for 2 months, why haven't you sought help earlier?

**Comment by darorl89** [comment]
I did actually, and all you could tell me is to add misfire_grace_time=None.
It's with scheduling for certain date, and still not launching for me randomly, especially when running on prod, never while testing...

**Comment by agronholm** [comment]
I get plenty of questions regarding APScheduler so I can't remember this particular case. Have you tried enabling debug logging (using `logging.DEBUG`) as the log level? That will tell you what the scheduler is doing.
I also have to point out that thousands of people use this library all the time without major difficulties. If it was "full of bugs" as you claim, there would be more open issues on the bug tracker. I think the current number of open bugs (3, including this one) is a pretty good achievement considering the myriad of features and integrations it offers.

**Comment by agronholm** [comment]
If you have any further complaints, feel free to drop by the APScheduler gitter channel. I will respond to all questions, eventually. Just keep it civilized.
