### ISSUE TITLE
Question about date trigger misfires

### ISSUE THREAD

**Issue by chaddotson** [agronholm/apscheduler#273]
Is there any option to allow jobs to always execute if missed (without setting a high misfire_grace_time)?  I was thinking about a job with a date trigger and I wanted it to execute on time or whenever the program comes back online if it was offline.

**Comment by agronholm** [comment]
What is the point of setting a misfire grace time if you don't want it to be respected?

**Comment by chaddotson** [comment]
Well actually I didn't want to specify a grace period.  I didn't think None was valid.

**Comment by agronholm** [comment]
Now that you know that it is, does that answer your question?

**Comment by chaddotson** [comment]
Yep, didn't know that a grace period of none would allow the job to execute.  Thanks.
