### ISSUE TITLE
Different processes can't get job

### ISSUE THREAD

**Issue by magaofei** [agronholm/apscheduler#274]
I started a Django application, using uwsgi, I set the 4 process, and then open a task executed once for 1 hours, I want to show the task in the information on the page, such as the next run time, I found that the request distribution access to the different processes, to get job the only 1 handling process can be displayed.

apscheduler==3.4.0
django==1.10.8
uwsgi==2.0.15
job_store, I've tried memory and redis
`scheduler.get_job(job_id='INTERFACE_AUTO_TEST_JOB_ID')`

**Comment by agronholm** [comment]
I have to say that even after reading your post 4 times, I could not understand anything you're saying. What does Django have to do with this? Are you running APScheduler in one process or several?
> I found that the request distribution access to the different processes, to get job the only 1 handling process can be displayed.

This sentence makes the least sense of all. What are you trying to say? "request distribution access"? WTF?
