### ISSUE TITLE
CronJob with delta value

### ISSUE THREAD

**Issue by cidrblock** [agronholm/apscheduler#276]
I'm looking to schedule a job x h:m before or after an expression based cronjob, for example 24hours before the 3rd sun of every month.

It seems like modeling it after the jitter functionality would be a good place to start, add it to the end of `    def get_next_fire_time(self, previous_fire_time, now):` 

Instead of _apply_jitter, basically _apply_delta.

Does the logic seem sound ?

**Comment by agronholm** [comment]
You could simply deduct `timedelta(1)` from the returned fire time (be sure to check for `None` though). Does this answer your question?
