### ISSUE TITLE
APScheduler : RuntimeError: cannot release un-acquired lock

### ISSUE THREAD

**Issue by zhiyiZeng** [agronholm/apscheduler#279]
I'm using APScheduler to schedule my multi-threading scripts, but when I started, the error camp up. Here is my codes.
`    
    scheduler = BackgroundScheduler()

    jobstores = {
        'default': SQLAlchemyJobStore(url='sqlite:///jobs_ip.sqlite')
    }
    executors = {
        'default': {'type': 'threadpool', 'max_workers': 1},
        # 'processpool': ProcessPoolExecutor(max_workers=5)
    }

    job_defaults_cron = {
        'id': 'crawl_ip',
        'trigger': 'cron',
        'day_of_week': 'mon-sun',
        # 'hour': '8',
        'hour': '17',
        'minute': '15',
        # 'coalesce': True,
        'max_instances': 1,
        'misfire_grace_time': 60,
    }

    scheduler.add_job(app, 'cron',
                      day_of_week=job_defaults_cron['day_of_week'],
                      hour=job_defaults_cron['hour'],
                      minute=job_defaults_cron['minute'],
                      id='crawl_ip')

    scheduler.configure(jobstores=jobstores, executors=executors, job_defaults=job_defaults_cron, timezone=utc)
    scheduler.start()

    while True:
        i = int(input('IP...'))`
Thanks in advance.

**Comment by agronholm** [comment]
"The error"? What error?

**Comment by agronholm** [comment]
Could you provide a self contained script that reproduces the error?

**Comment by zhiyiZeng** [comment]
Sorry, forget to say that the error is "cannot release unacquired lock".  It's already been solved and it's a bug of gevent. Thanks anyway :-)
