### ISSUE TITLE
ImportError: No module named apscheduler

### ISSUE THREAD

**Issue by sdq** [agronholm/apscheduler#280]
Any idea to solve this problem? Not work in any version...

**Comment by agronholm** [comment]
Doesn't look like you have it installed.

**Comment by agronholm** [comment]
Also, provide more details.

**Comment by ErickGSJ** [comment]
Is this a problem?
this error also block me,  I install apscheduler 3.5.3 by comand pip3 install apscheduler，and here is my code：

#!/usr/bin/env python3
from apscheduler.schedulers.blocking import BlockingScheduler

def aps_test():
    print('1234')

if __name__ == '__main__':
    scheduler = BlockingScheduler()
    scheduler.add_job(func=aps_test, trigger='cron', second='*/5')

    try:
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        pass
the following error occurs:
    from apscheduler.schedulers.blocking import BlockingScheduler
ModuleNotFoundError: No module named 'apscheduler.schedulers'; 'apscheduler' is not a package

**Comment by agronholm** [comment]
No details provided, no response in 10 months – closing.
