### ISSUE TITLE
Guarantee correctly executed jobs 

### ISSUE THREAD

**Issue by logoff** [agronholm/apscheduler#282]
I want to schedule jobs and guarantee that they finish correctly (function reach last line). Everything is working fine, but I see that when a job is started, it's removed from the database, even when the job did not finish the entire function.

**Comment by agronholm** [comment]
What exactly do you want to happen when the job raises an exception?

**Comment by agronholm** [comment]
If you want to leave a feature request, describe what you would like to be changed and how. Describing the existing state of matters does not give me any new information.

**Comment by logoff** [comment]
You are right @agronholm. What I suggest is having a way to check if the execution was correct or not.

**Comment by agronholm** [comment]
It already does have a mechanism for that: [event listeners](http://apscheduler.readthedocs.io/en/latest/userguide.html#scheduler-events). If this covers your use case, you should close this issue.

**Comment by logoff** [comment]
It seems the proper solution. I will give it a try. Thank you.
