### ISSUE TITLE
SyntaxError when using BackgroundScheduler in Python3.6

### ISSUE THREAD

**Issue by eqperes** [agronholm/apscheduler#284]
When importing BackgroundScheduler:

`from apscheduler.executors.pool import ThreadPoolExecutor` 

and when ThreadPoolExecutor is imported: 

`import concurrent.futures` 

which raises the following error:

`raise exception_type, self._exception, self._traceback`
`^`
`SyntaxError: invalid syntax`

**Comment by agronholm** [comment]
Where is concurrent.futures imported from? Are you sure you haven't accidentally installed the backport? Even then it would take extraordinary effort to have Python import that instead of the standard library version.

**Comment by eqperes** [comment]
It is imported from my virtualenv (I am not sure that I have understood your question). 
In any case `concurrent.futures` is imported in the `apscheduler/executors/pool.py` file.

**Comment by agronholm** [comment]
Why is it even installed in your virtualenv if you're running Python 3? That package is part of the Python standard library.

**Comment by agronholm** [comment]
Also, by "where is it imported from" I meant on your filesystem. That should be obvious from the full traceback.

**Comment by eqperes** [comment]
The path of the import is the following: 
"/opt/python/run/venv/lib/python3.4/site-packages/concurrent/futures/__init__.py"

I am using an AWS Elastic Beanstalk instance.

**Comment by agronholm** [comment]
That begs the question, or rather two questions:

1. Why is the backport installed in site-packages?
1. How is it that the interpreter imports that instead of the one in the standard library?

**Comment by agronholm** [comment]
Anyway, the solution should be simple – uninstall the backport. Then you should be fine.

**Comment by agronholm** [comment]
Do you still require assistance or can I close this issue?

**Comment by eqperes** [comment]
For some strange reason I can't uninstall the backport from AWS ElasticBeanstalk servers - it installs it back. 

But this is, so, an issue with AWS-EB configuration and not with the library.
