### ISSUE TITLE
Weekday numbers in crontab expressions correspond to wrong weekdays

### ISSUE THREAD

**Issue by qli-aa** [agronholm/apscheduler#286]
apscheduler/apscheduler/triggers/cron/expressions.py
WEEKDAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']
will map mon ==> 0, sun ==> 6

actually should map mon ==>1 , sun ==> 0 or 7
WEEKDAYS = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']

from cron wiki: https://en.wikipedia.org/wiki/Cron

**Comment by agronholm** [comment]
How is this affecting you? I would also like to point out the notice here saying that Monday is always the first weekday (as per the ISO standard). The only place where this might have an effect is the newly added crontab expression support. If so then I will fix it there locally.

**Comment by qli-aa** [comment]
I  migrated old cron task with 30 7 * * 4 cron expr from linux crontab to apscheduler, I found it was scheduled at Fri,  it was scheduled at Thur before.

**Comment by agronholm** [comment]
This is a bit more problematic than I thought at first. I cannot simply change the way the weekdays are indexed because it would break things for existing users of `CronTrigger`. On the other hand, APScheduler's weekday numbers do not correspond to cron's which causes confusion to people used to crontabs.

**Comment by chomey** [comment]
Yeap, we just ran into this as well :)

**Comment by qli-aa** [comment]
So it will be changed to crontab style ? or not ?

**Comment by agronholm** [comment]
`CronTrigger.from_crontab()` will be changed to respect crontab style weekday numbering. I will consider changing `CronTrigger` itself to use the same numbering in APScheduler 4.0, but for now I will keep backwards compatibility there.

**Comment by andrewchen5678** [comment]
when will 4.0 be released with this fix?

**Comment by agronholm** [comment]
Not very soon. In the meantime, I suggest you use weekday names instead and subscribe to updates on #465.

**Comment by Sebastiao-Assuncao** [comment]
@agronholm Gotcha! Thank you for the quick reply 🙏

**Comment by atharvakale343** [comment]
welp ran into this issue today

**Comment by agronholm** [comment]
> welp ran into this issue today

And decided to notify everyone on the issue?
