### ISSUE TITLE
Meet an error when reschedule the job via RPyC

### ISSUE THREAD

**Issue by zhoudaoyu** [agronholm/apscheduler#287]
Python 3.6.3

APScheduler Version: 3.5.1

RPyC Version: 3.4.4

I try to reschedule a job via rpyc client, but I met this error:

    Traceback (most recent call last):
      File "main.py", line 46, in <module>
        trigger = trigger)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/netref.py", line 199, in __call__
        return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/netref.py", line 72, in syncreq
        return conn.sync_request(handler, oid, *args)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 524, in sync_request
        raise obj
    TypeError: '>' not supported between instances of 'datetime.datetime' and 'datetime'
    
    ========= Remote Traceback (2) =========
    Traceback (most recent call last):
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 348, in _dispatch_request
        res = self._HANDLERS[handler](self, *args)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 625, in _handle_call
        return self._local_objects[oid](*args, **dict(kwargs))
      File "/home/zhoudaoyu/python_code/rctp/code/scheduler.py", line 92, in exposed_reschedule_job
        raise e
      File "/home/zhoudaoyu/python_code/rctp/code/scheduler.py", line 90, in exposed_reschedule_job
        trigger = trigger, **trigger_args)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 503, in reschedule_job
        next_run_time = trigger.get_next_fire_time(None, now)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/netref.py", line 199, in __call__
        return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/netref.py", line 72, in syncreq
        return conn.sync_request(handler, oid, *args)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 524, in sync_request
        raise obj
    _get_exception_class.<locals>.Derived: '>' not supported between instances of 'datetime.datetime' and 'datetime'
    
    ========= Remote Traceback (1) =========
    Traceback (most recent call last):
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 348, in _dispatch_request
        res = self._HANDLERS[handler](self, *args)
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 625, in _handle_call
        return self._local_objects[oid](*args, **dict(kwargs))
      File "/home/zhoudaoyu/anaconda3/lib/python3.6/site-packages/apscheduler/triggers/cron/__init__.py", line 168, in get_next_fire_time
        start_date = max(now, self.start_date) if self.start_date else now
    TypeError: '>' not supported between instances of 'datetime.datetime' and 'datetime'

here are the properties of now and self.start_date:

start_date <class 'datetime.datetime'> 2018-02-09 00:00:00+08:00

now <netref class 'datetime.datetime'> 2018-02-11 16:07:44.748765+08:00

server.py

    import pytz
    from datetime import datetime
    import time
    import rpyc
    from rpyc.utils.server import ThreadedServer
    
    from apscheduler.schedulers.background import BackgroundScheduler
    from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
    
    from apscheduler.executors.pool import ProcessPoolExecutor
    from apscheduler.triggers.cron import CronTrigger
    
    from utils.pre_load import yml_engines
    
    def init_scheduler():
        jobstores = {
                        'default': SQLAlchemyJobStore(engine=yml_engines["user_mmv_status"], tablename = "rctp_jobs")
                        }
        executors = {
                        'default': {'type': 'threadpool', 'max_workers': 20},
                        'processpool': ProcessPoolExecutor(max_workers=5)
                        }
        job_defaults = {
                        'coalesce': False,
                        'max_instances': 3
                        }
    
        scheduler = BackgroundScheduler()
    
        scheduler.configure(jobstores=jobstores, executors=executors, job_defaults=job_defaults, timezone=pytz.timezone('Asia/Shanghai'))
    
        return scheduler
    
    scheduler = init_scheduler()
    scheduler.start()
    
    def write_data(file_name):
        with open("/tmp/"+file_name, "a") as f:
            c_t = str(datetime.now()) + "\n"
            f.write(c_t)
            
    class JobSchedulerService(rpyc.Service):
        def exposed_add_job(self, func, **data):
            """Adds a new job."""
    
            try:
                job = scheduler.add_job(func, **data)
                print("add one job")
                return job
            except Exception as e:
                raise e
    
        def exposed_update_job(self, job_id, **data):
            """Updates a j8ob."""
    
            try:
                scheduler.modify_job(job_id, **data)
            except Exception as e:
                raise e
    
        def exposed_reschedule_job(self, job_id, jobstore=None, trigger=None, **trigger_args):
            try:
                scheduler.reschedule_job(job_id = job_id, jobstore = jobstore,
                                              trigger = trigger, **trigger_args)
            except Exception as e:
                raise e
    
        def exposed_pause_job(self, job_id):
            """Pauses a job."""
    
            try:
                scheduler.pause_job(job_id)
                job = scheduler.get_job(job_id)
            except Exception as e:
                raise e
    
        def exposed_resume_job(self, job_id):
            """Resumes a job."""
    
            try:
                scheduler.resume_job(job_id)
                job = scheduler.get_job(job_id)
            except Exception as e:
                raise e
    
        def exposed_remove_job(self, job_id):
            try:
                scheduler.remove_job(job_id)
            except Exception as e:
                raise e
    
    if __name__ == '__main__':
        protocol_config = {'allow_all_attrs': True, 'allow_pickle': True}
        server = ThreadedServer(JobSchedulerService, port=12345, protocol_config=protocol_config)
        try:
            server.start()
        except (KeyboardInterrupt, SystemExit):
            pass
        finally:
            server.close()
            scheduler.shutdown()

client.py

    
    import pytz
    import uuid
    import rpyc
    
    from apscheduler.triggers.cron import CronTrigger
    if __name__ == '__main__':
        job_id = "30d706d8-0c9b-11e8-b751-000c29d51830"
    
    
        #start_date = "2018-02-11"
        #end_date = "2018-02-12"
    
        #data = {    "trigger": "cron",
        #            "args" : ["a.log"],
        #            "start_date": start_date,
        #            "end_date": end_date,
        #            "second": "*/5",
        #            "id": job_id #str(uuid.uuid1())
        #            }
        #conn = rpyc.connect("localhost", 12345, config={"allow_all_attrs": True,'allow_pickle': True })
        #job = conn.root.add_job('scheduler:write_data', **data)
        #conn.close()
    
        data = {"start_date": "2018-02-11",
                "end_date": "2018-02-12",
                "second": "*/7"}
        conn = rpyc.connect("localhost", 12345, config={"allow_all_attrs": True,'allow_pickle': True })
        trigger = CronTrigger(**data)
        conn.root.reschedule_job(job_id,
                                 trigger = trigger)
        conn.close()

**Comment by adnion** [comment]
Same problem here. Did you find a solution?
```
start_date <class 'datetime.datetime'> 2018-02-09 00:00:00+08:00
now <netref class 'datetime.datetime'> 2018-02-11 16:07:44.748765+08:00
```

**Comment by zinglax** [comment]
I believe I am having a similar problem as well. 
```python
E           ========= Remote Traceback (1) =========                                                                                                  
E           Traceback (most recent call last):                                                                                                        
E             File "/home/zinglax/envs/met/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request                         
E               res = self._HANDLERS[handler](self, *args)                                                                                            
E             File "/home/zinglax/envs/met/lib/python3.9/site-packages/rpyc/core/protocol.py", line 592, in _handle_call                              
E               return obj(*args, **dict(kwargs))                                                                                                     
E             File "/home/zinglax/gits/marketing-engagement-tool/site/src/met/met_scheduler.py", line 114, in exposed_add_job                         
E               return scheduler.add_job(*args, **kwargs)                                                                                             
E             File "/home/zinglax/envs/met/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 420, in add_job                          
E               'trigger': self._create_trigger(trigger, trigger_args),                                                                               
E             File "/home/zinglax/envs/met/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 921, in _create_trigger                  
E               return self._create_plugin_instance('trigger', trigger, trigger_args)                                                                 
E             File "/home/zinglax/envs/met/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance          
E               return plugin_cls(**constructor_kwargs)                                                                                               
E             File "/home/zinglax/envs/met/lib/python3.9/site-packages/apscheduler/triggers/date.py", line 22, in __init__                            
E               self.run_date = convert_to_datetime(run_date, timezone, 'run_date')                                                                   
E             File "/home/zinglax/envs/met/lib/python3.9/site-packages/apscheduler/util.py", line 165, in convert_to_datetime                         
E               return tz.localize(datetime_, is_dst=None)                                                                                            
E             File "/home/zinglax/envs/met/lib/python3.9/site-packages/pytz/tzinfo.py", line 325, in localize                                         
E               loc_dt = dt + delta                                                                                                                   
E           TypeError: unsupported operand type(s) for +: 'type' and 'datetime.timedelta'                                                             
                                                                                                                                                      
```
Here are my two types
```python
dt = <netref class 'rpyc.core.netref.type'> 2021-09-30 05:40:15.230084
delta = <class 'datetime.timedelta'> -1 day, 0:00:00
```
Trying to use the `+` operator between the two.

**Comment by GBY-1** [comment]
Because start_date and end_date must datetime type
this is your params:
data = {"start_date": "2018-02-11",
            "end_date": "2018-02-12",
            "second": "*/7"}
data["start_date"] type is str,for example:print(type(data["start_date"]))
solution method:
1.you can define function model.It aims to limit data type
2.Or you can translate,for example:"datetime.strptime" method

**Comment by agronholm** [comment]
I'm closing this as v4.0 does not require RPyC to support multiple schedulers working with a common data store.
