### ISSUE TITLE
Method "pause" and "resume" in Job instance do not return the newest job.

### ISSUE THREAD

**Issue by m358807551** [agronholm/apscheduler#289]
```
job = scheduler.get_job(job_id)
job = job.pause()  # job.next_run_time is not None

job = scheduler.get_job(job_id)  # job.next_run_time is None now
```
And I do not find any method in Job that could judge whether a job is paused or not(version 3.3). Is there a better idea without using `next_run_time`?

**Comment by agronholm** [comment]
I thought I told you to use another venue to ask questions. This issue tracker is for bug reports and feature requests only.

**Comment by m358807551** [comment]
Sorry and I had asked this question again in google group [here](https://groups.google.com/forum/#!topic/apscheduler/iICROwbj16c)
