### ISSUE TITLE
The second time, it stopped.

### ISSUE THREAD

**Issue by liang1024** [agronholm/apscheduler#292]
code：
`   scheduler = BlockingScheduler()

    scheduler.add_job(runTarget, 'interval', max_instances=100, days=3, start_date=firsttime)

    scheduler.start()`

The second time, it stopped.
error：
`Run time of job "runtarget <trigger : interval[3 days ,0:00:00],next run at :2018-03-09 00:30:00 CST>" was missed by 0:00:01.776066`

Has anyone come across this?

**Comment by liang1024** [comment]
@agronholm hello???

**Comment by agronholm** [comment]
Is this your first time reporting an issue? You created it at 5 am my local time and 8 minutes later you're already wondering why you're not getting a response? Do you think that's reasonable?

APScheduler is pretty strict about being punctual so its default misfire grace time is set to 1 second. If for any reason the execution is delayed beyond that, the execution is skipped as a misfire. To avoid that you can set the `misfire_grace_time` option to a higher value either on the scheduler level or individual job level.

In the future, please only report actual bugs on this bug tracker. Ask questions on the Google group or StackOverflow.
