### ISSUE TITLE
Job not work if add or modify job without uwsgi reload

### ISSUE THREAD

**Issue by wilslee** [agronholm/apscheduler#294]
Hello, I am using the apscheduler with `uwsgi` in Ubuntu.  Now, I am in trouble, my job can not work in uwsgi if the job was added or modified or reschedule while  scheduler running. The jobs which add before the scheduler start was working normal. And it is running good in django runserver.

In my uwsgi config, I have set `preload=True` and `enable-threads=True`.
```
# uwsgi.ini
master = True
vacuum = True
processes = 2
threads = 4
py-autoreload = 1
preload=True
enable-threads=True
```
The job add before scheduler start was working normal
```
from apscheduler.schedulers.background import BackgroundScheduler
scheduler = BackgroundScheduler()
scheduler.add_job(job, id='job_id', replace_existing=True) 
scheduler.start()
```
Now, the job is running good. If some request action from api or other, modify or scheduler the job. or add new job
```
scheduler.modify_job(job_id, ...)
scheduler.reschedule_job(job_id, ...)
scheduler.add_job(new_job, id='new_job_id', replace_existing=True) 
```
We can see the new job or the change of job has update in scheduler with `print_jobs`, but it still no work without uwsgi reload.

**Comment by Bartimeus** [comment]
I have some issue.

**Comment by Bartimeus** [comment]
1) When flask app starts, I adds job 
```app.config['JOBS'].append(
                {
                    'id': 'test',
                    'func': cron_function,
                    'replace_existing': True,
                    'trigger': 'interval',
                    'seconds': 300
                }
            )
```


2) Then I try modify next_run_time like that

```
requests.patch(
    self.scheduler_api_prefix + '/jobs/' + self.job_name,
    json=dict(
        next_run_time=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    )
)
```

3) Nothing going on... Job don't start immediatly.

**Comment by agronholm** [comment]
Again, a full example is needed so I can verify that you're not misusing uwsgi or apscheduler itself. APScheduler also does not include any web components so make sure those are working first before complaining here.

**Comment by agronholm** [comment]
4 years and no reply – closing.

**Comment by wilslee** [comment]
您好。已收到您的邮件，谢谢！
