### ISSUE TITLE
Invalid utf8 character string warning

### ISSUE THREAD

**Issue by lior-dw** [agronholm/apscheduler#300]
The APScheduler produces a warning:
`/lib/python2.7/site-packages/pymysql/cursors.py:165: Warning: (1300, u"Invalid utf8 character string: '80027D'")` trying to execute SQL query `UPDATE job_store SET next_run_time=1522694809.97494, job_state='...' WHERE job_store.id = '...'`

I am using MySQL 5.7.17

**Comment by agronholm** [comment]
How can I reproduce this?

**Comment by lior-dw** [comment]
Try code like this:
```
sa_engine = create_engine('mysql+pymysql://'+mysql_string+"?charset=utf8", encoding="utf-8", pool_recycle=3600)
jobstores = {'default': SQLAlchemyJobStore(engine=sa_engine, tablename='job_store')}
job_defaults = {
	'coalesce': True,
	'misfire_grace_time': 24*60*60,
	'replace_existing': True,
}

scheduler = BackgroundScheduler(jobstores=jobstores, job_defaults=job_defaults, timezone=pytz.utc)
next_run_time = dt.datetime.now() + dt.timedelta(minutes=1)
self.scheduler.add_job(_callback, 'interval', id='job_id', minutes=1, replace_existing=True,  next_run_time=next_run_time)

scheduler.start()
```

**Comment by agronholm** [comment]
Any idea where that invalid UTF8 string comes from?

**Comment by lior-dw** [comment]
Yes, I think it's from the **job_state** column (which is BLOB):
https://stackoverflow.com/questions/36849144/how-to-avoid-encoding-warning-when-inserting-binary-data-into-a-blob-column-in-m

**Comment by agronholm** [comment]
I see. What do you expect me to do about this then?

**Comment by lior-dw** [comment]
Can you use the _binary  fix they describe?

**Comment by agronholm** [comment]
No, since I have no MySQL specific code paths here. I'm also not keen on adding code to work around a bug in an RDBMS I hate with a passion anyway.

**Comment by agronholm** [comment]
For reference, the relevant code is here: https://github.com/agronholm/apscheduler/blob/master/apscheduler/jobstores/sqlalchemy.py

**Comment by agronholm** [comment]
If this was a showstopper issue for MySQL, I would probably fix it, but it's just a bogus warning.
