### ISSUE TITLE
Support for window schedules

### ISSUE THREAD

**Issue by fredthomsen** [agronholm/apscheduler#302]
Supporting a job that has both an action for when a window starts and when it ends, and checking if the schedule starts within the window and firing the start job.  For example, disable the alarm between 3am and 4am.

I realize this can be done via client code, but native support would be cool.

**Comment by cstruct** [comment]
I would love if defining the the window as a [RRULE](https://tools.ietf.org/html/rfc5545) and a duration was supported.

**Comment by agronholm** [comment]
Can this not already be done using combining triggers?

**Comment by fredthomsen** [comment]
Perhaps it could.  In my mind, I had imagined two jobs one that performed the "inverted" operation of the other and to do that the function being executed as part of the job would need access to the job object to be aware whether or not it is within the window.  Perhaps I am approaching this incorrectly, but if there is a snippet of code that demonstrates this being done with the existing functionality, I would love for it to be shared here.

**Comment by agronholm** [comment]
I don't think I properly understand the use case. If you want to do something at 3 am and 4 am, you can already do that with existing triggers. What am I missing?

**Comment by agronholm** [comment]
This is not something I'm willing to support on APScheduler. As you said, you can do this already with a pair of jobs.
