### ISSUE TITLE
AsyncIOScheduler defaults to ThreadPoolExecutor

### ISSUE THREAD

**Issue by alexmbird** [agronholm/apscheduler#304]
From the documentation I would expect AsyncIOScheduler to execute scheduled jobs in the supplied asyncio event loop.  However it seems to use a ThreadPoolExecutor and this plays hell with the asyncio.Lock / asyncio.Queue-s I'm using to share data between my coroutines.  

I've also tried forcing it to use an AsyncIOExecutor with `executors={'default':AsyncIOExecutor()}`, but to no avail.

Here's a how to trigger the behaviour:

```
#!/usr/bin/env python3.6

import asyncio, threading
from apscheduler.schedulers.asyncio import AsyncIOScheduler

def my_schedule_job():
    print("Callback runs in thread %s" % (threading.current_thread(),))

async def my_coroutine():
    print("Coroutine runs in %s" % (threading.current_thread(),))
    await asyncio.sleep(10)

if __name__ == '__main__':
    print("Main runs in %s" % (threading.current_thread(),))
    loop = asyncio.get_event_loop()
    scheduler = AsyncIOScheduler(event_loop=loop)
    scheduler.add_job(my_schedule_job, 'interval', seconds=2)
    scheduler.start()
    loop.run_until_complete(my_coroutine())
```

Running under OSX and Ubuntu I get output like the following:

```
$ pip freeze | grep -i  apscheduler
APScheduler==3.5.1

$ ./experiments/apscheduler_async_test.py
Main runs in <_MainThread(MainThread, started 140735767671680)>
Coroutine runs in <_MainThread(MainThread, started 140735767671680)>
Callback runs in thread <Thread(ThreadPoolExecutor-0_0, started daemon 123145546076160)>
```

**Comment by agronholm** [comment]
This is not a bug, it is a design artifact which will go away in the next major release.

**Comment by agronholm** [comment]
Just so we're clear, AsyncIOScheduler does **not** default to `ThreadPoolExecutor`, it just runs any non-coroutine function in the default executor.

**Comment by alexmbird** [comment]
The jobs I'm trying to schedule need to run periodically - for example rotating an output file once an hour and uploading it to s3.  It would be possible to have a coroutine sleep 3600s, rotate the file then sleep again but I wanted a more versatile scheduling system I could use for other background tasks in my application - hence trying apscheduler.

I'm a little confused where you say "AsyncIOScheduler does not default to ThreadPoolExecutor" - as you can see from the example, it definitely is running `my_schedule_job()` in a different thread.   Is there some other way I should set it up so that it uses `apscheduler.executors.asyncio.AsyncIOExecutor` ?

**Comment by agronholm** [comment]
Your `my_schedule_job` function is a regular function. Make it into a coroutine function (`async def`) and it will be run in the event loop thread directly.

**Comment by agronholm** [comment]
This piece of code explains the behavior you're seeing: https://github.com/agronholm/apscheduler/blob/master/apscheduler/executors/asyncio.py#L49-L57

**Comment by alexmbird** [comment]
Wonderful - I was holding it wrong :)  Everything works as expected.  Thanks for your help. 

Unless there is one and I missed it, might be valuable to add a note to the docs so nobody else falls into the same trap.

**Comment by agronholm** [comment]
The behavior is explained in the documention of `AsyncIOExecutor` ([here](http://apscheduler.readthedocs.io/en/latest/modules/executors/asyncio.html)).
