### ISSUE TITLE
Apscheduler as a class member

### ISSUE THREAD

**Issue by masoudr** [agronholm/apscheduler#306]
Hi, 
I'm trying to create a simple class with `apscheduler` with specific jobstore suppose this simple example:

```

from datetime import datetime
from time import sleep

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore


class sched:
    def __init__(self):
        jobstores = {
            'default': SQLAlchemyJobStore(url='sqlite:///test.db')
        }
        self.scheduler = BackgroundScheduler(jobstores=jobstores)
        job2 = self.scheduler.add_job(self.tick, 'interval', args=[1, 2], kwargs=dict(a=2,b=3), seconds=5, replace_existing=True)
        self.scheduler.start()

    def tick(self, i, j, **kwargs):
        print("hello{} {}".format(i, j))
        for k in kwargs:
            print(k, ":", kwargs[k])



if __name__ == '__main__':
    #print(scheduler.get_jobs())
    schedule = sched()
    while True:
        sleep(1)


```
but it gaves me this error:

> TypeError: tick2() missing 1 required positional argument: 'j'

but when I change the instance name with this it works fine:
```
if __name__ == '__main__':
    #print(scheduler.get_jobs())
    sched = sched()
    while True:
        sleep(1)
```
It works fine. I don't have any problem with default `jobstore`. I don't know if the problem relates to `apscheduler` or not but I'm a little confused here why should I use an instance name with the exact name of the class name.
Thanks.

**Comment by agronholm** [comment]
Try this:
```python
self.scheduler.add_job(sched.tick, 'interval', args=[self, 1, 2], kwargs=dict(a=2,b=3), seconds=5, replace_existing=True)
```

**Comment by agronholm** [comment]
I also suggest following the PEP 8 standard for naming so that classes are named in CamelCase in order to avoid confusion.

**Comment by agronholm** [comment]
Oh right, you probably don't want to include the scheduler in `self`.

**Comment by agronholm** [comment]
You must understand that the `sched` instance needs to be serialized in the database in order for this to work.

**Comment by masoudr** [comment]
@agronholm I tried your first suggestion but it didn't work (as you said):

>     'job_state': pickle.dumps(job.__getstate__(), self.pickle_protocol)
> AttributeError: Can't pickle local object 'BaseExecutor.__init__.<locals>.<lambda>'
for your second suggestion, can you please explain a little more about how can I serialize my instance?
Do you mean pickle and unpickle or something else?
Thanks.

**Comment by agronholm** [comment]
All the arguments must be serialized (pickled) in the database, including the `sched` instance. How then is the scheduler supposed to unpickle something that contains the scheduler itself? That's why having the scheduler as part of the instance is a very bad idea.

**Comment by agronholm** [comment]
Not to mention that starting the scheduler directly in `__init__()` is also a bad idea, particularly from the testability standpoint.

**Comment by masoudr** [comment]
Hi,
I'm having this problem again. It seems that I can't use `apscheduler` as a class member but I have a big project and I need to create a separate module and define my schedule class (with lots of functions) inside it. How can I achieve that? Which type of class should I use?
Let me explain a little, if I create a class inside my main code and use that as I described here is working just fine. But when I create a separate module (.py file) from this class and import it I face the problem that some args are missing in my functions.
Thanks.

**Comment by agronholm** [comment]
What is a "schedule class" here? I can give advice if you show me some code but I am not some free consultancy service.

**Comment by masoudr** [comment]
Ok, I create a simple wrapper for apscheduler and called it `sched` as first example with a little modification suppose this code:
```
from time import sleep
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore


class sched:
    def __init__(self):
        jobstores = {
            'default': SQLAlchemyJobStore(url='sqlite:///test.db')
        }
        self.scheduler = BackgroundScheduler(jobstores=jobstores)

    def add_func(self, some_func, args={}, kwargs={}):
        job2 = self.scheduler.add_job(some_func, 'interval', args=args, kwargs=kwargs, seconds=5, replace_existing=True)

    def start(self):
        self.scheduler.start()


def tick(i, j, **kwargs):
    print("hello{} {}".format(i, j))
    for k in kwargs:
        print(k, ":", kwargs[k])


class other_class:
    def __init__(self):
        self.main_sched = sched()
        self.main_sched.add_func(self.tick_in_other_class, args=[1, 2], kwargs=dict(a=1, b=2))
        self.main_sched.start()

    def tick_in_other_class(self, i, j, **kwargs):
        print("hello{} {}".format(i, j))
        for k in kwargs:
            print(k, ":", kwargs[k])


if __name__ == '__main__':
    # the following three lines works fine
    # Schedule = sched()
    # Schedule.add_func(tick, args=[1, 2], kwargs=dict(a=1, b=2))
    # Schedule.start()
    # the below code give error about missing some args which already provided!
    new_class = other_class()

    while True:
        sleep(1)

```
The first three lines works fine, but when I want to create an instance in other class, it fails. This problem getting me crazy, I'm thinking about forgetting this job_store and create my own pickle and save every single job but I think it is not a good idea if you already implement that.

**Comment by deajan** [comment]
For whoever might need this, I managed to get APScheduler work as class member like:

```
class MyClass:
    def __init__(self):
        self._scheduler = None

    def my_function():
        return "OK"

    def schedule():
          self._scheduler = BackgroundScheduler()
          self._scheduler.start()

          # Use of external trigger to make Nuitka happy, see https://stackoverflow.com/a/51405831/2635443
          trigger = interval.IntervalTrigger(hours=12, jitter=11 * 3600)
          self._scheduler.add_job(self.my_function, trigger=trigger, kwargs={}, id='some-id')
```

I could then run with:
```
my_instance = MyClass()
my_instance.schedule()
```

**Comment by agronholm** [comment]
That works as long as you don't try to use a persistent data store or a process pool executor, both of which require pickling.
