### ISSUE TITLE
how to run a function like celery async_apply

### ISSUE THREAD

**Issue by shuxiang** [agronholm/apscheduler#308]
run a function  just one time, but async, just like celery's async_apply:
id = task.apply_async()
got result later:
result = task.AsyncResult(id)

I already use apscheduler to run cron job, for keep progam simple, I prefer to not use celery if apscheduler can do this

**Comment by agronholm** [comment]
APScheduler is a task scheduler, not a task queue. Perhaps you are looking for [concurrent.futures](https://docs.python.org/3.6/library/concurrent.futures.html) instead?
