### ISSUE TITLE
Global logger settings issues

### ISSUE THREAD

**Issue by qli-aa** [agronholm/apscheduler#314]
I try to setup a global logger like below
```
#Setup global logger
logger     = logging.getLogger('time-scheduler')
logger.setLevel(logging.DEBUG)
formatter  = logging.Formatter('%(asctime)s - %(module)s - %(funcName)s - %(name)s - %(levelname)s - %(message)s')
handler    = logging.StreamHandler(sys.stdout)
handler.setFormatter(formatter)
logger.addHandler(handler)
```

it only works for apscheduler.scheduler, but does not work for apscheduler.jobstores
I found I can pass my logger to [scheduler](https://github.com/agronholm/apscheduler/blob/master/apscheduler/schedulers/base.py#L690), but not [jobstores](https://github.com/agronholm/apscheduler/blob/master/apscheduler/jobstores/base.py#L39)

is it  expected ?

**Comment by agronholm** [comment]
How do you expect a logger named `time-scheduler` to do anything about the logging settings of `apscheduler`? Are you sure you've read the [logging.config](https://docs.python.org/3.7/library/logging.config.html) documentation?

**Comment by agronholm** [comment]
No reply in 4 months – closing.
