### ISSUE TITLE
timezone issue for scheduler

### ISSUE THREAD

**Issue by qli-aa** [agronholm/apscheduler#315]
sample code from apscheduler docs:
```
from pytz import utc
....
scheduler = BackgroundScheduler(jobstores=jobstores, executors=executors, job_defaults=job_defaults, timezone=utc)
```

it works for ubuntu, but after I change OS to amazonlinux, does not work
error message:
```
ERROR:apscheduler.jobstores.default:Unable to restore job "xxxx_job" -- removing it
Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 141, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/usr/local/lib64/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 125, in _reconstitute_job
    job_state = pickle.loads(job_state)
  File "/usr/local/lib/python2.7/site-packages/pytz/__init__.py", line 283, in _p
    return unpickler(*args)
  File "/usr/local/lib/python2.7/site-packages/pytz/tzinfo.py", line 539, in unpickler
    tz = pytz.timezone(zone)
  File "/usr/local/lib/python2.7/site-packages/pytz/__init__.py", line 177, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'local'
```
then I add a file /etc/timezone with content 'Etc/UTC', it works

when add a scheduled job, should it use timezone I passed in code otherwise read from /etc/timezone ?
looks like it always get it from [system config](https://github.com/agronholm/apscheduler/blob/master/apscheduler/schedulers/base.py#L691)

**Comment by qli-aa** [comment]
I found 2 issues here:
1. apscheduler does not use timezone keyword I passed ?
2.pytz/tzlocal try to get timezone function had a bug with amazonlinux distribution

**Comment by agronholm** [comment]
1. How did you pass the timezone argument?
2. Where should tzlocal find the local timezone on amazonlinux?

**Comment by qli-aa** [comment]
1.
pass timezone=utc to BackgroundScheduler like this:
```
from pytz import utc
scheduler = BackgroundScheduler(jobstores=jobstores, executors=executors, job_defaults=job_defaults, timezone=utc)
```

2. amazonlinux should be /etc/localtime, like centos/redhat instead of /etc/timezone, but tzlocal think it was not centos-like OS (because /etc/localtime exists but not a symlink), then return **local** timezone

**Comment by agronholm** [comment]
> amazonlinux should be /etc/localtime, like centos/redhat instead of /etc/timezone, but tzlocal think it was not centos-like OS (because /etc/localtime exists but not a symlink), then return local timezone

Didn't you just say that you had to **create** `/etc/timezone` yourself?

**Comment by qli-aa** [comment]
yes. I created /etc/timezone as a workaround solution

**Comment by agronholm** [comment]
For 1), lots of people use an explicit time zone and it works fine for them. Would you mind giving me a complete, minimal standalone script that demonstrates the problem?
For 2), if /etc/timezone is not there, does it at least have /etc/localtime or another source of timezone information?

**Comment by bngo92** [comment]
This is the issue I'm seeing on "CentOS Linux release 7.4.1708 (Core)"

`[ERROR] Unable to determine the name of the local timezone -- use an explicit timezone instead
Traceback (most recent call last):
  File "apscheduler/schedulers/base.py", line 334, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "apscheduler/schedulers/base.py", line 787, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "apscheduler/schedulers/base.py", line 773, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "apscheduler/triggers/cron/__init__.py", line 52, in __init__
    self.timezone = astimezone(timezone)
  File "apscheduler/util.py", line 80, in astimezone
    raise ValueError('Unable to determine the name of the local timezone -- use an explicit timezone instead')
ValueError: Unable to determine the name of the local timezone -- use an explicit timezone instead`

/etc/localtime does say UTC but since the zone is always local when using /etc/localtime, APScheduler doesn't work.
`$ cat /etc/localtime
TZif2UTCTZif2UTC
UTC0`

**Comment by agronholm** [comment]
@bngo92 Does this happen with the latest versions of tzlocal and apscheduler?

**Comment by likewhoa** [comment]
@bngo92 You need to use a timezone name (such as Europe/Helsinki). For me it was America/New_York. `echo "America/New_York >/etc/timezone` for instance.

**Comment by agronholm** [comment]
As for the first observed problem, it happened while restoring an *existing* job. The timezone you set for the scheduler does not affect jobs added *before* that. So, not a bug. As for the second, report that to the tzlocal issue tracker.
