### ISSUE TITLE
how to fetch missed jobs from scheduler

### ISSUE THREAD

**Issue by rohan-t** [agronholm/apscheduler#319]
I am using BackgroundScheduler scheduler to schedule my jobs.

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore

jobstores = {'default': SQLAlchemyJobStore(engine=my_db_engine)}
scheduler = BackgroundScheduler(jobstores=jobstores)
job = scheduler.add_job(my_job, run_date=some_future_time, misfire_grace_time=60)

I want to fetch missed jobs for scheduler which passed misfire_grace_time. The scheduler.get_jobs() will give only future jobs.

**Comment by agronholm** [comment]
Closing as invalid because you did not read the warning in the issue template. I will try to answer your SO post instead.
