### ISSUE TITLE
Drift in interval-based jobs?

### ISSUE THREAD

**Issue by user706** [agronholm/apscheduler#320]
Hi,

does an interval-based job ([example](https://github.com/agronholm/apscheduler/blob/master/examples/schedulers/background.py#L19))...

```python
 scheduler.add_job(tick, 'interval', seconds=3)
```

... have drift?

'couldn't find anything about "drift" in the documentation.

Of course, I do **not** want drift. In other words -- I would like to have a behaviour as in this example:

```python
import time

def go_avoid_drift(interval):
    trigg_at = time.monotonic()
    while True:
        # absolute time, when to trigger (avoids drift)
        trigg_at += interval

        # calc relative delay needed
        delay = trigg_at - time.monotonic()
        time.sleep(delay)
        
        print(time.monotonic())



go_avoid_drift(1.0)
```

Thanks for expanations.

**Comment by agronholm** [comment]
This bug tracker is not for asking questions. I thought the issue template clearly indicated that.
