### ISSUE TITLE
add_job is not executed in order

### ISSUE THREAD

**Issue by yanchdh** [agronholm/apscheduler#325]
```
scheduler = BlockingScheduler()

def work(n):
  print('work: %s' % n)

for i in range(11):
  scheduler.add_job(lambda i=i: work(i), 'date', id=str(i), run_date=datetime.datetime.now() + datetime.timedelta(seconds=1))

try:
  scheduler.start()
except (KeyboardInterrupt, SystemExit):
  pass

# output
work: 0
work: 1
work: 10
work: 2
work: 3
work: 4
work: 5
work: 6
work: 7
work: 8
work: 9
```

Why "wrok: 10" is not last?
Because, MemoryJobStore._get_job_index ordered with timestamp and job_id.
But why use job_id?　Is is a bug?

**Comment by agronholm** [comment]
Because the scheduled time is the same for all the jobs (as the accuracy is 1 second), so it sorts the jobs by the secondary criterion which is the job id, which in turn is a randomly generated identifier.

**Comment by agronholm** [comment]
Correction: since you're supplying your own job ids, it sorts by them. Naturally, the string "work 10" compares lower than "work 2" since "1" < "2".

**Comment by agronholm** [comment]
I'm wondering if we're on the same page here. Did you read my last message? What should it sort the due jobs by in your opinion, if not first by scheduled time and then job id?

**Comment by yanchdh** [comment]
Thank for your answer. So sorry for that. Hope this time my expression is clear enough.
First by scheduled time and then job id is OK. But the job id should self increasing to ensure that fun1 must be executed first than func2. That's what I mean.

**Comment by agronholm** [comment]
> But the job id should self increasing to ensure that fun1 must be executed first than func2.

Did you mean that I should change APScheduler somehow? I would remind you that the job id is just a string and will be sorted according to normal string sorting rules. And if you want different IDs, then assign them yourself. You yourself just assigned the jobs IDs which caused the jobs to sorted in an order where they are not executed in the order they were added.
