### ISSUE TITLE
Event of remove_job in listener

### ISSUE THREAD

**Issue by masoudr** [agronholm/apscheduler#327]
Hi,
I'm trying to implement a functionality that when a job reaches its end time and remove by the scheduler.
Suppose this script:
```
from time import sleep
from pprint import pprint
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.triggers.date import DateTrigger
from apscheduler.triggers.interval import IntervalTrigger
from apscheduler.events import EVENT_JOB_EXECUTED, EVENT_JOB_ERROR, EVENT_JOB_REMOVED


def job_executed(event):
    pprint(vars(event))
    print("hello from job_executed")


def func():
    return "hello from func"


if __name__ == '__main__':
    jobstores = {
        'default': SQLAlchemyJobStore(url='sqlite:///test.db')
    }
    sched = BackgroundScheduler(jobstores=jobstores)
    sched.add_listener(job_executed, EVENT_JOB_EXECUTED | EVENT_JOB_ERROR | EVENT_JOB_REMOVED)

    trig = IntervalTrigger(seconds=0.5)
    sched.add_job(func, trigger=trig,
                  id='func', replace_existing=True,
                  max_instances=1)
    sched.start()
    sleep(10)
    sched.remove_job('func')
    print("Done!!!")
    while True:
        pass

```

> hello from job_executed
> {'alias': None,
>  'code': 4096,
>  'exception': None,
>  'job_id': 'func',
>  'jobstore': 'default',
>  'retval': 'hello from func',
>  'scheduled_run_time': datetime.datetime(...),
>  'traceback': None}
> hello from job_executed
> {'alias': None, 'code': 1024, 'job_id': 'func', 'jobstore': 'default'}
> hello from job_executed
> Done!!!

Please consider that both `EVENT_JOB_EXECUTED` and `EVENT_JOB_REMOVED` must be on the same callback function. The `job_executed` function needs to know when the job gets removed by the scheduler. I see only `code` that is `1024` for `job_remove`. Another problem is the `job_id` is missing in `event` for a removed_job.  How do I know which `job_id` has been removed?
Thanks.

**Comment by ericgj** [comment]
It looks like the event object that gets passed to your callback for job removal has `job_id == 'func'` and `code == EVENT_JOB_REMOVED`.  Not sure what else you need?  The time it was removed is basically `datetime.now()` isn't it?

**Comment by masoudr** [comment]
@ericgj Thanks, but in the callback function, I need to check if it is called by `job_executed` or `job_remove` and the only difference I can see is the `code`. Is it true to check base on this attribute or there is another way?

**Comment by ericgj** [comment]
It looks like that's it, see this line in `remove_job`:  https://github.com/agronholm/apscheduler/blob/master/apscheduler/schedulers/base.py#L618
