### ISSUE TITLE
Flask application context is lost when using a persistent job store

### ISSUE THREAD

**Issue by petargyurov** [agronholm/apscheduler#331]
## Expected Behavior
Be able to store jobs whose functions are wrapped with the `app.app_context()` in a persistent job store like `SQLAlchemyJobStore`. **Note:** this all works fine for `MemoryJobStore`.

## Current Behavior
Function reference cannot be resolved when providing a function that is wrapped in another; providing the textual reference does not aleviate the issue because then the application context is lost.

## Detailed Description
My Flask application already utilises APScheduler's `MemoryJobStore` to run various tasks. I have a custom class of the scheduler that simply adds the application context to the equation:

```
class CustomScheduler(object):
	def __init__(self, app=None):
		self._scheduler = BackgroundScheduler()
		self.app = None
		if app:
		self.init_app(app)
	
	# stuff ...

	def add_job(self, func, trigger=None, job_id=None, args=None, kwargs=None,
                    replace_existing=False, **trigger_args):
		
                    def wrapped(*args, **kwargs):
			with self.app.app_context():
				func(*args, **kwargs)
		
		return self._scheduler.add_job(wrapped, id=job_id, trigger=trigger, args=args,
					       kwargs=kwargs, replace_existing=replace_existing,
					       **trigger_args)
```

This works fine with the in-memory jobstore. In my views I can schedule jobs as expected. However, when I configure the scheduler with a `SQLAlchemyJobStore`, the behaviour changes. I get the error:

`Error resolving reference my_app.custom.custom_scheduler:wrapped: error looking up object`

Ok, weird. Then trying with a textual reference will work right (i.e.: passing my function reference instead of `wrapped`)? Well, yes and no. The function is found and thus added successfully to the job store, but when the job runs it is missing the Flask application context and doesn't work properly.

It kind of makes sense to me that it works for `MemoryJobStore` and not for a persistent job store but I am not sure exactly why. 

Any ideas on how to reconcile this?

**Comment by agronholm** [comment]
How do you expect the scheduler to look up the target function if not by a textual reference? What should be serialized in the job object to help with that?

**Comment by petargyurov** [comment]
I'm not sure to be honest. I guess my question is why does this work for `MemoryJobStore` and not `SQLAlchemyJobStore`?

**Comment by agronholm** [comment]
Because MemoryJobStore does not serialize the jobs.

**Comment by petargyurov** [comment]
I see. I will close this since it's not an issue with the inherent design. Will ask on SO for possible workarounds since I am a bit lost on how to preserve the context in such a case - I get the feeling I don't want to be doing this in the first place but we'll see. Thanks.
