### ISSUE TITLE
AsyncIOScheduler stops my asyncio loop

### ISSUE THREAD

**Issue by TheBubblePopped** [agronholm/apscheduler#334]
```
import twitter
import discord
import logging
from apscheduler.schedulers.asyncio import AsyncIOScheduler
import asyncio


client = discord.Client()
shunpo = AsyncIOScheduler(timezone='utc')



@client.event
async def on_ready():
    print('We have logged in as {0.user}'.format(client))

@client.event
async def on_message(self, message):
    if message.author == client.user:
        return

#define later on if u have more functions
def setup_shed():
    pass

async def botSpeech():
    print("happend")

    print("2ndtime")


if __name__ == '__main__':
    shunpo.add_job(botSpeech, 'cron', day_of_week=1, day='8-15' )
    shunpo.start()


    #Making discord rdy and run service

    client.run('token')


```

This is my code if i change the     shunpo.add_job(botSpeech, 'cron', day_of_week=1, day='8-15' ) to something else it works for example if i pick just a day or something. 

If i pick  shunpo.add_job(botSpeech, 'cron', day='day='2nd tue') it does not aswell  the loop of the client.run just stops and i am getting the exit code 0 if i use the      shunpo.add_job(botSpeech, 'cron', minute=3 ) it works f.e.

**Comment by agronholm** [comment]
Can you reduce this code sample to something I could run? I.e. without the discord stuff. Your problem is a bit hard to reproduce otherwise. Have you also read the troubleshooting section of the documentation?

**Comment by agronholm** [comment]
Requested information not provided – closing.
