### ISSUE TITLE
I can only add a max of 10 jobs.

### ISSUE THREAD

**Issue by Juanjoorrego** [agronholm/apscheduler#337]
I can't seem to find anywhere in the documentation a way to add more than 10 jobs in parallel. I have about 12 of them, and only ten of them are executed for BlockingScheduler. Any ideas?

Would be great to add to the docs.

**Comment by agronholm** [comment]
There is a reason for the issue template which you have ignored – so that I would not have to ask for instructions for how to reproduce the problem.
