### ISSUE TITLE
Cannot shutdown BlockingScheduler from listener

### ISSUE THREAD

**Issue by defrank** [agronholm/apscheduler#338]
## Expected Behavior
Calling `BlockingScheduler.shutdown()` from a listener handler should join executor threads from the main thread.

## Current Behavior
With the `BlockingScheduler`, listeners are run in a thread.  Calls to `BlockingScheduler.shutdown()` from the listener fail on joining the threads because `shutdown` is meant to be called from the main thread.
```
python bug.py
Hello, World!
Error notifying listener
Traceback (most recent call last):
  File "/home/derek/.pyenv/versions/triggered-flows/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 828, in _dispatch_event
    cb(event)
  File "bug.py", line 14, in shutdown
    scheduler.shutdown()
  File "/home/derek/.pyenv/versions/triggered-flows/lib/python3.7/site-packages/apscheduler/schedulers/blocking.py", line 22, in shutdown
    super(BlockingScheduler, self).shutdown(wait)
  File "/home/derek/.pyenv/versions/triggered-flows/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 187, in shutdown
    executor.shutdown(wait)
  File "/home/derek/.pyenv/versions/triggered-flows/lib/python3.7/site-packages/apscheduler/executors/pool.py", line 26, in shutdown
    self._pool.shutdown(wait)
  File "/home/derek/.pyenv/versions/3.7.1/lib/python3.7/concurrent/futures/thread.py", line 204, in shutdown
    t.join()
  File "/home/derek/.pyenv/versions/3.7.1/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

## Steps to Reproduce
```
import time

from apscheduler.events import EVENT_JOB_EXECUTED
from apscheduler.schedulers.blocking import BlockingScheduler


def hello():
    print('Hello, World!')
    time.sleep(.1)


def shutdown(event):
    if scheduler.running:
        scheduler.shutdown()


if __name__ == '__main__':
    scheduler = BlockingScheduler()
    scheduler.add_listener(shutdown, EVENT_JOB_EXECUTED)
    scheduler.add_job(hello)

    try:
        scheduler.start()
    except KeyboardInterrupt:
        scheduler.shutdown()
```

## Context (Environment)
I was trying to use the listener handler to shutdown the scheduler after completing a job for testing purposes.

## Detailed Description
One solution I can think of is a 2-step shutdown where `BlockingScheduler.start` watches for a shutdown event and `BlockingScheduler.shutdown` (or new method) sets the event.
```
import threading
import time

from apscheduler.events import EVENT_JOB_EXECUTED
from apscheduler.schedulers.background import BackgroundScheduler


class BlockingScheduler(BackgroundScheduler):
    """A scheduler that blocks in the foreground, runs in the
    background, and is killable from a child thread.

    Use ``BlockingScheduler.run()`` instead of
    ``BlockingScheduler.start()`` and
    ``BlockingScheduler.interrupt()`` instead of
    ``BlockingScheduler.shutdown()``

    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._interrupt = threading.Event()

    def _configure(self, config):
        super()._configure(config)
        self._daemon = False

    def run(self):
        try:
            self.start()
            self._interrupt.wait()
        finally:
            self.shutdown()
        self._interrupt.clear()

    def interrupt(self):
        self._interrupt.set()


def hello():
    print('Hello, World!')
    time.sleep(.1)


def shutdown(event):
    scheduler.interrupt()


if __name__ == '__main__':
    scheduler = BlockingScheduler()
    scheduler.add_listener(shutdown, EVENT_JOB_EXECUTED)
    scheduler.add_job(hello)

    scheduler.run()
```

**Comment by agronholm** [comment]
But have you tried `shutdown(wait=False)`? That at least should work.

**Comment by defrank** [comment]
I can confirm `shutdown(wait=False)` appears to solve this issue.

### Test Script
```python3
#!/usr/bin/env python3
"""
GitHub Issue:
* https://github.com/agronholm/apscheduler/issues/338

"""
import time

from apscheduler.events import EVENT_JOB_EXECUTED
from apscheduler.schedulers.blocking import BlockingScheduler


def hello():
    print('Hello, World!')
    time.sleep(.1)


def shutdown(event):
    if scheduler.running:
        scheduler.shutdown(wait=False)


if __name__ == '__main__':
    scheduler = BlockingScheduler()
    scheduler.add_listener(shutdown, EVENT_JOB_EXECUTED)
    scheduler.add_job(hello)

    try:
        scheduler.start()
    except KeyboardInterrupt:
        scheduler.shutdown()
```

### Output
```sh
$ ./iss338.py
Hello, World!
```

### Additional
I did not get a chance to try this with the business problem I had.  If I remember correctly, I wrote a subclass that implemented the eventing solution I provided in https://github.com/agronholm/apscheduler/issues/338#issue-374186152 and so was able to work around the issue.

Thanks for the update!  I'll definitely keep this in mind for any future use cases.

**Comment by agronholm** [comment]
I think I should change the default to `wait=False` in v4.0 to avoid misunderstandings like this.

**Comment by defrank** [comment]
Please take my critique with a grain of salt as I'm not as involved with APScheduler at present.  Especially because I'm not taking into consideration the executors in this.

I think my misunderstanding stemmed from `BlockingScheduler.start` not returning a future.  The interface and naming imply that the scheduler is single threaded, which it clearly is not.

A core issue is modeling the scheduler API after [threading.Thread](https://docs.python.org/3/library/threading.html?highlight=threading#threading.Thread), which behaves more like a future.  By naming it `BlockingScheduler` and having it block the main thread, I assumed it to be single threaded and running in the foreground.  In reality it behaved like a future, blocked the foreground, and spawned a child thread to actually do the scheduling work.

I would prefer a separation of concerns here by splitting the concurrency management from the scheduler or renaming the class to imply it behaves more like `threading.Thread` (i.e., `SchedulingFuture`).  This would probably also do away with the need to have separate `BlockingScheduler` and `BackgroundScheduler` classes as the developer would decide how to use the scheduler.

`BlockingScheduler` could provide a more intuitive and explicit interface by returning a future when calling `BlockingScheduler.start` similar to [concurrent.futures.Executor.submit](https://docs.python.org/3/library/concurrent.futures.html?highlight=future#concurrent.futures.Executor.submit).

**Comment by CNG** [comment]
I came here trying to understand the intention of `BlockingScheduler` better.

I was hoping to piggy back on this library's cron style parsing to "convert" [python-rtmbot](https://github.com/slackapi/python-rtmbot)'s very simple jobs than run every X seconds to something like "every weekday at 09:00". I hoped I could instead use `apscheduler` to check every X seconds if any jobs came due, run them totally in the foreground and then return so the chatbot can keep doing its other work.

It may be time to fork rtmbot and integrate `apscheduler` into the core, which I was trying to avoid while I am [unsure about the future of that project](https://github.com/slackapi/python-rtmbot/issues/98).
