### ISSUE TITLE
CronTrigger.from_crontab only support 5 sections

### ISSUE THREAD

**Issue by gwh-cpnet** [agronholm/apscheduler#340]
This issue tracker is **ONLY** for reporting bugs.
Issues other than bug reports will be summarily closed.

Any support questions or feature requests should be directed to:

* [StackOverflow](http://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Google groups](http://groups.google.com/group/apscheduler)

raw crontab with 6 sections, which starts with second section, should work fine, since second is supported in the trigger

https://github.com/agronholm/apscheduler/blob/18b50d9ee9ff14e816b557e34d7d3abc861d57e5/apscheduler/triggers/cron/__init__.py#L86

**Comment by agronholm** [comment]
No cron standard I have seen supports 6 sections for the time specification. Link?

**Comment by agronholm** [comment]
I did some research and could not find anything. I'm closing this now since the main cron trigger does support seconds.
