### ISSUE TITLE
docs: add api reference to left navigation pane

### ISSUE THREAD

**Issue by pohmelie** [agronholm/apscheduler#343]
[API reference](https://apscheduler.readthedocs.io/en/latest/py-modindex.html) is most useful day-to-day  page (after you pass tutorial). Second time I spent 5 minutes to find link to this page, since it is not on left navigation pane. Sugget to add it.

**Comment by agronholm** [comment]
Can you suggest how I can do that? I have not found any way to add that link to the navigation pane.
I take it that you finally found the link from the documentation's front page?

**Comment by pohmelie** [comment]
> Can you suggest how I can do that?

I'm not too familiar with sphinx, but maybe it is to add `modindex` in common list [here](https://github.com/agronholm/apscheduler/blob/master/docs/index.rst) in `toctree` right after `faq`.

> I take it that you finally found the link from the documentation's front page?

Yes.

**Comment by agronholm** [comment]
> I'm not too familiar with sphinx, but maybe it is to add modindex in common list here in toctree right after faq.

I tried that before and it didn't work. If you find a working way to do it, please let me know.
