### ISSUE TITLE
the background scheduler does not update every 5 second

### ISSUE THREAD

**Issue by dwy904** [agronholm/apscheduler#348]
How can I let the job schedule to run every day at a certain time like 23:00?

When I tried on this mini code, I was expecting to receive an update for every 5 seconds by using the following script,

```python
from apscheduler.schedulers.background import BackgroundScheduler
from datetime import datetime 

def sensor():
    global a
    a = str(datetime.now())
    print(a)

sched = BackgroundScheduler(daemon = True)
sched.add_job(sensor, 'cron', second = 5)

sched.start()
```
However, I received the update from every minute.

```
2018-12-04 15:45:05.004699
2018-12-04 15:46:05.005055
2018-12-04 15:47:05.004249
```
What did I do wrong?

**Comment by agronholm** [comment]
If you wanted something to happen on fixed intervals, you want to use the "interval" trigger, not "cron". The schedule in your sample code triggers every minute when the second is 5, so like 23:00:05, 23:01:05 etc. That's how cron works (both the cron daemon and apscheduler's cron trigger).

**Comment by agronholm** [comment]
Also, please refrain from posting questions to the issue tracker which is meant for reporting bugs. And when you do, please follow the issue template form.
