### ISSUE TITLE
cronjob 15 10,12 * * 1,7 not supported, 

### ISSUE THREAD

**Issue by ArduChecker** [agronholm/apscheduler#349]
running 
rc = scheduler.add_job(takePicture, CronTrigger.from_crontab(cronjob))

with cronjob = 15 10,12 * * 1,7

stops execution, no result (rc) given back

According https://crontab.guru/#15_10,12_*_*_1,7
..this is a valid job

“At minute 15 past hour 10 and 12 on Monday and Sunday.”

Output
1st -> valid one
2nd -> code stops 

0 0 1,13 * *
takePicture (trigger: cron[month='*', day='1,13', day_of_week='*', hour='0', minute='0'], next run at: 2018-12-13 00:00:00 CET)

15 10,12 * * 1,7

Code:
def on_message(client,userdata, msg):
    if msg.topic == "/apscheduler/job":
        cronjob = msg.payload   
        rc = scheduler.add_job(takePicture, CronTrigger.from_crontab(cronjob))
        print rc
        logger.info("New Cronjob: "+str(cronjob))
        PublishMQTT('INFO','New Cronjob: {}'.format(str(msg.payload)))

**Comment by ArduChecker** [comment]
day week '7' (sunday) is according crontab.guru not standard....

**Comment by mchfrnc** [comment]
@ArduChecker according to the crontab's documentation, both 1 and 7 mean sunday, but there is also an information: 

> "When specifying day of week, both day 0 and day 7 will be considered Sunday. BSD and ATT seem to disagree about this."
 (source: https://linux.die.net/man/5/crontab)

But my question to @agronholm is - is there any reason, that days of week in CronTrigger starts from 0 as monday, while in the mentioned documentation of crontab, first day of week (as 0) is sunday?
It's not a big issue actually, but IMHO better solution would be to use the default crontab convention reagarding "day of week" field.

**Comment by agronholm** [comment]
I'm almost sure there was a good reason for this at some point, but remember that crontab support was added years later as an afterthought. This is something to consider for the next major version, when and if I have the energy to work on it.

**Comment by agronholm** [comment]
I have specified 0 and 7 to both mean Sunday in v4.0.

**Comment by agronholm** [comment]
Fixed as of cb50f0da.
