### ISSUE TITLE
apscheduler crash - Value Error related to timezone

### ISSUE THREAD

**Issue by AdityaVarmaG** [agronholm/apscheduler#352]
## Expected Behavior
My application uses apscheduler to run 8 threads in parallel. Whenever the below error occurs, apscheduler crashes without reporting to log/listeners.

## Current Behavior
![aps_base_month_error](https://user-images.githubusercontent.com/22930397/50415950-d6a53f00-0815-11e9-804a-a5f72ef22b83.PNG)

## Steps to Reproduce
This occurs rarely once/twice in a day (not fixed time).

## Context (Environment)
My application runs on CentOS. I created 8 jobs using background apscheduler

## Detailed Description
With this ValueError, all my jobs (8 running) suddenly stopped. I added logging,  exception and shutdown listeners. But nothing reports. 

I have no clue why this happens. This error started occurring after upgrading to latest 3.5.3 version.

In the current version, I modified the below line in base.py (My system uses UTC). Hopefully this resolves the issue.
#self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
from pytz import timezone
self.timezone = timezone('UTC')

How can we detect apscheduler crash (using log and listeners did not work)? Is there any chance to restart all current jobs, when apscheduler crash is detected?

**Comment by agronholm** [comment]
Are you by any chance monkey patching `datetime`? I cannot think of any other reason why `datetime.now()` would crash.
Your best bet is probably to add a try...except block around the `scheduler.start()` call while using `BlockingScheduler`. Then run the wrapper function in a thread.

Is there anything else I can do get this issue closed to your satisfaction?
