### ISSUE TITLE
Jobstore with pysqlcipher

### ISSUE THREAD

**Issue by masoudr** [agronholm/apscheduler#354]
Hi,
I'm trying to integrate `pysqlcipher3` with jobstores. I'm using this method with default SQLite:
```
        jobstores = {
            'default': SQLAlchemyJobStore(url='sqlite:///test.db')
        }
```
I tried to use [this refrence](https://docs.sqlalchemy.org/en/latest/dialects/sqlite.html#module-sqlalchemy.dialects.sqlite.pysqlcipher) but didn't work for me.
Thanks.

**Comment by agronholm** [comment]
I ask that you follow the issue template. This includes providing a runnable trivial script that reproduces the problem you're seeing. "Doesn't work" is not very helpful.

**Comment by masoudr** [comment]
@agronholm Sorry, I was getting this error:

> error in Scheduler.start() (pysqlcipher3.dbapi2.DatabaseError) file is not a database [SQL: 'PRAGMA table_info("apscheduler_jobs")'] (Background on this error at: http://sqlalche.me/e/4xp6)

It was because of an opening database with the wrong passphrase.
Here is an example:

```
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.executors.pool import ThreadPoolExecutor, ProcessPoolExecutor


def hello():
    print("hello")

if __name__ == "__main__":
    db_alchemy = "sqlite+pysqlcipher://:mypassword@/test.db"
    jobstores = {
            'default': SQLAlchemyJobStore(url=db_alchemy)
    }
    executors = {
        'default': ThreadPoolExecutor(20),
        'processpool': ProcessPoolExecutor(5)
    }
    job_defaults = {
        'coalesce': True,
        'max_instances': 1,
        'misfire_grace_time': 1
    }
    # main scheduler object
    sched = BackgroundScheduler(executors=executors,
                                    jobstores=jobstores,
                                    timezone="Asia/Tehran",
                                    job_defaults=job_defaults,
                                    daemon=True)
    sched.start()
    sched.add_job(hello, 'interval', seconds=2)
    while True:
        pass
```
