### ISSUE TITLE
AsyncIOScheduler.start() should be a coroutine

### ISSUE THREAD

**Issue by RealOrangeOne** [agronholm/apscheduler#360]
## Expected Behavior
It currently isn't possible to use tools like `asyncio.gather` with APScheduler.

## Current Behavior
Currently, `.start` does some weird things behind the scenes with the event loop, requiring you to `run_forever` it manually.

**Comment by agronholm** [comment]
It works this way because asyncio support was essentially shoehorned into the actual design. The next major iteration of APScheduler will introduce proper support.

**Comment by agronholm** [comment]
Proper async support has been provided in v4.0.0a1.
