### ISSUE TITLE
Except apps.py calling BackgroundScheduler not scheduling in django?

### ISSUE THREAD

**Issue by PrabhuSKIT** [agronholm/apscheduler#368]
I am writing the scheduling method in updater.py file. when I am calling that method from apps .py file it's scheduling the job working fine but the same method I am calling from another python file (testing.py) it's not working I don't know why?  If I am doing anything wrong please let me know? Please Help me out this problem.

**Comment by agronholm** [comment]
This is not the right venue for requesting help. Did you not read the issue template?
