### ISSUE TITLE
Python3 read error with job added with python2

### ISSUE THREAD

**Issue by giligiliduang** [agronholm/apscheduler#369]
## Expected Behavior

All jobs should be read correctly
## Current Behavior

```
def _reconstitute_job(self, job_state):
        job_state = pickle.loads(job_state) #UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 1: ordinal not in range(128)
        job_state['jobstore'] = self
        job = Job.__new__(Job)
        job.__setstate__(job_state)
        job._scheduler = self._scheduler
        job._jobstore_alias = self._alias
        return job
```
Then I followed https://stackoverflow.com/questions/11305790/pickle-incompatibility-of-numpy-arrays-between-python-2-and-3 change the code to ` job_state = pickle.loads(job_state,encoding="latin1")` then raise an `TypeError: an integer is required (got type str)` this question is very confused
## Steps to Reproduce

1. Python3 reads the job added with python2

## Context (Environment)

apscheduler-version:**3.6.0**
python-version:**3.6.2**
os:**windows**

**Comment by agronholm** [comment]
The "steps to reproduce" means listing instructions what to do to get the same error you did. You could just as well have said "reproduce the error".

**Comment by agronholm** [comment]
I asked for details but none were provided – closing as invalid.
