### ISSUE TITLE
QtScheduler - OverflowError

### ISSUE THREAD

**Issue by WildStriker** [agronholm/apscheduler#371]
Hi,

I was creating a custom trigger to run on a periodic basis using a QtScheduler when I encountered this issue.  This issue seems similiar to #263 but perhaps specific to QtScheduler.

Running on Windows 10, tested with both 32 and 64 bit versions of python

I didn't notice the issue right away as I had some jobs runnings every 10 seconds or so when when I cleared it out I got an OverflowError:
```
Traceback (most recent call last):
  File "\lib\site-packages\apscheduler\schedulers\qt.py", line 42, in _process_jobs
    self._start_timer(wait_seconds)
  File "\lib\site-packages\apscheduler\schedulers\qt.py", line 29, in _start_timer
    self._timer = QTimer.singleShot(wait_seconds * 1000, self._process_jobs)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

Issue seems to be when waiting longer than int max in seconds.  

Should be a quick fix as I tested it by making a const variable `INT_MAX = 2147483647` in qt.py and took the min value between that and `wait_seconds * 1000` before passing it to the QTimer

## Expected Behavior
wait_seconds * 1000 should fall back to 2147483647 for QtScheduler

## Current Behavior
If the only job(s) available total wait seconds is over this amount it will crash

## Steps to Reproduce
Add a job with any trigger, so long as its next fire date causes an OverflowError (30 days from now should do the trick)

## Example
(this is a copy of the QtScheduler example all i did was add a start_date 30 days from now)
```py
from datetime import datetime, timedelta
import signal
import sys

from apscheduler.schedulers.qt import QtScheduler

try:
    from PyQt5.QtWidgets import QApplication, QLabel
except ImportError:
    try:
        from PyQt4.QtGui import QApplication, QLabel
    except ImportError:
        from PySide.QtGui import QApplication, QLabel


def tick():
    label.setText('Tick! The time is: %s' % datetime.now())


if __name__ == '__main__':
    app = QApplication(sys.argv)

    # This enables processing of Ctrl+C keypresses
    signal.signal(signal.SIGINT, lambda *args: QApplication.quit())

    label = QLabel('The timer text will appear here in a moment!')
    label.setWindowTitle('QtScheduler example')
    label.setFixedSize(280, 50)
    label.show()

    scheduler = QtScheduler()

    # any trigger, so long as next fire time causes overflow
    scheduler.add_job(tick, 'interval', seconds=3, start_date=datetime.now() + timedelta(days=30))
    scheduler.start()

    # Execution will block here until the user closes the windows or Ctrl+C is pressed.
    app.exec_()
```

**Comment by agronholm** [comment]
On Windows, the global limit for waiting time should be well under that. I'll need to investigate further.
