### ISSUE TITLE
Daylight saving on interval trigger

### ISSUE THREAD

**Issue by sdefauw** [agronholm/apscheduler#372]
Hello,

We observed an issue on during the daylight saving clock on Europ/Brussels TZ during the night of 30 March and 31 March. After this time every schedule is executed with 1 hour of delay.

We thing it's an issue on the interval trigger (the cron trigger is already reported on your website). Mabe it is a behavior expected. But we want to have more information about it.

## Test
We did a simple test during in order to tackel the issue:
```python
import pytz
import datetime

from apscheduler.schedulers.background import BackgroundScheduler

def task():
	print("TASK EXECUTED")

scheduler = BackgroundScheduler()

scheduler.add_job(task, 'interval',
	start_date=datetime.datetime(2019, 3, 26, 16, 0, 0),
	days=7
)
scheduler.add_job(task, 'interval',
	start_date=datetime.datetime(2019, 4, 2, 17, 0, 0),
	days=7
)
scheduler.add_job(task, 'interval',
	start_date=datetime.datetime(2019, 4, 2, 20, 0, 0),
	days=7
)

scheduler.start()
scheduler.print_jobs()

```

## Expected Behavior
output expected:
```
Jobstore default:
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-04-02 16:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-04-02 17:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-04-02 20:00:00 CEST)
```
Where we shedule at 16:00.

## Current Behavior
output expected:
```
Jobstore default:
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-04-02 17:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-04-02 17:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-04-02 20:00:00 CEST)
```
Where we shedule at 17:00 and we expect 16:00

## Solution (path)
The path we made now, it's changing the method `get_next_fire_time` in  `trigger/interval.py`

Adding 
```python
next_fire_time = next_fire_time.tzinfo.localize(next_fire_time.replace(tzinfo=None))
```
and it become like this:
```python
 def get_next_fire_time(self, previous_fire_time, now):
        if previous_fire_time:
            next_fire_time = previous_fire_time + self.interval
        elif self.start_date > now:
            next_fire_time = self.start_date
        else:
            timediff_seconds = timedelta_seconds(now - self.start_date)
            next_interval_num = int(ceil(timediff_seconds / self.interval_length))
            next_fire_time = self.start_date + self.interval * next_interval_num
            # PATCH MADE
            next_fire_time = next_fire_time.tzinfo.localize(next_fire_time.replace(tzinfo=None))

        if self.jitter is not None:
            next_fire_time = self._apply_jitter(next_fire_time, self.jitter, now)

        if not self.end_date or next_fire_time <= self.end_date:
            return self.timezone.normalize(next_fire_time)
```

So we would like to have your expetise in order to know if this patch is good or we made a mistake ?

**Comment by sdefauw** [comment]
Someone can help me with this issue?

**Comment by agronholm** [comment]
If you give the start date as a timezone aware datetime then there should be no issue.
What is the actual detected timezone in the scheduler when this happens?

**Comment by agronholm** [comment]
The last line (`return self.timezone.normalize(next_fire_time)`) already converts between DST and non-DST. If you disagree, please give me a minimal reproducing example where you set the timezone manually.

**Comment by sdefauw** [comment]
See an example
```python
import pytz
from pytz import timezone, utc
import datetime

from apscheduler.schedulers.background import BackgroundScheduler

bru = timezone('Europe/Brussels')

d1 = datetime.datetime(2019, 3, 26, 16, 0, 0)
d2 = datetime.datetime(2019, 4, 2, 17, 0, 0)
d3 = datetime.datetime(2019, 4, 2, 20, 0, 0)

d1_tz = bru.localize(d1)
d2_tz = bru.localize(d2)
d3_tz = bru.localize(d3)

print(d1_tz.isoformat())
print(d2_tz.isoformat())
print(d3_tz.isoformat())



def task():
	print("TASK EXECUTED")

print(" === With TZ === ")
scheduler = BackgroundScheduler()

scheduler.add_job(task, 'interval',
	start_date=d1,
	days=7
)
scheduler.add_job(task, 'interval',
	start_date=d2,
	days=7
)
scheduler.add_job(task, 'interval',
	start_date=d3,
	days=7
)

scheduler.start()
scheduler.print_jobs()

print(" === With UTC === ")
scheduler = BackgroundScheduler()

scheduler.add_job(task, 'interval',
	start_date=utc.localize(d1),
	days=7
)
scheduler.add_job(task, 'interval',
	start_date=utc.localize(d2),
	days=7
)
scheduler.add_job(task, 'interval',
	start_date=utc.localize(d3),
	days=7
)

scheduler.start()
scheduler.print_jobs()


print(" === Without TZ === ")
scheduler = BackgroundScheduler()

scheduler.add_job(task, 'interval',
	start_date=d1,
	days=7
)
scheduler.add_job(task, 'interval',
	start_date=d2,
	days=7
)
scheduler.add_job(task, 'interval',
	start_date=d3,
	days=7
)

scheduler.start()
scheduler.print_jobs()
```

Output:
```
2019-03-26T16:00:00+01:00
2019-04-02T17:00:00+02:00
2019-04-02T20:00:00+02:00
 === With TZ === 
Jobstore default:
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 17:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 17:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 20:00:00 CEST)
 === With UTC === 
Jobstore default:
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 18:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 19:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 22:00:00 CEST)
 === Without TZ === 
Jobstore default:
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 17:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 17:00:00 CEST)
    task (trigger: interval[7 days, 0:00:00], next run at: 2019-06-11 20:00:00 CEST)
```

So in my example, I'm using the timezone "Brussels". So when I schedule an event at 16 o'clock before the daylight saving, I expect that the scheduler will execute the event at 16 o'clock one week later (after the daylight saving).
However, since we move from UTC+1 to UTC+2, the scheduler execute the event at 17 o'clock  (after the daylight saving).

**Comment by sdefauw** [comment]
Can we have some feedback based on the example I provided?

**Comment by agronholm** [comment]
Since the first and last start times are exactly 7 days (7 * 24 h) apart, it stands to reason that the next fire time (given the current date and time) would be the same, yes? The fact that they're both at 17:00:00 is due to the DST shift occurring in your time zone between the first and second start dates. If the next fire time for the first job was at 16:00 instead, it would fall one hour short of the 7 day interval.

**Comment by sdefauw** [comment]
I understand but for me, the 7 days with the daylight saving is not 7 * 24h.

For me, if I schedule an interval of each day (or every 7 days) I expect that fire each day of the year at the same hour (here, every day at 16:00:00). I don't want to fire half of the year at 16:00:00 and another half at 17:00:00.

So how can I change my code (example) in order to tackle the issue without changing the framework?

**Comment by agronholm** [comment]
The interval trigger is documented to fire on constant intervals. If you want something else, you will need a different kind of trigger. It sounds like the calendar interval trigger is what you want. I will integrate that in a future version of APScheduler, but for now you can find the base code [here](https://github.com/asphalt-framework/asphalt-scheduling/blob/master/asphalt/tasks/schedules/calendarinterval.py). It will need some adaptation on your part to work with APScheduler, but the code passes its test suite in its own repository.

**Comment by sdefauw** [comment]
Okay, thank you.
