### ISSUE TITLE
"Interval" scheduler skipping first iteration

### ISSUE THREAD

**Issue by ozone89** [agronholm/apscheduler#375]
Is this an intended behaviour?

I get there's a workaround [proposed by the author himself](https://stackoverflow.com/questions/43254531/python-apschedule-blockingscheduler-with-interval-trigger-start-immediately), but it seems a bit counter-intuitive to me, and it involves adding `from datetime import datetime` to your code, further cluttering it.

Could it be possible to at least add an option, like `skip_first_run=[True|False]`?

**Comment by agronholm** [comment]
It was the original behaviour and I intend to change it in the next major release.

**Comment by ozone89** [comment]
thank you :D
