### ISSUE TITLE
catch error if no local timezone

### ISSUE THREAD

**Issue by naseemkullah** [agronholm/apscheduler#376]
Would it be possible to catch the following error:

```
raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

and fallback to UTC?

Cheers

**Comment by agronholm** [comment]
You can do that. But I will not do it by default in APScheduler. The vast majority of systems have no trouble detecting the local timezone. Defaulting to UTC in such cases will lead to confusion and bug reports.
