### ISSUE TITLE
scheduler.get_jobs() does not return jobstore jobs

### ISSUE THREAD

**Issue by p-doyle** [agronholm/apscheduler#377]
This may not be a bug but after loading a jobstore with existing jobs, nothing is output from print_jobs():
```
scheduler = BackgroundScheduler()
scheduler.add_jobstore('sqlalchemy', alias='my_jobstore', url='sqlite:///example.db')
scheduler.print_jobs()
```

I would expect the jobs loaded from the jobstore to be pending but only after calling .start() will there be any output.  It seems the jobs are still available in scheduler._jobstores but they are only printed if the scheduler hasn't started yet...(see https://github.com/agronholm/apscheduler/blob/50a7e3935b19e01ce58582c5aae2fe9ccbfda988/apscheduler/schedulers/base.py#L664)  is that intended functionality?  I am interested in a way to get jobs from a jobstore before the starting the scheduler.

Thanks for all your work on this!

**Comment by agronholm** [comment]
It's intended functionality. Also next time do not ignore the issue template and post your question on SO or Gitter instead.
