### ISSUE TITLE
Incorrect source code on pypi?

### ISSUE THREAD

**Issue by synapticarbors** [agronholm/apscheduler#382]
I was attempting to build APScheduler 3.6.1 for conda-forge and was running into errors about imports of `six`, which looking at the source on github should not be there. When I downloaded the tarball from pypi, I can see that it looks to contain an old version of the code since all of the python 2.X dependencies are still listed and imported.

**Comment by agronholm** [comment]
I released v3.6.1 today just before I dropped Python 2 support, so everything should be in order, yes?

**Comment by synapticarbors** [comment]
I guess I was confused since `versionhistory.rst` says that version 3.6.0 dropped support, so I assumed version 3.6.1 would be py3-only.

**Comment by agronholm** [comment]
Ah, seems there was a mistake introduced by the code rebase operation.

**Comment by synapticarbors** [comment]
So just to be 100% explicit, version 3.6.1 will still support python 2.7 and the next release will be python >3.5 only. Is that correct?

**Comment by agronholm** [comment]
Yup.

**Comment by agronholm** [comment]
There may be additional patch release on the 3.x series but the feature development focuses only on 4.0 now.

**Comment by synapticarbors** [comment]
Great. Thank you for the clarification
