### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by flyfire100** [agronholm/apscheduler#383]
when i test my code, i find a random problem, this  is my  code
```python3
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.events import EVENT_JOB_EXECUTED,EVENT_JOB_ERROR
import time

scheduler = BackgroundScheduler()
 


def  mythandler(event):
    if event.exception:
        print(event.job_id, "is error=======")
    else:
        print(event.job_id, "is normal==========")
        scheduler.remove_job(event.job_id)

def job1( text):
    time.sleep(2)
    return "hello","minix"
    
scheduler.add_listener(mythandler,EVENT_JOB_EXECUTED | EVENT_JOB_ERROR)
scheduler.start()


for i in range(5):   
    scheduler.add_job(job1, 'interval', id=str(i),seconds=1,args=["hello"])


while True:
    jobs = scheduler.get_jobs()
    for job in jobs:
        print("jobid is ",job.id)
    time.sleep(1)
```

i  think  job1 will  run  five  times, but sometimes it   will run six times, like this
![image](https://user-images.githubusercontent.com/28288582/61605016-45e0f580-ac76-11e9-8b2d-b1754d859d4b.png)

so please help

**Comment by agronholm** [comment]
Please use the proper channels (StackOverflow, Gitter or Google group, as outlined [here](https://apscheduler.readthedocs.io/en/latest/userguide.html#getting-help) in the documentation). This issue tracker is for bug reports only.

**Comment by flyfire100** [comment]
i think this  is  a  bug

**Comment by agronholm** [comment]
Then at least please properly format the code and minimize the code in a way that is still reproduces the bug.

**Comment by agronholm** [comment]
So why do you think there is a bug? You're removing a job and then you wonder why it can't be fetched from the scheduler anymore? Or did I miss something?

**Comment by flyfire100** [comment]
job should no longer be performed after it have been removed

**Comment by agronholm** [comment]
You are seeing a race condition. For whatever reason, the delivery of the execution events is delayed so you get two calls about the same job. I suggest that you catch and ignore the `JobLookupError` to solve the problem here.
