### ISSUE TITLE
memory leak issue with cv2.imwrite

### ISSUE THREAD

**Issue by kioipp** [agronholm/apscheduler#385]
This issue tracker is **ONLY** for reporting bugs.
Issues other than bug reports will be summarily closed.

Any support questions or feature requests should be directed to:

* [StackOverflow](http://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Google groups](http://groups.google.com/group/apscheduler)

I use cv2 to read camera and dump frame by intervals , simply works well by a while circulation , but when added in BackgroundScheduler , it will lead to memory leak issue .

Here is the sample  code :

```python
# -*- encoding: utf-8 -*-
import time
import cv2
import re
import os
from datetime import datetime
from contextlib import AbstractContextManager
from apscheduler.schedulers.blocking import BlockingScheduler


class Camera(AbstractContextManager):
    def __init__(self, lane_id, uri):
        self.capture, self.width, self.height = None, None, None
        self.uri = uri
        self.lane_id = lane_id

    def __connect(self):
        if not self.capture:
            self.capture = cv2.VideoCapture(self.uri)

        retry = 3
        while retry > 0:
            time.sleep(0.01)
            if self.capture.isOpened():
                break
            self.capture.open(self.uri)
            retry -= 1

        pattern = r"\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b"
        self.camera_ip = re.findall(pattern, self.uri)[0]

        self.width = self.capture.get(3)  # cv2.cv.CV_CAP_PROP_FRAME_WIDTH = 3
        self.height = self.capture.get(
            4)  # cv2.cv.CV_CAP_PROP_FRAME_HEIGHT = 4

    def __exit__(self, exc_type, exc_value, traceback):
        self.release()

    def save(self):
        self.__connect()
        folder_path = self.buildFolder()
        if self.capture and self.height > 0 and self.width > 0:

            if True:
                ret, frame = self.capture.read()
                timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
                if ret:
                    cv2.imwrite(
                        '{}/{}_{}_{}.jpg'.format(folder_path, '33',
                                                 self.camera_ip, self.lane_id),
                        frame)
                    print("{}/{}_{}_{}.jpg is dumped".format(
                        folder_path, '33flab', self.camera_ip, self.lane_id))
            self.release()

        else:

            self.release()
            # raise errors.CameraSnapshotErro
            print("exit")
        return 0

    def buildFolder(self):
        now = datetime.utcnow()
        date = now.strftime("%Y%m%d")
        hour = now.strftime("%H")
        folder_path = '{}/{}/{}/files'.format('/log/test', date, hour)
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
        return folder_path

    def release(self):
        if self.capture is not None:
            self.capture.release()
            self.capture = None


if __name__ == "__main__":
    url = {
        "a": "rtsp://10.10.8.6:554/axis-media/media.amp?fps=30",
        "b": "rtsp://10.10.8.5:554",
        "c": "rtsp://10.10.8.5:554"
    }
    sched = BlockingScheduler()
    for i in range(0, 5):
        sched.add_job(Camera(i, url["a"]).save, 'interval', minutes=1)
        sched.add_job(Camera(i, url["b"]).save, 'interval', minutes=1)
    sched.start()
    '''
    Sample which would not cause memory leak
    while True:
        for i in range(0, 5):
            Camera(i, url["a"]).save()
            Camera(i, url["b"]).save()
        time.sleep(60)
    '''
```

**Comment by agronholm** [comment]
Can you provide a sample snippet which I can run that will reproduce the problem? You talk about a memory leak but you haven't given any numbers to support that.

**Comment by kioipp** [comment]
> Can you provide a sample snippet which I can run that will reproduce the problem? You talk about a memory leak but you haven't given any numbers to support that.

Hi @agronholm  , thanks for your reply ,  the sample codes on the my first post  is  what will reproduce the issue ,  to run that you need a cv2 docker-image and a vaild rtsp:// url ;

I also prepare some datas to support that :

## prepare 

I add some codes to print the current usage memory bytes around `self.release()` , like this : 

```python
            print("before release: {} bytes".format(returnShell(''' cat /sys/fs/cgroup/memory/memory.usage_in_bytes ''')))
            self.release()
            print("after release: {} bytes".format(returnShell(''' cat /sys/fs/cgroup/memory/memory.usage_in_bytes ''')))
```
the `returnShell()`  is like that : 

```python
def returnShell(command):
    result = subprocess.Popen([command], stdout=subprocess.PIPE, shell=True).communicate()[0].decode().strip("\n")
    return result
```

So before and after release() I will see the current current usage memory bytes 


## Using `apscheduler` to take snapshots  : 

> /log/test/20190805/03/files/20190805034207_10.10.8.6_0.jpg is dumped
before release: 1507930112 bytes
after release: 1237671936 bytes
/log/test/20190805/03/files/20190805034208_10.10.8.6_1.jpg is dumped
before release: 1534083072 bytes
after release: 1338081280 bytes
/log/test/20190805/03/files/20190805034209_10.10.8.5_4.jpg is dumped
before release: 1561563136 bytes
after release: 1570422784 bytes
/log/test/20190805/03/files/20190805034210_10.10.8.6_3.jpg is dumped
before release: 1826918400 bytes
after release: 1829068800 bytes
/log/test/20190805/03/files/20190805034212_10.10.8.6_4.jpg is dumped
before release: 1928679424 bytes
after release: 1923092480 bytes
/log/test/20190805/03/files/20190805034213_10.10.8.5_3.jpg is dumped
before release: 2012844032 bytes
after release: 2005966848 bytes
/log/test/20190805/03/files/20190805034214_10.10.8.5_0.jpg is dumped
before release: 2130505728 bytes
after release: 2134188032 bytes
/log/test/20190805/03/files/20190805034215_10.10.8.6_2.jpg is dumped
before release: 2222149632 bytes
after release: 2214686720 bytes
/log/test/20190805/03/files/20190805034216_10.10.8.5_2.jpg is dumped
before release: 2235269120 bytes
after release: 2220081152 bytes
/log/test/20190805/03/files/20190805034218_10.10.8.5_1.jpg is dumped
before release: 2231861248 bytes
after release: 2226237440 bytes
/log/test/20190805/03/files/20190805034307_10.10.8.6_0.jpg is dumped
before release: 2356969472 bytes
after release: 2368954368 bytes
/log/test/20190805/03/files/20190805034308_10.10.8.6_4.jpg is dumped
before release: 2414215168 bytes
after release: 2406707200 bytes
/log/test/20190805/03/files/20190805034309_10.10.8.5_2.jpg is dumped
before release: 2374987776 bytes
after release: 2359812096 bytes
/log/test/20190805/03/files/20190805034310_10.10.8.5_1.jpg is dumped
before release: 2411003904 bytes
after release: 2409807872 bytes
/log/test/20190805/03/files/20190805034311_10.10.8.6_2.jpg is dumped
before release: 2465587200 bytes
after release: 2458345472 bytes
/log/test/20190805/03/files/20190805034313_10.10.8.6_1.jpg is dumped
before release: 2509594624 bytes
after release: 2493722624 bytes
/log/test/20190805/03/files/20190805034314_10.10.8.5_3.jpg is dumped
before release: 2455465984 bytes
after release: 2448371712 bytes
/log/test/20190805/03/files/20190805034315_10.10.8.5_4.jpg is dumped
before release: 2474119168 bytes
after release: 2466754560 bytes
/log/test/20190805/03/files/20190805034316_10.10.8.5_0.jpg is dumped
before release: 2490929152 bytes
after release: 2478665728 bytes
/log/test/20190805/03/files/20190805034318_10.10.8.6_3.jpg is dumped
before release: 2516336640 bytes
after release: 2508484608 bytes
/log/test/20190805/03/files/20190805034407_10.10.8.6_0.jpg is dumped
before release: 2582659072 bytes
after release: 2580725760 bytes
/log/test/20190805/03/files/20190805034408_10.10.8.6_4.jpg is dumped
before release: 2617151488 bytes
after release: 2608517120 bytes
/log/test/20190805/03/files/20190805034409_10.10.8.5_1.jpg is dumped
before release: 2562224128 bytes
after release: 2544037888 bytes
/log/test/20190805/03/files/20190805034410_10.10.8.5_3.jpg is dumped
before release: 2560696320 bytes
after release: 2555203584 bytes
/log/test/20190805/03/files/20190805034411_10.10.8.5_4.jpg is dumped
before release: 2569482240 bytes
after release: 2559447040 bytes
/log/test/20190805/03/files/20190805034413_10.10.8.6_2.jpg is dumped
before release: 2577838080 bytes
after release: 2567979008 bytes
/log/test/20190805/03/files/20190805034414_10.10.8.5_0.jpg is dumped
before release: 2582732800 bytes
after release: 2580647936 bytes
/log/test/20190805/03/files/20190805034415_10.10.8.6_3.jpg is dumped
before release: 2634301440 bytes
after release: 2626580480 bytes
/log/test/20190805/03/files/20190805034416_10.10.8.6_1.jpg is dumped
before release: 2650476544 bytes
after release: 2637234176 bytes
/log/test/20190805/03/files/20190805034418_10.10.8.5_2.jpg is dumped
before release: 2577985536 bytes
after release: 2565955584 bytes

and docker stats showed : 

> CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
331dfecb44ac        cv-test        0.00%               2.057GiB / 3GiB     68.56%              22.6MB / 524kB      6.81MB / 2.3MB      13

## Using `while True` to take camera snapshots : 

> /log/test/20190805/03/files/20190805035044_10.10.8.6_0.jpg is dumped
before release: 809066496 bytes
after release: 533364736 bytes
/log/test/20190805/03/files/20190805035049_10.10.8.5_0.jpg is dumped
before release: 539004928 bytes
after release: 537464832 bytes
/log/test/20190805/03/files/20190805035054_10.10.8.6_1.jpg is dumped
before release: 817381376 bytes
after release: 815792128 bytes
/log/test/20190805/03/files/20190805035058_10.10.8.5_1.jpg is dumped
before release: 805863424 bytes
after release: 804339712 bytes
/log/test/20190805/03/files/20190805035103_10.10.8.6_2.jpg is dumped
before release: 819785728 bytes
after release: 818253824 bytes
/log/test/20190805/03/files/20190805035108_10.10.8.5_2.jpg is dumped
before release: 808214528 bytes
after release: 806375424 bytes
/log/test/20190805/03/files/20190805035112_10.10.8.6_3.jpg is dumped
before release: 825860096 bytes
after release: 824467456 bytes
/log/test/20190805/03/files/20190805035117_10.10.8.5_3.jpg is dumped
before release: 813912064 bytes
after release: 812380160 bytes
/log/test/20190805/03/files/20190805035122_10.10.8.6_4.jpg is dumped
before release: 829788160 bytes
after release: 828309504 bytes
/log/test/20190805/03/files/20190805035126_10.10.8.5_4.jpg is dumped
before release: 818012160 bytes
after release: 816435200 bytes
/log/test/20190805/03/files/20190805035231_10.10.8.6_0.jpg is dumped
before release: 832573440 bytes
after release: 831086592 bytes
/log/test/20190805/03/files/20190805035236_10.10.8.5_0.jpg is dumped
before release: 820805632 bytes
after release: 819175424 bytes
/log/test/20190805/03/files/20190805035240_10.10.8.6_1.jpg is dumped
before release: 834797568 bytes
after release: 833327104 bytes
/log/test/20190805/03/files/20190805035245_10.10.8.5_1.jpg is dumped
before release: 822652928 bytes
after release: 821121024 bytes
/log/test/20190805/03/files/20190805035250_10.10.8.6_2.jpg is dumped
before release: 835698688 bytes
after release: 834248704 bytes
/log/test/20190805/03/files/20190805035254_10.10.8.5_2.jpg is dumped
before release: 823627776 bytes
after release: 822185984 bytes
/log/test/20190805/03/files/20190805035259_10.10.8.6_3.jpg is dumped
before release: 837517312 bytes
after release: 835780608 bytes
/log/test/20190805/03/files/20190805035303_10.10.8.5_3.jpg is dumped
before release: 825225216 bytes
after release: 824057856 bytes
/log/test/20190805/03/files/20190805035308_10.10.8.6_4.jpg is dumped
before release: 838574080 bytes
after release: 837079040 bytes
/log/test/20190805/03/files/20190805035313_10.10.8.5_4.jpg is dumped
before release: 826785792 bytes
after release: 825131008 bytes


and docker stats showed : 

> CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
331dfecb44ac        cv-test        0.00%               752.8MiB / 3GiB     24.51%              78.8MB / 1.92MB     6.91MB / 2.34MB     3

**Comment by agronholm** [comment]
I do not have a valid rtsp URL. If there is a memory leak in apscheduler, surely it should be reproduceable without some camera library?

**Comment by agronholm** [comment]
One thing you could do: using DebugExecutor instead of ThreadPoolExecutor. That will simplify things somewhat.

**Comment by agronholm** [comment]
No further information was provided in 13 months so I will close this issue. If you feel this is in error, please provide instructions to reproduce this **locally**.

**Comment by CodingJzy** [comment]
我也遇到了啊

**Comment by CodingJzy** [comment]
解决了吗

**Comment by CodingJzy** [comment]
> > 您能否提供一个我可以运行的示例片段来重现该问题？你谈到了内存泄漏，但你没有给出任何数字来支持这一点。
> 
> 嗨，感谢您的回复，我的第一篇文章中的示例代码将重现该问题，要运行您需要一个 cv2 docker-image 和一个有效的 rtsp:// url;
> 
> 我还准备了一些数据来支持这一点：
> 
> ## 准备
> 我添加了一些代码来打印 cv.imwrite（） 之后的当前使用内存字节，如下所示：`self.release()`
> 
> ```python
>             print("before release: {} bytes".format(returnShell(''' cat /sys/fs/cgroup/memory/memory.usage_in_bytes ''')))
>             self.release()
>             print("after release: {} bytes".format(returnShell(''' cat /sys/fs/cgroup/memory/memory.usage_in_bytes ''')))
> ```
> 
> 是这样的：`returnShell()`
> 
> ```python
> def returnShell(command):
>     result = subprocess.Popen([command], stdout=subprocess.PIPE, shell=True).communicate()[0].decode().strip("\n")
>     return result
> ```
> 
> 所以在release（）之前和之后，我会看到当前使用的内存字节数
> 
> ## 用于拍摄快照：`apscheduler`
> > /log/test/20190805/03/files/20190805034207_10.10.8.6_0.jpg 在发布前被转储： 发布后 1507930112 字节： 1237671936 字节 /log/test/20190805/03/files/20190805034208_10.10.8.6_1.jpg 在发布前被转储： 1534083072 字节 发布后： 1338081280 字节 /log/test/20190805/03/files/20190805034209_10.10.8.5_4.jpg 在发布前被转储： 发布后 1561563136 字节：1570422784 字节 /log/test/20190805/03/files/20190805034210_10.10.8.6_3.jpg 在发布之前被转储： 1826918400 字节发布后：1829068800 字节 /log/test/20190805/03/files/20190805034212_10.10.8.6_4.jpg 在发布前被转储： 发布后 1928679424 字节： 1923092480 字节 /log/test/20190805/03/files/20190805034213_10.10.8.5_3.jpg 在发布前被转储：发布后 2012844032 字节：发布前转储 2005966848 字节 /log/test/20190805/03/files/20190805034214_10.10.8.5_0.jpg 发布前转储：发布后 2130505728 字节：2134188032 字节 /log/test/20190805/03/files/20190805034215_10.10.8.6_2.jpg 发布前转储：发布后 2222149632 字节：2214686720 字节 /log/test/20190805/03/files/20190805034216_10.10.8.5_2。jpg 在发布前被转储：发布后 2235269120 字节：2220081152 字节 /log/test/20190805/03/files/20190805034218_10.10.8.5_1.jpg 在发布前被转储：2231861248 字节 发布后：2226237440 字节 /log/test/20190805/03/files/20190805034307_10.10.8.6_0.jpg 在发布前被转储：2356969472 字节 发布后：2368954368 字节/log/test/20190805/03/files/20190805034308_10.10.8.6_4.jpg 在发布前被转储：2414215168 字节 发布后：2406707200 字节 /log/test/20190805/03/files/20190805034309_10.10.8.5_2.jpg 在发布前被转储：2374987776 字节 发布后：2359812096 字节 /log/test/20190805/03/files/20190805034310_10.10.8.5_1.jpg 在发布前被转储：2411003904 字节发布后：2409807872 字节 /log/test/20190805/03/files/20190805034311_10.10.8.6_2.jpg 在发布前被转储： 2465587200 字节 发布后：2458345472 字节 /log/test/20190805/03/files/20190805034313_10.10.8.6_1.jpg 在发布前被转储： 2509594624 字节 发布后：2493722624 字节 /log/test/20190805/03/files/20190805034314_10.10.8.5_3.jpg 被转储发布前：2455465984 字节 发布后：2448371712 字节 /log/test/20190805/03/files/20190805034315_10.10.8.5_4.jpg 发布前转储：2474119168 字节 发布后：2466754560 字节 /log/test/20190805/03/files/20190805034316_10.10.8.5_0.jpg 发布前转储：2490929152 字节 发布后：2478665728 字节/log/test/20190805/03/files/20190805034318_10.10.8.6_3.jpg 在发布之前被转储：发布后 2516336640 字节：2508484608 字节 /log/test/20190805/03/files/20190805034407_10.10.8.6_0.jpg i发布前转储：发布后 2582659072 字节：2580725760 字节 /log/test/20190805/03/files/20190805034408_10.10.8.6_4.jpg 发布前转储：发布后 2617151488 字节：2608517120 字节 /log/test/20190805/03/files/20190805034409_10.10.8.5_1.jpg 发布前转储：发布后 2562224128 字节：2544037888 字节/log/test/20190805/03/files/20190805034410_10.10.8.5_3.jpg 在发布前被转储： 2560696320 字节 发布后： 2555203584 字节 /log/test/20190805/03/files/20190805034411_10.10.8.5_4.jpg 在发布前被转储： 2569482240 字节 发布后： 2559447040 字节 /log/test/20190805/03/files/20190805034413_10.10.8.6_2.jpg 在发布前被转储： 2577838080 字节发布后：2567979008 字节 /log/test/20190805/03/files/20190805034414_10.10.8.5_0.jpg 在发布前被转储： 2582732800 字节 发布后：2580647936 字节 /log/test/20190805/03/files/20190805034415_10.10.8.6_3.jpg 在发布前被转储： 2634301440 字节 发布后：2626580480 字节 /log/test/20190805/03/files/20190805034416_10.10.8.6_1.jpg 被转储发布前：2650476544 字节 发布后：2637234176 字节 /log/test/20190805/03/files/20190805034418_10.10.8.5_2.jpg 发布前转储：2577985536 字节 发布后：2565955584 字节
> 
> Docker 统计数据显示：
> 
> > 容器 ID 名称 CPU 内存使用率百分比/限制内存百分比 净 I/O 块 I/O PIDS 331dfecb44ac cv-test 0.00% 2.057GiB / 3GiB 68.56% 22.6MB / 524kB 6.81MB / 2.3MB 13
> 
> ## 用于拍摄相机快照：`while True`
> > /log/test/20190805/03/files/20190805035044_10.10.8.6_0.jpg 在发布前被转储： 809066496 字节 发布后： 533364736 字节 /log/test/20190805/03/files/20190805035049_10.10.8.5_0.jpg 在发布前被转储： 539004928 字节 发布后： 537464832 字节 /log/test/20190805/03/files/20190805035054_10.10.8.6_1.jpg 在发布前被转储： 817381376 字节 发布后： 815792128字节 /log/test/20190805/03/files/20190805035058_10.10.8.5_1.jpg 在发布前被转储： 805863424 字节 发布后：804339712 字节 /log/test/20190805/03/files/20190805035103_10.10.8.6_2.jpg 在发布前被转储： 819785728 字节 发布后：818253824 字节 /log/test/20190805/03/files/20190805035108_10.10.8.5_2.jpg 在发布前被转储：808214528 字节发布后：806375424 字节 /log/test/20190805/03/files/20190805035112_10.10.8.6_3.jpg 在发布前被转储： 825860096 字节 发布后：824467456 字节 /log/test/20190805/03/files/20190805035117_10.10.8.5_3.jpg 在发布前被转储： 813912064 字节 发布后：812380160 字节 /log/test/20190805/03/files/20190805035122_10.10.8.6_4.jpg 之前被转储release：发布后 829788160 字节：828309504 字节 /log/test/20190805/03/files/20190805035126_10.10.8.5_4.jpg 发布前转储：发布后 818012160 字节：816435200 字节 /log/test/20190805/03/files/20190805035231_10.10.8.6_0.jpg 发布前转储：发布后 832573440 字节：831086592 字节 /log/test/20190805/03/files/20190805035236_10.10.8.5_0。JPG在发布前被转储：820805632字节 发布后：819175424字节 /log/test/20190805/03/files/20190805035240_10.10.8.6_1.jpg 发布前转储：834797568字节 发布后：833327104字节 /log/test/20190805/03/files/20190805035245_10.10.8.5_1.jpg 发布前转储：822652928字节 发布后：821121024字节/log/test/20190805/03/files/20190805035250_10.10.8.6_2.jpg 在发布前被转储：发布后 835698688 字节：834248704 字节 /log/test/20190805/03/files/20190805035254_10.10.8.5_2.jpg 在发布前被转储：823627776 字节 发布后：822185984 字节 /log/test/20190805/03/files/20190805035259_10.10.8.6_3.jpg 在发布前被转储：发布后 837517312 字节release：835780608 字节 /log/test/20190805/03/files/20190805035303_10.10.8.5_3.jpg 在发布之前被转储： 825225216 字节 发布后：824057856 字节 /log/test/20190805/03/files/20190805035308_10.10.8.6_4.jpg 在发布前被转储： 838574080 字节 发布后：837079040 字节 /log/test/20190805/03/files/20190805035313_10.10.8.5_4.jpg 在发布前被转储：释放后 826785792 字节：825131008 字节
> 
> Docker 统计数据显示：
> 
> > 容器 ID 名称 CPU 内存使用率百分比/限制内存百分比 净 I/O 块 I/O PIDS 331dfecb44ac cv-test 0.00% 752.8MiB / 3GiB 24.51% 78.8MB / 1.92MB 6.91MB / 2.34MB 3

后面呢？找到问题了吗

**Comment by agronholm** [comment]
We don't speak Chinese here. Please speak English.
