### ISSUE TITLE
Jobstore TypeError: can't pickle thread.lock objects

### ISSUE THREAD

**Issue by srPuebla** [agronholm/apscheduler#386]
Hi,

Version Python 2.7.15
SQLAlchemy (1.3.3)
APScheduler (3.6.1)

I have an issue with APScheduler. Using jobstore and trying to pass the "scheduler" to the function thread, you obtain the error:

  File "C:\Python27\lib\site-packages\apscheduler\jobstores\sqlalchemy.py", line 95, in add_job
    'job_state': pickle.dumps(job.__getstate__(), self.pickle_protocol)
TypeError: can't pickle thread.lock objects

I have the next script:

```

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
import random
import time

def tasks_implementer(job_scheduler, ticket_id):
    print("Thread Start "+str(ticket_id))
    print(str(job_scheduler.state))
    time.sleep(3)
    print("Thread End "+str(ticket_id))


DB_HOSTNAME  = "127.0.0.1"     # TODO ENCODE
DB_PORT      = 3306            # TODO ENCODE
TUFIN_DB     = "PontAxiansDB"  # TODO ENCODE
DB_USER      = "root"          # TODO ENCODE
DB_PWD       = ""              # TODO ENCODE

TABLE_JOBSTORE = "jobrestore_threads"
#URL_JOBSTORE = 'mysql://%s:%s@%s/%s' % (DB_USER, DB_PWD, DB_HOSTNAME, TUFIN_DB)
URL_JOBSTORE = 'mysql+mysqlconnector://%s:%s@%s/%s' % (DB_USER, DB_PWD, DB_HOSTNAME, TUFIN_DB)


job_store = SQLAlchemyJobStore(url = URL_JOBSTORE, tablename = TABLE_JOBSTORE)
job_scheduler = BackgroundScheduler()
job_scheduler.add_jobstore(job_store)
job_scheduler.start()
print(str(job_scheduler.state))

try:
    while True:
        ticket_id = random.randint(1,101)
        job_scheduler.add_job(
                tasks_implementer,
                'interval',
                seconds= 5,
                kwargs={
                    'job_scheduler': job_scheduler,
                    'ticket_id': str(ticket_id),
                },
                id=str(ticket_id))
        time.sleep(100)
        time.sleep(2)
except (KeyboardInterrupt, SystemExit):
    job_scheduler.shutdown()


```

As you can see, i am trying to pass object "job_scheduler" to "task_implementer" method, cause i want to add more jobs inside the job. It is working if i remove "job_scheduler" from the variables or if i remove the jobstore.

Could you help me?

Thanks!

**Comment by agronholm** [comment]
I am not sure what you hope to accomplish by passing a (defunct) copy of the scheduler object to the scheduled function, but that is not going to work. The scheduler cannot and should not be serialized. I suggest that you make it available as a global instead.

**Comment by srPuebla** [comment]
Thank you for answer. This monday i will test like global variable.

**Comment by Voyz** [comment]
@srPuebla see [my answer](https://github.com/agronholm/apscheduler/issues/421#issuecomment-796657310) in #421 for more info on this issue.
