### ISSUE TITLE
schedule async function

### ISSUE THREAD

**Issue by zkdfbb** [agronholm/apscheduler#387]
when I add an async function, It works well, but if I use cython build, it doesn't work.

here is test.py

```
from apscheduler.schedulers.asyncio import AsyncIOScheduler
import asyncio


class Pipe:

    def __init__(self):
        self.sched = AsyncIOScheduler()
        self.loop = asyncio.get_event_loop()

    async def run(self):
        print(f'start run sched: {self.loop.time()}')

    def main(self):
        self.sched.add_job(self.run, 'interval', seconds=1)
        self.sched.start()
        self.loop.run_forever()


def main():
    pipe = Pipe()
    pipe.main()


if __name__ == '__main__':
    main()
```

and setup.py

```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

extensions = []
extensions.append(Extension('test', ['test.py']))
setup(ext_modules=cythonize(extensions, compiler_directives={'language_level': 3}))
```

build:  

```
python setup.py build_ext --inplace
```

run: 

```
python -c 'from test import main; main()'
```

it shows:

```
/root/.miniconda3/lib/python3.7/asyncio/base_events.py:1765: RuntimeWarning: coroutine 'Pipe.run' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.
```

**Comment by agronholm** [comment]
Could you dig deeper into this? Is the async executor not seeing your target function as an async function after cythonizing?

**Comment by zkdfbb** [comment]
@agronholm Yes, it seems to be a normal function, and running run_job in base.py

**Comment by zkdfbb** [comment]
@agronholm can it be solved ?

**Comment by agronholm** [comment]
Is there a way to tell cythonized async functions apart from regular functions? If so, then maybe I can add some detection logic. Otherwise I don't think it's possible.

**Comment by agronholm** [comment]
Well of course you could always use a custom version of AsyncExecutor that unconditionally runs everything on the event loop thread.

**Comment by zkdfbb** [comment]
@agronholm can you give me a sample ? thanks

**Comment by agronholm** [comment]
I'm not going to code the solution for you but I can give you a couple pointers. First you need to modify the AsyncExecutor code so that it always calls `run_coroutine_job()` instead of checking if the callable is a coroutine function. Then, if you need to run regular functions on the event loop thread as well, you need to modify `run_coroutine_job()` so that it checks if the return value was a coroutine (using `inspect.iscoroutine()`) and if it is, await on that coroutine object.

**Comment by zkdfbb** [comment]
@agronholm thanks, I will check if it works
