### ISSUE TITLE
Job with triggers or[cron, cron] scheduled for the past is never run or removed

### ISSUE THREAD

**Issue by sersorrel** [agronholm/apscheduler#389]
## Expected Behavior

If a job is scheduled and it can only be run in the past (specifically, far enough in the past that it will not be run – longer ago than `misfire_grace_time`), it should be removed from the jobstore.

## Current Behavior

Jobs which are scheduled to occur far in the past with a trigger like `or[cron, cron]` don't have a `next_run_time` in the database, but also aren't removed:

```
# select id,next_run_time from apscheduler_jobs ;
                   id                   | next_run_time
----------------------------------------+---------------
 reminders_for_2019_1_supervisor_submit |
 reminders_for_2019_1_student_invite    |
 2019_1_student_complete                |    1576886340
```

## Steps to Reproduce

I don't have time right now to minimise this, sorry. I'm encountering it with [this application](https://github.com/wsi-cogs/deploy) – if you can work out how to get it running, then schedule a rotation with some dates far in the past (e.g. a year ago), and look at the `reminders_for_*` jobs in the database ([here](https://github.com/wsi-cogs/backend/blob/c635c1086feb36494b55235a6d7541b9fa0c0b39/cogs/scheduler/scheduler.py#L157-L183) is the code which schedules those jobs).

I will hopefully have time to look at making a smaller testcase over the weekend.

## Context (Environment)

This should never pose a real problem for us (since scheduling events more than `misfire_grace_time` in the past is a very rare occurrence in our application), but it's a little unnerving to have jobs sitting around in the database that will never be executed, and I don't really want to complicate the already-complex scheduling logic with tests to make sure that the triggers are all in the future before scheduling a job.

**Comment by agronholm** [comment]
The redesigned scheduling logic in v4.0.0a1 should eliminate this problem. Let me know if it doesn't.
