### ISSUE TITLE
remove job not stop func thread / process

### ISSUE THREAD

**Issue by sherry0429** [agronholm/apscheduler#390]
## Expected Behavior
I use Background Apscheduler to schedule my jobs,  my job function will boot some threads or processes (use openstack.taskflow)
when i call job.remove(), it want to job stopped.

## Current Behavior
I use Background Apscheduler to schedule my jobs,  my job function will boot some threads or processes.
when i call job.remove(), it not stopped. still running ( i can see log from it )

## Steps to Reproduce
1. make a simple taskflow example and "run" method
2.apscheduler add job -> "run" method
3.get job instance and call job.remove()
4.job not stopped.

I want to know how to stop job (not just remove it from schedule) ? is there i need some extra code to stop my job without apscheduler ?

thanks.

**Comment by agronholm** [comment]
Can you point out the standard library function or method to stop a running thread?

**Comment by sherry0429** [comment]
```python
instance = self.scheduler.get_job(job.code)
instance.remove()
```

**Comment by agronholm** [comment]
No, that is not what I'm asking. This code removes a job but does not stop any currently running executions of it.

**Comment by sherry0429** [comment]
yes，that is what i want to know, I find this code only remove job from scheduler but not stop current running job thread / process. so i want to know what function in apscheduler should use ?

I guess job's interrupted code not manage by apscheduler, right ? maybe when i use job.remove(), i also need use some code like myjob.stop() to stop my job ? is there any way to get job's thread or process handle ? 

thanks. my project now only use job.remove to stop job and i find it not stop it so i open this issue.

**Comment by agronholm** [comment]
If you got the thread handle (`threading.Thread`) object, what would you do with it?

**Comment by sherry0429** [comment]
```python
thread.terminate()
```
or
```python
thread.set_stop_flag()
# this method will set stop flag variable in thread class from false to true.
```

**Comment by agronholm** [comment]
Where do you see such things? I don't see them: https://docs.python.org/3.5/library/threading.html

**Comment by sherry0429** [comment]
sorry, i forget it is a thread, 
```python
process.terminate()
```

if it is a thread,
i will use like this :

```python
class mythread(Thread):
    ...
    def set_stop_flag(flag):
        self.stop = flag
    def run():
        while True:
            if self.stop:
                break
   ...

# and call mythread.set_stop_flag(False) to stop it
```

**Comment by agronholm** [comment]
APScheduler 3.x will not have any way to stop running jobs, but I will consider something for 4.0.

**Comment by sherry0429** [comment]
OK, thanks!
