### ISSUE TITLE
Return value of the scheduled function

### ISSUE THREAD

**Issue by salmanshahid8** [agronholm/apscheduler#392]
Hi all,
Since a few days I am looking for a solution to get the returned values of the function that executes at a scheduled time. Here is a sample function.

```
def get_data(dir):
    df = pd.DataFrame()
    file_name = "nofile"
    # The rest of the body of the code executes and updates the two variables df and file_name
    return df, file_name
```

What I want to do is to schedule this function at 6:00 AM. If the _file_name_ remains "nofile" after the execution of "get_data()" at 6:00 AM, the function should be re-executed at 6:00 PM. So like this

```
 def sched():
    # Schedule at 6 AM
    # Here I cannot get the file_name as return value of get_data()
    if file_name == "nofile":
        # Schedule at 6 PM
        file_name = "nofile"
```

I have no idea how to do it with apscheduler. Please help.

**Comment by agronholm** [comment]
Perhaps you should consider reading the [documentation](https://apscheduler.readthedocs.io/en/latest/modules/events.html#apscheduler.events.JobExecutionEvent)? Or the issue template, which says this issue tracker is only for reporting bugs? The [documentation](https://apscheduler.readthedocs.io/en/latest/userguide.html#getting-help) also contains a section for getting help with APScheduler problems.

**Comment by salmanshahid8** [comment]
Yup,
I read the documentation and especially this **my_listener()** part. I also already read the other link you shared.
In addition I also looked at a stackoverflow for a similar problem. However the solution lies there is not according to my requirement. 
Could you please elaborate how I can get a return value using  *my_listener()**?



> 
> 
> Perhaps you should consider reading the [documentation](https://apscheduler.readthedocs.io/en/latest/modules/events.html#apscheduler.events.JobExecutionEvent)? Or the issue template, which says this issue tracker is only for reporting bugs? The [documentation](https://apscheduler.readthedocs.io/en/latest/userguide.html#getting-help) also contains a section for getting help with APScheduler problems.

**Comment by agronholm** [comment]
What is `my_listener()`? Look, as I already said, this issue tracker is NOT the right venue for anything other than reporting bugs. If you ask on StackOverflow and provide the proper background information, I will help you. But not here on Github.

**Comment by salmanshahid8** [comment]
My apologies for using the wrong plateform.
I posted the question on[ stackoverflow](https://stackoverflow.com/questions/58013776/return-values-of-scheduled-function). Please guide there.
