### ISSUE TITLE
why use del thread here ? thanks.

### ISSUE THREAD

**Issue by sherry0429** [agronholm/apscheduler#396]
first, sorry, I try to send email but i not find any email address here, so I push this here,

recently I read the code about apscheduler and I find this code in background.py

```python
    def shutdown(self, *args, **kwargs):
        super(BackgroundScheduler, self).shutdown(*args, **kwargs)
        self._thread.join()
        del self._thread
```

could you tell me why when _thread join and then call del ? 
I guess this is for resources recycle but i am not sure,

I try this:
```python
import threading
import time

def test():
    while True:
        print("hello")
        time.sleep(1)
    print("stopping ....")

th = threading.Thread(target=test)
th.daemon = False
th.start()
time.sleep(5)
print("try stop")
th.join()
del th
print("done")
```

and i find it never print "done", could you help me understand this ? thanks !

**Comment by agronholm** [comment]
> first, sorry, I try to send email but i not find any email address here

The issue templates lists **three** venues for getting assistance, and says that this issue tracker is ONLY for *bug reports*. Did you not read it?
