### ISSUE TITLE
No trigger by the name "calendarinterval" was found

### ISSUE THREAD

**Issue by cheizer** [agronholm/apscheduler#402]
pip install apscheduler installs APScheduler-3.6.2-py2.py3-none-any.whl which should contain the calendarinterval trigger. It appears that the calendarinterval.py file is not included in the pip install. 

Steps to reproduce:
1) python3 -m venv env
2) source env/bin/activate
3) pip3 install apscheduler
4) create test.py with example code from docs and try and run

There for the example code in the docs does not work, it just complains that the trigger was not found.

**Comment by agronholm** [comment]
The calendar interval trigger is part of the APScheduler 4.0 codebase. You must be reading the documentation of the development version, yes?

**Comment by agronholm** [comment]
I've updated the RTD settings, pointing users to the "stable" version by default.

**Comment by cheizer** [comment]
No, I 'm not looking at the beta docs. I'm looking at the "latest" version of the docs.

**Comment by agronholm** [comment]
Yes, "latest" is the latest build and "stable" corresponds to the latest release. You'll want to look at "stable".
