### ISSUE TITLE
Latest release breaks on dependent library

### ISSUE THREAD

**Issue by cdong8812** [agronholm/apscheduler#403]
The latest release seems to be breaking on a dependency library, I'm running an application on AWS and I'm getting the following error from Elastic event log and thus the docker container can't be launched:

Docker container quit unexpectedly after launch: datetime_to_utc_timestamp File "/usr/local/lib/python2.7/site-packages/apscheduler/util.py", line 27, in <module> from trollius import iscoroutinefunction ImportError: No module named trollius. Check snapshot logs for details.

I'm using Python 2.7 in my Dockerfile and It looks like it's missing the "trollius" dependent library from installation.

**Comment by agronholm** [comment]
I've put out v3.6.3 which fixes this.
