### ISSUE TITLE
Version history not up to date

### ISSUE THREAD

**Issue by adamchainz** [agronholm/apscheduler#404]
The current released version is 3.6.3 but the current version history document only goes up to 3.6.1: https://apscheduler.readthedocs.io/en/latest/versionhistory.html

What are the recent user-facing changes?

**Comment by agronholm** [comment]
The [version history](https://github.com/agronholm/apscheduler/blob/3.x/docs/versionhistory.rst) **is** up to date, but seems like the RTD configuration was not all there. I've triggered a new build and hopefully the latest changelog finds its way to the default version of the docs.

**Comment by adamchainz** [comment]
Thanks!
