### ISSUE TITLE
AsyncIOScheduler and Flask App not worked together

### ISSUE THREAD

**Issue by abinhho** [agronholm/apscheduler#405]
I am using flask to build some APIs inside a docker container. Beside that, I has some CRON to run and fetch data from other APIs and store to DB.

But, when I using `AsyncIOScheduler` and `asyncio`, Flask app could not start. Only CRON run.
Here is my code.
```
def __init__(self):
        self.sched = AsyncIOScheduler(daemon = True)
        pass

def run(self):
        self.sched.add_job(self.do_something, "interval", seconds = 5, id = __name__)

        self.sched.start()
        loop = asyncio.get_event_loop()
        try:
            loop.run_forever()
        except (KeyboardInterrupt, SystemExit):
            loop.stop()
            self.sched.shutdown()
            pass
```

Any help !

**Comment by kaos** [comment]
Quart is a flask compatible framework that supports asyncio.

**Comment by agronholm** [comment]
Why are you running asyncioscheduler with a synchronous web framework anyway? And why are you not following the provided issue template? It's there for a reason. Anything else should go to either StackOverflow, Gitter or the Google group.
