### ISSUE TITLE
remove_job and pause_job not working

### ISSUE THREAD

**Issue by xinqinglxl** [agronholm/apscheduler#409]
Hi there, I am new to apscheduler and trying to use it in my flask app(with gunicorn as web server).

I created a module named task_manager.py and used it to mange my apscheduler job.
In task_manager.py I want to do like add, remove, pause to apscheduler job.
task_manager.py:

```
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.executors.pool import ThreadPoolExecutor

executors = {
    'default': ThreadPoolExecutor(cfg.thread_pool_size)
}
job_defaults = {
    'coalesce': True,
    'max_instances': 10,
    'misfire_grace_time':600
}

class TaskManager:
    def start_scheduler(self):
        self.scheduler.start()

    def add_scheduler_job(self, job_id, ...):
        job_obj = self.scheduler.add_job(job_func, 'interval', ...)

    def remove_job(self, job_id):
        self.scheduler.remove_job(job_id)

    def pause_job(self, job_id):
        self.scheduler.pause_job(job_id)
```

While starting the gunicorn I add job to apscheduler in gunicorn's on_starting() and it works fine.
Then I tried to stop/pause the job added above. So I created a restful api name remove_job(job_id),
i the restful api I invoked TaskManager's remove_job/pause_job functions, but nether them working.

In apscheuder's it said the job already removed, but it still running.
server_remove_job.log:
2019-12-02 08:32:48,963 base.py[line:627] INFO Removed job myfunc1
...
2019-12-02 08:41:06,497 base.py[line:123] INFO Running job myfunc1
...
2019-12-02 08:51:06,491 base.py[line:123] INFO Running job myfunc1

server_pause_job.log:
myfunc1 (trigger: interval[0:02:00], paused)
...
2019-12-03 **02:33:45**,980 base.py[line:123] INFO Running job myfun1 next run at: 2019-12-03 **02:33:45** UTC)
...
2019-12-03 **02:35:46**,147 base.py[line:123] INFO Running job "myfun1, next run at: 2019-12-03 **02:35:45** UTC)"

thx for all suggest.

**Comment by agronholm** [comment]
Please provide a way for me to reproduce the problem. That snippet won't run on its own, and I have not used gunicorn. Can you perhaps strip this down and reproduce using only apscheduler?

**Comment by xinqinglxl** [comment]
use flask-apscheduler as work around, close.
