### ISSUE TITLE
The task will cache?

### ISSUE THREAD

**Issue by 0x587** [agronholm/apscheduler#420]
## Expected Behavior
Changes as database data changes

## Current Behavior
If only one thread is opened, the data will never change.
When I open 20 threads, the data of the thread after the database data changes is updated.

## Steps to Reproduce
1. I use the Flask-apscheduler.
2. Use SQLAlchemy to get database data. 
3. Create a task that runs every second to get database data.
4. Chang the data in database.

## Context (Environment)
Win10 1903 python3.7 apscheduler3.6.3

### task code
``` py
def check_node_health():
    for node in Node.query.all():
        if node.records:
            last_time = datetime.datetime.min
            print(node.records)
            for record in Record.query.filter_by(chip_id=node.chip_id).all():
                last_time = max(last_time, record.create_datetime)
            print(last_time)
            print((datetime.datetime.now() - last_time).seconds)
```
### config code
``` py
SCHEDULER_API_ENABLED = True
JOBS = [
    {
        'id': 'node_health_checker',
        'func': check_node_health,
        'args': '',
        'trigger': 'interval',
        'seconds': 1
    }
]
SCHEDULER_EXECUTORS = {
    'default': ThreadPoolExecutor(20),
}
```
![批注 2020-02-04 233511](https://user-images.githubusercontent.com/40025941/73759515-078ccd00-47a7-11ea-821c-02a60e65d648.png)
### As the picture shows:
The last line of data is what I added at runtime
Duplicate tasks run by the thread, showing updated data,but some are not.
So I suspect that the thread executing the task will cache the data.

**Comment by agronholm** [comment]
The steps to reproduce are quite vague. Please provide a complete minimal example, without using flask-apscheduler (this is a third party project, not supported here).

**Comment by 0x587** [comment]
I will try it tomorrow morning,think.

**Comment by 0x587** [comment]
## This is reproduce code
``` py
from flask import Flask
from apscheduler.schedulers.blocking import BlockingScheduler
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


class Config:
    SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:0408@192.168.0.202:3306/TEMP'
    SQLALCHEMY_TRACK_MODIFICATIONS = False


app = Flask(__name__)
app.config.from_object(Config)
sch = BlockingScheduler()
db = SQLAlchemy(app)
migrate = Migrate(app, db)


class DataModel(db.Model):
    __tablename__ = 'data'
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    create_datetime = db.Column(db.DateTime)


def job():
    print(DataModel.query.all())


sch.add_job(job, 'interval', seconds=1)
sch.start()
```
## This is my run result
![批注 2020-02-05 142718](https://user-images.githubusercontent.com/40025941/73816467-ad7e1d00-4823-11ea-8b32-ae6eb7dd959e.png)

### Last record I add in runtime.

**Comment by agronholm** [comment]
I don't have your database so I can't run this. Can we just focus on the scheduler? Are you saying that the task runs too often, or what?

**Comment by 0x587** [comment]
No.
Each task will query the database once, but some tasks cannot query the updated data.
Look at my picture,Some tasks can query the updated data for a total of two,but some tasks can only query the previous single piece of data.

So I wonder if the task will cache the data without running a new query.

**Comment by agronholm** [comment]
Your problem does not seem to have anything to do with scheduling. APScheduler does not set up or operate the database connection you're using, so why have you reported this as an APScheduler problem?
For the record, I think your problem stems from transaction isolation. You might not be closing transactions properly.

**Comment by 0x587** [comment]
Thanks for your guidance, I found the problem.**Thanks!!!!!!!!!!**
