### ISSUE TITLE
Using sqlalchemy datastore with another sqalchem instance "TypeError: can't pickle _thread._local objects"

### ISSUE THREAD

**Issue by aidiss** [agronholm/apscheduler#421]
Application is throwing `TypeError: can't pickle _thread._local objects` when I am using another sqlalchemy instance

## Expected Behavior
apscheduler should work.

## Current Behavior
I have application that instantiates a class that has methods that use sqlalchemy

## Steps to Reproduce
1. Use whatever scheduler with sqlalchemy backed
2. Create another modules with a class that has method that uses sqlalchemy
3. Start scheduler and call a method that uses sqlalchemy

## Dump

```
TypeError: can't pickle _thread._local objects
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
Traceback (most recent call last):
  File "scheduler.py", line 65, in <module>
    sched.start()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\apscheduler\schedulers\background.py", line 33, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\apscheduler\schedulers\base.py", line 162, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\apscheduler\schedulers\base.py", line 867, in _real_add_job
    store.add_job(job)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\apscheduler\jobstores\sqlalchemy.py", line 95, in add_job
    'job_state': pickle.dumps(job.__getstate__(), self.pickle_protocol)
TypeError: can't pickle _thread._local objects
```

If you need more info just let me know

**Comment by agronholm** [comment]
It sounds like you're trying to pass an unserializable argument to the job. Please provide a complete example that reproduces the problem.

**Comment by ziyueWu** [comment]
I've got a similar problem.
Mac OS version: 10.15.3
python version: 3.7

There are two files: 
etl.py is a tornado application
test_service.py tries to add a job and starts the tornado scheduler

Steps:
1. run etl.py 
2. run test_service.py

Then the log:
```
[I 200302 12:00:11 etl:284] Server Inititial ... 
[I 200302 12:00:11 etl:293] Server Inititial Success! 
[I 200302 12:00:16 etl:69] add job by get
[I 200302 12:00:16 base:440] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[I 200302 12:00:16 etl:82] 
    add job by get success!
[I 200302 12:00:16 web:2246] 200 GET /job/add?jobId=1&jobName=dayTask&cron=0%2F1+%2A+%2A+%2A+%2A (127.0.0.1) 1.48ms
[E 200302 12:00:16 web:1788] Uncaught exception GET /scheduler/start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:31001', method='GET', uri='/scheduler/start', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Library/Python/3.7/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/wuziyue/Desktop/projects/AI-projects/etl-template/etl.py", line 196, in get
        sched.start()
      File "/Library/Python/3.7/site-packages/apscheduler/schedulers/base.py", line 162, in start
        self._real_add_job(job, jobstore_alias, replace_existing)
      File "/Library/Python/3.7/site-packages/apscheduler/schedulers/base.py", line 867, in _real_add_job
        store.add_job(job)
      File "/Library/Python/3.7/site-packages/apscheduler/jobstores/redis.py", line 82, in add_job
        self.pickle_protocol))
    AttributeError: Can't pickle local object 'WeakSet.__init__.<locals>._remove'
[E 200302 12:00:16 web:2246] 500 GET /scheduler/start (127.0.0.1) 4.53ms
```

Whether the jobstore in add_job is set 'mysql' or 'redis', the same log shows.
Here is the example:

in etl.py:

```
sql_alchemy_job_store = SQLAlchemyJobStore(url='mysql+pymysql://user:password@host:3306/apscheduler?charset=utf8',tablename='apscheduler_jobs')
job_stores = {'mysql': sql_alchemy_job_store,
              'redis': RedisJobStore(db=1, jobs_key='apscheduler.jobs', run_times_key='apscheduler.run_times')}
sched = TornadoScheduler(jobstores=job_stores)

class AddJobHandler(tornado.web.RequestHandler):
    '''
        input：{'jobId':'1','jobName'='dayTask','cron'='0 5 * * *'}
        '''
    def get(self):
        logging.info("add job by get")
        try:
            job_id = self.get_query_argument('jobId')
            job_name = self.get_query_argument('jobName')
            cron_string = self.get_query_argument('cron')
            sched.add_job(self.run,
                          trigger=CronTrigger.from_crontab(cron_string),
                          jobstore='redis',
                          id=job_id,
                          name=job_name,
                          max_instances=3)

            logging.info("\nadd job by get success!")
            self.write("add job id: " + job_id + " job name: " + job_name)
        except Exception as e:
            logging.exception(e)

    def run(self):
        service.xxx_service.sth_to_run()

class StartHandler(tornado.web.RequestHandler):
    def get(self):
        sched.start()
        result = sched.running
        self.write("start scheduler: %s" % result)

(and other tornado application codes...)
```


in test_service.py:

```
job_url = 'http://localhost:31001/job/'
scheduler_url = 'http://localhost:31001/scheduler/'

def requests_get(url, params):
    response = requests.get(url, params=params)
    # response.encoding = "utf-8"
    print(response.status_code)
    print(response.text)
    return response.text

def add_job_1():
    url = job_url + 'add'
    param = {"jobId": "1",
             "jobName": "task1",
             "cron": '0/1 * * * *'}  # 每分钟跑一次
    result = requests_get(url, param)

def start():
    url = scheduler_url + 'start'
    param = {}
    result = requests_get(url, param)
    print("start")

if __name__ == "__main__":
    add_job_1()
    start()
```

**Comment by agronholm** [comment]
You must realize that when you schedule an instance method as a job, it will have to serialize the instance with all its attributes. Those attributes are by no means guaranteed to be serializable.

**Comment by ersaijun** [comment]
> You must realize that when you schedule an instance method as a job, it will have to serialize the instance with all its attributes. Those attributes are by no means guaranteed to be serializable.

serialize the instance with all its attributes？what the meaning of serialize the instance

**Comment by agronholm** [comment]
Serializing means converting an in-memory object to a bytestream that can be saved to persistent storage and later restored from there. An instance method is a function bound to an instance of a class. When you schedule a job that targets an instance method, that instance must be serialized along with the reference to the method definition in order for the restoration to be possible.

**Comment by ersaijun** [comment]
Thanks. I understand now.

so,I canot use jobstores when I add a job of an instance. 
The code like this:
`m_scheduler = BackgroundScheduler(jobstores=jobstores)
m_scheduler.add_job(api_audio.stop_program, id='job_date_once',
		                    trigger='date',
		                    run_date='2020-08-06 20:06:05', replace_existing=True, )

api_audio = API_audio()  # an instance of class
m_scheduler.start()
`
it will cause error : TypeError: can't pickle _thread.lock objects

Is there any method to solve the problem?

**Comment by agronholm** [comment]
> so,I canot use jobstores when I add a job of an instance.

Yes, but you cannot have the scheduler as an attribute of the instance.

**Comment by agronholm** [comment]
Your `API_audio` class does not appear to contain the scheduler instance, so maybe you're having this problem for other reasons?

**Comment by skjoher** [comment]
> Is there any method to solve the problem?

facing the same issue. any fix....

**Comment by agronholm** [comment]
> facing the same issue. any fix....

Depends on what the problem is. If you're trying to add function arguments that aren't serializable, then that is not a fixable problem – you need to change your architecture.

**Comment by Voyz** [comment]
@skjoher @ersaijun 

If you run into this issue and don't know how to `change your architecture.` then read the following:

* There's something in your code that can't be pickled - ie. it cannot be "passed" from one process to another. Probably that's a member field of a class.
* You need to figure out what it is - normally the error log will give you some hints, although not always. Look around your class code and try to think what fields are you storing. Could any of these cause issues with pickling? Primitive objects are easy to pickle, you want to look for some complex stuff. Maybe you're storing a complex uWSGI app in your class? Things like that can cause problems.
* The easiest way to solve this is to 'destroy' and 'recreate' these complex fields before and after pickling respectively. Consider the following class:

```python
class MyClass():
    def __init__(self):
        self.ssl_context = ssl.SSLContext()
        
    def run_task(self):
        print('running task')

my_class = MyClass()
scheduler = BlockingScheduler({'default': ProcessPoolExecutor())
scheduler.add_job(my_class.run_task)
```

We create an instance of `MyClass` that contains a field that cannot be pickled - `self.ssl_context`. We then attempt to schedule a the `run_task` method using APS, which like [Alex outlined above ](https://github.com/agronholm/apscheduler/issues/421#issuecomment-669879135) will attempt to pickle all fields of the `my_class` instance.

To solve this, let's avoid pickling `ssl_context` and recreate it manually upon unpickling instead:

```python
class MyClass():
    def __init__(self):
        self.ssl_context = ssl.SSLContext()

    def run_task(self):
        print('running task')

    # will be called on pickling
    def __getstate__(self):
        state = self.__dict__.copy()
        del state['ssl_context'] # remove the unpicklable ssl_context
        return state

    # will be called on unpickling
    def __setstate__(self, state):
        self.__dict__.update(state)
        self.ssl_context = ssl.SSLContext() # recreate the ssl_context 
```

This method then applies to whatever is causing your pickling issues. Look around your code, find out what can't be pickled and use this destroy-and-rebuild method. Bear in mind that this may not work for every case (as some objects cannot be rebuilt like this correctly), but chances are your class can indeed be rewritten. Remember that this rebuilding can use objects that were successfully pickled by accessing the `state`!


Funny enough, the APS schedulers themselves cannot be pickled either. Make sure that none of your pickled classes store any APS schedulers, ie. don't do this:

```python
class MyClass():
    def __init__(self):
       # THIS IS A BAD IDEA!
        self.scheduler = BlockingScheduler({'default': ProcessPoolExecutor())
        self.scheduler.add_job(self.run_task)

    def run_task(self):
        print('running task')
```

Or if you do, make sure to delete the scheduler on pickling, and recreate it (including its jobs!) on unpickling.

You can read more in [this article on Medium.](https://towardsdatascience.com/multiprocessing-and-pickle-how-to-easily-fix-that-6f7e55dee29d)

Good luck! 👋

**Comment by TAUMachado** [comment]
Hello,

I'm having a similar issue after implementing SQLAlchemyJobStore in my code.
Trying to add a job results in the following error: TypeError: cannot pickle 'SSLContext' object.

My code is as following:

In views.py:
```
@app.before_first_request
def schedule_jobs():
 
    scheduler = BackgroundScheduler(
        jobstores={'default': SQLAlchemyJobStore(url='sqlite:///jobs.sqlite')}
    )
    scheduler.start()
    data = Data()
    scheduler.add_job(data.schedule_app,
                      trigger='interval',
                      hours=int(os.getenv('UPDATE_FREQUENCY')))
```

In data.py:
```
class Data:

    def __init__(self):
        self.ssl_context = ssl.SSLContext()

    def __getstate__(self):
        state = self.__dict__.copy()
        del state['ssl_context']
        return state

    def __setstate__(self, state):
        self.__dict__.update(state)
        self.ssl_context = ssl.SSLContext()

    def schedule_app(self):
        print("Task added Successfully")
```
Complete trace:
```
2021-04-03T10:18:48.206620307Z Traceback (most recent call last):
2021-04-03T10:18:48.206623307Z   File "/tmp/8d8f6862c98e628/antenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
2021-04-03T10:18:48.206626507Z     response = self.full_dispatch_request()
2021-04-03T10:18:48.206629507Z   File "/tmp/8d8f6862c98e628/antenv/lib/python3.8/site-packages/flask/app.py", line 1945, in full_dispatch_request
2021-04-03T10:18:48.206632707Z     self.try_trigger_before_first_request_functions()
2021-04-03T10:18:48.206635807Z   File "/tmp/8d8f6862c98e628/antenv/lib/python3.8/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
2021-04-03T10:18:48.206638907Z     func()
2021-04-03T10:18:48.206641807Z   File "/tmp/8d8f6862c98e628/app/views.py", line 39, in schedule_jobs
2021-04-03T10:18:48.206644907Z     scheduler.add_job(data.schedule_app,
2021-04-03T10:18:48.206647807Z   File "/tmp/8d8f6862c98e628/antenv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 448, in add_job
2021-04-03T10:18:48.206650907Z     self._real_add_job(job, jobstore, replace_existing)
2021-04-03T10:18:48.206653807Z   File "/tmp/8d8f6862c98e628/antenv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 872, in _real_add_job
2021-04-03T10:18:48.206656907Z     store.add_job(job)
2021-04-03T10:18:48.206659807Z   File "/tmp/8d8f6862c98e628/antenv/lib/python3.8/site-packages/apscheduler/jobstores/sqlalchemy.py", line 95, in add_job
2021-04-03T10:18:48.206662907Z     'job_state': pickle.dumps(job.__getstate__(), self.pickle_protocol)
2021-04-03T10:18:48.206665907Z TypeError: cannot pickle 'SSLContext' object
```

Is there a way to fix this?
I am using  SQLAlchemyJobStore only in order to avoid having multiple workers in multiple instances executing the scheduled job (I am running this application in Azure with 8 instances and following Gunicorn config: gunicorn -w 8 --preload --worker-class gevent.
Is there any way to achieve that without using SQLAlchemyJobStore? 
Thank you in advance.

**Comment by agronholm** [comment]
@TAUMachado could you make this into a self contained example, preferably leaving our the web framework?

**Comment by TAUMachado** [comment]
Hello @agronholm,
I performed some tests inside and outside the web framework.
In all cases, what fixed the issue was creating a class and instantiating the class Data and putting the function that I wanted to execute there and then calling that in the jobscheduler.
the code looks like this now in views.py:

```
class Job:
    def job(self):

        data = Data()
        data.schedule_app()
        print("Job executed successfully)


@app.before_first_request
def schedule_jobs():
    """Before the first ever request of the app, it will create all the data banks specified in the Models.py script"""
    scheduler = BackgroundScheduler(
        jobstores={'default': SQLAlchemyJobStore(url='sqlite:///jobs.sqlite')}
    )
    scheduler.start()
    job = Job()
    scheduler.add_job(job.job,
                      trigger='interval',
                      minutes=int(os.getenv('UPDATE_FREQUENCY')))
```

I still don't understand why this works.

**Comment by agronholm** [comment]
I can investigate further if you provide me an example that reproduces the problem without the web framework.
By the way, what you're doing with with sqlalchemy job store – have you read [this](https://apscheduler.readthedocs.io/en/stable/faq.html#how-do-i-share-a-single-job-store-among-one-or-more-worker-processes) part of the FAQ?

**Comment by TAUMachado** [comment]
Hello @agronholm.
Sorry for the delayed answer. I could not reproduce the issue again outside Flask context. 
Probably is an issue with the APScheduler and Flask.
I read the documentation and tried to implement the solution with rpyc, but I'm maybe missing something related to setting an AppService to listen to a specific Port.
I noticed that there is an exception for when workers try to execute a job with the same id. 
I tried to implement an exception handler to tell it to start the job and if it gets the Conflit ID exception, so simply do nothing, I still couldn't test it properly, but I noticed that executing BackgroundScheduler().get_jobs() returns me an empty list even if there is a scheduled job. Am I missing something? My code looks like this:

```
class Data_instance:
    def data_init(self):
        data = Data()
        data.schedule_app()


@app.before_first_request
def scheduled_job():
    scheduler = BackgroundScheduler()
    scheduler.start()
    dt = Data_instance()

    scheduler.add_job(dt.data_init,
                      trigger='interval',
                      hours=int(os.getenv('UPDATE_FREQUENCY')))


def return_job():
    return BackgroundScheduler().get_jobs()
```

And the version with the exception handler:

```
class Data_instance:
    def data_init(self):
        data = Data()
        data.schedule_app()


@app.before_first_request
def scheduled_job():
    scheduler = BackgroundScheduler()
    scheduler.start()
    dt = Data_instance()
    try:
        scheduler.add_job(dt.data_init,
                      id='data_update',
                      trigger='interval',
                      hours=int(os.getenv('UPDATE_FREQUENCY')))
    except apscheduler.jobstores.base.ConflictingIdError:
        pass


def return_job():
    return BackgroundScheduler().get_jobs()
```

**Comment by agronholm** [comment]
Why are you expecting a newly created scheduler to return anything from `get_jobs()`? I want to understand that train of thought.

As for RPyC, have you looked at the [examples](https://github.com/agronholm/apscheduler/tree/master/examples/rpc)?

**Comment by TAUMachado** [comment]
@agronholm I thought it would return also the jobs in the queue for the BackgroundScheduler. I probably understood it wrong.
Gonna try the example again tomorrow and post the result here.

**Comment by agronholm** [comment]
> @agronholm I thought it would return also the jobs in the queue for the BackgroundScheduler.

By what logic? If you create two schedulers:
```
scheduler1 = BackgroundScheduler()
scheduler2 = BackgroundScheduler()
```
Do you expect scheduler1 and scheduler2 to be the same scheduler? So there can every only be one scheduler no matter how many of them you try to create?
