### ISSUE TITLE
apscheduler.scheduler:Execution of job skipped: maximum number of running instances reached (1)

### ISSUE THREAD

**Issue by ylmzgrk** [agronholm/apscheduler#423]
I know that there are lot of questions asked in this topic. I read all of them but couldn't get a clear solution for my case.

I have a python code running on ubuntu server that has 2 functions. First function (getKlines) receive data from api every 30 minutes, second function (execute) run an alogithm on the received data.

At first i built the setup like below;

sched = BlockingScheduler()

sched.add_job(getKlines,'cron', minute="*/30", second=0, max_instances=5)

sched.add_job(execute, 'cron', minute="*/30", second=1, max_instances=5)

sched.start()

But after a period of time, i get apscheduler.scheduler:Execution of job skipped: maximum number of running instances reached error. Until i recognize and manually act, my code hangs and doesn't run when the next 30 minutes come.

As offered in similar cases, i increase max instance number in job defaults but still get the error thus change the code structure as below;

trigger=OrTrigger([CronTrigger(hour='', minute='0'),CronTrigger(hour='', minute='30')])

trigger1=OrTrigger([CronTrigger(hour='', minute='1'),CronTrigger(hour='', minute='31')])

def listener(event):

if event.exception:
    print("error")
job_defaults = { 'max_instances': 20,

}

scheduler = BlockingScheduler(job_defaults=job_defaults)

scheduler.add_listener(listener, EVENT_JOB_ERROR)

scheduler.add_listener(listener, EVENT_JOB_MAX_INSTANCES)

scheduler.add_job(getKlines,trigger)

scheduler.add_job(execute, trigger1)

scheduler.start()

but unfortunately although the frequency is decreased still i'm getting the error. I add also event listener but it also doesn't work sometimes to let me know the job is hanged.

Really appreciate your help.

**Comment by agronholm** [comment]
As already explained in the issue template, I will need a standalone example that reproduces the problem. Your code above is not since it gives me no clue why the scheduled functions are taking so long. Have you approached the problem from that perspective?

On another note, this tracker is only for reporting bugs (again, as explained in the issue template). Do you consider this a scheduler bug?

**Comment by ylmzgrk** [comment]
Hi,
Thanks a lot for your quick response.

I'm new to Github. Sorry if it is not the right place to raise this issue. I also asked it from stackoverflow.com (no: 60723306)
I couldn't understand the root cause. Since it works perfectly fine for a period of time (more than weeks) i don't think it is because of my code but i'm not sure.
Really appreciate if you can help me with that. 

For my second case, i try to catch max-instance errors via event listeners. I think i built it as specified in the API document. Event listener is also working properly for a certain period of time bu than i get error "apscheduler listener no module named event". Do you have a guess about causing that?

Sorry again if i'm not asking these questions conveniently and really appreciate your help.

**Comment by agronholm** [comment]
I will try to answer your question there, but I will still need a reproducing example.

**Comment by ylmzgrk** [comment]
Alex i edit the code on stackoverflow. Appreciate if you can look at it.

**Comment by liqing1990** [comment]
I also have this problem. Is there a solution? As long as the maximum is reached and it goes online, my program will not trigger a timer task. The value displays a warning message.

**Comment by agronholm** [comment]
@liqing1990 yes, fix your code so that the previous runs actually finish before new ones are started.

**Comment by kmcmearty** [comment]
@agronholm, in your response to @liqing1990 above, you mentioned there is a solution to error: `Execution of job skipped: maximum number of running instances reached (1)`?

you mentioned, 'fix your code so that the previous runs actually finish before new ones are started.'
My problem is that one job takes a while to execute and another job that is scheduled comes in and makes the max number error.

Is there a way to stop the scheduled job from executing before the current job is done running?

**Comment by agronholm** [comment]
> Is there a way to stop the scheduled job from executing before the current job is done running?

Not from APScheduler's side. Threads generally cannot be forcibly stopped. You can build a mechanism into your code that makes it voluntarily stop (a global flag or something). Using that together with locks could solve your problem.

**Comment by lucasjinreal** [comment]
I got same error, my function runed more than 1min, I forcely set loop for 1min, but set  coalesce=True,

it should waiting for the function run done then start another,. but actually it stuck forever:

 (trigger: interval[0:01:00], next run at: 2024-09-22 11:37:15 CST)" skipped: maximum number of running instances reached (1)

anyone knows why>

this is not expected at all

**Comment by agronholm** [comment]
> I got same error, my function runed more than 1min, I forcely set loop for 1min, but set coalesce=True,
> 
> it should waiting for the function run done then start another,. but actually it stuck forever:
> 
> (trigger: interval[0:01:00], next run at: 2024-09-22 11:37:15 CST)" skipped: maximum number of running instances reached (1)
> 
> anyone knows why>
> 
> this is not expected at all

And which version were you running?
