### ISSUE TITLE
Problem with job trigger on date

### ISSUE THREAD

**Issue by mizamae** [agronholm/apscheduler#425]
Hello,

I am scheduling a background scheduler with a job setup with a trigger='date'. When it executes, it is supposed to be automatically deleted from the jobstore (SQLAlchemy in my case) but it raises an exception:
I set the scheduler as:
```
scheduler=BackgroundScheduler()
scheduler..add_jobstore('sqlalchemy', url=jobstoreUrl)
```
I add the job as:
```
scheduler.add_job(func=callback,trigger='date',id=id,args=(),kwargs={'cls':self.__class__,'pk':self.pk},
                              run_date=start_date+datetime.timedelta(seconds=self.CONNECTION_TIMEOUT))
```
and when it enters the calling function, it raises the following traceback:
 

>  File "D:\Python\Python3.5.3\lib\threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "D:\Python\Python3.5.3\lib\threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\Python\Python3.5.3\lib\site-packages\apscheduler\schedulers\blocking.py", line 30, in _main_loop
>     wait_seconds = self._process_jobs()
>   File "D:\Python\Python3.5.3\lib\site-packages\apscheduler\schedulers\base.py", line 997, in _process_jobs
>     self.remove_job(job.id, jobstore_alias)
> TypeError: remove_job() takes 2 positional arguments but 3 were given

I am using Python 3.5.3 and APScheduler 3.6.3...

is this a known bug?? or am I doing anything wrong??

Thans a lot!!

**Comment by agronholm** [comment]
That TypeError just can't happen with an unmodified scheduler. See [this line](https://github.com/agronholm/apscheduler/blob/master/apscheduler/schedulers/base.py#L583) for proof. Please provide a simple standalone example that reproduces the bug.

**Comment by mizamae** [comment]
Hi @agronholm , thanls a lot for your quick feedback, it is very much appreciated

I am using the standard library. I have tried the same trigger='date' inside a simple script and it works perfectly. The thing is that my use is within Django where different threads start playing and in this context, it fails; but I cannot find why... something similar happened to me when I set the callback as a method of an instance, where the 'self' arg is passed implicitly and so the scheduler receives one parameter more than those expected...

**Comment by agronholm** [comment]
I'm going to say this one final time: if you want help, please provide a script that reproduces the problem and which I can run too. Otherwise I cannot help you since this is not a common problem.

**Comment by mizamae** [comment]
I am sorry but I cannot reproduce it outside Django.
All I can say is that it seems to be fixed using the the django apscheduler wrapper:
https://github.com/jarekwg/django-apscheduler

best regards and sorry to disturb you
