### ISSUE TITLE
OrTrigger does not work with DateTriggers

### ISSUE THREAD

**Issue by DmitriiKolesnichenko** [agronholm/apscheduler#427]
I create trigger `OrTrigger(DateTrigger(date1), DateTrigger(date2))`.
`date1` < `date2`.

## Expected Behavior
Trigger fire twice: in `date1` and `date2`.

## Current Behavior
Trigger fires once: in `date1`.

## Detailed Description
It occurs because `DateTrigger.get_next_fire_time()` returns `None` if `previous_fire_time` is not `None`. If we use `OrTrigger`, we pass `previous_fire_time` to all included triggers. And all of them returns `None` after the first fire of `OrTrigge`. So it will never work multiple times.

**Comment by Laurel-rao** [comment]
put your OrTrigger code below please.

**Comment by agronholm** [comment]
> put your OrTrigger code below please.

Not necessary; the analysis sounds correct. This indeed seems like a bug to me.

**Comment by agronholm** [comment]
I am currently working on the refactoring of the trigger system in APScheduler 4.0. The stateful nature of triggers there solves this problem since `OrTrigger` will store the trigger times produced by all the contained triggers.

**Comment by agronholm** [comment]
Come to think of it, this is actually fixable even in v3.x if the logic is changed to only return `None` if the previous fire time is equal to or later than the run date of the trigger.

**Comment by agronholm** [comment]
Solved by the addition of stateful triggers (17a353f073a5e34bf033ad0013577063fcf6741c).
