### ISSUE TITLE
job store "next_run_time" should only be updated when the job is finished

### ISSUE THREAD

**Issue by LeonKarabchevsky** [agronholm/apscheduler#429]
long running jobs that are terminated unexpectedly won't resume or start again execution when the scheduler is restarted when using a persistent job store

## Expected Behavior
The job will start its execution as soon as the scheduler is restarted 

## Current Behavior
The job does no execute again

## Steps to Reproduce
1. Create a long running job 
2. Add the job to a scheduler with a  persistent job store
3. restart the the scheduler process

## Context (Environment)
I have a docker container which executes periodic tasks that  sometimes can crash due to various issue.

## Detailed Description
move the following code at base scheduler:
job._modify(next_run_time=job_next_run)
jobstore.update_job(job)

to a callback function which will be called by 
executor.submit_job(job, run_times)
when it finishes executing the job

**Comment by agronholm** [comment]
Your assumption of how the scheduler works is mistaken. The field in the subject is updated when a job is handed to an executor and a new scheduled time is then calculated. This is how the scheduler was designed to work. If you need your job to retry after a failed attempt, I suggest using a library like Tenacity.

Feel free to comment here if you disagree.

**Comment by LeonKarabchevsky** [comment]
Thank you for your response, 
I did not mean to retry a failed job but to **resume one stopped in the middle of execution** due to reasons such as OOM crash.
Any other solution will require the usage of persistent data storage and mostly duplicate functionality already implemented in the job store.
This looks like a very helpful feature to have.

**Comment by agronholm** [comment]
How would you expect this to work? It's not like the global state of the process is saved somewhere when the process crashes. The only possibility would be to schedule a new run of the job if the scheduler detects that it was left unfinished when the process crashed.
