### ISSUE TITLE
from apscheduler.schedulers.background import BackgroundScheduler BackgroundScheduler()

### ISSUE THREAD

**Issue by Jie-Yuan** [agronholm/apscheduler#433]
UnknownTimeZoneError                      Traceback (most recent call last)
<ipython-input-8-d934dc9a5d49> in <module>
      1 from apscheduler.schedulers.background import BackgroundScheduler
----> 2 BackgroundScheduler()

/usr/local/lib/python3.6/dist-packages/apscheduler/schedulers/base.py in __init__(self, gconfig, **options)
     85         self._pending_jobs = []
     86         self.state = STATE_STOPPED
---> 87         self.configure(gconfig, **options)
     88 
     89     def configure(self, gconfig={}, prefix='apscheduler.', **options):

/usr/local/lib/python3.6/dist-packages/apscheduler/schedulers/base.py in configure(self, gconfig, prefix, **options)
    124         # Override any options with explicit keyword arguments
    125         config.update(options)
--> 126         self._configure(config)
    127 
    128     def start(self, paused=False):

/usr/local/lib/python3.6/dist-packages/apscheduler/schedulers/background.py in _configure(self, config)
     27     def _configure(self, config):
     28         self._daemon = asbool(config.pop('daemon', True))
---> 29         super(BackgroundScheduler, self)._configure(config)
     30 
     31     def start(self, *args, **kwargs):

/usr/local/lib/python3.6/dist-packages/apscheduler/schedulers/base.py in _configure(self, config)
    695         # Set general options
    696         self._logger = maybe_ref(config.pop('logger', None)) or getLogger('apscheduler.scheduler')
--> 697         self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
    698         self.jobstore_retry_interval = float(config.pop('jobstore_retry_interval', 10))
    699 

/usr/local/lib/python3.6/dist-packages/tzlocal/unix.py in get_localzone()
    163     global _cache_tz
    164     if _cache_tz is None:
--> 165         _cache_tz = _get_localzone()
    166 
    167     return _cache_tz

/usr/local/lib/python3.6/dist-packages/tzlocal/unix.py in _get_localzone(_root)
     84                     if not etctz:
     85                         continue
---> 86                     tz = pytz.timezone(etctz.replace(' ', '_'))
     87                     if _root == '/':
     88                         # We are using a file in etc to name the timezone.

/usr/local/lib/python3.6/dist-packages/pytz/__init__.py in timezone(zone)
    179                 fp.close()
    180         else:
--> 181             raise UnknownTimeZoneError(zone)
    182 
    183     return _tzinfo_cache[zone]

UnknownTimeZoneError: 'Africa/'

**Comment by agronholm** [comment]
Why did you paste this traceback here?
