### ISSUE TITLE
Why sqlalchemy jobstores remove job whether it is executed or not?

### ISSUE THREAD

**Issue by DungeonMasterAkshay** [agronholm/apscheduler#435]
My use case  : I dont want to delete record from table.

can we add more column to this table.

If it is possible then add 'isactive' column which is used for checking whether this record is active or not.

If 'isactive' == 0 : then record is active in future it is going to execute.
else this record is executed already.

**Comment by agronholm** [comment]
Please do not ignore the issue template. If you have feature requests, take them to either the Google group or Gitter. You can then explain your use case in depth.
