### ISSUE TITLE
SQLAlchemy JobStore potential incorrect usage of where clause

### ISSUE THREAD

**Issue by thehesiod** [agronholm/apscheduler#438]
here: https://github.com/agronholm/apscheduler/blob/master/apscheduler/jobstores/sqlalchemy.py#L132

if you were to pass multiple conditions (which this library itself doesn't do, however a superclass may do) it would end up passing a tuple to sqlalchemy's where resolver where it only supports one causing an error.

I believe it should loop through the clauses and append each clause to the previously build where statement or `_and` then together

**Comment by thehesiod** [comment]
indeed, if I do this:
```python
    def _get_jobs(self, *conditions):
        #  https://github.com/agronholm/apscheduler/issues/438
        assert len(conditions) == 1
        conditions = (sqlalchemy.and_(conditions[0], self.jobs_t.c.id.like(f'{self._fbn_job_filter_prefix}-%')),)
        jobs = super()._get_jobs(*conditions)
        return jobs
``` 
it works

**Comment by agronholm** [comment]
Yeah, simply wrapping them with `and_()` ought to work.
