### ISSUE TITLE
Got an exception: Timezone offset does not match system offset

### ISSUE THREAD

**Issue by codeyourdream** [agronholm/apscheduler#439]
The BackgroundScheduler doesn't start because of a timezone offset error. 
Here's the code I'm running in my app:
```
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger

scheduler = BackgroundScheduler()
trigger = IntervalTrigger(minutes=5)
job = scheduler.add_job(my_job, trigger)
scheduler.start()
```
This app is packaged into EXE with pyinstaller.

## Expected Behavior
It runs fine on a number of my test computers, but fails on one of my alpha testers machine (it's Windows 10).
The expected behavior is that the scheduler is started and the job is added to the schedule.

## Current Behavior
It crashes with the following trace (partial):
```
2020-06-22 20:04:57,423 ERROR    exception Timezone offset does not match system offset: 7200 != 3600. Please, check your config files.
Traceback (most recent call last):
  File "dc_service.py", line 32, in <module>
  File "site-packages\apscheduler\schedulers\base.py", line 87, in init
  File "site-packages\apscheduler\schedulers\base.py", line 126, in configure
  File "site-packages\apscheduler\schedulers\background.py", line 29, in _configure
  File "site-packages\apscheduler\schedulers\base.py", line 697, in _configure
  File "site-packages\tzlocal\win32.py", line 95, in get_localzone
  File "site-packages\tzlocal\utils.py", line 46, in assert_tz_offset
ValueError: Timezone offset does not match system offset: 7200 != 3600. Please, check your config files.
2020-06-22 20:04:57,446 ERROR    exception Timezone offset does not match system offset: 7200 != 3600. Please, check your config files.
Traceback (most recent call last):
  File "dc_service.py", line 36, in <module>
  File "site-packages\apscheduler\triggers\interval.py", line 44, in init
  File "site-packages\tzlocal\win32.py", line 95, in get_localzone
  File "site-packages\tzlocal\utils.py", line 46, in assert_tz_offset
ValueError: Timezone offset does not match system offset: 7200 != 3600. Please, check your config files.
2020-06-22 20:04:57,446 ERROR    exception name 'scheduler' is not defined
Traceback (most recent call last):
  File "dc_service.py", line 40, in <module>
NameError: name 'scheduler' is not defined
2020-06-22 20:04:57,447 ERROR    exception name 'scheduler' is not defined
```

## Context (Environment)
Python 3.8.3
APScheduler 3.6.3

## Detailed Description
I assume the scheduler shouldn't crash because of the timezone offset issue. In my code I'm not manipulating the timezone, I just need a simple function to run every N minutes.

---

By the way, there was a problem with the app built with the latest pyinstaller - got this error after running the executable: No module named 'pkg_resources.py2_warn'. The only workaround I found was the code above, the code provided in the docs:
```
job = scheduler.add_job(myfunc, 'interval', minutes=2)
```
worked when I ran my code with Python but crashed with an error, and I found that it's because of the 'interval' parameter.
Not sure if I should create a separate issue for this one.

**Comment by agronholm** [comment]
The program crashes in the tzlocal package. It's probably crashing because it detects that the given local timezone does not match the one indicated by the rest of the standard library functions, so something must be wrong.

Do you suggest that I catch this exception and replace it with something better?

**Comment by agronholm** [comment]
The easy workaround here is to explicitly define the local time zone if it can't be detected properly.

**Comment by codeyourdream** [comment]
My experience with this is not good enough to provide suggestions. Maybe a better exception would be nice.
In case of my app - the thing is that it doesn't need to depend on timezone at all. I understand that you have to use tzlocal for more advanced time operations, but maybe for simple "every X minutes" runs the timezone can be ignored? Or maybe you could just throw a warning and set timezone to some default value.

**Comment by agronholm** [comment]
Then again, if you don't have any advanced needs, why not just make a loop with `time.sleep(x * 60)`? No time zone needed there...

**Comment by agronholm** [comment]
Defaulting to some arbitrary time zone would surprise users of other trigger types (cron and calendarinterval are particularly prone to this), so I don't. Anyways, I have never seen tzlocal fail like that so this was completely unexpected. It would be nice to understand how it happened, although I don't maintain the tzlocal library.

**Comment by codeyourdream** [comment]
> Then again, if you don't have any advanced needs, why not just make a loop with time.sleep(x * 60)? No time zone needed there...

Sure, I ended up using something like that. I used apscheduler because I thought it's future proof - I may need more advanced features later.

> It would be nice to understand how it happened, although I don't maintain the tzlocal library.

I checked with the person who got that error - he said there are some issues with the time zone in Windows - sometimes it changes for an unknown reason. This is probably a rare case,

**Comment by agronholm** [comment]
Since there is nothing I can do about this, I'm closing the issue. Open a new issue with repro instructions if you feel that APScheduler needs a specific fix.
