### ISSUE TITLE
Task is not properly added to sceduler

### ISSUE THREAD

**Issue by matej2** [agronholm/apscheduler#443]
## Expected Behavior
Task would be added to sceduler and ran in random amount of seconds (from 1 to 3)

## Current Behavior

clock.py:
```py
import asyncio
import os
from datetime import datetime
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from trigger import RandomIntervalTrigger

def tick():
    print(f'Tick! Current time is {datetime.now()}, Next scedule is: {RandomIntervalTrigger(hours=3, minutes=55, seconds=59, timezone="Europe/Rome").get_next_fire_time(None, datetime.now())}')


if __name__ == '__main__':
    scheduler = AsyncIOScheduler()
    scheduler.add_job(tick, RandomIntervalTrigger(seconds=3))
    scheduler.start()
    print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))

    # Execution will block here until Ctrl+C (Ctrl+Break on Windows) is pressed.
    try:
        asyncio.get_event_loop().run_forever()
    except (KeyboardInterrupt, SystemExit):
        pass
```

trigger.py
```py
from apscheduler.triggers.interval import IntervalTrigger
from datetime import timedelta
from datetime import datetime
import random


class RandomIntervalTrigger(IntervalTrigger):
    def __init__(self, weeks=0, days=0, hours=0, minutes=0, seconds=0, start_date=None, end_date=None, timezone=None,
                 jitter=None):
        # Saving the parameters
        self.__weeks = weeks
        self.__days = days
        self.__hours = hours
        self.__minutes = minutes
        self.__seconds = seconds

        # Creating the random parameters
        weeks = random.randint(1, weeks) if weeks != 0 else weeks
        days = random.randint(1, days) if days != 0 else days
        hours = random.randint(1, hours) if hours != 0 else hours
        minutes = random.randint(1, minutes) if minutes != 0 else minutes
        seconds = random.randint(1, seconds) if seconds != 0 else seconds

        # Initializating the trigger
        super().__init__(weeks, days, hours, minutes, seconds, start_date, end_date, timezone, jitter)

    def get_next_fire_time(self, previous_fire_time: datetime, now: datetime):
        # Creating the random parameters
        weeks = random.randint(1, self.__weeks) if self.__weeks != 0 else self.__weeks
        days = random.randint(1, self.__days) if self.__days != 0 else self.__days
        hours = random.randint(1, self.__hours) if self.__hours != 0 else self.__hours
        minutes = random.randint(1, self.__minutes) if self.__minutes != 0 else self.__minutes
        seconds = random.randint(1, self.__seconds) if self.__seconds != 0 else self.__seconds

        # Generating the new scheduling time
        offset = timedelta(days=days, seconds=seconds, minutes=minutes, hours=hours, weeks=weeks)

        if previous_fire_time is None:
            previous_fire_time = now

        new_time = previous_fire_time + offset

        return new_time

```

Pipfile:
```
[packages]
apscheduler = "*"
requests = "*"

[requires]
python_version = "3.6"
```

Output:

> Press Ctrl+C to exit

The task does not run. I think that this is a bug. 

## Steps to Reproduce

1. Create required files
2. Pipenv install
3. Pipenv shell
4. Run `python3 clock.py`

## Context (Environment)

As described, I want to scedule tasks at random times by using IntervalTrigger. I want it to run on Heroku. I am using Python version 3.6.8, pipenv version 2020.6.2 and apsceduler version 3.6.3

**Comment by agronholm** [comment]
The fact that APScheduelr has a bug tracker does not mean that we are going to debug **your** code. The existing interval trigger works fine. If you go and override things and it breaks, at least do the courtesy of pointing out a behavior in APScheduler itself which you think is a bug.

**Comment by matej2** [comment]
I think that the bug is in `scheduler.start()`.  Documentation states that I should extend IntervalTrigger and overrriding get_next_fire_time method.

Can you at least add an example code with custom IntervalTrigger?

**Comment by agronholm** [comment]
Why is the code of the default `IntervalTrigger` not enough? What more do you need to debug this yourself?

**Comment by agronholm** [comment]
And why do you think there is a bug with `scheduler.start()`? What led you to that conclusion?

**Comment by matej2** [comment]
As I stated, I need to scedule tasks at random times. [Here](https://groups.google.com/u/1/g/apscheduler/c/iOlq7Li4du4) I read that this could be done by implementing custom IntervalTrigger

**Comment by agronholm** [comment]
Yes, your intent is clear. I just wanted to know why you think the bug lies specifically in `scheduler.start()`.

**Comment by matej2** [comment]
I have tried debugging and found out that RandomInterval properly prints out next scedule time. So the problem could be in add_job or in start because the job is being ran only once

**Comment by matej2** [comment]
Nevermind, I fixed it
