### ISSUE TITLE
Code and tests are broken

### ISSUE THREAD

**Issue by lhfelis** [agronholm/apscheduler#446]
This issue tracker is **ONLY** for reporting bugs.
Issues other than bug reports will be summarily closed.

Any support questions or feature requests should be directed to:

* [StackOverflow](http://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Google groups](http://groups.google.com/group/apscheduler)

## Expected Behavior

* `pip install .` OK
* `pytest` OK

## Current Behavior

* `pip install .` Fails. `cbor2` is missed and `dateutil` should be `python-dateutil` in dependency.
* `pytest` Fails. Number of error cases is huge.

## Steps to Reproduce

1. Clone from `master` branch
2. Setup local python environment
3. `pip install .` or `pip install -e .`, with all the extras installed. I failed here, and succeeded after added `cbor2` and changed `dateutil` to `python-dateutil` in `setup.cfg[[options]install_requires]`.
4. `pytest` failed with more than 100 errors.

## Context (Environment)

I just wanted to play with the code but found that both the code and tests are broken.
Maybe I can help fix the tests but after some effort I failed. 

## Detailed Description

1. In `setup.cfg[[options]install_requires]`,  `cbor2` is missed. `dateutil` is typo and should be `python-dateutil`.
2. `apscheduler.triggers.base` related code are broken since refactoring in commit `17a353f073a5e34bf033ad0013577063fcf6741c`.
3. Some test fixture missing after refactoring.
4. `apscheduler.triggers` could not be loaded correctly as plugins.

**Comment by agronholm** [comment]
I'm aware that the master branch is a mess. It could not really be helped as the project is undergoing a heavy refactoring effort. I will sort it out once I switch my focus to this project again. I've fixed the `python-dateutil` dependency in setup.cfg – thank you for that.
