### ISSUE TITLE
AsyncIOScheduler not triggering with ProactorEventLoop or SelectorEventLoop

### ISSUE THREAD

**Issue by keethesh** [agronholm/apscheduler#447]
This issue tracker is **ONLY** for reporting bugs.
Issues other than bug reports will be summarily closed.

Any support questions or feature requests should be directed to:

* [StackOverflow](http://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Google groups](http://groups.google.com/group/apscheduler)

## Expected Behavior

The function must be triggered when using one of these
## Current Behavior

The function doesn't get triggered
### This doesn't work
```python3
from apscheduler.schedulers.asyncio import AsyncIOScheduler

scheduler = AsyncIOScheduler()
if sys.platform == "win32":
    loop = asyncio.ProactorEventLoop()
else:
    loop = asyncio.SelectorEventLoop()
asyncio.set_event_loop(loop)
loop = asyncio.get_event_loop()

scheduler.add_job(async_func, trigger="cron",
                              hour=11, minute=11)
scheduler.start()
loop.run_forever()
```
### But this does
```python3
from apscheduler.schedulers.asyncio import AsyncIOScheduler

scheduler = AsyncIOScheduler()
loop = asyncio.get_event_loop()

scheduler.add_job(async_func, trigger="cron",
                              hour=11, minute=11)
scheduler.start()
loop.run_forever()
```

**Comment by agronholm** [comment]
Which Python version is this?

**Comment by agronholm** [comment]
The problem here isn't the proactor event loop, it's that you switch to a different loop **after** you create the scheduler. The scheduler stores the current event loop which is not the one you end up running.
