### ISSUE TITLE
jobstores-redis problem

### ISSUE THREAD

**Issue by qxy741865551** [agronholm/apscheduler#456]
![image](https://user-images.githubusercontent.com/27914934/92222624-de195880-eed1-11ea-8d9a-73345451df6c.png)
![image](https://user-images.githubusercontent.com/27914934/92222663-ed98a180-eed1-11ea-95fc-ccdca26326b8.png)
 the mapping arg must be a dict,but the arg is a float value

**Comment by Max-AR** [comment]
I got this error as well, reverting to redis 2.10.6 works as a temp fix.

**Comment by agronholm** [comment]
What error did you get, and with what version of the redis library?

**Comment by agronholm** [comment]
What version of apscheduler are you running? This was fixed back in 2018 (eaf8dbd5).

**Comment by agronholm** [comment]
Closing as the issue was fixed a long time ago already.
