### ISSUE TITLE
Set thread_name_prefix in ThreadPoolExecutor

### ISSUE THREAD

**Issue by ayeteng** [agronholm/apscheduler#458]
I'd like to set up the thread_name_prefix for the ThreadPoolExecutor which is available in Python3.6
https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

New in version 3.6: The thread_name_prefix argument was added to allow users to control the threading.Thread names for worker threads created by the pool for easier debugging.

I cannot find the relevant setting in Apscheduler. 

## Expected Behavior

Look for the parameter to setup thread_name_prefix
```
from apscheduler.executors.pool import ThreadPoolExecutor, ProcessPoolExecutor

executors = {
    'default': ThreadPoolExecutor(max_workers=1, thread_name_prefix='My Apscheduler Executor'),
    'processpool': ProcessPoolExecutor(1)
}
```

## Current Behavior

This is my setup for a scheduler:
```
executors = {
    'default': ThreadPoolExecutor(max_workers=1, thread_name_prefix='My Apscheduler Executor'),
    'processpool': ProcessPoolExecutor(1)
}
scheduler = TornadoScheduler(executors=executors)
scheduler.add_job(self._clean_up_counter_daily, trigger='cron', hour='0', minute='0', id='clean_up_counter_daily')
scheduler.start()
```

If I don't set the thread name prefix, I can get the name of ThreadPoolExecutor equal to 'ThreadPoolExecutor-0_0'. But if I set the thread_name_prefix in the ThreadPoolExecutor, there is a error message as below:
```
__init__() got an unexpected keyword argument 'thread_name_prefix'
  File "/home/ubuntu/mgr.py", line 198, in run_scheduled
    'default': ThreadPoolExecutor(max_workers=1, thread_name_prefix='My Apscheduler Executor'),
```

It's a nice to have feature request. Please check if this can be supported in new version

**Comment by agronholm** [comment]
If you read the template, this tracker is only for bug reports. This is not a bug. I will probably allow feature requests again after v4.0 but for now it's nearly pointless to receive them as 4.0 is an almost complete rewrite.
