### ISSUE TITLE
[BUG] Incorrect schedule time

### ISSUE THREAD

**Issue by teemue** [agronholm/apscheduler#460]
## Expected Behavior
Return proper time

## Current Behavior
According to the dev, APScheduler is used in Vorta (GUI for Borg Backup) to set backup interval. APScheduler does not return right time.

## Steps to Reproduce & context
In Vorta, open Scheduling tab and set backup interval hour. It returns very inconsistent time values. 
Graphic presentation of the problem is provided in Vorta's repo (borgbase/vorta#659)

**Comment by agronholm** [comment]
Please read the bug reporting template and follow it. I will close issues that do not follow the template.

**Comment by agronholm** [comment]
"Return proper time"? Please provide an example that reproduces the problem **without the external software**. You need to prove that this is an APScheduler bug.

**Comment by agronholm** [comment]
No explanation was provided and poster does not answer questions. Closing.
