### ISSUE TITLE
Log module string formatting

### ISSUE THREAD

**Issue by zxzhuty** [agronholm/apscheduler#462]
I found some bugs in the log module

e.g.

schedulers  base.py
`self._logger.info('Added job "%s" to job store "%s"', job.name, jobstore_alias)`
output：Added job "%s" to job store "%s"
this is not quite what I want

If I fix it
`self._logger.info(('Added job %s to job store %s')%(job.name, jobstore_alias))`
The results are correct

But,There are many similar problems with this project
I hope good people can fix it

**Comment by agronholm** [comment]
The logger does string interpolation lazily, which is why I am not using the `%` operator there. Are you actually getting that output in your logs? I'm not, so if this is really the case, please provide some means for me to reproduce the problem locally.

**Comment by zxzhuty** [comment]
> The logger does string interpolation lazily, which is why I am not using the `%` operator there. Are you actually getting that output in your logs? I'm not, so if this is really the case, please provide some means for me to reproduce the problem locally.


Thanks,The output on the console is normal,I guess there might be something wrong with my code.The job I did is as follows:
1.General code:
```
#main.py

import time,logging
from apscheduler.schedulers.blocking import BlockingScheduler
from Untils_LogToDb import LogToDb

def run():
    print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))

scheduler = BlockingScheduler()
aplog=logging.getLogger('apscheduler')
LEVEL = logging.INFO
FORMAT = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(level=LEVEL, format=FORMAT)
```
2.Store log to database
In short, it is to write a class inheritance logging.Handler , and rewrite the emit method

```
#LogToDb.py

import logging
import time
from Untils_DbHandle import DbHandle

class LogToDb(logging.Handler):
    def __init__(self):
        logging.Handler.__init__(self)
        self.db = DbHandle()
        self.TABLE_NAME = '******'
    def emit(self, record):
        print(record.msg) #The printed information here is not correct
        createdtime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(record.created))
        level = record.levelname
        msg = record.msg
        sql = "INSERT INTO "+self.TABLE_NAME+(" (**,**,**) VALUES('%s', '%s', '%s');") % (
        createdtime, level, msg)
        self.db.insert(sql)
    def close(self):
        self.db.close()
```
3.End
```
main.py
logdb = LogToDb()
logdb.setLevel(LEVEL)
aplog.addHandler(logdb)
scheduler.add_job(run,"interval", seconds=2)
scheduler.start()
```
The information I get in the database:
```
# logid, createdtime, level, msg
'4093', '2020-09-25 09:09:30', 'INFO', 'Adding job tentatively -- it will be properly scheduled when the scheduler starts'
'4094', '2020-09-25 09:09:30', 'INFO', 'Added job \"%s\" to job store \"%s\"'
'4095', '2020-09-25 09:09:30', 'INFO', 'Scheduler started'
'4096', '2020-09-25 09:09:32', 'INFO', 'Running job \"%s\" (scheduled at %s)'
'4097', '2020-09-25 09:09:32', 'INFO', 'Job \"%s\" executed successfully'
```
Incorrect string format.I don't know what the problem is,Maybe I made some low-level mistakes.I'm hoping to get some hints. Thanks very much.

**Comment by agronholm** [comment]
As I suspected, you are using a custom logging handler and there seems to be a bug in it. This is beyond the scope of this bug tracker and you will have to get help elsewhere. Sorry.
