### ISSUE TITLE
Ignore some dates in a cron-scheduled task

### ISSUE THREAD

**Issue by Phyks** [agronholm/apscheduler#468]
Hi,

I am using apscheduler in a tool to run actions based on events in a (ICS) calendar. The translation from ICS recurring events to cron format is pretty straightforward. It seems, however, that apscheduler cron syntax is not able to handle exceptions (for some occurrences of a recurring event which are removed).

I could hack something on my side, checking at each run if the current timeframe is an exception. Is there, however, some traction to write this within apscheduler and make a proper PR?

Best,

**Comment by agronholm** [comment]
This issue tracker is only for reporting bugs (as should have been obvious from the template you chose to ignore).

You question, however, is valid and I will be happy to answer it on any of the venues given in the template or the documentation.

**Comment by Phyks** [comment]
Sorry for posting in the wrong place, such a template usually implies "feature request" as in "code it for me" and not PR-ready code. Usual practice I saw around is to have all purely dev-related tracking (issues or developing features together) in Github. I read too fast and missed the specificity here.

However, I don't have any Gitter / SO / Google groups account and cannot create one (for reasons beyond simple technical issues). So I guess I will hack something on my side.

**Comment by agronholm** [comment]
Clearly you have a Github account so you can just join the APScheduler Gitter room: https://gitter.im/apscheduler/Lobby
