### ISSUE TITLE
Use apscheduler to dynamically add jobs I use it in a wrong way?

### ISSUE THREAD

**Issue by RyanHuang1102** [agronholm/apscheduler#471]
Step 1. this is my add.py to add jobs
```
from datetime import datetime, timedelta
import sys
import os

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.redis import RedisJobStore
import logging

jobstores = {
    'default': RedisJobStore(host='localhost', port=6379)
}

scheduler = BackgroundScheduler(jobstores=jobstores)

def alarm():
    time = datetime.now()
    os.system("echo \"Alarm! This alarm was scheduled at %s\" >> /var/log/test.log"%(time))

def add(task_func, task_id):
    #print task_func,task_id
    scheduler.add_job(task_func, 'interval', id=task_id, name=task_id, seconds=10)


if __name__ == '__main__':
    add(alarm, 'my_job1')
    add(alarm, 'my_job2')
    scheduler.start()
    scheduler.shutdown()
```

I added two jobs first, then start and shutdown 

> 1. I just used add_job but it will not really add it.

> 2. So I did start and shutdown. But I don't really sure that it need shut down or not.

Step 2 .and then start test.py ; python test.py
```
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.redis import RedisJobStore
jobstores = {
        'default': RedisJobStore(host='localhost', port=6379)
}
scheduler = BackgroundScheduler(jobstores=jobstores)

if __name__ == '__main__':
    #scheduler.add_job(alarm, 'interval', id='my_job0', seconds=10)
    try:
        scheduler.start()
        # This is here to simulate application activity (which keeps the main thread alive).
        while True:
            time.sleep(2)
    except (KeyboardInterrupt, SystemExit):
        # Not strictly necessary if daemonic mode is enabled but should be done if possible
        print "shutdown scheduler"
        scheduler.shutdown()
```
it works, but when I add a new job id=my_job3 it did nothing.

## Expected Behavior

I want to dynamic add, get , remove jobs when apsheduler is starting.
get jobs -> it works, but not sure I use it in a right way. Can you give me a best way? or more use case?
```
from apscheduler.jobstores.redis import RedisJobStore
RedisJobStore().get_all_jobs()
```
remove jobs -> it works, but not sure I use it in a right way. Can you give me a best way? or more use case?
```
from apscheduler.jobstores.redis import RedisJobStore
RedisJobStore().remove_all_jobs()
```

## Steps to Reproduce

what I am trying is:
step 1. add two jobs
step 2. starting apsheduler -> successful
step 3. add a new job  -> fail

## Context (Environment)

APScheduler==3.6.3
redis==3.5.3
ubuntu 16.04

## Detailed Description

I try others way like:
step1. -> step2. -> kill python test.py -> step 3. -> restart test.py  (it works)
But I am not sure it is a good way to use.
When add new job must kill main thread?
any option to restart? must kill and then restart?

**Comment by RyanHuang1102** [comment]
![apsheduler](https://user-images.githubusercontent.com/36656343/96574709-62992c80-1302-11eb-9e9a-b4e64f764f8f.jpg)

**Comment by RyanHuang1102** [comment]
When scheduler is starting, can't add a new job?

**Comment by agronholm** [comment]
What do you mean? Are you getting an error? Please give the details.

**Comment by RyanHuang1102** [comment]
jobstores = {
        'default': RedisJobStore(host='localhost', port=6379)
}
scheduler = BackgroundScheduler(jobstores=jobstores)
1. I add two jobs(id=job1 and job2), and then 
        scheduler.start()
        while True:
            time.sleep(2)
it start well.....
2.  if I want start a new job(id = job3), how can I implement it?
I try that,
    Add a new job(id = job3), and then scheduler.start() -> it will run (job1,job2,job3)
-> duplicate

**Comment by agronholm** [comment]
Use `replace_existing=True` when adding those jobs.

**Comment by RyanHuang1102** [comment]
with replace_existing=True when adding those jobs.
so it run scheduler two times?  one is starting job1,job2 the other is job3 ?

**Comment by agronholm** [comment]
I don't understand you. As it says in the documentation, `replace_existing=True` just means it replaces jobs in the store with those IDs. It doesn't affect the running of the scheduler itself.

**Comment by RyanHuang1102** [comment]
When job1,job2 is starting....
I want add a new job3, what should I do?

**Comment by agronholm** [comment]
Just call `scheduler.add_job()` as normal. I cannot understand what problem you are having with that.

**Comment by RyanHuang1102** [comment]
I called scheduler.add_job() to add job3, but it didn't add to store.

**Comment by agronholm** [comment]
Can you show me a script that reproduces this problem?

**Comment by RyanHuang1102** [comment]
add.py
```
from datetime import datetime, timedelta
import sys
import os,time

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.redis import RedisJobStore
import logging

jobstores = {
    'default': RedisJobStore(host='localhost', port=6379)
}

job_defaults= {
    'coalesce': True,
    'max_instances': 1,
    'misfire_grace_time':300

}
scheduler = BackgroundScheduler(jobstores=jobstores, job_defaults=job_defaults)

def alarm(task_id, params):
    time = datetime.now()
    os.system("echo \"[%s] Alarm! This alarm was scheduled at %s\" >> /var/log/test.log"%(task_id, time))
    os.system("echo params: %s >> /var/log/test.log"%(params))

def add(task_func, task_id, **kwargs):
    scheduler.add_job(task_func,'interval', args=[task_id, kwargs], id=task_id, name=task_id, seconds=10)

if __name__ == '__main__':
    add(alarm, 'my_job1', haha=123, gg=234)
    add(alarm, 'my_job2')
    try:
        scheduler.start()
        # This is here to simulate application activity (which keeps the main thread alive).
        while True:
            time.sleep(2)
    except (KeyboardInterrupt, SystemExit):
        # Not strictly necessary if daemonic mode is enabled but should be done if possible
        print "shutdown scheduler"
        scheduler.shutdown()
```
python add.py
this script add two jobs!

**Comment by RyanHuang1102** [comment]
add1.py
```
from datetime import datetime, timedelta
import sys
import os,time

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.redis import RedisJobStore
import logging

jobstores = {
    'default': RedisJobStore(host='localhost', port=6379)
}

job_defaults= {
    'coalesce': True,
    'max_instances': 1,
    'misfire_grace_time':300

}
scheduler = BackgroundScheduler(jobstores=jobstores, job_defaults=job_defaults)

def alarm(task_id, params):
    time = datetime.now()
    os.system("echo \"[%s] Alarm! This alarm was scheduled at %s\" >> /var/log/test.log"%(task_id, time))
    os.system("echo params: %s >> /var/log/test.log"%(params))

def add(task_func, task_id, **kwargs):
    scheduler.add_job(task_func,'interval', args=[task_id, kwargs], id=task_id, name=task_id, seconds=10)


if __name__ == '__main__':
    add(alarm, 'my_job3', hh=123,cc=123)
```
python add1.py
to add job3

**Comment by RyanHuang1102** [comment]
get.py
```
from datetime import datetime, timedelta
import sys
import os

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.jobstores.redis import RedisJobStore
import logging

jobstores = {
        'default': RedisJobStore(host='localhost', port=6379)
}
scheduler = BackgroundScheduler(jobstores=jobstores)

def alarm(time):
    print('Alarm! This alarm was scheduled at %s.' % time)


if __name__ == '__main__':
    ret = RedisJobStore().get_all_jobs()
    dic = {'task':ret}
    print dic
```
python get.py
get all jobs in store

**Comment by agronholm** [comment]
You never said that you're adding jobs from a different process than where the scheduler is running. This is not supported in APScheduler 3. The [FAQ](https://apscheduler.readthedocs.io/en/stable/faq.html#how-do-i-share-a-single-job-store-among-one-or-more-worker-processes) explains why this won't work and provides a workaround.

**Comment by RyanHuang1102** [comment]
OK, thank you very much

**Comment by santhosh2252** [comment]
Please check this blog, It might be helpful for those who want to add jobs dynamically to apscheduler at runtime without restarting it.

https://levelup.gitconnected.com/apscheduler-dynamic-task-scheduling-library-in-python-fc1e6eb33c85#:~:text=Starting%20from%20the%20imports%2C%20we,BlockingScheduler%20%3B%20same%20with%20the%20trigger.

**Comment by legout** [comment]
> You never said that you're adding jobs from a different process than where the scheduler is running. This is not supported in APScheduler 3. The [FAQ](https://apscheduler.readthedocs.io/en/stable/faq.html#how-do-i-share-a-single-job-store-among-one-or-more-worker-processes) explains why this won't work and provides a workaround.

Will this be possible in APScheduler 4? If yes? Is it documented somewhere, how to do that?

Thanks.

**Comment by agronholm** [comment]
It's documented in the [user guide](https://apscheduler.readthedocs.io/en/master/userguide.html). The key is that APScheduler 4 allows running multiple schedulers against the same data store.

**Comment by legout** [comment]
Thanks a lot!
