### ISSUE TITLE
Unable to pause a data based trigger job (invalid job id)

### ISSUE THREAD

**Issue by som-shekhar** [agronholm/apscheduler#472]
Situation: I have a data based trigger which is supposed to be executed in the next 5 second. This job takes approximately takes 5minutes to complete. I have cached the job instance which I received after calling add_job() method, so that later based on the user request I can pause or resume the job.

Expected Output: The job should be paused when pause() method is called on the cached job instance.

Current Output: When I try to pause, it is not able to find the job id from the job store and I am not able to pause the job.

Cause: After seeing the code, I found that since there is no next trigger for this job, hence it gets removed from the job store and hence the pause() method while looking up from the job store doesn't finds the job.

Please let me know if there is way to pause this already running job?

**Comment by christopherpickering** [comment]
I don't think that pause() will pause a running instance, but will stop future runs from being created, until you un-pause the job. For that to work it obviously needs to be a scheduled job, not a one-off. You can add some code inside the class or function you are running to handle a pause. Basically at each step of your program check if it should be paused or continue.

Inside your "runner" function or class you can also check/log when the job completed.

The apscheduler is just triggering a function to start, either one time, or on the schedules, anything we want to do with that running function is done outside the scheduler.

**Comment by som-shekhar** [comment]
Thanks for the explaination
