### ISSUE TITLE
skipped: maximum number of running instances reached (1)

### ISSUE THREAD

**Issue by morestart** [agronholm/apscheduler#474]
this is my code, my task is download satellite image

```python
def create_task():
    try:
        content = yaml.load(data, Loader=yaml.FullLoader)
        FYDownloadTime = content['FYDownloadTime']
        JAXADownloadTime = content['JAXADownloadTime']

        job_defaults = {
            "coalesce": True, 
        }
        executors = {
            "thread_pool": ThreadPoolExecutor(),
        }
        scheduler = BlockingScheduler(job_defaults=job_defaults, timezone=pytz.timezone("Asia/Shanghai"),
                                      executors=executors)

        if not os.path.exists('cache'):
            os.makedirs('cache/JAXA')
            os.makedirs('cache/FY4')
        if not os.path.exists('satelliteImg'):
            os.makedirs('satelliteImg/JAXA')
            os.makedirs('satelliteImg/FY4')

        scheduler.add_job(downloadJAXA, 'cron', minute="*/9", hour=JAXADownloadTime,
                          id='jaxa')
        scheduler.add_job(downloadFY4, 'cron', minute="*/5", hour=FYDownloadTime,
                          id='fy4')

        scheduler.start()

    except ScannerError:
        logging.warning(
                        'FYDownloadTime: 6-21\n'
                        'JAXADownloadTime: 6-21')
        time.sleep(4)
```

2020-11-05 18:20:00,009 - apscheduler.scheduler-WARNING Execution of job "downloadFY4 (trigger: cron[hour='6-21', minute='*/5'], next run at: 2020-11-05 18:20:00 CST)" skipped: maximum number of running instances reached (1)

When get this warn, the The program will be blocked
I must restart my program...

**Comment by agronholm** [comment]
Is this a bug report?

**Comment by morestart** [comment]
maybe it's a bug, i don't know, because it just has a warning

**Comment by agronholm** [comment]
Was the message unclear then? If the job is still running when it's scheduled to run again, it will be skipped if the maximum number of concurrent running instances (which default to 1) has been reached. This is normal. If you want multiple instances of the same job to run concurrently, just change the `max_instances` setting to a higher value.

**Comment by morestart** [comment]
no, i just get this message. i try set `max_instances =200` , it will be work, but after a few days, It still has this problem. When this problem arises, my program will be blocked at a time. 
example, the apscheduler info display my task will run at 6:00, but when the time is 7:00, my task not run, log will have this warn, But my program is still running, just not scheduled downloads

**Comment by agronholm** [comment]
Are you saying it's still complaining about `maximum number of running instances reached (1)` (with 1 as the number), even though you set `max_instances=200` for the job?

**Comment by morestart** [comment]
Yes, it's just that the program takes longer to run normally than it does not

**Comment by agronholm** [comment]
Clearly the snippet you pasted in the description is not representative of your actual application. If the error message displays the number 1 and not 200, then you've not entered the parameter in the correct place.
Also, this part of your configuration does not do anything since you're assigning any jobs to this executor:
```
        executors = {
            "thread_pool": ThreadPoolExecutor(),
        }
```

**Comment by morestart** [comment]
```Python
scheduler = BlockingScheduler()

     
scheduler.add_job(downloadJAXA, 'cron', minute="*/9", hour=JAXADownloadTime,
                          id='jaxa', max_instances=200)
scheduler.add_job(downloadFY4, 'cron', minute="*/5", hour=FYDownloadTime,
                          id='fy4', max_instances=200)
```

this is my first code...

**Comment by agronholm** [comment]
If the error says that 1 is the maximum number of instances then it's some other job that is hitting that problem. Please ensure that all your jobs have the correct parameter.

**Comment by agronholm** [comment]
Closing as stale.

**Comment by liqing1990** [comment]
> no, i just get this message. i try set `max_instances =200` , it will be work, but after a few days, It still has this problem. When this problem arises, my program will be blocked at a time.
> example, the apscheduler info display my task will run at 6:00, but when the time is 7:00, my task not run, log will have this warn, But my program is still running, just not scheduled downloads


I also have this problem. Is there a solution? As long as the maximum is reached and it goes online, my program will not trigger a timer task. The value displays a warning message.

**Comment by timolson** [comment]
I also get this error in the BlockingScheduler()

How can you say this is not a bug if it's the BlockingScheduler?  There should only be one thread and thus it's impossible to have more than one instance running, or else the scheduler itself would not get execution since control is still with the job.

You can find that some people including myself have worked around this _bug_ by [reverting to an older version](https://stackoverflow.com/questions/24921383/apscheduleradvance-python-scheduler-importerror-no-module-named-scheduler/25710016#25710016).  Nothing else is required to "fix" the behavior.

Please re-open and examine for version 3.  Is there a leak or bad reference count somehow in BlockingScheduler?  Needs a finally somewhere?

**Comment by lucasjinreal** [comment]
I think this problem it not fixed at all.

Still got this erorr at 2024.

We can not increase the max-instance to avoid it, it will eventually hit when runs enough time, by increase maxinstance is a tupid solution, at least from current this lib I can see.

**Comment by HK-Mattew** [comment]
> I think this problem it not fixed at all.
> 
> Still got this erorr at 2024.
> 
> We can not increase the max-instance to avoid it, it will eventually hit when runs enough time, by increase maxinstance is a tupid solution, at least from current this lib I can see.

Hello,

I believe that version 3 is not receiving updates. Because the maintainer is working on the new version 4 of APScheduler.

**Comment by agronholm** [comment]
> I think this problem it not fixed at all.
> 
> Still got this erorr at 2024.
> 
> We can not increase the max-instance to avoid it, it will eventually hit when runs enough time, by increase maxinstance is a tupid solution, at least from current this lib I can see.

If your task takes long enough for the next fire time to be hit, and you don't want concurrent executions of that task, what do you expect to happen then?

**Comment by lucasjinreal** [comment]
maybe there could be a waiting, for the task done, and then start the queue, however, currently behavior will forever waiting (3.0x)

**Comment by agronholm** [comment]
Forever waiting? What do you mean? The job will just be skipped if it reaches the maximum number of instances.

Am I correct that you're suggesting that the next job would start running immediately after the previous one completes?

**Comment by lucasjinreal** [comment]
The actual situation may be more complex than I had anticipated. However, the appearance suggests that there is seemingly perpetual waiting even when the tasks have been completed.

**Comment by agronholm** [comment]
I'm not understanding. Please elaborate on this "perpetual waiting".

**Comment by lucasjinreal** [comment]
Alright, I have moved into `schedualer`, hope youself have fun. Your comments have too much emotional comments.

**Comment by HK-Mattew** [comment]
> Tudo bem, eu mudei para `schedualer`, espero que você se divirta. Seus comentários têm muitos comentários emocionais.

I'm sorry, But it's clear that you have limited knowledge on the subject. Because of your lack of knowledge, you want to treat people with disrespect. You have complete freedom to use other libs.
