### ISSUE TITLE
scheduler.remove_job() does not seem to completely remove the job

### ISSUE THREAD

**Issue by jtfidje** [agronholm/apscheduler#475]
## Expected Behavior
If I add a job with ID 123 and my task fails because of bad input from user, I expect `skipped: maximum number of running instances reached`
Subsequently, I call `scheduler.remove(123)` to remove my job and add a new job with ID 123 with valid input.
I then expect the task to run without errors.

## Current Behavior
Performing the steps above; After I add the job again with valid input, I still get `skipped: maximum number of running instances reached`.

## Steps to Reproduce
**1.**
```python
scheduler.add_job(
    tasks.get_url, # A function that performs a plain requests.get() call against a url 
    "interval",
    args=[url], # INVALID url for task function
    id="TestJob",
    **interval, # dict with seconds, minutes, etc
)
``` 
The endpoint that I provide a url to only accepts `http`. In step 1, I give URL to endpoint with `https://` prefix and expect task to fail.
**2.**
```python
scheduler.remove_job("TestJob")
```
**3.**
```python
scheduler.add_job(
    tasks.get_url, # A function that performs a plain requests.get() call against a url 
    "interval",
    args=[url], # VALID url for task function
    id="TestJob",
    **interval, # dict with seconds, minutes, etc
)
```
After this, task still fails. 

## Context (Environment)
APScheduler is used in conjunction with FastAPI and with a Redis backend.

## Detailed Description
In addition to the descriptions already provided:  

If I perform steps 1 through 3 and the new job is still failing, if I restart the application but _keep_ the job in Redis, the task immediately starts working the application comes back up again!

**Comment by agronholm** [comment]
> If I add a job with ID 123 and my task fails because of bad input from user, I expect skipped: maximum number of running instances reached

No, tasks only fail with this error if the task is already running in the executor and the scheduler is trying to schedule another instance of it to run on the executor.

> Performing the steps above; After I add the job again with valid input, I still get skipped: maximum number of running instances reached.

This is because there is no way to cancel running jobs and a job with that task id is still running in the executor. What do you expect me to do about this? Why does your task stall if invalid input is given to it, instead of raising an exception?

**Comment by jtfidje** [comment]
Aha - clearly my bad for misunderstanding that part. Thank you for answering so quickly!

My task is handling the exceptions though - or at least I thought so. Please have a look:
```python
def get_url(url: str):
    try:
        res = requests.get(url, verify=False)

        try:
            res_json = res.json()
        except json.decoder.JSONDecodeError:
            res_json = {}
            logger.warning(f"Failed to decode response from {url}")

        logger.info(f"GET {url} {res.status_code}: {res_json}")
        res.raise_for_status()
    except requests.exceptions.HTTPError as err:
        logger.error(err)
    except requests.exceptions.RequestException as err:
        err_type = err.__class__.__name__
        logger.error(f"Scheduled job got '{err_type}' against: {url}")
    except Exception:
        logger.exception()
```

**Comment by agronholm** [comment]
So is it failing or stalling? Also, you're not aborting the process if JSON decoding fails. Was this intentional?

**Comment by jtfidje** [comment]
Yes, that part is intentional. but thanks for pointing it out.

I understand now what is happening; You pointing out that the task is stalling made me suddenly realize that the request takes _forever_ to timeout. I tested now manually setting a timeout threshold, and everything works as expected. 100% my fault - sorry for that.

Time is a valuable thing, so I really appreciate you spending some of yours to help today.
Case closed!
