### ISSUE TITLE
next run time missed by some seconds in job scheduling

### ISSUE THREAD

**Issue by sidnaik03** [agronholm/apscheduler#476]
I have scheduled crone jobs using AP scheduler. Jobs not get fired on the schedule time, and its give a message like 'next run time missed by some seconds in job scheduling'. I read about it [here](https://stackoverflow.com/questions/30235604/next-run-time-missed-by-some-seconds-in-job-scheduling-in-apscheuler) and set misfire_grace_time. Now some scheduled job get fire by delay of 5 seconds and some not get fired at all. ( There is no consistency on which job get fired. Suppose I have 2 jobs A & B. Sometimes A get fired sometime B or both get fired or none of it). I am using with python3.5 with MSSQL/POSTGRES database on windows 12 server (12 GB RAM, i5 processor). I also read this is because of all resources get busy that's why this delay occurred but I didn't follow it. (In my case , my server always have free 5-6 GB RAM, so not exactly understood resources busy means what)
## Expected Behavior

Excepted behavior is schedule job should get fire on the time (With/without setting misfire_grace_time).
## Current Behavior

Scheduled job not get fired on the schedule time. If we set misfire_grace_time, its get fired sometime.

## Steps to Reproduce

1. Sorry, I am not sure how to reproduce the issue.
## Context (Environment)

Stack:
1)Python 3.5 
2)python framework - Falcon.
3) Windows 12 Server (12 GB RAM, i5 processor).
4)MSSQL/POSTGRES database for the scheduler tables (Tested on both)

Please help

**Comment by agronholm** [comment]
If you cannot tell me how to reproduce this, what do you expect me to do about it?

**Comment by agronholm** [comment]
Have you tried reproducing the problem in a simplified setting (just the scheduler, no database)?

**Comment by agronholm** [comment]
Closing as stale.
