### ISSUE TITLE
Cron trigger not running job

### ISSUE THREAD

**Issue by raokrutarth** [agronholm/apscheduler#484]
**Describe the bug**
The test job does not run

**To Reproduce**
```python
from os import environ
from apscheduler.executors.asyncio import AsyncIOExecutor
from apscheduler.executors.pool import ThreadPoolExecutor
from apscheduler.jobstores.memory import MemoryJobStore
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from pytz import utc

"""
    Local async function scheduler allows periodic or
    timed function execution. Uses Redis backend to queue
    up jobs so multiple workers and coordinate jobs.
"""

job_store = (
    MemoryJobStore()
)  # FIXME due to a bug in the apscheduler + gunicorn combination


scheduler: AsyncIOScheduler = AsyncIOScheduler(
    jobstores={
        "default": job_store,
    },
    executors={"default": AsyncIOExecutor(), "cron": ThreadPoolExecutor()},
    # timezone=utc,
    job_defaults={
        "coalesce": True,  # Trigger only one job to make up for missed jobs.
        "max_instances": 1,  # Allow only one execution of a job per time.
    },
)

if __name__ == "__main__":
    from time import sleep

    @scheduler.scheduled_job(
        'cron',
        day_of_week='mon-fri',
        hour='*',
        minute='0-59',
        timezone="US/Pacific",
    )
    def test_job():
        print("test job ran")

    scheduler.start()

    while 1:
        print("...")
        sleep(4)
```

**Expected behavior**
`test job ran` should be printed.

**Additional context**
None

**Comment by agronholm** [comment]
It's not running because you're not running the asyncio event loop. See the [example](https://github.com/agronholm/apscheduler/blob/3.x/examples/schedulers/asyncio_.py) for how to use `AsyncIOScheduler`. Are you sure you want to use this particular scheduler instead of `BackgroundScheduler` though?

**Comment by raokrutarth** [comment]
```python
from os import environ
from apscheduler.executors.asyncio import AsyncIOExecutor
from apscheduler.executors.pool import ThreadPoolExecutor
from apscheduler.jobstores.memory import MemoryJobStore
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from pytz import utc

"""
    Local async function scheduler allows periodic or
    timed function execution. Uses Redis backend to queue
    up jobs so multiple workers and coordinate jobs.
"""

job_store = (
    MemoryJobStore()
)  # FIXME due to a bug in the apscheduler + gunicorn combination


scheduler: AsyncIOScheduler = AsyncIOScheduler(
    jobstores={
        "default": job_store,
    },
    executors={"default": AsyncIOExecutor(), "cron": ThreadPoolExecutor()},
    # timezone=utc,
    job_defaults={
        "coalesce": True,  # Trigger only one job to make up for missed jobs.
        "max_instances": 1,  # Allow only one execution of a job per time.
    },
)

if __name__ == "__main__":

    from time import sleep
    import uvicorn
    import fastapi

    app = fastapi.FastAPI()

    @app.on_event("startup")
    def app_bootstrap():
        @scheduler.scheduled_job(
            'cron',
            day_of_week='mon-fri',
            hour='*',
            minute='0-59',
            timezone="US/Pacific",
        )
        def test_job():
            print("test job ran")

        scheduler.start()

        print("app started")

    uvicorn.run(app, workers=1)
```

this also does not run. I believe uvicorn starts an asyncio loop.

I need to use the `AsyncIOScheduler` because some of my jobs are async functions. 

ps. the example link at the botton of [this](https://apscheduler.readthedocs.io/en/stable/modules/schedulers/background.html?highlight=BackgroundScheduler#apscheduler.schedulers.background.BackgroundScheduler) page gives a 404.

**Comment by raokrutarth** [comment]
Also, the interval triggers seem to work for similar scenerios

**Comment by raokrutarth** [comment]
@agronholm please reopen the bug if the new snippet seems valid.

**Comment by agronholm** [comment]
What I think happens here is that `uvicorn.run()` instantiates a new event loop rather than using the existing one. That would cause the scheduler to not run at all. Does uvicorn have a hook system that lets you run code after it's been started?

**Comment by agronholm** [comment]
Sorry, I totally misread the code – you're already doing that.

**Comment by agronholm** [comment]
My hunch was right though: the scheduler is using a different event loop. Moving scheduler initialization to the `app_bootstrap()` callback will fix the code. I'll see if I can make adjustments to the 3.x branch to mitigate this problem.

**Comment by raokrutarth** [comment]
This is more of a question but if I have a file that is never imported like the below, will ht job never get scheduled? Apart from importing the job in the `__init__.py` of the module, is there a better way to make sure the job gets scheduled?

![image](https://user-images.githubusercontent.com/8570223/104606455-9ac7b700-5634-11eb-9b66-4a8f4db41806.png)

**Comment by agronholm** [comment]
You are required to run the code that schedules the jobs. The decorator is just an alternate way to do `schedule.add_job()` after all.

**Comment by imirzadeh** [comment]
Yeah, that was my problem too. But since I'm using FastAPI and I use the AsyncScheduler from the API, I can run:
```
uvicorn server:app --host <HOST> --port <PORT> --reload
```
and it works fine for me.

**Comment by prshir** [comment]
I was in similar situation. I started `AsyncIOScheduler` when event loop hasn't run yet. So job was added to scheduler but never executed. 
After reading this issue I realized that scheduler should be started when event loop is running.
