### ISSUE TITLE
Ideas for how to generate a listing of jobs that will run in the next x days?

### ISSUE THREAD

**Issue by christopherpickering** [agronholm/apscheduler#485]
Hi!

Is there a way to generate a simulated schedule of jobs that will be running in the next few days? Currently if I just do "get jobs" It only show the next run, not the planned runs.

For a very basic example, if I have a job (job 1) that is scheduled on a 1 hour interval, I would get a list that shows all the times that we plan to run this job. 

| Name | Schedule |
| :------------- | :----------: |
| Job 1 | 1:00PM |
| Job 1 | 2:00PM |
| Job 1 | 3:00PM |
| Job 1 | 4:00PM |
| Job 1 | 5:00PM |
| Job 1 | 6:00PM |

Maybe there is some logic I can use based on how you are already interpreting the cron/interval/oneoff?

Thanks,
Christopher

**Comment by agronholm** [comment]
If you have a question, please use one the [provided venues](https://apscheduler.readthedocs.io/en/stable/userguide.html#getting-help). Don't post questions on the issue tracker.
