### ISSUE TITLE
Unclear why job executes multiple times

### ISSUE THREAD

**Issue by raokrutarth** [agronholm/apscheduler#488]
**Describe the bug**
Setting a cron job to run at ~4pm everyday but the job runs multiple times as the logs show.

**To Reproduce**

__code__
```

_job_defaults = {
    "coalesce": True,  # Trigger only one job to make up for missed jobs.
    "max_instances": 1,  # Allow only one execution of a job per time.
}

local_scheduler: BackgroundScheduler = BackgroundScheduler(
    jobstores={
        "default": job_store,
    },
    executors={
        "default": ThreadPoolExecutor(),
    },
    timezone=_timezone,
    job_defaults=_job_defaults,
)

@local_scheduler.scheduled_job(
    # assuming trader runs in PDT timezone
    name="notify.daily.report",
    trigger=CronTrigger(
        day_of_week="mon-fri",
        hour="16",
        jitter=120,
    ),
)
def my_func()
   ...
```

Logs:

![image](https://user-images.githubusercontent.com/8570223/107724206-2b2b0300-6c98-11eb-9866-9f1185c12a9b.png)

**Expected behavior**
Job should only run once ~4 pm.

**Comment by agronholm** [comment]
More info is needed:

Are you running the latest APScheduler? Does this happen every day? Are you sure you're only running one scheduler?

**Comment by agronholm** [comment]
Those job defaults are built-in defaults btw, so no need to give them explicitly.

**Comment by raokrutarth** [comment]
1. Version: `APScheduler @ file:///home/zee/.cache/pypoetry/artifacts/a7/b5/3d/6c1f4ce4d6b2abb25515b1121068561b778b2fae6c9c49b6a4246d1123/APScheduler-3.6.3-py2.py3-none-any.whl`
2. Seen 3 days in a row.
3. Process and thread are printed in the logs. Two schedulers are running, however, only one is used in the decorator.

![image](https://user-images.githubusercontent.com/8570223/107776451-6fe58700-6cf6-11eb-964a-8a2c96e50b87.png)

**Comment by agronholm** [comment]
You are not using the latest version. Please upgrade and see if the error persists.

**Comment by agronholm** [comment]
Did it work with the latest APScheduler?

**Comment by junior-senior** [comment]
I'm running 3.7.0 and have the same issue.

**Comment by agronholm** [comment]
@junior-senior can you tell me how to reproduce the problem? This would be a lot faster to figure out if I could do that.

**Comment by junior-senior** [comment]
I think mine was caused by uwsgi, I've resolved it by using the threading.time and queue libraries to create a setInterval decorator

**Comment by agronholm** [comment]
I can't imagine why uWSGI would cause jobs to be executed multiple times.

**Comment by yhling** [comment]
I think this may be related to issue #291 where using jitter can cause the job to be rescheduled twice.

**Comment by agronholm** [comment]
The improved jitter feature in v4.0.0a1 eliminates jitter as the cause of such issues.
