### ISSUE TITLE
async def doesn't work?

### ISSUE THREAD

**Issue by jianmaikj** [agronholm/apscheduler#490]
APScheduler version: 3.7.0
python: 3.8.0
os: centos 7.5

**To Reproduce**
```
APS = AsyncIOScheduler(
    jobstores={
        'default': SQLAlchemyJobStore(url=DATABASE_TASK_URL)
    },
    executors={
        'default': {'type': 'threadpool', 'max_workers': 20},
        'processpool': ProcessPoolExecutor(max_workers=5)
    },
    job_defaults={
        'coalesce': True,
        'max_instances': 10,
        'replace_existing': True
    }
)
async def mytask():
    print('ok')

APS.add_job(
        trigger='interval',
        days=7,
        func=mytask,
        id='001',
        next_run_time=datetime.now()
    )
```
`/usr/local/lib/python3.8/concurrent/futures/thread.py:82: RuntimeWarning: coroutine 'mytask' was never awaited`

**Comment by agronholm** [comment]
This is because you opted to use a thread pool executor instead of the default asynchronous executor. Remove that and it will work.

**Comment by jianmaikj** [comment]
> This is because you opted to use a thread pool executor instead of the default asynchronous executor. Remove that and it will work.

thank you very much！
