### ISSUE TITLE
CRON weekday Syntax doesn't match standard CRON conventions (0 should be SUNDAY but it's MONDAY)

### ISSUE THREAD

**Issue by candyapplecorn** [agronholm/apscheduler#495]
# This bug is fixed in this OPEN PR:

https://github.com/agronholm/apscheduler/pull/381/files#diff-d2039686a7b887460cffb4522619e4deb818bccc50c1aa26228cea4661950a40R13

**Describe the bug**
When 0 is input as a day of week AP Scheduler interprets it as MONDAY however standard CRON conventions dictate it should be SUNDAY

**To Reproduce**
put 0 for a weekday while scheduling a job with a CRON trigger. 

**Expected behavior**
the task should run on Sunday. But it won't, it'll run on Monday

**Additional context**
https://github.com/agronholm/apscheduler/blob/master/apscheduler/triggers/cron/expressions.py#L10

Perhaps put Sunday as the 0th element AND 7th element? Or modulo 7 the index?

https://crontab.guru/#*_*_*_*_0

![image](https://user-images.githubusercontent.com/5856981/109692918-eaf3cd80-7b3d-11eb-8053-91fdbf0aeb89.png)

# Temporary workaround for those with this issue: 

Just use abbreviations of weekdays:

![image](https://user-images.githubusercontent.com/5856981/109693247-4c1ba100-7b3e-11eb-9e94-b2fccbc30c87.png)

**Comment by agronholm** [comment]
This was fixed in master (upcoming 4.0) in cb50f0dab93fccf39c091062f48899ab4ac53a51. Is the workaround of using day names not good enough in the 3.x series?

**Comment by candyapplecorn** [comment]
The workaround works, thank you @agronholm
