### ISSUE TITLE
Should job kwarg next_run_time be allowed to be None?

### ISSUE THREAD

**Issue by invokermain** [agronholm/apscheduler#496]
**Is your feature request related to a problem? Please describe.**
Adding a job to the scheduler with `next_run_time = None` starts the job as paused, even if the scheduler is started with `paused=False` (the default so meaningless but shows that this can be confusing). I am guessing it's because `next_run_time  = None` is treated differently to the default of `Undefined`.

I think this behaviour is non-obvious enough to cause issues.

**Describe the solution you'd like**
This issue could be avoided by raising an error or warning when a job is added with `next_run_time = None`, or this could be treated the same as it being undefined.

**Describe alternatives you've considered**
Does `next_run_time = None` have any use cases? If so, this issue could be simply solved by adding this behaviour to the documentation around `add_job()`.

**Comment by agronholm** [comment]
Why are you passing `None` to next_run_time if you don't want to prevent it from starting? It's clearly documented as:
```
next_run_time: when to first run the job, regardless of the trigger (pass  ``None`` to add the job as paused)
```
There are clearly use cases for this since this was specifically requested as a feature years back.

**Comment by invokermain** [comment]
Ah apologies, my fault for missing that in the docs. I only looked in the user guide. Was just raising in case it wasn't in the docs as it caught me out.

My scenario was loading job configuration (kwargs) from yaml files. So using something like `next_run_time=now() if job_name in config['run_on_startup'] else None` caught me out.

**Comment by agronholm** [comment]
Yeah, just don't add that kwarg if it's `None`. I'm closing this now as the issue seems to be resolved.
