### ISSUE TITLE
Option to not remove jobs on completion

### ISSUE THREAD

**Issue by daddycocoaman** [agronholm/apscheduler#500]
**Is your feature request related to a problem? Please describe.**
Hi. In my app, I am giving users the option to run any particular job as recurring or just run it once. Regardless of job schedule, I am keeping track of all executions in a separate table. In order to do this, I have to call `apscheduler.get_job` during `EVENT_JOB_EXECUTED`. Unfortunately, when the job is run once, it is removed from the database before I can make that call to get details about the execution, making it impossible for me to store information about the result. 

**Describe the solution you'd like**
I would like an option for the scheduler to not remove jobs on completion of single run events. Maybe give it a status of "COMPLETE" or something. That way, it's still clear to APScheduler that a job was run at some point, event though it won't have to handle it anymore.

Alternatively, it might be more generally useful to pass the entire Job during the event lifecycle. This might be a lot slower for people with a bunch of jobs though. 

**Describe alternatives you've considered**
Because I am also storing the output of the executions, I haven't found a way to grab the return string in any other way but through the JobExecutionEvent.

**Comment by daddycocoaman** [comment]
I'm aware that "Jobs" are going away with 4.0 but hoping this is taken into consideration for the next iteration. It wasn't immediately clear in the progress tracker how things were going to end up.

**Comment by agronholm** [comment]
Is there a reason why event listeners are not a suitable solution for you?

**Comment by agronholm** [comment]
In v4.0, the old concept of "Job" is going to be split into "schedules" and "jobs". The scheduler processes schedules and spawns jobs as necessary. The worker(s) then grab jobs and run them. To be notified of the result of a job, you would add an event listener on the worker. The exact semantics of event listeners are still up in the air for v4.0 though.

**Comment by daddycocoaman** [comment]
The event listeners work as they should, except the job is removed for single run events, and I need to capture the actual submitted Job from the jobstore.

Here is how I'm handling jobs and it works great for recurring jobs:
```python
def jobExecHandler(event: JobExecutionEvent):
    try:
        db = SessionLocal()
        job = AfishScheduler.get_job(event.job_id)
        output = str(event.exception) if event.exception else event.retval
        execution = Execution(
            eid=str(uuid.uuid4()),
            job_id=event.job_id,
            name=job.name,
            module=job.kwargs["module"],
            project=job.kwargs["project"],
            output=output,
            state=EventCodes(event.code).name,
            scheduled_time=event.scheduled_run_time,
        )
        db.add(execution)
        db.commit()

        if event.exception:
            AfishScheduler.pause_job(event.job_id)
    except:
        # log errors here
        pass

I just realized I could have an alternate method of keeping track of single run jobs in a list or something on submission, capture the result on the way out, then send to my executions table. I guess that'll work in the meantime. I should get a [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging)

I would still support an option in 4.0 to not completely remove the single-run jobs from the jobstore though if that's possible.

Closing.

**Comment by agronholm** [comment]
I think your use case is valid but I would look into modifying the job completion event so that it contains all the necessary information.

**Comment by daddycocoaman** [comment]
I agree! In the meantime, I've just subclassed the scheduler I'm using and added additional logic to handle single run events. Thanks for the consideration.
