### ISSUE TITLE
Cannot install APScheduler3.5.3 from source code

### ISSUE THREAD

**Issue by zhang5324496** [agronholm/apscheduler#506]
We downloaded the source code of APScheduler3.5.3 and installed APScheduler from the source code. There was no problem before March 8, but problems occurred after 3.8.

The error message is as follows:

`/tmp/easy_install-YOyEMH/setuptools_scm-6.0.1/src
<pkg_resources.WorkingSet object at 0x7f7a3d4dd8d0>
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    'zookeeper = apscheduler.jobstores.zookeeper:ZooKeeperJobStore [zookeeper]'
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 120, in run
    return func()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 52, in <module>
    'rethinkdb': ['rethinkdb >= 2.4.0'],
  File "setup.py", line 29, in scm_config
    'Programming Language :: Python :: 3.4',
  File "/tmp/easy_install-YOyEMH/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
  File "/tmp/easy_install-YOyEMH/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
  File "/tmp/easy_install-YOyEMH/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
    print(*k)
          ^
SyntaxError: invalid syntax`

It seems to say that the version of python is wrong, so I tried to change the version of python to 3.6.4 and re-installed through the source code. At this time, the installation was successful. But when quoted, the error message is as follows:

`from apscheduler.schedulers.background import BackgroundScheduler
ImportError: No module named apscheduler.schedulers.background`

Can someone tell me where I went wrong? thanks

env:
   Linux version 3.10.0-957.27.2.el7.x86_64

**Comment by agronholm** [comment]
Why are you trying to install an old version anyway? 3.7.0 is the latest. Also, how are you installing it? You should using `pip` to install it. Are you sure you're trying to import it in the same Python version you installed it to?

**Comment by zhang5324496** [comment]
> Why are you trying to install an old version anyway? 3.7.0 is the latest. Also, how are you installing it? You should using `pip` to install it. Are you sure you're trying to import it in the same Python version you installed it to?


For safety reasons, we need to fix the versions of all third-party packages in our project.
I downloaded the source package APScheduler-3.5.3.tar.gz from the official website and installed it using command ‘python setup.py install' .

From November last year to March 3rd, APScheduler can be installed normally in this way. The above error occurred during the installation on April 1.
We installed it in the docker environment, and it stands to reason that the environment should not change.

Any information that  I need to provide, please tell me. thank you

**Comment by agronholm** [comment]
If you're installing it on Docker, please provide a minimal Dockerfile that reproduces the problem. Still, `pip install` is the recommended method of installation.

**Comment by zhang5324496** [comment]
> If you're installing it on Docker, please provide a minimal Dockerfile that reproduces the problem. Still, `pip install` is the recommended method of installation.

As mentioned above, we all put third-party packages into our own libraries. No external network downloads during runtime.
The following dockerfile is modified based on our dockerfile, it can reproduce the problem phenomenon.

`FROM centos:7.8.2003

RUN yum install -y wget unzip \
    gcc openssl-devel bzip2-devel \
    automake autoconf libtool make which \
    java-1.8.0-openjdk-devel gcc-c++

WORKDIR /usr/src

RUN wget https://files.pythonhosted.org/packages/a6/5b/f399fcffb9128d642387133dc3aa9bb81f127b949cd4d9f63e5602ad1d71/setuptools-39.1.0.zip && \
    wget https://files.pythonhosted.org/packages/42/a7/c9569e03058430cef420d3543e8f63bc7b32d77ae03278becae977cf32a7/APScheduler-3.5.3.tar.gz && \
    wget https://files.pythonhosted.org/packages/ce/73/99e4cc30db6b21cba6c3b3b80cffc472cc5a0feaf79c290f01f1ac460710/tzlocal-2.1.tar.gz && \
    wget https://files.pythonhosted.org/packages/01/62/ddcf76d1d19885e8579acb1b1df26a852b03472c0e46d2b959a714c90608/requests-2.22.0.tar.gz && \
    wget https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz

RUN tar -zxvf Python-2.7.15.tgz && \
    unzip setuptools-39.1.0.zip  && \
    tar -xzvf APScheduler-3.5.3.tar.gz && \
    tar -xzvf requests-2.22.0.tar.gz && \
    tar -xzvf tzlocal-2.1.tar.gz

WORKDIR Python-2.7.15

RUN ./configure --enable-optimizations

RUN make altinstall && \
    yum clean all

WORKDIR /usr/src
RUN whereis python
RUN cd setuptools-39.1.0 && \
    /usr/local/bin/python2.7 setup.py install && \
    cd ../tzlocal-2.1 && \
    /usr/local/bin/python2.7  setup.py install && \
    cd ../APScheduler-3.5.3 && \
    /usr/local/bin/python2.7  setup.py install && \
    cd ../requests-2.22.0 && \
    /usr/local/bin/python2.7  setup.py install`

**Comment by agronholm** [comment]
After 1 hour of building this, I decided not to continue. Didn't get past the first command. Can you reproduce this using the official Python image?

Also, why are you installing all those libraries separately? They don't even cover all the dependencies of apscheduler (pytz and six are not included). This causes those external dependencies to be implicitly fetched over the Internet, contrary to what I believe you intended.

**Comment by zhang5324496** [comment]
> After 1 hour of building this, I decided not to continue. Didn't get past the first command. Can you reproduce this using the official Python image?
> 
> Also, why are you installing all those libraries separately? They don't even cover all the dependencies of apscheduler (pytz and six are not included). This causes those external dependencies to be implicitly fetched over the Internet, contrary to what I believe you intended.

Thanks for helping. It seems that the problem is caused by the version of setuptool-scm. After I fixed its version from 6.0.1 to 5.0.1, it can be installed normally.
