### ISSUE TITLE
Storing extra columns than just job id, next_run_time, and job_state.

### ISSUE THREAD

**Issue by alegend4u** [agronholm/apscheduler#508]
**Is your feature request related to a problem? Please describe.**
I want to implement my own ```CustomJobStore``` that subclasses ```SQLAlchemyJobStore``` which will use extended version of table ```apscheduler_jobs``` (some extra columns I would like to store.) But for that I have to also come up with my own ```CustomJob``` that subclasses ```Job```. And for that I would have to implement my own scheduler as well that uses ```CustomJob```

**Describe the solution you'd like**
Maybe there should be a ```BaseJob``` abstract class which can be registered with the existing scheduler to make it use ```CustomJob``` instead of ```Job```.

**Additional context**
The reason I have to extend table is that I want to store some extra columns specific to business.

**Comment by agronholm** [comment]
APScheduler 4.0 will support metadata for schedules and jobs (which are a separate concept there). Can you elaborate on your requirements? I'm inclined to support custom data in schedules (and jobs) though not as top level items.

**Comment by w-Bro** [comment]
i have a same situation now, and i am trying to rewrite SQLAlchemyJobStore. It seems that this feature will be supported on v4.0, any plan for publish v4.0 recently?

**Comment by agronholm** [comment]
With f36a398c, I think I can close this, as that change should cover this use case. If you still need explicit columns, just override the `get_table_definitions()` method on `SQLAlchemyDataStore`.

**Comment by mahdihaghverdi** [comment]
Hi @alegend4u 
I have done this and it works:
```python
class Base(DeclarativeBase):
    __abstract__ = True
    id: Mapped[str] = mapped_column(primary_key=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        server_default=None,
    )

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__!r}({self.id!r})>"


class Jobs(Base):
    __tablename__ = 'blablabla'
    name: Mapped[str | None] = mapped_column(default=None)
    last_name: Mapped[str | None] = mapped_column(default=None)
    next_run_time = Column("next_run_time", Float(25), index=True)
    job_state = Column("job_state", LargeBinary, nullable=False)


class ExtendedSQLAlchemyJobStore(SQLAlchemyJobStore):
    def __init__(
        self,
        url=None,
        engine=None,
        tablename="apscheduler_jobs",
        metadata=None,
        pickle_protocol=pickle.HIGHEST_PROTOCOL,
        tableschema=None,
        engine_options=None,
    ):
        super(BaseJobStore).__init__()
        self.pickle_protocol = pickle_protocol
        metadata = maybe_ref(metadata) or MetaData()

        if engine:
            self.engine = maybe_ref(engine)
        elif url:
            self.engine = create_engine(url, **(engine_options or {}), echo=True)
        else:
            raise ValueError('Need either "engine" or "url" defined')

        self.jobs_t = Jobs.__table__
```
sqlite `.schema`:
```
sqlite> .schema
CREATE TABLE blablabla (
        name VARCHAR, 
        last_name VARCHAR, 
        next_run_time FLOAT, 
        job_state BLOB NOT NULL, 
        id VARCHAR NOT NULL, 
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, 
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, 
        deleted_at DATETIME, 
        PRIMARY KEY (id)
);
CREATE INDEX ix_blablabla_next_run_time ON blablabla (next_run_time);
sqlite> 

```

**Comment by agronholm** [comment]
There's the `metadata` attribute which supports any JSON compatible types, just so you know. No need to subclass a data store if that attribute fits your use case.

**Comment by mahdihaghverdi** [comment]
try this
```python
class Base(DeclarativeBase):
    pass

class Job(Base):
    __tablename__ = "jobs"
    name: Mapped[str]

SQLAlchemyJobStore(tablename="jobs", metadata=Base.metadata # or Job.metadata
)
```

and you get an error from sqlalchemy which says, metadata already exists and you should pass `extend_existing=True` to `Table` which we cannot.

**Comment by agronholm** [comment]
You misunderstand. I'm talking about the `metadata` attribute on [tasks](https://github.com/agronholm/apscheduler/blob/master/src/apscheduler/_structures.py#L70), [schedules](https://github.com/agronholm/apscheduler/blob/master/src/apscheduler/_structures.py#L191) and [jobs](https://github.com/agronholm/apscheduler/blob/master/src/apscheduler/_structures.py#L316), supported across all data stores.

**Comment by mahdihaghverdi** [comment]
Can you please (if you have time) show some examples with code for the problem we are facing? (problem: I want a custom table for `SQLALchemyJobStore` to use and populate)

**Comment by agronholm** [comment]
> Can you please (if you have time) show some examples with code for the problem we are facing? (problem: I want a custom table for `SQLALchemyJobStore` to use and populate)

I could try but you need to describe the use case in enough detail.

**Comment by mahdihaghverdi** [comment]
I want my jobs table look like this:
```python
from datetime import datetime
from typing import Any, TypeAlias
from uuid import UUID

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import JSON as PGJSON
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

PyJSON: TypeAlias = dict[str, Any]


class Base(DeclarativeBase):
    __abstract__ = True
    type_annotation_map = {PyJSON: PGJSON}

    id: Mapped[str] = mapped_column(primary_key=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        server_default=None,
    )

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__!r}({self.id!r})>"

class Jobs(Base):
    col1: Mapped[str]
    col2: Mapped[int]
    col3: Mapped[dict]
    next_run_time = Column("next_run_time", Float(25), index=True)
    job_state = Column("job_state", LargeBinary, nullable=False)
```

and only with [this way](https://github.com/agronholm/apscheduler/issues/508#issuecomment-2869066080) it is possible.

**Comment by agronholm** [comment]
You've already shown that code. I was asking about the use case. What are you trying to achieve with this?

**Comment by agronholm** [comment]
Yes, you've **repeatedly** told me that you want custom columns. And for the third time: what is the use case for them? What are you doing with those extra columns that could not be stored in another table?

**Comment by mahdihaghverdi** [comment]
Look at this:
```python
class Notification(Base):
    __tablename__ = 'notifs'
    title: Mapped[str]
```

I want to have the ID of the notif record in my jobs table so that I can `JOIN` them in SQL.

Something like this:
```python
class Jobs(Base):
    __tablename__ = 'jobs'
    notification_id: Mapped[UUID] = mapped_column(ForeignKey('notifications.id', ondelete="CASCADE", onupdate="CASCADE"))  # THIS
    next_run_time: Mapped[float] = mapped_column(Float(25), index=True)
    job_state: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)

```

**Comment by agronholm** [comment]
What is the notifications table used for, and how is it populated? Can the same notification have multiple connected jobs? Can it be connected to schedules or tasks too?

**Comment by mahdihaghverdi** [comment]
- Notifications table is used to store all the notifications of the app. There are two types of notifs, some of them are triggered immediately and some of the are scheduled.
- It is populated by the app for any notif to be sent. Then another part of the app is responsible for sending or scheduling the notifs. 
- No one notif only have one job connected.
- No it is bound to Jobs now
