### ISSUE TITLE
Assistance with creating a WTForm for all possible cron variations?

### ISSUE THREAD

**Issue by caffeinatedMike** [agronholm/apscheduler#510]
I'm trying to create a [WTForms](https://wtforms.readthedocs.io/en/2.3.x/) form for scheduling tasks based on the [`cron`](https://github.com/agronholm/apscheduler/tree/master/apscheduler/triggers/cron) trigger, but after reviewing all the possible options, especially with the added super-helpful [expression types](https://apscheduler.readthedocs.io/en/stable/modules/triggers/cron.html#expression-types), I'm struggling with coming up with an exhaustive list of every possible combo and am at a loss as to how best represent those options in a form.
1. Is there an exhaustive list of every logical combination of the cron parameters anywhere?
2. Could someone possibly assist in helping construct the necessary fields for a form that can be used to product valid cron values that can be passed to the `scheduler.add_job` function?

My use-case deals with a `Report` db model, in which I figure I'd have a single string field that could be used to store the crontab statement (somehow produced after scheduling a job via `scheduler.add_job`). Then when viewing the form again, the `report.schedule` field would be passed to `CronTrigger` (`CronTrigger.from_crontab(report.schedule)`) in order to get the various parts of the cron to populate the form with.

**Comment by agronholm** [comment]
I will not respond here because this issue tracker is for bug reports and feature requests only. Support questions go to the forums mentioned [here](https://apscheduler.readthedocs.io/en/stable/userguide.html#getting-help).
