### ISSUE TITLE
Lost connection to MySQL When using the DjangoJobStore

### ISSUE THREAD

**Issue by Tesla-lu** [agronholm/apscheduler#511]
**Describe the bug**
Lost connection to MySQL When using the DjangoJobStore,
but it worked when i don't call add_jobstore() function (I known the default jobstore class is MemoryJobStore)

**To Reproduce**
flow is part of my codes (which copy from runapscheduler.py part of  README.md):
scheduler = BlockingScheduler(timezone=settings.TIME_ZONE)
scheduler.add_jobstore(DjangoJobStore(), "default")

**Expected behavior**
the mysql connection is lost when i add a jobstore by  DjangoJobStore

**Additional context**
Error getting due jobs from job store 'default': (2013, 'Lost connection to MySQL server during query')

**Comment by agronholm** [comment]
This project does not have a `DjangoJobStore`. Please submit a ticket with the [django-apscheduler](https://github.com/jcass77/django-apscheduler) project.

**Comment by Tesla-lu** [comment]
...... sorry
