### ISSUE TITLE
Incorrect wait seconds calculated, when using Interval Scheduler.

### ISSUE THREAD

**Issue by Kartar-Dhiman** [agronholm/apscheduler#513]
**Describe the bug**
For any value grater than 49 days scheduler calculates the same seconds (4294967.000000 seconds) for next wakeup time. 

**To Reproduce**
Please run this script and observe the next wakeup time for the job.
I want to trigger the job in every 90 days but the time calculated for job is not exceeding 49 days( in seconds from logs).

`
import logging
from datetime import datetime, timedelta

from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.triggers.interval import IntervalTrigger

def collect_data():
    """
    Method to collect data.
    """
    print(str(datetime.now()) + "    In collect data ..")

def initiate_cron_service():
    """
    Configure and start the scheduler
    """
    print("Starting the scheduler...")
    scheduler = BlockingScheduler()
    scheduler.add_job(
        func=collect_data,
        trigger=IntervalTrigger(days=90, start_date=datetime.now() + timedelta(seconds=2)),
        replace_existing=True
    )
    # starting the scheduler
    scheduler.start()

if __name__ == "__main__":
    logging.basicConfig()
    logging.getLogger('apscheduler').setLevel(logging.DEBUG)
    initiate_cron_service()
`

**Expected behavior**
For every 90 days interval the scheduler should calculate the accurate time.
For Eg:
For **90** days the seconds should be **7776000**
but the scheduler is showing **4294967** seconds every time the value exceeds the **49 Days** duration.
@sumitkumarsoni

**Comment by agronholm** [comment]
Why do you think this is a bug? There is a limit placed due to Windows limitations. Waking up more often than necessary should not interfere with the operation of the scheduler.

**Comment by Kartar-Dhiman** [comment]
Got it @agronholm 
Thanks for replying fast.
