### ISSUE TITLE
job not running after  a time

### ISSUE THREAD

**Issue by fangqian** [agronholm/apscheduler#516]
source code:

```python3
async def _print_info(ins=None):
    while True:
        now_date = time.strftime("%Y-%m-%d %X")
        print(f"now: {now_date}", ins.state if ins else None)
        if ins:
            ins.print_jobs()
        print("redis==========")
        await asyncio.sleep(50)

class AIOScheduler(AsyncIOScheduler):
    def __new__(cls, *args, **kwargs):
        if not hasattr(cls, '_instance'):
            cls._instance = super(AIOScheduler, cls).__new__(cls, *args, **kwargs)

        return cls._instance

    def run(self):
        try:
            print("scheduler is running!")
            self.start()
            self.print_jobs()

            loop = asyncio.get_event_loop()
  
            loop.create_task(_print_info(self))
            loop.run_forever()
```

when start the func run, the func _print_info will print the jobs, but after  running  a time,
the line  " print(f"now: {now_date}", ins.state if ins else None)" still runing
but  ins.print_jobs() show that my jobs not exist. 
that's means my redis jobstore  something wrong after   running  a time?

but every time start, it work truly, just happen after running a time.

logs like below:
redis==========
scheduler is running!
Jobstore default:
    No scheduled jobs
Jobstore redis:
    approve_work_expire (trigger: cron[minute='*/1'], next run at: 2021-06-07 17:27:00 CST)
    seckill_order_expire (trigger: cron[minute='*/1'], next run at: 2021-06-07 17:27:00 CST)
    ....
now: 2021-06-07 17:26:09 1
redis==========
scheduler is running!
Jobstore default:
    No scheduled jobs
Jobstore redis:
    approve_work_expire (trigger: cron[minute='*/1'], next run at: 2021-06-07 17:27:00 CST)
    seckill_order_expire (trigger: cron[minute='*/1'], next run at: 2021-06-07 17:27:00 CST)
    ....
now:2021-06-07 17:26:59 1
...
now: ***
now: ***
now: ***

**Comment by fangqian** [comment]
logs:
now: 2021-06-07 18:08:51 1
Jobstore default:
    No scheduled jobs
Jobstore redis:
    approve_work_expire (trigger: cron[minute='*/1'], next run at: 2021-06-07 18:09:00 CST)
    seckill_order_expire (trigger: cron[minute='*/1'], next run at: 2021-06-07 18:09:00 CST)
    
redis==========
now: 2021-06-07 18:09:41 1
Jobstore default:
    No scheduled jobs
Jobstore redis:
    No scheduled jobs
redis==========
now: 2021-06-07 18:10:31 1
Jobstore default:
    No scheduled jobs
Jobstore redis:
    No scheduled jobs
redis==========

**Comment by agronholm** [comment]
Please include a reproducing script that I can also run to get the same results.

**Comment by fangqian** [comment]
I want to ask that: if  I delete the jobstore redis key, job in run forever will be dormant? and the new key(new job) will never restore?

**Comment by agronholm** [comment]
I don't understand what you mean by "job in run forever". If you delete the key of a job in a redis job store, the scheduler won't run that job (it's as if you used the scheduler to delete it).

**Comment by fangqian** [comment]
ok
