### ISSUE TITLE
BackgroundScheduler in python is running two instances instead of 1

### ISSUE THREAD

**Issue by psnehal** [agronholm/apscheduler#521]
0

I am using the background scheduler in python to run one job which does the anlaysis and then update the database . Below is the code for the same : So expected behavior is it will run one thread and wait for 15 seconds then run for the second instance. But this is running two instances together and then taking the break the of 59 second. Below is the output of the job I am running with timestamp

`scheduler.add_job(func=print_date_time, trigger="interval",seconds=59)

scheduler.start()

print(scheduler.get_jobs())`
``

`job started at  02:54:11

 in the beginning tweetid :  blank new tid is :  1090278987920740353
tid not in the database
job finished 

job started at  02:54:13
 in the beginning tweetid :  blank new tid is :  1090278987920740353
tid not in the database
job finished 

job started  02:55:10
 in the beginning tweetid :  blank new tid is :  1090278987920740353
tid not in the database
job finished 

job started  02:55:12
 in the beginning tweetid :  blank new tid is :  1090278987920740353
tid not in the database
job finished `*************************************************************************************************************************************
I am trying to implement this flask app of python. This is causing inserting the key in the database twice and I am getting the duplicate entry error.

**Comment by psHA5** [comment]
I'm trying a similar thing in Flask, and getting a duplicate job execution.

INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "send_email" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-11-26 10:04:02.725802+00:00 (in 120.000000 seconds)
INFO:werkzeug: * Restarting with stat
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "send_email" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-11-26 10:04:04.299018+00:00 (in 120.000000 seconds)
firing email - 10:04:02
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "send_email (trigger: interval[0:02:00], next run at: 2021-11-26 10:04:02 GMT)" (scheduled at 2021-11-26 10:04:02.725802+00:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-11-26 10:06:02.725802+00:00 (in 119.999833 seconds)
INFO:apscheduler.executors.default:Job "send_email (trigger: interval[0:02:00], next run at: 2021-11-26 10:06:02 GMT)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "send_email (trigger: interval[0:02:00], next run at: 2021-11-26 10:04:04 GMT)" (scheduled at 2021-11-26 10:04:04.299018+00:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-11-26 10:06:04.299018+00:00 (in 119.988630 seconds)
firing email - 10:04:04
INFO:apscheduler.executors.default:Job "send_email (trigger: interval[0:02:00], next run at: 2021-11-26 10:06:04 GMT)" executed successfully

**Comment by agronholm** [comment]
Are you sure you don't have two workers running the app? There is a [FAQ entry](https://apscheduler.readthedocs.io/en/3.x/faq.html#how-do-i-use-apscheduler-in-a-web-application) about running APScheduler in web apps. Have you read it?

**Comment by psHA5** [comment]
Thanks for helping out. I did read it, but kind of missed that.

What worked for me was switching debug from True to False in Flask, though you can switch off the reloader apparently:

if __name__ == '__main__':
    app.run(debug=False)

https://stackoverflow.com/questions/27149386/issue-when-running-schedule-with-flask?rq=1

**Comment by agronholm** [comment]
Did you have a similar issue @psnehal ?

**Comment by corenuts007** [comment]
> Thanks for helping out. I did read it, but kind of missed that.
> 
> What worked for me was switching debug from True to False in Flask, though you can switch off the reloader apparently:
> 
> if **name** == '**main**': app.run(debug=False)
> 
> https://stackoverflow.com/questions/27149386/issue-when-running-schedule-with-flask?rq=1

Thank you very much for solution

**Comment by agronholm** [comment]
Seems like this was resolved back in the day.

**Comment by Frpratik** [comment]
I'm getting the same problem in django could you please help me
