### ISSUE TITLE
TypeError: can't pickle _queue.SimpleQueue objects

### ISSUE THREAD

**Issue by rushkii** [agronholm/apscheduler#522]
**Describe the bug**
```
can't pickle _queue.SimpleQueue objects

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "run.py", line 69, in reminder_command
    job = sched.add_job(bot.send_message, 'date', run_date=res['string'], args=[user.id, opt[0]], replace_existing=True)
  File "/app/.heroku/python/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 448, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "/app/.heroku/python/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 872, in _real_add_job
    store.add_job(job)
  File "/app/.heroku/python/lib/python3.7/site-packages/apscheduler/jobstores/mongodb.py", line 89, in add_job
    'job_state': Binary(pickle.dumps(job.__getstate__(), self.pickle_protocol))
  TypeError: can't pickle _queue.SimpleQueue objects
```
**To Reproduce**
```
from pyrogram import Client, idle, filters
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.jobstores.mongodb import MongoDBJobStore
from apscheduler.executors.pool import ThreadPoolExecutor, ProcessPoolExecutor

#https://my.telegram.org/apps
bot = Client("Session", api_id=api_id, api_hash="api_hash", bot_token="bot:token")
client = pymongo.MongoClient("mongodb+srv://a:a@host.mongodb.net/?retryWrites=true&w=majority")
jobstores = {
  'default': MongoDBJobStore(database='reminder', client=client)
}
executors = {
    'default': ThreadPoolExecutor(20),
    'processpool': ProcessPoolExecutor(5)
}
sched = AsyncIOScheduler(jobstores=jobstores, executors=executors)
sched.start()

@bot.on_message(filters.command(['remind', 'remind@NekohaReminderbot']) & (filters.private | filters.group))
async def reminder_command(_, msg):
    job = sched.add_job(bot.send_message, 'date', run_date=str(datetime.now()+dtime.timedelta(minutes=10)), args=[msg.from_user.id, "Test reminder"], replace_existing=True)
    await msg.reply(f"Job has been stored with ID {job.id}")

if __name__ == '__main__':
    bot.start()
    idle()
    bot.stop()
```

**Expected behavior**
Should be stored to MongoDB, but it return an error.

**Comment by agronholm** [comment]
APScheduler needs to pickle objects stored along the job and it cannot make unpickleable objects pickleable. What do you expect from me here?

**Comment by rushkii** [comment]
> 
> 
> APScheduler needs to pickle objects stored along the job and it cannot make unpickleable objects pickleable. What do you expect from me here?

It means the `bot.send_message` object can't be stored? or I must pickle it first? Sorry, I have no idea what to do.
I've tested it on my local without jobstore and it works fine. But, when it using mongodb jobstore it return error.

**Comment by agronholm** [comment]
> It means the bot.send_message object can't be stored?

No, because it's a bound method which means the entire `pyrogram.Client` object needs to be serialized (pickled) to be sent to the mongodb server. The reason it works in a local job store is because no serialization is necessary since the object stays in memory.

**Comment by rushkii** [comment]
> 
> 
> > It means the bot.send_message object can't be stored?
> 
> No, because it's a bound method which means the entire `pyrogram.Client` object needs to be serialized (pickled) to be sent to the mongodb server. The reason it works in a local job store is because no serialization is necessary since the object stays in memory.

```
async def remind_me(user_id, text):
  await bot.send_message(user_id, text)

@bot.on_message(filters.command(['remind', 'remind@NekohaReminderbot']) & (filters.private | filters.group))
async def reminder_command(_, msg):
    job = sched.add_job(remind_me, 'date', run_date=res['string'], args=[user.id, opt[0]], replace_existing=True)
```

I put this in a global but, it show an error.
```
/app/.heroku/python/lib/python3.7/site-packages/apscheduler/executors/base.py:71: RuntimeWarning: coroutine 'remind_me' was never awaited
```
Is pickle doesn't support asyncio or am I wrong to do it? Any idea to solve this? thanks

**Comment by rushkii** [comment]
Uhh, It solved now. I searched all issue in this repo.

executors problem: https://github.com/agronholm/apscheduler/issues/490#issuecomment-779780317
misfire_grace_time: https://github.com/agronholm/apscheduler/issues/146#issuecomment-222475540

Thanks for that, I appreciate it.
