### ISSUE TITLE
The flask-apscheduler task is missing

### ISSUE THREAD

**Issue by SongweiCao** [agronholm/apscheduler#523]
Use flask-apscheduler to create a timing task. The database for storing the timing task is redis. If the timing task runs for a period of time, the ID of the timing task will be automatically deleted, which leads to the failure of the timing task. How to solve this problem?

**Comment by agronholm** [comment]
StackOverflow is the appropriate venue for asking questions. Besides, you have ignored the issue template so I will not answer this question here.
