### ISSUE TITLE
How to properly crash

### ISSUE THREAD

**Issue by GuillaumeLachaud** [agronholm/apscheduler#524]
**What**
I am using a BlockingScheduler and would like to kill the whole python process when any jobs raises a specific exception

**Why**
The usecase is the following. At some point, our process can mess up with one of the shared SQL connection pool we have. When this happens, all subsequent jobs runs will fail until we restart the container in which this runs. The best course of action for us would be to let the process crash when this exception is raised and let Docker take care of restarting a fresh process.
But it looks like every exception in jobs are caught by BlockingScheduler. 

Is adding a listener on `EVENT_JOB_ERROR` a good way to do this. Can I properly raise an exception in the listener? It seems to be caught in there as well.

**Comment by agronholm** [comment]
This issue tracker is not the proper venue to ask questions. They are listed in the [documentation](https://apscheduler.readthedocs.io/en/stable/userguide.html#getting-help).
