### ISSUE TITLE
Memory Leak when future time is set

### ISSUE THREAD

**Issue by AdityaVarmaG** [agronholm/apscheduler#526]
**Description**
When the system time is updated to future time (for ex 10 yrs), there is sudden rise in resources and the system hangs in no time. Running it on python 3.6 (CentOS-Raspberry PI).

**To Reproduce**
Run the below script. While it is running, update the system time from terminal to future time (ex. 12-Jul-2031).

def timedisplay():
	print("Current Time =", time.time())

sch = BackgroundScheduler()
sch.start()
sch.add_job(timedisplay, 'interval', seconds=1, id='timedisplay_id')

while True:
	# to keep scheduler active
	time.sleep(1)

**Expected behavior**
Scheduler needs to adjust its next trigger to the future time.

**Additional context**
Tried to reschedule the job by getting current ID. But, due to system hang, nothing is working from the failure point.

**Comment by agronholm** [comment]
Consider the case where a scheduler is restarted after a long time of being shut down, say, 1 hour? That means it has missed 3600 executions of the job. Now it has to calculate all the execution periods that it has missed. This is going to take a lot of time.

The scheduler relies on a functioning system clock. How would you have me change its behavior?

**Comment by agronholm** [comment]
Also, what could be the use case where you need to set the system clock 10 years forward?

**Comment by AdityaVarmaG** [comment]
Actually, the system time is wrongly reported from GPS with 10yrs ahead time. So, before we realize and set the time back to current time, the system is getting hanged. 

Could you suggest any alternative to avoid this? We tried to reschedule all the jobs with no luck.

**Comment by agronholm** [comment]
Does it hang even after a restart (assuming the clock is correct now)?

**Comment by AdityaVarmaG** [comment]
On restart of application, it is working fine. But, we were not able to shutdown/ reschedule the apscheduler. I made the below change (added 1ms sleep) as a temporary solution to avoid system crash. But, even after this change, somehow the handler is not returning back, so that I can reschedule the jobs.
 
![image](https://user-images.githubusercontent.com/22930397/125290237-b854af80-e33d-11eb-8ed3-27730b61def9.png)

**Comment by agronholm** [comment]
Considering that it has to calculate 315360000 run times, I am not surprised.

**Comment by agronholm** [comment]
Is the issue clear or do you still need help?

**Comment by AdityaVarmaG** [comment]
The issue is solved. You can close it.
