### ISSUE TITLE
how to kill a job that takes too much time

### ISSUE THREAD

**Issue by fengges** [agronholm/apscheduler#528]
I set max_ Instances is  1, but the job is stuck because of unknown error。

The next job can't be executed because of the error. How to solve this problem.

**Comment by agronholm** [comment]
Please do not ignore the issue tracker template. Ask questions using one of the [proper venues](https://apscheduler.readthedocs.io/en/stable/userguide.html#getting-help). I will summarily dismiss any questions submitted as issues here.
