### ISSUE TITLE
apscheduler 3.6.1 and tzlocal 3.x TypeError

### ISSUE THREAD

**Issue by ngtvspc** [agronholm/apscheduler#536]
**Describe the bug**
Version 3.6.1 of [apscheduler](https://github.com/agronholm/apscheduler/releases/tag/v3.6.1) has a dependency on [tzlocal](https://github.com/agronholm/apscheduler/blob/1428971e178f861a5d104e9cbf8ce936384089bc/setup.py#L44) that has shifted upwards as of today and [this release ](https://pypi.org/project/tzlocal/) of tzlocal. This is causing a bug when using the APIs of BackgroundScheduler and ThreadPoolExecutor

**To Reproduce**
Using version 3.6.1 of apscheduler that I installed via `git clone` and `pip install -e` within a virtualenv
```
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from apscheduler.schedulers.background import BackgroundScheduler
>>> from apscheduler.executors.pool import ThreadPoolExecutor
>>> BackgroundScheduler(executors={'default': ThreadPoolExecutor(2)})
<apscheduler.schedulers.background.BackgroundScheduler object at 0x7f7d313e7e50>
>>> a = BackgroundScheduler(executors={'default': ThreadPoolExecutor(2)})
>>> a.add_job(lambda x: print('asdf'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shawn/Documents/apsched/apscheduler/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/home/shawn/Documents/apsched/apscheduler/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/home/shawn/Documents/apsched/apscheduler/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/home/shawn/Documents/apsched/apscheduler/apscheduler/triggers/date.py", line 20, in __init__
    timezone = astimezone(timezone) or get_localzone()
  File "/home/shawn/Documents/apsched/apscheduler/apscheduler/util.py", line 84, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
```

**Expected behavior**
I think for this version tzlocal just needs to be pinned, but I haven't investigated the real cause of this issue. Perhaps a breaking change in tzlocal for this major version?

**Additional context**
I ran the tox tests on `master` and those seem to pass fine, so it seems like it's only an error for version 3.6.1

**Comment by justinvanwinkle** [comment]
I ran into this too, it seems like it would be a good idea to extend apscheduler to support zoneinfo objects since those are now in the standard library in 3.9.

**Comment by agronholm** [comment]
This has already been done in master for v4.0. Integrating this into the 3.x branch would require a major effort due to the differing semantics. As a quick fix I'll limit the tzlocal version to `< 3` there.

**Comment by agronholm** [comment]
Wait a minute. The 3.x already specified `tzlocal ~= 2.0` as an install requirement so it shouldn't be a problem. Exactly how did you run into trouble with this?

**Comment by agronholm** [comment]
If you're using an older version of APScheduler, it doesn't have the proper pinning for tzlocal, so please upgrade.

**Comment by iamwm** [comment]
We're using version 3.5.1 and encountering the same problem in the production environment. I wonder if this will be risky to upgrade from 3.5.1 to 3.7.0? 
Thank you for your time !

**Comment by agronholm** [comment]
There are no breaking changes, but please do run your test suite again with 3.7.0 before deploying to production.

**Comment by agronholm** [comment]
Also, **always** pin your dependencies to exact versions. This kind of problem should only occur when you try to update your project dependencies. There are several tools to this end, including poetry and pip (`pip freeze` + `pip install -c ...`).

**Comment by ngtvspc** [comment]
@agronholm as for how we're hitting this issue, we're using 3.6.1 specifically which does not specify `tzlocal ~=2.0` it instead `tzlocal >= 1.2`

We'll look at upgrading, thanks
