### ISSUE TITLE
Add func parameter in `remove_job`

### ISSUE THREAD

**Issue by r-priyam** [agronholm/apscheduler#541]
**Describe the solution you'd like**
Currently:
```python
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger

scheduler = AsyncIOScheduler()

async def foo():
    ...

scheduler.add_job(foo, id="abc", CronTrigger(minute="10"))
scheduler.remove_job("abc")  # will remove the job with the id "abc"
```
Enhancement:
```python
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger

scheduler = AsyncIOScheduler()

async def foo():
    ...

scheduler.add_job(foo, id="abc", CronTrigger(minute="10"))
scheduler.remove_job(foo)  # will remove the job with the func foo
```

**Comment by agronholm** [comment]
If somebody has added multiple jobs with `foo()`, should they all be removed?

**Comment by priyamroy** [comment]
> If somebody has added multiple jobs with `foo()`, should they all be removed?

`Inside foo()?` Yes
`Multiple functions with the name foo?`
Don't know if someone would like to have same function name in same file...it's kinda like breaking python laws

**Comment by samh194** [comment]
> > If somebody has added multiple jobs with `foo()`, should they all be removed?
> 
> `Inside foo()?` Yes
> `Multiple functions with the name foo?`
> Don't know if someone would like to have same function name in same file...it's kinda like breaking python laws

I think what @agronholm is referring to, is that you can have multiple schedules of the same function with different parameters. By removing a job using only the function parameter, this would need to remove all instances of the schedule using that function, which is probably undesirable behaviour.

**Comment by priyamroy** [comment]
> > > If somebody has added multiple jobs with `foo()`, should they all be removed?
> > 
> > 
> > `Inside foo()?` Yes
> > `Multiple functions with the name foo?`
> > Don't know if someone would like to have same function name in same file...it's kinda like breaking python laws
> 
> I think what @agronholm is referring to, is that you can have multiple schedules of the same function with different parameters. By removing a job using only the function parameter, this would need to remove all instances of the schedule using that function, which is probably undesirable behaviour.

Owh hmm. I haven't seen any use cases of it roughly but can be in some rare cases. In our team none uses that in that way and all functions are used for registering one event only.

Quite unsure that why someone will use it in that way as `CronTrigger` is very flexible and can schedule any job easily.

> If a user is removing one job then it can also have a possibility that they won't need other job too.

> If any user have multiple jobs register for one function then they will have to remove all from the Id's and hence using a function removal can be easy here.

**Comment by agronholm** [comment]
Other user have different needs. Some software allow multiple users to add schedules dynamically, so the same function could be scheduled by multiple users separately.
