### ISSUE TITLE
ImportError: cannot import name 'AsyncScheduler' from 'apscheduler.schedulers'

### ISSUE THREAD

**Issue by moshe-coh** [agronholm/apscheduler#545]
I'm trying to install the module on my server and I get the error ImportError: cannot import name 'AsyncScheduler' from 'apscheduler.schedulers'

I tried to print(dir(apscheduler)) and this is the result:

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'release', 'version', ' version_info ']

Why is the module not fully installed?

**Comment by agronholm** [comment]
What part of the documentation led you to believe you should do such an import?

**Comment by moshe-coh** [comment]
Sorry. I apologize it was my mistake to read something old on another site.

Although I had another error and it was also resolved:
https://github.com/agronholm/apscheduler/issues/461
By installing the directory tzlocal ~ = 2.0 instead of 3.0
Thank you so much for the amazing library!

**Comment by agronholm** [comment]
> Sorry. I apologize it was my mistake to read something old on another site.

Not likely, since `AsyncScheduler` only exists in the upcoming 4.0 version. Perhaps you found your way to the `master` branch documentation?

> Thank you so much for the amazing library!

Thanks, and you're welcome! :smile:
