### ISSUE TITLE
How to make apscheduler shutdown after all the jobs are finished.

### ISSUE THREAD

**Issue by sea72** [agronholm/apscheduler#548]
I want to use apscheduler to do limited jobs and shutdown.
I tried the blocking scheduler which never exit.
And background which shutdown before jobs finished

> scheduler = BlockingScheduler()  
>scheduler.add_job(job, 'cron', hour = '9-11', minute = '*/5', end_date =  "2021-09-16 11:35:00", timezone = tz)   
>scheduler.start()  
>scheduler.shutdown()

**Comment by agronholm** [comment]
There are a [number of venues](https://apscheduler.readthedocs.io/en/3.x/userguide.html#getting-help) to get assistance but the bug tracker is not one of them.
