### ISSUE TITLE
"interval" trigger supports "months" and "years‘’ option

### ISSUE THREAD

**Issue by coolsnake** [agronholm/apscheduler#549]
In some case, we have an scheduler in which a task may be executed every two months or two years. 
The current implementation does not support this kind of setting.  
It should be much better to support "weeks" or "years" option.

**Comment by agronholm** [comment]
Already implemented for APScheduler 4: https://github.com/agronholm/apscheduler/blob/master/src/apscheduler/triggers/calendarinterval.py
