### ISSUE TITLE
Cannot get jobs before scheduler is started

### ISSUE THREAD

**Issue by radiantone** [agronholm/apscheduler#558]
**Describe the bug**
Cannot get jobs before scheduler is started

**To Reproduce**
call scheduler.get_jobs(jobstore='xxx')

**Expected behavior**
Whether or not a scheduler is running does not affect the jobs in the jobstore. In order to avoid adding duplicate jobs I need to know what jobs are already scheduled. In order to do that, I have to consult the scheduler which confers with the jobstore. This should be possible regardless whether the scheduler has been started.

**Additional context**
version 3.7

**Comment by agronholm** [comment]
Do you mean you never want to replace the jobs that already exist, even if your updated code contains new parameters like an updated trigger?

What you can also do is start the scheduler in paused mode, so you have direct access to the job store. Then trying to add a job with an existing ID will raise `ConflictingIdError`.
