### ISSUE TITLE
Scheduler allows adding duplicate jobs

### ISSUE THREAD

**Issue by radiantone** [agronholm/apscheduler#559]
**Describe the bug**
Scheduler allows adding duplicate jobs

**To Reproduce**
Start a scheduler with a jobstore that has an existing job with id='ABC'. Then add a new job "add_job" with the same id. 
The scheduler does not fail gracefully and seems to contain the duplicate job in memory.

**Expected behavior**
scheduler.add_job() should simply throw an exception about the duplicate job id and continue gracefully with scheduled jobs.

**Additional context**
version 3.7

**Comment by kartikeyrajvaidya** [comment]
How `add_job()` function works internally in apscheduler.

- The `add_job` function internally calls the `_real_add_job` method.
- `_real_add_job` function internally calls the `add_job` method of the Store.
- The `store.add_job()` Adds the given job to this store or raises `ConflictingIdError:` if there is another job in this store with the same ID.
- The caller of the `store.add_job()` i.e `_real_add_job` handles this error and updates the existing job.

This is an ideal behaviour, create the job if it doesn't exist else update the existing job.

But you can fix your problem in two ways:
1] Fetch the job before creating a new job if a job with the same Id exists, ignore else create.
2] Override the `_real_add_job` function and remove the part which handles the `ConflictingIdError` and handle it from where you are calling `add_job()`

**Comment by Abyssknight** [comment]
> How `add_job()` function works internally in apscheduler.
> 
>     * The `add_job()` function internally calls the `_real_add_job()` method.
> 
>     * `_real_add_job()` function internally calls the `add_job()` method of the Store.
> 
>     * The `store.add_job()` Adds the given job to this store or raises `ConflictingIdError:` if there is another job in this store with the same ID.
> 
>     * The caller of the `store.add_job()` i.e `_real_add_job()` handles this error and updates the existing job.
> 
> 
> This is an ideal behavior, create the job if it doesn't exist else update the existing job.
> 
> But you can fix your problem in two ways: 1] Fetch the job before creating a new job if a job with the same Id exists, ignore else create. 2] Override the `_real_add_job()` function and remove the part which handles the `ConflictingIdError` and handle it from where you are calling `add_job()`

I'm confused, the doc said:

> If you schedule jobs in a persistent job store during your application’s initialization, you MUST define an explicit ID for the job and use replace_existing=True or you will get a new copy of the job every time your application restarts!

But if the original job was replaced, how can i make the original job run continuely

**Comment by agronholm** [comment]
The updated design in v4.0.0a1 has made this a non-issue.

**Comment by LuisFelix** [comment]
For others running to a similar issue, resolved my problem by adding the following parameter when running my server: 
`python manage.py runserver --noreload`
