### ISSUE TITLE
BackgroundScheduler with shutdown(wait=False) doesn't exit

### ISSUE THREAD

**Issue by robertoramsis** [agronholm/apscheduler#567]
**Describe the bug**
Using python v3.6.6, apscheduler v3.6.3 BackgroundScheduler and persistent storage.

Trying to shutdown the BackgroundScheduler without waiting for the running jobs to complete. Added "wait=False" but main() doesn't exit.

Slightly modified the documentation [example](https://github.com/agronholm/apscheduler/blob/3.x/examples/schedulers/background.py ) as below and it shows a similar behavior:

**To Reproduce**
```python
from datetime import datetime
import time
import os
import logging
from apscheduler.schedulers.background import BackgroundScheduler

def tick():
    print('Tick! The time is: %s' % datetime.now())
    time.sleep(1000)

if __name__ == '__main__':
    scheduler = BackgroundScheduler()
    scheduler.add_job(tick, 'interval', seconds=3)
    logging.basicConfig()
    logging.getLogger('apscheduler').setLevel(logging.DEBUG)
    scheduler.start()
    print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))

    try:
        # This is here to simulate application activity (which keeps the main thread alive).
        while True:
            time.sleep(2)
    except (KeyboardInterrupt, SystemExit):
        # Not strictly necessary if daemonic mode is enabled but should be done if possible
        scheduler.shutdown(wait=False)
    print("END.", flush=True)  
```

**Expected behavior**
BackgroundScheduler to not hold main() after shutdown(wait=False) and exit immediately.

Original StackOverflow [LINK](https://stackoverflow.com/questions/69352255/how-to-use-backgroundscheduler-with-shutdownwait-false-to-exit) discussing this issue with Alex Grönholm.

Encountered same behavior with more recent versions apscheduler v3.8.0 and python v3.8.10

**Comment by agronholm** [comment]
Closing, as `ThreadPoolExecutor` cannot be shut down forcefully (the interpreter can get to an inconsistent state if you try).
