### ISSUE TITLE
RuntimeWarning Error

### ISSUE THREAD

**Issue by ElissonRodrigues** [agronholm/apscheduler#568]
I would like to report this little error:

python3.10/site-packages/apscheduler/executors/base.py:71: RuntimeWarning: coroutine 'ping_server' was never awaited

**Comment by agronholm** [comment]
Sounds like you scheduled a coroutine function without using AsyncIOScheduler, am I right?

**Comment by ElissonRodrigues** [comment]
Yes you are right. This code that occurred this error is from someone else, I'm making bug fixes. thanks.
