### ISSUE TITLE
Use another augmented assignment statement

### ISSUE THREAD

**Issue by elfring** [agronholm/apscheduler#571]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/src/apscheduler/triggers/interval.py b/src/apscheduler/triggers/interval.py
index 8b3d0bc..1b11095 100644
--- a/src/apscheduler/triggers/interval.py
+++ b/src/apscheduler/triggers/interval.py
@@ -56,7 +56,7 @@ class IntervalTrigger(Trigger):
         if self._last_fire_time is None:
             self._last_fire_time = self.start_time
         else:
-            self._last_fire_time = self._last_fire_time + self._interval
+            self._last_fire_time += self._interval
 
         if self.end_time is None or self._last_fire_time <= self.end_time:
             return self._last_fire_time
```

**Comment by agronholm** [comment]
This must've been an artifact of previous code refactorings.

**Comment by elfring** [comment]
Thanks for [the integration of a tiny source code improvement](https://github.com/agronholm/apscheduler/commit/a9b8d6caa1db4afd29b769e52da7ddd937726c84 "Used an augmented assignment statement").
