### ISSUE TITLE
How to connect to redis cluster in RedisJobStore

### ISSUE THREAD

**Issue by singhkirtii** [agronholm/apscheduler#582]
Hi, I am using ApSchedular for running cron jobs in my system and using the redis job store for the same.
I have redis cluster configured in the system so the connection needs to be made with the same.
I am using below format to connect to Redis.

from apscheduler.jobstores.redis import RedisJobStore

redis_job_store = RedisJobStore(jobs_key=JOBS_KEY, run_times_key=RUN_TIMES, host=REDIS_CLUSTER_HOST, port=REDIS_PORT, password=REDIS_PASSWORD)

Is there some other parameter to be added in above connection string in order to connect with Redis cluster?

**Comment by agronholm** [comment]
How did you manage to open an issue that is neither a bug report or a feature request? The templates explicitly disallow any other kinds of issues to be reported.

**Comment by Bibo-Joshi** [comment]
https://github.com/agronholm/apscheduler/issues/new is still reachable - see https://github.com/github/feedback/discussions/4951 :)

**Comment by agronholm** [comment]
This has been addressed in master by allowing one to supply their own Redis client so you can just pass a clustered Redis client. If that doesn't work, let me know and I will reopen the issue.
