### ISSUE TITLE
`AsyncIOExecutor` and class-based job callbacks

### ISSUE THREAD

**Issue by Bibo-Joshi** [agronholm/apscheduler#583]
**Is your feature request related to a problem? Please describe.**
I have a class along the lines

```python
class MyTask:
    ...

    (async) def __call__(self, *args, **kwargs):
        ....
```
and use this as job callback via `scheduler.add_job(MyTask(), **job_kwargs)`. This works fine on 3.x with `BackgroundScheduler`. However, when using `AsyncIOScheduler`, when the job runs, `asyncio` will issue a warning about `MyTask.__call__` not having been awaited.

This is due to `util.iscoroutinefunction` returning `False` for `MyTask()` in `AsyncIOExecutor._do_submit_job`:

https://github.com/agronholm/apscheduler/blob/4ded0dceb05acc95b8ef14cfe397e91391a5d39a/apscheduler/executors/asyncio.py#L48-L56

**Describe the solution you'd like**

Add support for passing callable non-function-objects as callbacks to `AsyncIOScheduler` by modifying  `util.iscoroutinefunction` to something like

```python
def iscoroutinefunction_partial(f):
    while isinstance(f, partial):
        f = f.func

    return iscoroutinefunction(f) or (hasattr(f, '__call__') and iscoroutinefunction(f.__call__))
```

This does the trick.

**Describe alternatives you've considered**
TBH, I don't see any alternative solutions for this in terms of what APS could do. Ofc an alterantive would be for me to re-design my scheduling. That's probably feasible and not too hard. But this use case seemed reasonable enough for me to open an issue 🙃 

**Additional context**
_If_ there is a chance for another 3.x release and you would be okay with including this, I'm happy to try & PR with the solution proposed above.
I'm aware that development is currently headed for v4. I haven't tried finding out if this is an issue on v4 as well or how it could be supported. If you agree with adding support for is in general, I can try to investigate v4 in this regard.

**Comment by agronholm** [comment]
This should work out of the box on APScheduler 4 (master). Currently the scheduler is not quite operational in practice, however, but this is something I intend to work on during my upcoming holidays in two weeks. I've been severely sidetracked by my other projects but that work is rapidly approaching the finish line.

**Comment by agronholm** [comment]
Oh, and if it _doesn't_ work on master, I think it should. Feel free to experiment and see if you can get it scheduled. Documentation for v4 does not exist yet so you'll have to look at the test suite for clues.

**Comment by Bibo-Joshi** [comment]
Thanks for the quick reply! 

> Oh, and if it *doesn't* work on master, I think it should.

Nice 👍 will try to have a look soonishly :)

**Comment by Bibo-Joshi** [comment]
Hi. Finally got around to try on master (https://github.com/agronholm/apscheduler/commit/a9b8d6caa1db4afd29b769e52da7ddd937726c84). Based on [this example](https://github.com/agronholm/apscheduler/blob/a9b8d6caa1db4afd29b769e52da7ddd937726c84/examples/schedulers/async_.py), I cooked up the following:

```python
import asyncio
import logging

import anyio
from apscheduler.schedulers.async_ import AsyncScheduler
from apscheduler.triggers.interval import IntervalTrigger
from apscheduler.workers.async_ import AsyncWorker


class SayHello:
    async def __call__(self):
        print('Hello!')


async def main():
    async with AsyncScheduler() as scheduler, AsyncWorker(scheduler.data_store):
        await scheduler.add_schedule(SayHello(), IntervalTrigger(seconds=1))
        # await scheduler.wait_until_stopped()
        # wait_until_stopped is apparently not yet implemented, so naively sleeping for now
        await asyncio.sleep(10)

logging.basicConfig(level=logging.DEBUG)
try:
    anyio.run(main)
except (KeyboardInterrupt, SystemExit):
    pass
```

However, currently `marshalling.callable_to_ref` can't handle this correctly. More precisely, this exception is triggered:

https://github.com/agronholm/apscheduler/blob/56afe91d5dc338db3440b2e9ecdea3e522dba30f/src/apscheduler/marshalling.py#L88-L89

After inserting

```python
    if hasattr(func, '__call__'):
        func = func.__call__
```
at the very start of `marshalling.callable_to_ref`, the example runs as expected but ofc `callable_from_ref` can't correctly rebuild the `SayHello` object from `'__main__:SayHello.__call__'`. I haven't yet tried to figure out what exactly `callable_from/to_ref` are used for and how serialization works on v4 …

**Comment by agronholm** [comment]
I think it would be reasonable to assume that this should work. I will add a test to ensure that it does.

**Comment by EveryTian** [comment]
Is there any follow-up on this issue?

**Comment by agronholm** [comment]
Properly supporting many types of callables in the scheduler is among the items I'm working on for v4.0.0a2, so this should be resolved in the near term.

**Comment by agronholm** [comment]
I successfully ran this with the latest `master`:
```py
import asyncio

from apscheduler import AsyncScheduler


class SayHello:
    async def __call__(self):
        print('Hello!')


async def main():
    async with AsyncScheduler() as scheduler:
        await scheduler.configure_task("hello", func=SayHello())
        await scheduler.add_job("hello")
        await scheduler.run_until_stopped()

asyncio.run(main())
```
