### ISSUE TITLE
Timezone bug with pytz 4.1 and asyncio scheduler

### ISSUE THREAD

**Issue by dmanser92** [agronholm/apscheduler#599]
**Describe the bug**
When initializing an asyncio scheduler inside of a FastAPI project I get TypeErrors concerning the pytz timezones:
```
/usr/local/lib/python3.10/site-packages/tzlocal/unix.py:177: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 425, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 926, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 911, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/local/lib/python3.10/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/local/lib/python3.10/site-packages/apscheduler/util.py", line 94, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
```
Here's the link to the StackOverflow thread where I first documented this issue: https://stackoverflow.com/a/71204250/4827923
I've tried all combinations with apscheduler 3.8.1/3.9.0 and tzlocal 4.0 /4.1, same error always. I am forced to use tzlocal 2.1, with this version it works without issues.

**To Reproduce**
1. Create a Dockerfile with this content:
```
FROM python:3.10.2-alpine3.15
RUN pip install apscheduler==3.8.1 tzlocal==4.1
```
2. Build the image: `docker build -t testingapsch:latest ./test`
3. Execute a command that initializes an asyncio scheduler and adds a job: `docker run -it testingapsch:latest python3 -c "import apscheduler.schedulers.asyncio; scheduler = apscheduler.schedulers.asyncio.AsyncIOScheduler(); scheduler.add_job(lambda: print("2"), 'interval', minutes=1);"`
4. Get the error message

**Expected behavior**
add_job method does not fail with tzlocal 4.1 as the issue is supposed to be solved according to the version history: https://apscheduler.readthedocs.io/en/3.x/versionhistory.html

**Comment by agronholm** [comment]
I've removed that check and will release v3.9.1 now. I would like to remind that non-pytz time zone support is still experimental and may fail, particularly with the cron trigger.

**Comment by dmanser92** [comment]
Wow that was fast, thanks!
