### ISSUE TITLE
global misfire_grace_time does not work

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#6]
Originally reported by: **Anonymous**

---

The default misfire_grace_time value for a job is set 1 in Job.**init**():

```
#!python
class Job(object):
    def __init__(self, trigger, func, args, kwargs, name=None,
                 misfire_grace_time=1, max_runs=None, max_concurrency=1):
```

So the following code in Schedule.add_job() does not work: 

```
#!python

class Scheduler(object):
    def add_job():
        ...
        job = Job(trigger, func, args or [], kwargs or {}, **options)
        if job.misfire_grace_time is None:
            job.misfire_grace_time = self.misfire_grace_time
        ...
```

---
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/6

**Comment by aivel** [comment]
the problem still occurs

**Comment by agronholm** [comment]
Please elaborate. "Does not work" is not a good description.

**Comment by aivel** [comment]
The parameter has no effect when passed to Scheduler.add_job, whereas seem to work fine if configured with configure()

**Comment by agronholm** [comment]
Please run the following script and tell me which value it prints: 3 (the scheduler default) or 4 (the per-job value):
```python
from apscheduler.schedulers.background import BackgroundScheduler

scheduler = BackgroundScheduler(misfire_grace_time=3)
scheduler.start()
job = scheduler.add_job(lambda: None, 'interval', seconds=60, misfire_grace_time=4)
print(job.misfire_grace_time)
```
