### ISSUE TITLE
ARRAY or JSONB type for tags on postgres

### ISSUE THREAD

**Issue by Reskov** [agronholm/apscheduler#617]
I am trying to add filtering by tags using the scheduler 4.0 version.

JSON type on Postgres does not support [contains operator](https://www.postgresql.org/docs/14/functions-json.html).
Thus, as a solution, I need to add extra cast to JSONB before search, and write something like
`self.t_schedules.c.tags.cast(JSONB).contains(tags)`

This is not a huge problem, by the way, but I want to keep my code tidy and avoid unnecessary casting.

So, can we use the `ARRAY` type for `tags` field instead of JSON, (alternatively JSONB) for Postgres

```python
    def get_table_definitions(self) -> MetaData:
        if self.engine.dialect.name == 'postgresql':
            ...
            tag_type = postgresql.ARRAY(String()) # or postgresql.JSONB
        else:
            tag_type = JSON
```

**Comment by agronholm** [comment]
I had the same exact idea but I'm not sure how to work with that when using other brands of RDBMS. Tags may not be an official thing in 4.0.0a1 but I will take this under advisement.
