### ISSUE TITLE
when the jobstores is mysql, the scheduled task does not work properly

### ISSUE THREAD

**Issue by goehls** [agronholm/apscheduler#623]
This issue tracker is **ONLY** for reporting bugs and requesting new features.

APScheduler          3.9.1

If you're not
reasonably sure that you've found a bug, please ask first (preferably on
[Gitter](https://gitter.im/apscheduler/Lobby))!

:warning: Any issues filed that ignore the template will be summarily closed!

**Describe the bug**
when the jobstores is mysql, the scheduled task does not work properly. The type of next_run_time is float, This will cause the calculation of next_run_time to be inaccurate（Loss of accuracy of next_run_time）. and the task does not work properly. when changing the type of next_run_time to double, the task can work.
**Expected behavior**
<img width="666" alt="image" src="https://user-images.githubusercontent.com/77818535/164743823-d132e223-6825-48ed-a35a-493eb2c23689.png">

**Comment by agronholm** [comment]
The only effect of that field is determining which order the jobs get picked up. You said "the task does not work properly" but failed to explain what that means. "Doesn't work" is not a proper bug report.

**Comment by goehls** [comment]
I insert a task to be executed every 3 seconds at the current time (timestamp=1650677467), the next_run_time of the corresponding record of apscheduler_jobs is 1650680060.

```python
  SQLALCHEMY_DATABASE_URL = 'mysql+pymysql://root:password@127.0.0.1:3306/qa_tools'
  jobstores = {
      'default': SQLAlchemyJobStore(url=SQLALCHEMY_DATABASE_URL,engine_options={'echo':True})  # SQLAlchemyJobStore指定存储链接
  }
  executors = {
      'default': ThreadPoolExecutor(5),
      'processpool': ProcessPoolExecutor(10)
  }
  job_defaults = {
      'coalesce': False,
      'max_instances': 20
  }
  config,gconfig = {},{}
  config['jobstores']=jobstores
  config['executors']=executors
  config['job_defaults']=job_defaults
  gconfig['apscheduler.logger']=log
  gconfig['apscheduler.timezone']='Asia/Shanghai'
  log.info(f'config:{config}\ngconfig:{gconfig}')

  scheduler = BackgroundScheduler(gconfig=gconfig,**config)
  log.info("start apscheduler...")
  scheduler.start()
  scheduler.add_job('sched.processor.mockTest:random_error', 'interval', id='random_error', seconds=3, replace_existing=True)


```

**Comment by goehls** [comment]
when
