### ISSUE TITLE
How to associate django_apscheduler_djangojob with my own model by ForeignKey

### ISSUE THREAD

**Issue by jayt1001** [agronholm/apscheduler#624]
like this：
![image](https://user-images.githubusercontent.com/29675005/165487026-817a861e-3d19-4c23-ac3c-2ea40bc56a6f.png)

**Comment by agronholm** [comment]
You ignored the template and posted an enhancement request, so I'm closing this. This project isn't even affiliated with django_apscheduler, so you should go ask them.
