### ISSUE TITLE
There is a bug in python 3.10

### ISSUE THREAD

**Issue by InfernalAzazel** [agronholm/apscheduler#634]
This issue tracker is **ONLY** for reporting bugs and requesting new features.

Any support questions should be directed to:

* [StackOverflow](https://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Github discussions](https://github.com/agronholm/apscheduler/discussions)

If you're not
reasonably sure that you've found a bug, please ask first (preferably on
[Gitter](https://gitter.im/apscheduler/Lobby))!

:warning: Any issues filed that ignore the template will be summarily closed!

**Describe the bug**
Traceback (most recent call last):
  File "/home/desay/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 900, in _create_plugin_instance
    plugin_cls = class_container[alias]
KeyError: 'cron'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/desay/Documents/code/github/test/main.py", line 11, in <module>
    scheduler.add_job(test_tick, 'cron', seconds=5)
  File "/home/desay/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 424, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/home/desay/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 925, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/home/desay/.local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 903, in _create_plugin_instance
    plugin_cls = class_container[alias] = plugin_container[alias].load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'funcsigs; python_version < "3.5"' distribution was not found and is required by the application

Process finished with exit code 1

os: ubutun 20.04 lts 

![2022-06-09 09-13-20 的屏幕截图](https://user-images.githubusercontent.com/40333954/172743394-cf6bde57-e4b0-457a-8b52-f5af47b6b6e1.png)

**Comment by agronholm** [comment]
It seems that you have not installed APScheduler, so the entry points are not available.

**Comment by InfernalAzazel** [comment]
I'm sure I have APScheduler 3.9.1 installed

**Comment by agronholm** [comment]
> I'm sure I have APScheduler 3.9.1 installed

How did you install it?

**Comment by InfernalAzazel** [comment]
![2022-06-09 17-01-49 的屏幕截图](https://user-images.githubusercontent.com/40333954/172808843-d595664a-88b7-4836-92aa-72314ff1c56e.png)

**Comment by agronholm** [comment]
The test suite passes on 3.10. Please provide repro instructions starting from a fresh virtualenv.

**Comment by agronholm** [comment]
It passed the test suite on Python 3.10 on Fedora Linux 36. Again, you need to give me instructions on how to reproduce the problem, starting from creating a fresh virtualenv.

**Comment by InfernalAzazel** [comment]
hey dude can use venv is it a dependency conflict?
![2022-06-10 09-16-51 的屏幕截图](https://user-images.githubusercontent.com/40333954/172971264-deba6a35-f2fd-45e6-ad60-ab28d0b63965.png)
![2022-06-10 09-18-08 的屏幕截图](https://user-images.githubusercontent.com/40333954/172971270-6385b120-d891-41fc-91a8-deabf11ae7f2.png)
![2022-06-10 09-18-16 的屏幕截图](https://user-images.githubusercontent.com/40333954/172971275-d730ad61-8278-404c-ac5f-fddc4309d783.png)
![2022-06-10 09-19-02 的屏幕截图](https://user-images.githubusercontent.com/40333954/172971278-418dfaf7-1113-4a60-8936-a7cb927af424.png)

**Comment by spectreseven1138** [comment]
I had this issue on Ubuntu as well, and was able to resolve it by upgrading setuptools using pip.
