### ISSUE TITLE
Adding new jobstore dynamically to already running ApScheduler

### ISSUE THREAD

**Issue by mohit-blazop** [agronholm/apscheduler#636]
We are trying to add a new jobstore dynamically to an already running BackgroundScheduler. 

The scheduler.add_jobstore() function works fine as we can see new jobs registered in jobstore based database. However, the added job doesn't run at the scheduled time (it seems executor is not picking new jobstore automatically). When we restart the BackgroundScheduler then it picks the jobs added in new jobstore. 

ApScheduler Version: 3.7.0
Jobstore: MongoDB

Regards,
Mohit

**Comment by agronholm** [comment]
I am curious about the use case. This has not come up before. In APScheduler v4, each scheduler only supports a single data store, requiring you to run multiple schedulers in order to use multiple data stores.

**Comment by mohit-blazop** [comment]
The use case is to support multi-tenancy wherein we just need one cron-like scheduler which is executing multiple customers' jobs per their own defined schedules which are saved in their own datastores. 

For security reasons, we are isolating each tenant's data in its own database instance. 

My request will be to not stop the support of multiple datastores per scheduler. Otherwise, we have to run multiple schedulers 
microservices to support multiple tenants causing more compute cost. 

Thanks,

**Comment by agronholm** [comment]
Why would you have to run multiple microservices for that? Why not just run multiple schedulers in the same process?

**Comment by mohit-blazop** [comment]
Well, we could but it adds more complexity for us. 

In our scenario, we are using flask_cli to start micro-service and create singleton instance of scheduler (to avoid duplicate scheduling). And provide plug-n-play model for tenant to come and go by dynamically adding job-store on need basis.
 
Do you see any issues in this implementation? OR is there any limit on the number of jobs one scheduler can execute at a time?  

Thanks for your support.

**Comment by agronholm** [comment]
There is likely a maximum number of jobs that the scheduler can schedule per second, based on your hardware. APScheduler 4, on the other hand, was designed to allow multiple schedulers to work in tandem, so the more scheduler processes you run, the faster the jobs can get scheduled (assuming you have enough schedules to benefit from multiple schedulers). Note that _scheduling_ and _running_ the jobs are two different things. You could have multiple schedulers and just one executor handling them if you so choose. The schedulers and executors are totally decoupled from each other in APScheduler 4, and you can run the executors in entirely separate processes.

**Comment by agronholm** [comment]
By the way, I checked and `add_jobstore()` should wake up the scheduler so it picks up the jobs from the new job store.

**Comment by mohit-blazop** [comment]
**Our observation:**

On an already running scheduler, add_jobstore() as a function adds new jobstore successfully and create new job in this added jobstore also. We can preview next schedule time for newly added job in jobstore. However, new job doesn't kick-off from this newly added jobstore.

Whereas, same scheduler instance is kicking-off jobs from jobstores which were added to scheduler before starting this singleton instance.

It seems executor is not picking up newly added jobstore unless we restart scheduler instance.

**Comment by mohit-blazop** [comment]
sure, For example, APSchedulerService is a singleton service configuring and starting a singleton instance of BackgroundScheduler(). And it also has a method to add a new job_store while BackgroundScheduler is already running.

`
class APSchedulerService(object):

    __instance = None  # Keep instance reference 

    @staticmethod 
    def getInstance():
        """ Static access method. """
        if APSchedulerService.__instance is None:
            APSchedulerService.__instance = APSchedulerService()

        return APSchedulerService.__instance

    def __init__(self):
        self.scheduler = BackgroundScheduler()

    ## configure & start AP scheduler with configuration required for tenant account name
    def configAndStartScheduler(self) -> BackgroundScheduler:
		## get all jobstores for all tenants
		jobStores = apSchedulerSettings.getJobStoresConfigsForAllAccounts()
		## get default executor & jobdefault settings 
        executors = {
            'default': ThreadPoolExecutor(20),
            'processpool': ProcessPoolExecutor(5)
        }
        jobDefaults = {
            'coalesce': False,
            'max_instances': 3
        }
		
	    ## configure scheduler for all job_stores and executor
        self.scheduler.configure(jobstores=jobStores, executors=executors, job_defaults=jobDefaults, timezone=utc)
	    self.scheduler.start()

    ## add new job store to scheduler
    def addJobStore(self, accountName):
		## get job store for new account
        jobStore = apSchedulerSettings.getJobStore(accountName)
		## add it to already running scheduler
        self.scheduler.add_jobstore(jobStore, accountName)
`

**Comment by mohit-blazop** [comment]
And add_job is simple call, which successfully schedules job in that jobstore, we can see in our mongodb also. But executor doesn't pick up, unless we restart BackgroudScheduler.

`scheduler.add_job(funct, args=(my_args), id=jobId, name=jobName, trigger=trigger, jobstore=accountName)
`

**Comment by agronholm** [comment]
I need a script that I can actually run, and it will demonstrate the issue. And it should have nothing extra in it.

**Comment by mohit-blazop** [comment]
Sorry for the delayed response.  I couldn't reproduce the issue with my sample script so we checked again and found the issue with our code.

The issue was, that our python program (which adds a new job store on the fly) was running in new `'os.fork()'` process which was dying once that unit of work is over. 

Thanks for your guidance though.
