### ISSUE TITLE
Or'ing a DateTrigger and an IntervalTrigger replaces the start date of the interval trigger

### ISSUE THREAD

**Issue by fhriley** [agronholm/apscheduler#640]
I am attempting to create a job that schedules on a whole interval, but also executes immediately on startup. For example, if a program is started at 12:00:12 and the interval is 30 seconds, the job will run at 12:00:12 and then at 12:00:30, 12:01:00, etc. I first tried like this:

```python

    scheduler = BlockingScheduler({
        'apscheduler.job_defaults.coalesce': 'true',
        'apscheduler.job_defaults.max_instances': '1',
        'apscheduler.timezone': os.getenv('TZ', 'UTC'),
    })

    interval_secs = 30
    now = datetime.datetime.now().timestamp()
    next_invoke = int(math.ceil(now) + (interval_secs - 1)) // interval_secs * interval_secs
    start_date = datetime.datetime.fromtimestamp(next_invoke - interval_secs)

    scheduler.add_job(task, 'interval', seconds=interval_secs, start_date=start_date)
```

The `start_date` is in the past so I expected this to run immediately, but it didn't run until the next interval. To me, this is a bug, but you might also say it's just not intuitive. I then tried an `OrTrigger`:

```python

start_date = datetime.datetime.fromtimestamp(next_invoke)
trigger = OrTrigger([DateTrigger(), IntervalTrigger(seconds=interval_secs, start_date=start_date)])
```

This triggers immediately as expected, but the interval trigger then triggers with a `start_date` from when the `DateTrigger` triggered rather than the `start_date` I specified. This seems like a bug.

**Comment by agronholm** [comment]
It works exactly as designed. A design which has been changed in master. Here's the [workaround](https://stackoverflow.com/a/43277102/242021).

**Comment by fhriley** [comment]
The workaround doesn't work:

```python
job = scheduler.add_job(lambda: thermo_task(data), 'interval', seconds=interval_secs, start_date=start_date)
job.next_run_time = dt
```

It has the same problem:

```
DEBUG:2022-07-04 13:22:36,128:start_date=2022-07-04 13:23:00
DEBUG:2022-07-04 13:22:36,145:next_run_time=2022-07-04 13:22:36.145231-07:00
DEBUG:2022-07-04 13:22:36,256:starting thermo task
DEBUG:2022-07-04 13:23:06,150:starting thermo task
```

Since it is working as designed, are you saying this cannot be done with `apscheduler`?

**Comment by agronholm** [comment]
You're supposed to give `next_run_time` as a keyword argument to `add_job()`.

**Comment by fhriley** [comment]
Same problem:

```python
job = scheduler.add_job(lambda: thermo_task(data), 'interval', seconds=interval_secs, start_date=start_date, next_run_time=dt)
```

```
DEBUG:2022-07-04 13:31:39,140:start_date=2022-07-04 13:32:00
DEBUG:2022-07-04 13:31:39,156:next_run_time=2022-07-04 13:31:39.156964-07:00
DEBUG:2022-07-04 13:31:39,269:starting thermo task
DEBUG:2022-07-04 13:32:09,160:starting thermo task
```

I also tried setting `next_run_time` to a time in the past:

```python
now = datetime.datetime.now().timestamp()
next_invoke = int(math.ceil(now) + (interval_secs - 1)) // interval_secs * interval_secs
start_date = datetime.datetime.fromtimestamp(next_invoke - interval_secs)
job = scheduler.add_job(lambda: thermo_task(data), 'interval', seconds=interval_secs, start_date=start_date, next_run_time=start_date)
```

```
DEBUG:2022-07-04 13:33:41,919:start_date=2022-07-04 13:33:30
DEBUG:2022-07-04 13:33:41,935:next_run_time=2022-07-04 13:33:41.935929-07:00
WARNING:2022-07-04 13:33:42,047:Run time of job "main.<locals>.<lambda> (trigger: interval[0:00:30], next run at: 2022-07-04 13:33:30 MST)" was missed by 0:00:12.047886
DEBUG:2022-07-04 13:34:00,010:starting thermo task
```

**Comment by agronholm** [comment]
Does this not work for you?
```python
from datetime import datetime

from apscheduler.schedulers.blocking import BlockingScheduler

start_date = datetime.now()
scheduler = BlockingScheduler()
scheduler.add_job(print, "interval", args=["hello"], seconds=2, start_date=start_date, next_run_time=start_date)
scheduler.start()
```

**Comment by fhriley** [comment]
No, as my example stated in my first paragraph:

If a program is started at 12:00:12 and the interval is 30 seconds, the job will run at 12:00:12 and then at 12:00:30, 12:01:00, 12:01:30, ...

If you take my last debug output above, the program was started at `13:31:39`, the task ran the first time at that time, but then it didn't run again until `13:32:09` when it should have run at `13:32:00`.

**Comment by agronholm** [comment]
That sounds like you need an `OrTrigger` using a `CronTrigger` with `second=0,30` and a `DateTrigger` that runs the job straight away, isn't that right? `IntervalTrigger` should not be involved here at all then.

**Comment by fhriley** [comment]
Yes! Thank you! I missed that the `CronTrigger` supports seconds since cron usually only does minutes.
