### ISSUE TITLE
Compatibility with MyPy

### ISSUE THREAD

**Issue by rustam-ashurov-mcx** [agronholm/apscheduler#648]
MyPy fails to analyze typings from apscheduler throwing errors like:
```
Skipping analyzing "apscheduler.schedulers.base": module is installed, but missing library stubs 
or py.typed marker
```
Could we add py.typed file in the root folder of apscheduler distribution package, would be great to have type checking

**Comment by agronholm** [comment]
Um, it's already [there](https://github.com/agronholm/apscheduler/blob/master/src/apscheduler/py.typed).

**Comment by agronholm** [comment]
To elaborate, I won't add it to the 3.x branch, but 4.x will have it.

**Comment by rustam-ashurov-mcx** [comment]
great, many thanks! So it will be there with 4.x release? (just to be sure)

**Comment by agronholm** [comment]
Yes, that is what I just said.
