### ISSUE TITLE
Job exceptions silently ignored

### ISSUE THREAD

**Issue by courtland** [agronholm/apscheduler#652]
**Describe the bug**

If an async job has an uncaught runtime exception, the scheduler correctly fails the job, but the exception is masked and easily overlooked. 

**To Reproduce**

Below is a basic modification of the simple async standalone example using the "blocking" scheduler syntax in the latest 4.x/master branch.

```python
from __future__ import annotations

from asyncio import run
from datetime import datetime
from pprint import pprint

from apscheduler._events import JobReleased
from apscheduler.schedulers.async_ import AsyncScheduler
from apscheduler.triggers.interval import IntervalTrigger


def tick():
    # This evaluates and the time is printed
    print("Hello, the time is", datetime.now())

    # Either of these fail the job. I would expect to at least get the exception
    # logged? Or is there an appropriate way to implement a job exception handler?
    frak()
    raise Exception("frak")


def listener(event) -> None:
    print(f"Job event: {event.__class__}")
    if isinstance(event, JobReleased):
        pprint(event.outcome)


async def main():
    async with AsyncScheduler() as scheduler:
        scheduler.event_broker.subscribe(listener)

        await scheduler.add_schedule(tick, IntervalTrigger(seconds=10))

        await scheduler.wait_until_stopped()


run(main())
```

```bash
# Output
Job event: <class 'apscheduler.TaskAdded'>
Job event: <class 'apscheduler.ScheduleAdded'>
Job event: <class 'apscheduler.JobAdded'>
Job event: <class 'apscheduler.ScheduleUpdated'>
Job event: <class 'apscheduler.JobAcquired'>
Hello, the time is 2022-08-02 17:34:29.404791
Job event: <class 'apscheduler.JobReleased'>
<JobOutcome.error: 2>
```

**Expected behavior**

The exception to be logged and/or available to the event handler.

**Additional context**

Although in an ideal world the job rescues its own exceptions and does not contain blatant errors, it seems reasonable that there should be at least some kind of warning logged? I was using apscheduler 3.x for a while, and when I switched to the master/4.x branch I started to notice that errors in my code went unnoticed during development for a bit. This is in an application with multiple jobs, where the other jobs might succeed and things appear to "work" looking at the logs. Not that it's a reason to keep doing so, but I recall my 3.x-based scheduler logging the exceptions.

Is there a good way to at least get at the Exception object. I couldn't seem to find it using an event subscriber. Is there a clean way to implement a handler that has access to the `JobResult`, which has the exception object?

I apologize in advance if this is a dumb question / not-a-bug. FWIW I am very grateful for the work you've done recently with the 4.x polish.

**Comment by agronholm** [comment]
>Is there a good way to at least get at the Exception object. I couldn't seem to find it using an event subscriber. Is there a clean way to implement a handler that has access to the JobResult, which has the exception object?

Hm, something along these lines?
```python
from __future__ import annotations

from asyncio import run
from datetime import datetime
from pprint import pprint
from traceback import print_exception

from apscheduler import JobReleased, JobOutcome, current_scheduler
from apscheduler.schedulers.async_ import AsyncScheduler
from apscheduler.triggers.interval import IntervalTrigger


def tick():
    # This evaluates and the time is printed
    print("Hello, the time is", datetime.now())

    # Either of these fail the job. I would expect to at least get the exception
    # logged? Or is there an appropriate way to implement a job exception handler?
    raise Exception("frak")


async def listener(event) -> None:
    print(f"Job event: {event.__class__}")
    if isinstance(event, JobReleased):
        pprint(event.outcome)
        if event.outcome is JobOutcome.error:
            result = await current_scheduler.get().get_job_result(event.job_id)
            print_exception(type(result.exception), result.exception, result.exception.__traceback__)


async def main():
    async with AsyncScheduler() as scheduler:
        scheduler.event_broker.subscribe(listener)

        await scheduler.add_schedule(tick, IntervalTrigger(seconds=10))

        await scheduler.wait_until_stopped()
        breakpoint()


run(main())
```

**Comment by courtland** [comment]
That works great for my purposes. Thank you!

**Comment by agronholm** [comment]
I had intended to add housekeeping background tasks that would purge old job results, but I forgot about that somewhere along the way. The consequence is that job results are never removed from the data store which is obviously bad. This needs to be addressed, if not in the first alpha then the second.

**Comment by agronholm** [comment]
I've pushed commits that should eliminate the problem in your use case. The results of scheduled jobs are now never saved.

**Comment by agronholm** [comment]
Oh, and errors are logged by the workers too.
