### ISSUE TITLE
Method ensure_index in removed in mongo 5

### ISSUE THREAD

**Issue by becash** [agronholm/apscheduler#657]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [x] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.5.1

### What happened?

Traceback (most recent call last):
  File "/root/data/sync_scheduler.py", line 140, in <module>
    SCHEDULER.start()
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/blocking.py", line 18, in start
    super(BlockingScheduler, self).start(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 151, in start
    store.start(self, alias)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/jobstores/mongodb.py", line 57, in start
    self.collection.ensure_index('next_run_time', sparse=True)
  File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 3200, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'ensure_index' method on a 'Collection' object it is failing because no such method exists.

### How can we reproduce the bug?

//  cause
//  https://www.mongodb.com/docs/manual/reference/method/db.collection.ensureIndex/#mongodb-method-db.collection.ensureIndex

JOBSTORES = {
    'default':
        mongodb.MongoDBJobStore(client=mongo_sync.client, database=options.mongo['db'], collection='apscheduler.jobs'),
}

EXECUTORS = {
    'default': {
        'type': 'threadpool',
        'max_workers': 20,
    },
}

SCHEDULER = BlockingScheduler(
    timezone=constants.TIMEZONE,
    jobstore_retry_interval=60,
    jobstores=JOBSTORES,
    executors=EXECUTORS)
SCHEDULER.start()

**Comment by becash** [comment]
problem is bigger,  scheduler not use many methods,  like  insert_one,  update_one, ....

**Comment by agronholm** [comment]
Where do you find `ensure_index` [here](https://github.com/agronholm/apscheduler/blob/3.x/apscheduler/jobstores/mongodb.py)?

**Comment by becash** [comment]
TypeError: 'Collection' object is not callable. If you meant to call the 'ensure_index' method on a 'Collection' object it is failing because no such method exists.

im use old version,  sorry my mistake

**Comment by agronholm** [comment]
Yes, this is why I added the checkbox "I have checked that my bug is still present in the latest release" – which you confirmed you had done.
