### ISSUE TITLE
[DEPRECATED] Use of `asyncio.get_event_loop()` : Update to `asyncio.get_running_loop()`

### ISSUE THREAD

**Issue by eric-nguyen-cs** [agronholm/apscheduler#660]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Please replace the use of `asyncio.get_event_loop()` (deprecated in Python 3.10) in your codebase by `asyncio.get_running_loop()` 

### Use case

While using APScheduler in an app, testing the app with `pytest` throws this warning: 
`apscheduler/schedulers/asyncio.py:43: DeprecationWarning: There is no current event loop 
self._eventloop = asyncio.get_event_loop()`

**Comment by agronholm** [comment]
This is no longer an issue in master (v4.0). The 3.x branch will only get critical bugfixes at this point.
