### ISSUE TITLE
Timezone not working for BackgroundScheduler and CronTrigger

### ISSUE THREAD

**Issue by giusepic** [agronholm/apscheduler#667]
### Things to check first

- [x] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1

### What happened?

I want to run a Background job by specifying a timezone. 

It looks like a very simple task, but the timezone gets always ignored and the job is triggered using the system timezone. Is there any problem because I'm using CronTrigger?

In below's code, for example, the job is triggered in my local timezone (Europe/Vienna) instead of the specified London timezone.

### How can we reproduce the bug?

```python
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger

TEST_CRON = '37 11 * * *'


def test():
    print('Hello')


sched = BackgroundScheduler(daemon=True, timezone='Europe/London')
sched.add_job(test, CronTrigger.from_crontab(TEST_CRON))
sched.start()

input("Press [Enter] to continue.")
```

**Comment by giusepic** [comment]
thanks for the reply! how exactly can I do that?

**Comment by agronholm** [comment]
It's one of the documented parameters:

```python
CronTrigger.from_crontab(TEST_CRON, timezone='Europe/London')
```

**Comment by giusepic** [comment]
Oh I see, sorry I've been researching but totally missed this! 
Thank you so much!
