### ISSUE TITLE
Ability to add a list of function names instead of adding multiple jobs

### ISSUE THREAD

**Issue by 411A** [agronholm/apscheduler#671]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

I have a file in which I want to run all functions one by one, just like calling them in `__name__ = '__main__'`.
Instead of adding the `scheduled_job()` decorator to all of those functions or adding multiple jobs, I need to include their name as a **list** inside one `add_job()` as they share the same timings without different arguments.
I searched for it & didn't see anything, I don't know if it's already implemented.
Thanks for your great tool!

### Use case

Running multiple functions with same timing & properties just like they've been called inside `__name__ = '__main__'`.

**Comment by agronholm** [comment]
So...why don't you just create a new function that runs these other functions?

**Comment by 411A** [comment]
Sorry, Right after opening the issue I realized I could do that 😅 Thanks for your great tool & your quick reply!
