### ISSUE TITLE
ASGI Middleware example doesn't work in 4.0.0a

### ISSUE THREAD

**Issue by ThinksFast** [agronholm/apscheduler#673]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

4.0.0a2

### What happened?

Hello, I am trying to adapt your example to create a middleware for an ASGI framework I'm using called Starlite, which based on their docs, seems [straightforward](https://starlite-api.github.io/starlite/usage/7-middleware/2-creating-middleware/2-using-middleware-protocol/).  But as far as I can tell, the scheduler isn't getting started, I never see the `tick()` function get called and nothing prints. 

So I tried running the [example provided for Starlette (v0.21.0)](https://github.com/agronholm/apscheduler/blob/master/examples/web/asgi_starlette.py).  The `tick()` never prints for Starlette, and I get the following printed out in the log:

`INFO:     ASGI 'lifespan' protocol appears unsupported.`  (I only get this for Starlette, not Starlite)

I understand APScheduler v4 is still an alpha release, so I wanted to see if this is a known issue, or if there's a workaround I could try.

Cheers

### How can we reproduce the bug?

Running the exact code provided in the example should reproduce the issue.

https://github.com/agronholm/apscheduler/blob/master/examples/web/asgi_starlette.py

I'm using Python 3.11 and Starlette 0.21.0.

**Comment by agronholm** [comment]
The problem seems to be that you're running `master` examples against `4.0.0a2`. These two versions are **not** compatible. Please run either master code against master examples or 4.0.0a2 code against 4.0.0a2 examples.

**Comment by ThinksFast** [comment]
@agronholm thanks for the quick reply!  I can only see a master branch, and some branches which are much older and marked as stale.  (or maybe I'm misunderstanding something)

**Comment by agronholm** [comment]
4.0.0a2 is a tag, not a branch: https://github.com/agronholm/apscheduler/tree/4.0.0a2/examples/web

**Comment by ThinksFast** [comment]
Ah, got it.  Ok, the Starlette example is working now, but not Starlite.  I'll keep working at it, thanks again for the quick help!

**Comment by agronholm** [comment]
What problem are you seeing with Starlite?

**Comment by ThinksFast** [comment]
@agronholm I'm not seeing anything in Starlite, and that's the problem.  No print outs and there's nothing in the log, no exceptions from what I can see.  

And trying to debug the middleware, I can see the `SchedulerMiddleware` gets initialized, but the `__call__` dunder doesn't seem to get called, I never get to step through it.

Here's a minimal example to reproduce.  And based on [Starlite docs](https://starlite-api.github.io/starlite/usage/7-middleware/2-creating-middleware/2-using-middleware-protocol/), this should be the correct way to [inject middleware with a kwarg](https://starlite-api.github.io/starlite/usage/7-middleware/1-using-middleware/3-define-middleware/). 


```
from __future__ import annotations

import logging
from datetime import datetime

import uvicorn
from apscheduler.datastores.async_sqlalchemy import AsyncSQLAlchemyDataStore
from apscheduler.eventbrokers.asyncpg import AsyncpgEventBroker
from apscheduler.schedulers.async_ import AsyncScheduler
from apscheduler.triggers.interval import IntervalTrigger
from sqlalchemy.ext.asyncio import create_async_engine
from starlite import DefineMiddleware, Request, Starlite, State, get
from starlite.middleware.base import MiddlewareProtocol
from starlite.types import ASGIApp, Receive, Scope, Send

logger = logging.getLogger(__name__)


def tick():
    print("Hello, the time is", datetime.now())
    logger.info("Hello, the time is", datetime.now())


class SchedulerMiddleware(MiddlewareProtocol):
    def __init__(
        self,
        app: ASGIApp,
        scheduler: AsyncScheduler,
    ) -> None:
        super().__init__(app)
        self.app = app
        self.scheduler = scheduler

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "lifespan":
            async with self.scheduler:
                await self.scheduler.add_schedule(
                    tick, IntervalTrigger(seconds=1), id="tick"
                )
                await self.scheduler.start_in_background()
                await self.app(scope, receive, send)
        else:
            await self.app(scope, receive, send)


@get("/")
async def root(request: Request, state: State) -> str:
    return "Hello, world!"


engine = create_async_engine("postgresql+asyncpg://postgres:secret@localhost/testdb")
data_store = AsyncSQLAlchemyDataStore(engine)
event_broker = AsyncpgEventBroker.from_async_sqla_engine(engine)
scheduler = AsyncScheduler()
middleware = [DefineMiddleware(SchedulerMiddleware, scheduler=scheduler)]

app = Starlite(route_handlers=[root], middleware=middleware)

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)

```

**Comment by ThinksFast** [comment]
According to the Starlite team, they don't give Middleware access to the ASGI LifeSpan events. They suggested scaffolding the scheduler in `on_startup`.

So that's what's going on.  Is `AsyncScheduler` still the right tool to use?  Or would you suggest a different approach?

**Comment by agronholm** [comment]
The scheduler requires `async with` to be used. Does `on_startup()` work with that? I'm doubtful.

**Comment by agronholm** [comment]
A dirty workaround would be to use an `AsyncExitStack`. Have the scheduler enter the stack in `on_startup()` and then exit the stack in `on_shutdown()` (or whatever they call it). This requires that they use the same task for both though.

**Comment by ThinksFast** [comment]
I tried the following function and added it to `on_startup`, but the task only runs once.

```
async def schedule_tasks():
    data_store = AsyncSQLAlchemyDataStore(engine)
    event_broker = AsyncpgEventBroker.from_async_sqla_engine(engine)
    scheduler = AsyncScheduler()
    async with scheduler:
        await scheduler.add_schedule(tick, IntervalTrigger(seconds=1), id="tick")
        await scheduler.start_in_background()
```


From Log:
```
INFO - 2022-10-27 13:23:39,915 - main - main - Tasks Scheduled
INFO - 2022-10-27 13:23:39,922 - apscheduler.schedulers.async_ - async_ - Added new schedule (task=Task(id='main:tick', func=<function tick at 0x1057b7c40>, max_running_jobs=None, misfire_grace_time=None, state=None), trigger=IntervalTrigger(seconds=1, start_time='2022-10-27 13:23:39.919836+03:00')); next run time at 2022-10-27 13:23:39.919836+03:00
Hello, the time is 2022-10-27 13:23:39.924319
INFO - 2022-10-27 13:23:39,924 - main - main - Hello, the time is 2022-10-27 13:23:39.924263
INFO - 2022-10-27 13:23:39,924 - apscheduler.workers.async_ - async_ - Job 188e173d-b318-43a7-90ed-3b9eaab19a7c completed successfully
INFO - 2022-10-27 13:23:39,924 - apscheduler.schedulers.async_ - async_ - Scheduler stopped
INFO - 2022-10-27 13:23:39,925 - apscheduler.workers.async_ - async_ - Worker stopped
INFO:     Application startup complete.
```

**Comment by agronholm** [comment]
That's because you're shutting down the scheduler right away (when it exits the `async with` block).

**Comment by ThinksFast** [comment]
That makes sense.  I was trying to follow the pattern from the Middleware example.  And you mentioned `async with` is required.

But without it, the code throws an exception.  

This function:
```
async def schedule_tasks():
    data_store = AsyncSQLAlchemyDataStore(engine)
    event_broker = AsyncpgEventBroker.from_async_sqla_engine(engine)
    scheduler = AsyncScheduler()
    await scheduler.add_schedule(tick, IntervalTrigger(seconds=1), id="tick")
    await scheduler.start_in_background()
```

Throws:
```
ERROR:    Traceback (most recent call last):
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/starlite/asgi.py", line 243, in lifespan
    await self.startup()
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/starlite/asgi.py", line 293, in startup
    await self._call_lifespan_handler(handler)
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/starlite/asgi.py", line 279, in _call_lifespan_handler
    await async_callable()
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/starlite/utils/sync.py", line 69, in __call__
    return cast("T", await self.wrapped_callable["fn"](*args, **kwargs))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Documents/GitHub/luna-burn/main.py", line 97, in schedule_tasks
    await scheduler.add_schedule(tick, IntervalTrigger(seconds=1), id="tick")
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/apscheduler/schedulers/async_.py", line 177, in add_schedule
    await self.data_store.add_task(task)
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/apscheduler/datastores/async_adapter.py", line 49, in add_task
    await to_thread.run_sync(self.original.add_task, task)
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/apscheduler/datastores/memory.py", line 131, in add_task
    self._events.publish(TaskAdded(task_id=task.id))
    ^^^^^^^^^^^^
AttributeError: 'MemoryDataStore' object has no attribute '_events'

ERROR:    Application startup failed. Exiting.
```

**Comment by agronholm** [comment]
Yeah, that's why it's required. So try the `AsyncExitStack` route to see if that works.

**Comment by ThinksFast** [comment]
I sincerely appreciate the help!  I don't know anything about `AsyncExitStack`, but I'll research and try to figure it out.  🙏

**Comment by agronholm** [comment]
Create the exit stack somewhere, then call `await exit_stack.__aenter__()` in `on_startup` and `await exit_stack.__aexit__(None, None, None)` in `on_shutdown()`. In `on_startup()`, you can then activate the scheduler by `await exit_stack.enter_async_context(scheduler)`.

**Comment by agronholm** [comment]
Even better if you have access to whatever exception triggered the shutdown (pass that to `__aexit__()` as type, value, `value.__traceback__`).
