### ISSUE TITLE
APscheduler using AsyncIOScheduler does not trigger on Python 3.11 

### ISSUE THREAD

**Issue by thehaxxa** [agronholm/apscheduler#674]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1

### What happened?

I just tested my python program using Apscheduler (with AsyncIOScheduler) in Python 3.11. 
I have found that scheduled jobs no longer run. 

For example I have a job that looks like this: 

`scheduler.add_job(testPrint, 'interval', seconds=30)`

On Python 3.9/3.10 it would run the testPrint callback and on Python 3.11 it fails to. 

I haven't investigated further than this, but it should be simple enough to replicate. 

### How can we reproduce the bug?

Install Python 3.11 
Run Apscheduler using AsyncIOScheduler
Confirm Job's function callback does not run in any context.

**Comment by idogross** [comment]
Also received this issue with a very similar command:
`scheduler.add_job(sync_inventory, "interval", args=[config], minutes=config.sync_interval)`

And error:
```
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'funcsigs; python_version < "3.5"' distribution was not found and is required by the application
```
This results from this line:
`Traceback (most recent call last):
  File ".../apscheduler/schedulers/base.py", line 900, in _create_plugin_instance
    plugin_cls = class_container[alias]
KeyError: 'interval'`

I used python 3.10 with Linux Ubuntu 22.04 (APScheduler==3.9.1.post1)

**Comment by agronholm** [comment]
I need a script that reproduces the problem. AsyncIOScheduler requires a running asyncio event loop to work.

**Comment by agronholm** [comment]
Closing due to a lack of responses.
