### ISSUE TITLE
asyncio.exceptions.CancelledError on scheduler.shutdown()

### ISSUE THREAD

**Issue by ThinksFast** [agronholm/apscheduler#675]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1

### What happened?

Hi again, 

So I downgraded to `APScheduler v3.9.1` (from the latest alpha2) and set up a job using `AsyncIOScheduler()` in the `Starlite` API framework.  This was the easiest path forward for me (RE #673)

I am able to successfully start and stop the scheduler with the Starlite `on_startup` and `on_shutdown` events.  But on shutdown, I am getting exceptions thrown after the shutdown event.  

Is this something I need to worry about, or is there anything I can do to handle the errors?  The tasks query an API and write to a DB. 

STACKTRACE:
```
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO - 2022-10-27 16:13:33,785 - main - main - 🛑 Stopping task scheduler
INFO - 2022-10-27 16:13:33,786 - apscheduler.scheduler - base - Scheduler has been shut down
ERROR - 2022-10-27 16:13:33,791 - apscheduler.executors.default - base_py3 - Job "main (trigger: interval[0:01:00], next run at: 2022-10-27 16:14:08 EAT)" raised an exception
Traceback (most recent call last):
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Documents/GitHub/data-wrangler/src/job.py", line 332, in main
    async with rate_limiter:
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/aiolimiter/leakybucket.py", line 110, in __aenter__
    await self.acquire()
  File "/miniforge3/envs/py311/lib/python3.11/site-packages/aiolimiter/leakybucket.py", line 97, in acquire
    await wait_for(
  File "/miniforge3/envs/py311/lib/python3.11/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError
INFO:     Application shutdown complete.
INFO:     Finished server process [78813]
INFO:     Stopping reloader process [78810]

```

### How can we reproduce the bug?

Here are the functions I'm using to schedule the jobs.  I tried added `scheduler.remove_all_jobs()` before shutdown, but that created even more exceptions.

```
async def start_scheduler(state: State):
    scheduler = AsyncIOScheduler()
    scheduler.add_job(
        main, "interval", seconds=60, max_instances=1, id="data_job_1"
    )
    scheduler.start()
    state.scheduler = scheduler
    logger.info("🚦 Starting the task scheduler")


async def stop_scheduler(state: State):
    scheduler = state.scheduler
    scheduler.shutdown(wait=True)
    logger.info("🛑 Stopping task scheduler")
```

**Comment by agronholm** [comment]
Asyncio support was added to the 3.x series as an afterthought. It never worked really well, so in v4.0 I redesigned the library as async-first. I should mention that, among other things, `wait=True` does not work with the asyncio scheduler, as there is no way to  wait for the shutdown in a synchronous function.

**Comment by ThinksFast** [comment]
Ok, thanks for the info here.  Looking forward to a stable 4.0, and making it work with Starlite.

**Comment by agronholm** [comment]
Did the `AsyncExitStack` approach not work?

**Comment by agronholm** [comment]
I am interested in integrations with third party frameworks, so would you mind showing what you had and which didn't work?

**Comment by ThinksFast** [comment]
Sure, happy to!  

Honestly, I didn't get anywhere with the `AsyncExitStack` idea.  I spent more than an hour working on it, but it's just way over my head and I needed to make some progress.  It could be a viable workaround, I just couldn't sort it out.

After that, I relayed your comments to the Starlite team in their discord #help channel.  The lead maintainer of Starlite suggested persisting the `scheduler` into the application `state`, which I tried, but the `scheduler` was still killed after the first job run, due to the `async with`.  

We tried to hack that a bit further by adding a `while True: await asyncio.sleep(0)` to the end of the `on_startup` function, but then the application would never complete startup.  Which makes sense, but it was worth a try.  That code is below, happy to share a full working example if you want to play with it.

Persisting the scheduler to the app state does seem like a good idea.  It'd make the scheduler available at all levels of the application, and convenient to manage.

A bit later, someone else in the Starlite discord shared a code example they're using in a FastAPI app.  That code didn't work in APScheduler 4.0, so I downgraded and was able to get it working from there. 

That was my journey, hope it helps!


```
## pattern using the application state to persist a reference to the scheduler

async def on_startup(state: State):
    engine = create_async_engine(
        "postgresql+asyncpg://postgres:secret@localhost/testdb"
    )
    data_store = AsyncSQLAlchemyDataStore(engine)
    event_broker = AsyncpgEventBroker.from_async_sqla_engine(engine)
    async with AsyncScheduler() as scheduler:
        await scheduler.add_schedule(tick, IntervalTrigger(seconds=1), id="tick")
        await scheduler.start_in_background()
        state.scheduler = scheduler
        while True:
            await asyncio.sleep(0)

     
```

**Comment by agronholm** [comment]
I was hoping to see what you tried to do with `AsyncExitStack`, based on my advice.
