### ISSUE TITLE
Failed to reset db's

### ISSUE THREAD

**Issue by cepheidev** [agronholm/apscheduler#680]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

lastest

### What happened?

setting every at 1 am, db will reset the setting's.  but get error ```Run time of job "reset_menfess (trigger: cron[hour='1', minute='0'], next run at: 2022-11-19 01:00:00 WIB)" was missed by 0:00:04.995930```

### How can we reproduce the bug?

```from apscheduler.schedulers.asyncio import AsyncIOScheduler
from bot import Bot, data, Database

async def reset_menfess():
    db = Database(data[0])
    x = await db.reset_menfess()
    await Bot().kirim_pesan(x=str(x))
    print('BOT BERHASIL DIRESET')

scheduler = AsyncIOScheduler(timezone="Asia/Jakarta")
scheduler.add_job(reset_menfess, trigger="cron", hour=1, minute=0)
scheduler.start()

Bot().run()
```

**Comment by agronholm** [comment]
Why do you think this is a bug in apscheduler?

**Comment by agronholm** [comment]
Are you sure you don't have the job added twice? That could cause this, if indeed the function is running as you say.

**Comment by InfernalAzazel** [comment]
I also encountered something like this

![Screenshot from 2022-12-16 17-29-29](https://user-images.githubusercontent.com/40333954/208067516-aa2c3149-7486-4af3-8a0d-6826fe4ffcd5.png)

**Comment by agronholm** [comment]
Something like what? Run time of job missed?

**Comment by agronholm** [comment]
No response, closing.
