### ISSUE TITLE
It is not possible to set max_running_jobs for a task

### ISSUE THREAD

**Issue by akshaykumar90** [agronholm/apscheduler#697]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

4.0.0a2.post35

### What happened?

I want multiple instances of a task running concurrently. Looks like I need to set `max_running_jobs` for the task definition.  The `add_job` and `add_schedule` methods (which is the only way to create task?) do not support this option.

A workaround is manually updating the database with the desired value.

### How can we reproduce the bug?

Not applicable.

**Comment by agronholm** [comment]
The `configure_task()` method was added back in October 2023 (1ecb343b). This setting is not enforced yet, however, and has been the one feature blocking the first 4.0 series beta release, but that's a separate matter.
