### ISSUE TITLE
Snyk High vulnerability issue found on imported dependency: setuptools@57.5.0 

### ISSUE THREAD

**Issue by Choughton2t** [agronholm/apscheduler#698]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1.post1

### What happened?

https://security.snyk.io/vuln/SNYK-PYTHON-SETUPTOOLS-3180412
There is a high REdos vulnerability in a dependent package 

### How can we reproduce the bug?

Run Snyk with any repository importing apscheduler and it will warn you of a high vulnerability.
![image](https://user-images.githubusercontent.com/85574537/211021515-1c9fb866-9695-4fb5-ad6b-816250bb3234.png)

**Comment by agronholm** [comment]
Why are you reporting this here? APScheduler doesn't constrain setuptools versions.
