### ISSUE TITLE
Lost connection to Elasctisearch

### ISSUE THREAD

**Issue by Pad0y** [agronholm/apscheduler#699]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1.post1

### What happened?

I want to implement a function to query the data in Elasticsearch at regular intervals, but the connection timeout problem occurs after the regular task is executed once. Even if I set Elasticsearch's connection parameters or delete the connection object and recreate it, this situation cannot be avoided, but in a resident process like flask, this problem does not occur. 

I set the parameter `max_instances=1`, but I still get the warning `maximum number of running instances reached (1)` after the query is executed, so the elasticsearch instance is not destroyed

This is the error log message

```
INFO  - 2023-01-11 16:10:34 - 16008 - MainThread - Adding job tentatively -- it will be properly scheduled when the scheduler starts
Execution of job "source1-insert (trigger: interval[0:01:00], next run at: 2023-01-11 16:12:34 CST)" skipped: maximum number of running instances reached (1) 
.....
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x00000260BD15FF48>: Failed to establish a new connection: [Errno 10060] [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。) 
Execution of job "source1-insert (trigger: interval[0:01:00], next run at: 2023-01-11 16:14:34 CST)" skipped: maximum number of running instances reached (1)
```

I look forward to receiving your answer as soon as possible, thank you very much!

### How can we reproduce the bug?

```
from elasticsearch_dsl.connections import get_connection
from elasticsearch_dsl.connections import Elasticsearch

def test_query():
    # 获取elasticsearch连接对象Get elasticsearch connection object
    client: Elasticsearch = get_connection()
    # Print cluster health information
    print(client.cluster.health())

def runScheduler():
    timezone = settings.TIMEZONE
    scheduler_log = LogFactory.get_logger('scheduler')
    scheduler = GeventScheduler(logger=scheduler_log, timezone=timezone)

    scheduler.add_job(test_query, "interval", minutes=1, id="test-1", name="test-query")

    executors = {
        "default": {"type": "threadpool", "max_workers": 10},
        "processpool": GeventExecutor(),
    }
    job_defaults = {"coalesce": False, "max_instances": 1}
    scheduler.configure(executors=executors, job_defaults=job_defaults, timezone=timezone)
    g = scheduler.start()  
    print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))
    try:
        g.join()
    except (KeyboardInterrupt, SystemExit):
        pass
```

**Comment by agronholm** [comment]
How is the connection loss to Elastic Search caused by APScheduler? I don't see how. I can't really test this locally either because I don't have Elastic Search running here.

**Comment by agronholm** [comment]
Closing due to inability to reproduce the problem, and lack of responses.
