### ISSUE TITLE
Check if scheduler running

### ISSUE THREAD

**Issue by wonjerry** [agronholm/apscheduler#700]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

I am using this library for scheduling internal cache file deletion when I launch a ui server made with streamlit. However, due to the nature of streamlit, there are cases where the scheduler is called multiple times.

In this case, it would be nice if the scheduler could easily check the status by providing the is_running() method. without breaking the code.

And if there is a chance, I would like to implement the function and raise PR.

### Use case

```python
if not scheduler.is_running():
  scheduler.start() or do something
```

**Comment by agronholm** [comment]
Is the `running` property not good enough?

**Comment by wonjerry** [comment]
Oh I missed it. I think I can use this. Thanks for the reply!
