### ISSUE TITLE
job successfully added but never removed

### ISSUE THREAD

**Issue by shuffleyxf** [agronholm/apscheduler#708]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.0

### What happened?

I am using apscheduler to schedule some task, and do something when the task stop through the EVENT_JOB_REMOVED. But i found that  job will never deleted when the time between start and end is shorter than interval, and never trigger EVENT_JOB_REMOVED.

### How can we reproduce the bug?

```
import datetime
import time


from apscheduler.events import EVENT_JOB_REMOVED
from apscheduler.schedulers.background import BackgroundScheduler


def my_listener(event): 
    print('remove job!')


def func(): 
    print('hello, apcheduler')
    
    
if __name__ == '__main__':
    scheduler = BackgroundScheduler()
    scheduler.add_listener(my_listener, EVENT_JOB_REMOVED)
    scheduler.start()
    end_time = datetime.datetime.now() + datetime.timedelta(seconds=3)
    scheduler.add_job(func, 'interval', seconds=5, end_date=end_time)

    while True:
        print(scheduler._jobstores['default'].get_all_jobs())
        time.sleep(5)
```

**Comment by riosw** [comment]
I think this happens because the job is considered as "will never run" (i.e. `next_run_time` is `None`). In fact, in that code snippet, `func()` never got called.

For example, calling `add_job` with slightly later `start_date` argument works. It properly executes `func()` once and removes the job:
```
scheduler.add_job(
        func,
        "interval",
        seconds=5,
        start_date=datetime.datetime.now() + datetime.timedelta(seconds=1),
        end_date=end_time,
    )
```

**Comment by riosw** [comment]
My comment earlier might be more of an inspection of the issue. If you need more help, feel free to comment!

**Comment by shuffleyxf** [comment]
I understand what you said, but I still think the task should be removed and trigger EVENT_JOB_REMOVED rather than kept forever.

**Comment by agronholm** [comment]
Could you try this with APScheduler 4.0.0a2 (or `master`)? I feel this isn't a problem on 4.x anymore, but I'll fix it if it happens there too.

**Comment by shuffleyxf** [comment]
I believe this issue still exists on master. The following code reproduces the issue.
```
import datetime

from apscheduler import TaskRemoved, TaskAdded

from apscheduler.schedulers.sync import Scheduler
from apscheduler.triggers.interval import IntervalTrigger


def remove_listener(event):
    print('remove task!')


def add_listener(event):
    print('add task!')


def func():
    print('hello, apcheduler')


if __name__ == '__main__':
    scheduler = Scheduler()
    scheduler.event_broker.subscribe(remove_listener, {TaskRemoved})
    scheduler.event_broker.subscribe(add_listener, {TaskAdded})
    end_time = datetime.datetime.now() + datetime.timedelta(seconds=3)
    trigger = IntervalTrigger(seconds=5, end_time=end_time)
    scheduler.add_schedule(func, trigger)
    scheduler.run_until_stopped()
```

**Comment by agronholm** [comment]
I think there's a misunderstanding regarding v4.0 here: the task isn't supposed to go away, only the schedule and any jobs spawned from it.

**Comment by agronholm** [comment]
Closing due to lack of responses.
