### ISSUE TITLE
AsyncIOScheduler can't wait for jobs with interval

### ISSUE THREAD

**Issue by 0xARROWK** [agronholm/apscheduler#713]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.1

### What happened?

Hello !

I'm using asyncio and apscheduler in order to communicate with a BLE device. I need to poll to this device every 0.1s, and apscheduler was doing the job, but I had to change my library to communicate with this device. 

This new library use asyncio, so I tried to implement the example for asyncio, which bring us here :
- https://github.com/agronholm/apscheduler/blob/3.x/examples/schedulers/asyncio_.py

Unfortunately I'm getting this error, that's coming from "run_forever" function :

![image](https://user-images.githubusercontent.com/67783173/224273302-36c45056-e72e-4b3d-b487-d4566ff1d98a.png)

**Comment by agronholm** [comment]
The linked example works fine. If you have an example I can run to reproduce the problem you're having, please share it here. Otherwise there's nothing I can do.

**Comment by agronholm** [comment]
Closing due to lack of responses.
