### ISSUE TITLE
PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html   return tzinfo.localize(dt)

### ISSUE THREAD

**Issue by NicolasSteuernagle** [agronholm/apscheduler#718]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1

### What happened?

I have created a simple scheduler that completes a task every 5 seconds. When I run the scheduler however, I get this warning message. PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)

Below is the implementation of the scheduler:
def email_scheduler():
    scheduler = BackgroundScheduler()
    scheduler.add_job(send_email_reminders, 'cron', second='*/5')
    scheduler.start()

I've looked around online and in the link provided but still haven't found much of a fix.

### How can we reproduce the bug?

def email_scheduler():
    scheduler = BackgroundScheduler()
    scheduler.add_job(some_function, 'cron', second='*/5')
    scheduler.start()

**Comment by agronholm** [comment]
It's not an error, and it's fixed in master (the 4.0 series).

**Comment by agronholm** [comment]
Also duplicates #576 and #572.
