### ISSUE TITLE
add_job with replace_existing=True still creates new job

### ISSUE THREAD

**Issue by keriksson-rosenqvist** [agronholm/apscheduler#720]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.1

### What happened?

When using `add_job` with the `replace_existing` kwarg set to True, I expect the current job with the defined ID to be updated, instead I see a new instance of a job with the same ID added to the list of jobs.

### How can we reproduce the bug?

__MWE:__
```
from apscheduler.schedulers.background import BackgroundScheduler

scheduler = BackgroundScheduler()

print(scheduler.get_jobs())
# real output: []
# expected output: []
id = "my_job_id"
scheduler.add_job(print, "cron", "HelloWorld", hour=10,
                  id=id, replace_existing=True)
print(scheduler.get_jobs())
# real output: [<Job (id=my_job_id name=print)>]
# expected output: [<Job (id=my_job_id name=print)>]
scheduler.add_job(print, "cron", "HelloWorld", hour=12,
                  id=id, replace_existing=True)
print(scheduler.get_jobs())
# real output: [<Job (id=my_job_id name=print)>, <Job (id=my_job_id name=print)>]
# expected output: [<Job (id=my_job_id name=print)>]
```

**Comment by agronholm** [comment]
What you're seeing is a job being tentatively added to the store. Since the scheduler hasn't actually started the job store yet, it has no way of knowing if there is a job there with a conflicting ID. This is resolved once the scheduler is actually started. This may seem confusing to users, which is why I've opted for a different design in the 4.0 series.
