### ISSUE TITLE
Custom sqlalchemy table name

### ISSUE THREAD

**Issue by wangyuhuiever** [agronholm/apscheduler#722]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Is there a way to set a custom table name in sqlalchemy, such as add a prefix 'apsheduler_'. hard code table name may cause user have to change there service table name.

### Use case

Now I have a job object with some data: waiter, waitress, accountant ...
If use async_sqlalchemy data_store, I must rename my job tablename to others

**Comment by wangyuhuiever** [comment]
And will looks neater in visualization tools

**Comment by agronholm** [comment]
You can override `SQLAlchemyDataStore.get_table_definitions()` method to modify the table definitions as you like.

**Comment by wangyuhuiever** [comment]
sorry I can't. 
in function `__attrs_post_init__` have this code
```
self.t_metadata = self._metadata.tables["metadata"]
```
here will use table name again

**Comment by martinkirch** [comment]
I managed to add a prefix by defining and using this data store:

```python
class PrefixedDataStore(SQLAlchemyDataStore):

    def get_table_definitions(self):
        upstream_metadata = super().get_table_definitions()
        for table in upstream_metadata.tables.values():
            table.name = "apscheduler_" + table.name
        return upstream_metadata
```

Indexes are still using the non-prefixed name, but that's much less visible and less likely to conflict with application's names.

Thanks for the hint on `get_table_definitions` - and for APS of course !
