### ISSUE TITLE
On import or start, I see a warning (PytzUsageWarning)

### ISSUE THREAD

**Issue by Wikinaut** [agronholm/apscheduler#724]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.1

### What happened?

```
/usr/local/lib/python3.9/dist-packages/apscheduler/util.py:428: PytzUsageWarning:
The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495).
For more details on migrating to a PEP 495-compliant implementation,
see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
```
Just use apscheduler in 'cron', minute=15 mode.
Raspberry PI OS LITE

### How can we reproduce the bug?

This part triggers the warning.
```
def setup_scheduler():
        from apscheduler.schedulers.background import BackgroundScheduler

        schedule_showtime = BackgroundScheduler(daemon=True)
        schedule_showtime.add_job(showtime, 'cron', minute="*")
        schedule_showtime.start()

        schedule_gong1 = BackgroundScheduler(daemon=True)
        schedule_gong1.add_job(gong1, 'cron', minute=15)
        schedule_gong1.start()

        schedule_gong2 = BackgroundScheduler(daemon=True)
        schedule_gong2.add_job(gong2, 'cron', minute=30)
        schedule_gong2.start()
```
Full source code is here https://github.com/Wikinaut/pinetradio

**Comment by lmunch** [comment]
Setting the timezone like this removed the warning for me:
https://github.com/agronholm/apscheduler/discussions/570#discussioncomment-3383707
But that is just a work around.

**Comment by Wikinaut** [comment]
Thanks!
