### ISSUE TITLE
No module named 'apscheduler.schedulers'

### ISSUE THREAD

**Issue by msher100** [agronholm/apscheduler#731]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.1

### What happened?

I am use windows 10 (or versin 11), python 3.10.11, spyder IDE version 5.4.3 or vscode version 1.77.3 (plugin Chinese package)
after pip install apscheduler, it works fine at my computer PowerShell, or cmd console. But there is always error message over vscode and spyder in my first line: import from apscheduler.schedulers.blocking import BlockingScheduler (or
from apscheduler.schedulers.background import BackgroundScheduler), i was giving a error message: "ModuleNotFoundError: No module named 'apscheduler.schedulers'; 'apscheduler' is not a package".
I have tried locate the apschedule path location and put it into spyder path, with or without additonal path line, the error keeps show, that I couldn't go any further.
Thus, I try to type in line by line in powershell console, it works. But I couldn't officially use powershell python console as my usual working tools. 
<img width="804" alt="Screenshot 2023-04-30 195518" src="https://user-images.githubusercontent.com/55918381/235351601-3f546f74-8e58-49ff-8407-e7a4dded0ba6.png">
<img width="377" alt="Screenshot 2023-04-30 195028" src="https://user-images.githubusercontent.com/55918381/235351602-0e2dc40d-0047-40c0-acec-e16734e46abd.png">

### How can we reproduce the bug?

'''
windows 11, spyder 5.4.3, vscode 1.77.3, python 3.10.11
apscheduler 3.10.1
'''
<img width="419" alt="Screenshot 2023-04-30 200142" src="https://user-images.githubusercontent.com/55918381/235351846-ca34a19c-eab7-4e9f-b285-11a5016d5942.png">

from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.schedulers.background import BackgroundScheduler

**Comment by agronholm** [comment]
Have you created a module named `apscheduler.py` somewhere in your codebase?

**Comment by msher100** [comment]
I am, for practice of apshcedule I just learned. Damn, so so so stupid I am.Thank you so much for your quick response.Michael HerrSent from my iPhoneOn Apr 30, 2023, at 20:04, Alex Grönholm ***@***.***> wrote:﻿
Have you created a module named apscheduler.py somewhere in your codebase?
