### ISSUE TITLE
window 2019   BlockingScheduler  run error

### ISSUE THREAD

**Issue by songsh** [agronholm/apscheduler#745]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1-post1

### What happened?

timer don't run,   Scheduled tasks are executed once or twice but not executed

### How can we reproduce the bug?

```python
def job2():
    print('job2')

if __name__=="__main__":
    scheduler = BlockingScheduler()
    scheduler.add_job(job2, 'cron', day_of_week='0-6', hour=19, minute=5)
    file_handler = logging.FileHandler("log2.txt", encoding="UTF-8")
    logging.getLogger().addHandler(file_handler)
    scheduler._logger = logging
    scheduler.start()
```

**Comment by agronholm** [comment]
What do you mean "executed but not executed"? That doesn't make sense.

**Comment by songsh** [comment]
Scheduled tasks are executed once or twice , and stop run

**Comment by agronholm** [comment]
Have you tried added debug logging?

**Comment by songsh** [comment]
i debug, not work

**Comment by agronholm** [comment]
This is not helpful, as it doesn't give me any more information to help you. What are you seeing in the debug log? Does it help if you decrease the interval? Have you tried on other operating systems?

**Comment by agronholm** [comment]
Closing due to lack of responses.
