### ISSUE TITLE
When change the os's time, the apcheduler can't work well

### ISSUE THREAD

**Issue by sangensong** [agronholm/apscheduler#752]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.1

### What happened?

first, I run the python file
second, when I run the cmd below on linux
```sh
date -s 20220711
```
the task will not run forever

### How can we reproduce the bug?

```python
import datetime
from apscheduler.executors.pool import ThreadPoolExecutor

from apscheduler.schedulers.blocking import BlockingScheduler


def hello():
    print('hello', datetime.datetime.now())


def world():
    print("world", datetime.datetime.now())


def hello_world():
    print("hello_world", datetime.datetime.now())


max_thread_num = 20
tasks = [
    {
        'func': hello,
        'trigger': 'interval',
        'seconds': 1,
        'coalesce': False
    },
    {
        'func': world,
        'trigger': 'interval',
        'seconds': 2,
        'coalesce': False
    },
    {
        'func': hello_world,
        'trigger': 'interval',
        'seconds': 3,
        'coalesce': False
    },

]
executors = {
    'default': ThreadPoolExecutor(max(max_thread_num, len(tasks)))
}
task_start_interval = 1
scheduler = BlockingScheduler(executors=executors)
next_run_time = datetime.datetime.now()
for task in tasks:
    next_run_time += datetime.timedelta(seconds=task_start_interval)
    task['next_run_time'] = next_run_time
    scheduler.add_job(**task)
scheduler.start()
```

**Comment by agronholm** [comment]
How would the scheduler know to get notified of system clock changes?

**Comment by sangensong** [comment]
I think below code might have design error. It's impossible to notify event when `self._event.wait(wait_seconds)` will wait too long time
```python
    def _main_loop(self):
        wait_seconds = TIMEOUT_MAX
        while self.state != STATE_STOPPED:
            self._event.wait(wait_seconds)
            self._event.clear()
            wait_seconds = self._process_jobs()
```

**Comment by agronholm** [comment]
Can you explain? This code is waiting for any notification for `wait_seconds`, and proceeds to process the jobs if there is no notification within that time.

**Comment by agronholm** [comment]
I've opened #794 as a feature request. That should cover this case if I understood correctly.
