### ISSUE TITLE
dictionary changed size during iteration in update_job

### ISSUE THREAD

**Issue by sbofirov** [agronholm/apscheduler#753]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.6.0

### What happened?

I have a job with interval 1 minute. In the arguments it contains instance of django model.
The job was executed successfully and after that it should be rescheduled.
Then during the serialization I saw following error:
```
Exception in thread APScheduler:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/argos/.local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 30, in _main_loop
    wait_seconds = self._process_jobs()
  File "/home/argos/.local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 995, in _process_jobs
    jobstore.update_job(job)
  File "/home/argos/.local/lib/python3.6/site-packages/apscheduler/jobstores/sqlalchemy.py", line 105, in update_job
    'job_state': pickle.dumps(job.__getstate__(), self.pickle_protocol)
RuntimeError: dictionary changed size during iteration
```
What could be the reason?

* It's because of the serialization of django model
* job itself was modified during serialization
* concurrency problem

I think lock mechanism will prevent 2 & 3.

### How can we reproduce the bug?

I'm not able to reproduce is it.

**Comment by agronholm** [comment]
What do you think I should do about this? How can you be sure this is a problem with APScheduler? More than likely it's because whatever is being pickled is being altered in during the pickling operation.

**Comment by sbofirov** [comment]
It was just a question. 
Maybe it was wrongly assigned as a bug even though the interval job was not rescheduled anymore.
So I removed django model from scheduler job to prevent serialization problems.

**Comment by agronholm** [comment]
There's a [Q&A](https://github.com/agronholm/apscheduler/discussions/categories/q-a) section in the discussion forum.

**Comment by jskcnsl** [comment]
I'm having the same problem (python 3.10, version 3.10.1), is there any way to avoid this ? Make sure arguments of apscheduler job fixed, or something else ?

And I found this error will block all job's before I restart scheduler.
