### ISSUE TITLE
Fast-track the next run of the job

### ISSUE THREAD

**Issue by omacchioni** [agronholm/apscheduler#757]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Sorry, I did not find how to do this in the FAQ.

I would like to force an "interval" job to be processed at the earliest possible date (taking into account constraints, like the `max_instances` configuration)

### Use case

* I have a job running every 30 minutes checking for events
* The processing takes a few seconds
* Sometimes I *know* there is an event waiting, and I want to process it as soon as possible - so I would like to run my scheduled job (except if it's already running of course.... if it's running I want to re-run it as soon as possible)
* If I could refer to the running job using its ID and queue an immediate run, while keeping the interval settings, I'd be happy
* Then of course the job needs to continue his life and restart after 30 minutes (or 30 minutes after the last normal run, I don't really care)

**Comment by agronholm** [comment]
> Sometimes I know there is an event waiting, and I want to process it as soon as possible - so I would like to run my scheduled job (except if it's already running of course.... if it's running I want to re-run it as soon as possible)

If you know an event is waiting, why don't you process it in the same job? Why do you need to spawn another job for this?

**Comment by omacchioni** [comment]
Because the job may already be running, and don't want 2 instances of the job running in parallel. I want to re-use apscheduler's `max_instances` limitation mechanism, not re-implement it.

**Comment by agronholm** [comment]
I'm not suggesting to run two jobs in parallel, but why not handle the next even within the same job?

**Comment by omacchioni** [comment]
Sorry, I was not clear.

The event is not generated within the job, it's generated in an asynchronous process.

So we have 2 things:

(1) Asynchronous process generating an event once in a while. I don't have control of the timing here, I'm called by another system.
(2) Scheduled job running every 30 minutes to process the events - some of them have been generated by (1), some by other systems

When (1) happens, I would like to start the job (2) at the earliest occurence.

**Comment by agronholm** [comment]
Ok, couldn't you just react to 1) by firing up a new job for the task via `scheduler.add_job()`?

**Comment by omacchioni** [comment]
Possibly - but won't this potentially conflict with a run of the same job which would have be triggered by the scheduler ?

The risk I see is the following sequence of events:

1 - job is started by scheduler, `max_instances` = 1
2 - event happens (jobs is still running)
3 - add_job() is called by the process generating the event... but job is still running... so we have 2 instances of the job running, which is not what I want because `max_instances` is 1

**Comment by agronholm** [comment]
If you think two jobs could run concurrently even with `max_instances=1`, what do you suppose the setting does then?

**Comment by omacchioni** [comment]
My understanding was that `max_instances` limits the number of instances for a given job in case it takes longer to run than its frequency - cf https://apscheduler.readthedocs.io/en/3.x/userguide.html#limiting-the-number-of-concurrently-executing-instances-of-a-job

This code shows the issue I have:

``` python
from apscheduler.schedulers.background import BackgroundScheduler

import logging
import time

logging.basicConfig()
logging.getLogger('apscheduler').setLevel(logging.DEBUG)
logger = logging.getLogger()

def event_processor():
    logger.warning("Job Start")
    time.sleep(5)
    logger.warning("Job End")

if __name__ == '__main__':
    scheduler = BackgroundScheduler()

    # Regular event_processor which runs once in a while
    scheduler.add_job(event_processor, "interval", seconds=10, max_instances=1)
    scheduler.start()

    # Simulating an asynchronous event for which I want to trigger the job immediately.
    time.sleep(12)   # Supposabely I would receive and process the event here
    scheduler.add_job(event_processor, max_instances=1)     # Trigger job ASAP with add_job()
    time.sleep(30)
```

Running it gives:

```
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "event_processor" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-11-13 23:33:17.949225+01:00 (in 9.998909 seconds)
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "event_processor (trigger: interval[0:00:10], next run at: 2023-11-13 23:33:17 CET)" (scheduled at 2023-11-13 23:33:17.949225+01:00)
WARNING:root:Job Start
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-11-13 23:33:27.949225+01:00 (in 9.999131 seconds)
INFO:apscheduler.scheduler:Added job "event_processor" to job store "default"
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "event_processor (trigger: date[2023-11-13 23:33:19 CET], next run at: 2023-11-13 23:33:19 CET)" (scheduled at 2023-11-13 23:33:19.951273+01:00)
WARNING:root:Job Start
INFO:apscheduler.scheduler:Removed job 079bce04a0984794b8042ef38fed46e5
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-11-13 23:33:27.949225+01:00 (in 7.995872 seconds)
WARNING:root:Job End
INFO:apscheduler.executors.default:Job "event_processor (trigger: interval[0:00:10], next run at: 2023-11-13 23:33:27 CET)" executed successfully
WARNING:root:Job End
INFO:apscheduler.executors.default:Job "event_processor (trigger: date[2023-11-13 23:33:19 CET], next run at: 2023-11-13 23:33:19 CET)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-11-13 23:33:37.949225+01:00 (in 9.999476 seconds)
INFO:apscheduler.executors.default:Running job "event_processor (trigger: interval[0:00:10], next run at: 2023-11-13 23:33:37 CET)" (scheduled at 2023-11-13 23:33:27.949225+01:00)
WARNING:root:Job Start
[...]
```

We can see that there are 2 consecutive "Job Start", so `max_instances` is not respected (why would it be? There is nothing linking those 2 add_jobs() besides the function name)

**Comment by agronholm** [comment]
Oh, I see where the confusion comes from. My head was totally in the 4.x world now, where you can define a *task* and set its `max_running_jobs` to 1. Apologies. Then again, even in 4.x, the setting doesn't work properly yet, and I spent some time last weekend working on that specific code.

So to sum this up, what you want will be totally doable in 4.x once I get the setting working properly. Unfortunately I have no intention of adding new features to the 3.x series.

**Comment by omacchioni** [comment]
Thank you for your answer and the time you've spent to understand my issue, and I hope it gives you interesting information on how people are using / abusing of apscheduler.

**Comment by agronholm** [comment]
Given that `max_running_jobs` should now work on master, I'm closing this issue as there's nothing else to be done.
