### ISSUE TITLE
TypeError: SQLAlchemyDataStore._retry.<locals>.after_attempt() missing 1 required positional argument: 'retry_state'

### ISSUE THREAD

**Issue by Henkhogan** [agronholm/apscheduler#759]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

4.0 | Commit ab53b012f11eee9e6a67e3f1e31ccc35c9839a85

### What happened?

`    schedules = await self.data_store.acquire_schedules(self.identity, 100)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/apscheduler/datastores/sqlalchemy.py", line 509, in acquire_schedules
    async for attempt in self._retry():
  File "/venv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 317, in iter
    self.after(retry_state)
TypeError: SQLAlchemyDataStore._retry.<locals>.after_attempt() missing 1 required positional argument: 'retry_state'`

### How can we reproduce the bug?

Use the SQLAlchemyDataStore

apparently the self argument was added wrongly [here](https://github.com/agronholm/apscheduler/blob/ab53b012f11eee9e6a67e3f1e31ccc35c9839a85/src/apscheduler/datastores/sqlalchemy.py#L156)

PR: https://github.com/agronholm/apscheduler/pull/760

**Comment by agronholm** [comment]
Fixed via #760.
