### ISSUE TITLE
LookupError: No trigger by the name "interval" was found

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#77]
Originally reported by: **Rodrigo Brim (Bitbucket: [rodrigo_brim](http://bitbucket.org/rodrigo_brim), GitHub: Unknown)**

---

Hello.

I'm getting this error with OSX 10.9.4. The following lines describes my problem. Sorry if this is a stupid post.

```
#!bash

rbr:python rodrigo$ pip list | grep -i apscheduler
APScheduler (3.0.1)
```

rbr:python rodrigo$ cat ./schedule.py 

```
#!python

#!/usr/bin/python
from datetime import datetime
import os

from apscheduler.schedulers.blocking import BlockingScheduler

def tick():
    print('Tick! The time is: %s' % datetime.now())

if __name__ == '__main__':
    scheduler = BlockingScheduler()
    scheduler.add_job(tick, 'interval', seconds=3)
    print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))

    try:
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        pass
```

```
#!bash

rbr:python rodrigo$ ./schedule.py 
Traceback (most recent call last):
  File "./schedule.py", line 14, in <module>
    scheduler.add_job(tick, 'interval', seconds=3)
  File "/Library/Python/2.7/site-packages/apscheduler/schedulers/base.py", line 330, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/Library/Python/2.7/site-packages/apscheduler/schedulers/base.py", line 782, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/Library/Python/2.7/site-packages/apscheduler/schedulers/base.py", line 766, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No trigger by the name "interval" was found
rbr:python rodrigo$
```

---
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/77

**Comment by nstanoszek** [comment]
Hi, I am seeing this issue with py2exe suddenly on the latest versions.  I have updated setuptools and everything, but have no luck.  When not frozen, APScheduler works wonderfully!

Thoughts?

**Comment by delphiai** [comment]
Hi, I am also experiencing this problem, my traceback is as follows, when i install via pip no errors are prevalent.

However when installing via easy install I get this error:

```
  File "build\bdist.win-amd64\egg\apscheduler\executors\base_py3.py", line 12
    async def run_coroutine_job(job, jobstore_alias, run_times, logger_name):
            ^
SyntaxError: invalid syntax

creating c:\users\delphi\anaconda2\lib\site-packages\apscheduler-3.3.1-py2.7.egg
Extracting apscheduler-3.3.1-py2.7.egg to c:\users\delphi\anaconda2\lib\site-packages
  File "c:\users\delphi\anaconda2\lib\site-packages\apscheduler-3.3.1-py2.7.egg\apscheduler\executors\base_py3.py", line 12
    async def run_coroutine_job(job, jobstore_alias, run_times, logger_name):
            ^
SyntaxError: invalid syntax

Adding apscheduler 3.3.1 to easy-install.pth file

Installed c:\users\delphi\anaconda2\lib\site-packages\apscheduler-3.3.1-py2.7.egg
Processing dependencies for apscheduler
Finished processing dependencies for apscheduler
```

This is the error my traceback is producing

```
  File "C:\Users\Delphi\Anaconda2\lib\site-packages\apscheduler\schedulers\base.py", line 888, in _create_plugin_instance

LookupError: No trigger by the name "interval" was found
```

Thanks in advance for help

**Comment by agronholm** [comment]
You're seeing those messages because easy_install tries to compile them to bytecode, which fails when a Python 2 interpreter encounters Python 3 syntax. It's harmless.

**Comment by ierturk** [comment]
Hi, I experienced the problem and fixed as explained at [this link](https://stackoverflow.com/a/53938833/4187237)

**Comment by DanieleB89** [comment]
Problem is still here

**Comment by agronholm** [comment]
@DanieleB89 Are you using PyInstaller or what else is causing your problem?

**Comment by DanieleB89** [comment]
my actions:
pip install apscheduler

got this:
Successfully installed apscheduler-3.6.3 pytz-2020.1 setuptools-47.3.1 six-1.15.0 tzlocal-2.1


in a random .py file:
"
from apscheduler.schedulers.background import BackgroundScheduler

def job1():
    print("Job 1 fired")

scheduler = BackgroundScheduler()
scheduler.add_job(job1, 'interval', seconds=2, id="job1")
scheduler.start()
"

after esecution got this error:
Got this:
  File "...\lib\site-packages\apscheduler\schedulers\base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "...\lib\site-packages\apscheduler\schedulers\base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "...\lib\site-packages\apscheduler\schedulers\base.py", line 904, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No trigger by the name "interval" was found

**Comment by agronholm** [comment]
That is strange. But if this was a general problem with pip installs, a lot more people would come here to complain about it.
Are you running this on Windows?

**Comment by DanieleB89** [comment]
Yes, I made few changes to the code and I got it running. I've posted my code fix here: https://stackoverflow.com/questions/28682723/no-trigger-by-the-name-interval-was-found/

**Comment by agronholm** [comment]
This still doesn't explain why the trigger lookup failed, even though you have recent versions of all the involved tools.

**Comment by DanieleB89** [comment]
I'm new to apscheduler, maybe it's something I did wrong. I found this library interesting: no problem for me if it's just an alias not working (at least for me).

**Comment by agronholm** [comment]
Yes, I understand. But I don't see anything wrong with your code.

**Comment by n2201** [comment]
Have you restarted the kernel after the restart? That could be your problem

**Comment by agronholm** [comment]
> Have you restarted the kernel after the restart? That could be your problem

Uh, what?
