### ISSUE TITLE
python 3.9 APScheduler have unexcept keyword

### ISSUE THREAD

**Issue by JE-Chen** [agronholm/apscheduler#770]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

 APScheduler-3.10.2-py3-none-any

### What happened?

On python3.9 import APScheduler will raise an error.
All my package on python 3.9 using APScheduler CI/CD Failed but success on 3.8, 3.10, 3.11

### How can we reproduce the bug?

import APScheduler on python 3.9
![image](https://github.com/agronholm/apscheduler/assets/33644111/3eda6309-04b9-4526-93cf-246de445666d)
![image](https://github.com/agronholm/apscheduler/assets/33644111/a63cbd0e-cd01-44fe-aef5-f278662c4ecd)

**Comment by agronholm** [comment]
Fixed by #773.
