### ISSUE TITLE
`AndTrigger` `get_next_fire_time` is not returning value in a specific case

### ISSUE THREAD

**Issue by juguerre** [agronholm/apscheduler#783]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.4

### What happened?

`AndTrigger` `get_next_fire_time` is not returning value when firetimes from inner triggers are different (last `else`), as shown in code from `combining.py`

```python
    def get_next_fire_time(self, previous_fire_time, now):
        while True:
            fire_times = [trigger.get_next_fire_time(previous_fire_time, now)
                          for trigger in self.triggers]
            if None in fire_times:
                return None
            elif min(fire_times) == max(fire_times):
                return self._apply_jitter(fire_times[0], self.jitter, now)
            else:
                now = max(fire_times)
```

### How can we reproduce the bug?

Just combining with `AndTrigger`  two triggers returning different firetimes ... the job then is never triggered.

**Comment by juguerre** [comment]
Just adding:
```python
return now
```
Seems to fix the problem.

**Comment by agronholm** [comment]
The point of `AndTrigger` is to return any fire times that the two triggers agree on. If you feed it two triggers that never agree on a fire time, what is the trigger then expected to return?

**Comment by juguerre** [comment]
Exactly `max(fire_times)` meaning the most 'limiting' `fire_time`. That is what I expected. 
Anyway, if the intended behaviour is only return fire_time is all triggers agree ... is not an evident behaviour.

**Comment by agronholm** [comment]
> Exactly `max(fire_times)` meaning the most 'limiting' `fire_time`. That is what I expected. Anyway, if the intended behaviour is only return fire_time is all triggers agree ... is not an evident behaviour.

How so? Have you read the documentation of `AndTrigger`? The first line says exactly this:
> Always returns the earliest next fire time that all the given triggers can agree on.

**Comment by agronholm** [comment]
In `master` (APScheduler 4.x), `AndTrigger` has a threshold setting that allows some leeway for determining if the fire times match or not, so they don't have to match exactly. This allows for combining `IntervalTrigger` and `CronTrigger`.

**Comment by juguerre** [comment]
@agronholm if  it's working as intended no problem ... just close this issue.
I did not read the documentation on that point obviously, just because I thought I was understanding correctly, sorry.
I see now that my need is not covered with `AndTrigger` ... AndMaxTrigger could be a possible new trigger class for that need.
Thanks for your time.
