### ISSUE TITLE
Distinguishing between deletion events in different situations

### ISSUE THREAD

**Issue by GOOD-AN** [agronholm/apscheduler#792]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

It is possible to distinguish between a deletion event caused by the completion of the execution of a job plan and an event in which a job is explicitly deleted.

### Use case

In practice, the deletion event caused by the completion of the execution of a job plan and the event that a job is explicitly deleted will trigger different functions to run, and the results of the runs will be completely different.

**Comment by agronholm** [comment]
Implemented via the `finished` attribute of the `ScheduleRemoved` event (a67a82c821d5eeb882192d453dea215f7e8987bf).

**Comment by GOOD-AN** [comment]
Wow! Thank you!!!
