### ISSUE TITLE
imports does not work

### ISSUE THREAD

**Issue by yyokusa** [agronholm/apscheduler#796]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.4

### What happened?

Imports does not work.

pip list
Package     Version
----------- ------------
APScheduler 3.10.4

python
Python 3.11.0 (main, Oct 10 2023, 00:19:53) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from apscheduler import Scheduler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Scheduler' from 'apscheduler' (/Users/<user>/.pyenv/versions/venv3-11/lib/python3.11/site-packages/apscheduler/__init__.py)

python
Python 3.11.0 (main, Oct 10 2023, 00:19:53) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from apscheduler import AsyncScheduler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'AsyncScheduler' from 'apscheduler' (/Users/<user>/.pyenv/versions/venv3-11/lib/python3.11/site-packages/apscheduler/__init__.py)

### How can we reproduce the bug?

Just try imports from the given code example in the link:

https://apscheduler.readthedocs.io/en/master/userguide.html#running-the-scheduler

--> from apscheduler import AsyncScheduler

**Comment by agronholm** [comment]
Are you looking at the correct version of the documentation for the version you have installed?

**Comment by agronholm** [comment]
The link seems to point to master while you're running the 3.x series.

**Comment by yokusrelynkno** [comment]
Thank you!

**Comment by yyokusa** [comment]
Thank you!

**Comment by scaleoutsean** [comment]
> The link seems to point to master while you're running the 3.x series.

To be fair the docs link in GH 3.0 branch (https://github.com/agronholm/apscheduler/tree/3.0) points to that `latest` (master) location rather than the expected [3.x](https://apscheduler.readthedocs.io/en/3.x/userguide.html) docs. That got me as well.

**Comment by ekeric13** [comment]
considering 4.0 is pre-release, it would be great if the docs defaulted to stable (3.x) and not to master. just a suggestion! either way glad the docs are being published for all the versions.

**Comment by agronholm** [comment]
They DO default to 3.x – https://apscheduler.readthedocs.io/ redirects to the 3.x documentation. Likewise, the documentation link on PyPI also points to the 3.x docs. Where did YOU arrive to the master docs?

**Comment by agronholm** [comment]
> > The link seems to point to master while you're running the 3.x series.
> 
> To be fair the docs link in GH 3.0 branch (https://github.com/agronholm/apscheduler/tree/3.0) points to that `latest` (master) location rather than the expected [3.x](https://apscheduler.readthedocs.io/en/3.x/userguide.html) docs. That got me as well.

Wrong branch – the 3.x branch contains the latest 3.x code.
