### ISSUE TITLE
Add tags to tasks, schedules and jobs

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#798]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Tasks, schedules and jobs could have tags assigned to them. Schedulers could then pick only jobs that have compatible tags.

### Use case

This will greatly help in heterogeneous environments where you need certain hardware or a certain operating system to run a particular job.

**Comment by agronholm** [comment]
@NikBiks You can make your case here for a simpler solution.

**Comment by NixBiks** [comment]
Not sure I understand your thinking around using < or > in the tags. Should tags simply be unique strings?

The moment you create a job, task or a schedule, you can also add a list of tags for it. And when you start a worker you can provide a list of tags to consume from. We can jump on a call sometime if you want (I'm in Copenhagen so same time zone I think) - not today though

**Comment by agronholm** [comment]
Suppose a job runs code that requires a specific Python version, or some other metric. It's very impractical to have to enable every valid value in the scheduler where valid tag values can be a numeric range.

**Comment by agronholm** [comment]
Imagine an AI related job requiring a certain amount of VRAM. Only schedulers hosted on machines that have at least that much VRAM available should pick up those jobs.

**Comment by agronholm** [comment]
The closest implementation that I can think of is the [node affinity](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/) system in Kubernetes.

**Comment by agronholm** [comment]
I guess the term "tag" would be somewhat misleading in this case then.

**Comment by NixBiks** [comment]
I think that gets complex real fast. I'd definitely advocate for a simple string - at least as the first step. The other feature could raise all kinds of trouble I think. 

If not a simple string solution then you might want to rename to worker_consume_conditions or similar.

**Comment by agronholm** [comment]
Completed via f36a398c.
