### ISSUE TITLE
Allow multiple jobs to be scheduled in one scheduler instance

### ISSUE THREAD

**Issue by carkod** [agronholm/apscheduler#802]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Provide maybe an `add_jobs` method that allows multiple jobs to be scheduled. E.g.
```python
from apscheduler.schedulers.background import BackgroundScheduler
scheduler = BackgroundScheduler()

def job1():
    for _ in range(1000):
        print('a')

def job2():
    for _ in range(1000):
        print('b')

h = 10 
m = 0

scheduler.add_jobs([
  { job1, 'cron', hour=h, minute=m },
  { job2,'cron', hour=h ,minute=m },
  ...
])
scheduler.start()
atexit.register(lambda: scheduler.shutdown())
```

Such that `add_jobs` takes a `list` of parameters.

Searching existing issues, [this one may be related](https://github.com/agronholm/apscheduler/issues/671) but I believe it's a little different and the OP didn't provide a solution.

### Use case

Currently, it looks like the [only way to add multiple jobs](https://stackoverflow.com/questions/52933597/can-apscheduler-run-two-jobs-with-same-cron-trigger) is to set them seperately, e.g.:

```python
from apscheduler.schedulers.background import BackgroundScheduler
scheduler = BackgroundScheduler()

def job1():
    for _ in range(1000):
        print('a')

def job2():
    for _ in range(1000):
        print('b')

h = 10 
m = 0

scheduler.add_job(job1,'cron',hour=h,minute=m)
scheduler.add_job(job2,'cron',hour=h,minute=m)
scheduler.start()
atexit.register(lambda: scheduler.shutdown())
```
Looking [in the codebase](https://github.com/search?q=repo%3Aagronholm%2Fapscheduler%20add_job&type=code), I don't see an option to do it at the moment

**Comment by agronholm** [comment]
Sorry, didn't notice this before. What is the motivation behind this request? That is, what's the problem with making separate calls to add jobs?

**Comment by agronholm** [comment]
Closing due to lack of responses.
