### ISSUE TITLE
Arbitrarily fired triggers.

### ISSUE THREAD

**Issue by nuno-andre** [agronholm/apscheduler#818]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

It would be great to leverage the events system to able to launch jobs programmatically. Something like:

```python
    ...
    async with AsyncScheduler() as scheduler:
        await scheduler.add_schedule(fn, EventTrigger(), id='some_id')
    ...
```

And then, from elsewhere in the code:
```python
    ...
    event = TriggerEvent(id='some_id')
    await event.fire()
    ...
```

I have tried to do it myself but I have to pass the scheduler to the trigger, `current_async_scheduler` returns `None` at initialization.

### Use case

Probably none that is not covered by `.add_job()`, but it could simplify many workflows.

**Comment by agronholm** [comment]
How would the `EventTrigger` class work? I'm not comprehending this.

**Comment by agronholm** [comment]
Closing due to lack of responses.
