### ISSUE TITLE
404 Not Found when accessing the API reference from `master` version to any other version

### ISSUE THREAD

**Issue by achieveordie** [agronholm/apscheduler#855]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

master

### What happened?

The documentation link from the README directs us towards https://apscheduler.readthedocs.io/en/master/, i.e. the master version of the docs, if we open the API reference and then try to switch to different versions (`stable`, `3.x`, `latest`) we get a 404.

This is happening because the path for the previous versions was `/py-modindex` (eg: https://apscheduler.readthedocs.io/en/latest/py-modindex.html) whereas the master version has `/api` (https://apscheduler.readthedocs.io/en/master/api.html#).

There's a redirect missing which would switch from `api` to `py-modindex` in case older versions are accessed.

### How can we reproduce the bug?

I'm mentioning the exact steps to follow for further clarity:

#### Steps to follow:
1. Visit the link https://apscheduler.readthedocs.io/en/master/ from README.
2. Click on the API Reference tab on the left.
3. Change to any other version from the bottom left corner:
![image](https://github.com/agronholm/apscheduler/assets/54197164/745cbe2f-5474-42c0-ae3d-582f6cdbf9cc)
4. Voila, 404 not found:
![image](https://github.com/agronholm/apscheduler/assets/54197164/9121fe62-6b42-4dcb-be3e-0dccf7a6e354)

**Comment by agronholm** [comment]
The API reference is structured differently in v3 and v4, so you need to first go to the index, switch versions and then click on the API reference.
