### ISSUE TITLE
AsyncIOScheduler not working with MongoDBJobStore (PicklingError)

### ISSUE THREAD

**Issue by difhel** [agronholm/apscheduler#871]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.4

### What happened?

I use asyncio scheduler because my project uses an asyncio based framework (aiogram). When I receive a message, I create a task that will execute after a certain number of seconds:
```py
@router.message(Command("schedule"))
async def aps(message: Message):
    seconds_delay = int(message.text.split()[-1])
    job = SchedulerWrapper().add_job(
        my_function,
        "date",
        run_date=datetime.datetime.now() + datetime.timedelta(seconds=seconds_delay),
        args=[message]
    )
    print(job)
    await message.answer("Scheduled")
```
Here's my code with the scheduler (I'm using Singleton wrapper to make sure only one scheduler object is used):
```py
import apscheduler.schedulers.asyncio
from apscheduler.jobstores.mongodb import MongoDBJobStore
from apscheduler.jobstores.memory import MemoryJobStore
from shared.db import client

jobstores = {
    "default": MongoDBJobStore("giveaways-bot", client=client)
}
# jobstores = {
#     "default": MemoryJobStore()
# }

class SchedulerWrapper:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance.scheduler = apscheduler.schedulers.asyncio.AsyncIOScheduler(
                jobstores={'default': MongoDBJobStore(client=client)},
                job_defaults={'misfire_grace_time': 1},
                timezone='UTC',
                serializer="json"
            )
            cls._instance.scheduler.start()
        return cls._instance

    def add_job(self, *args, **kwargs):
        return self.scheduler.add_job(*args, **kwargs)

    def shutdown(self):
        self.scheduler.shutdown()

async def my_function(message) -> None:
    await message.answer("pong")
```
If you uncomment and use memory jobstore instead of MongoDB, the code works perfectly. This error occurs with MongoDB:
```
Traceback (most recent call last):
  <erased aiogram trace>
  File "/mnt/c/Users/Mark/Desktop/Projects/kwork/giveaways/bot/routers/admin/router.py", line 110, in admin_set_winners
    job = SchedulerWrapper().add_job(
  File "/mnt/c/Users/Mark/Desktop/Projects/kwork/giveaways/bot/scheduler.py", line 53, in add_job
    return self.scheduler.add_job(*args, **kwargs)
  File "/mnt/c/Users/Mark/Desktop/Projects/kwork/giveaways/.venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 457, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "/mnt/c/Users/Mark/Desktop/Projects/kwork/giveaways/.venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 881, in _real_add_job
    store.add_job(job)
  File "/mnt/c/Users/Mark/Desktop/Projects/kwork/giveaways/.venv/lib/python3.10/site-packages/apscheduler/jobstores/mongodb.py", line 89, in add_job
    'job_state': Binary(pickle.dumps(job.__getstate__(), self.pickle_protocol))
_pickle.PicklingError: Can't pickle <function AsyncIOScheduler.wakeup at 0x7f943470f490>: it's not the same object as apscheduler.schedulers.asyncio.AsyncIOScheduler.wakeup
```

### How can we reproduce the bug?

See the code above

**Comment by agronholm** [comment]
I tried running your script but it complains about the `shared.db` import.

**Comment by difhel** [comment]
I have prepared an MRE for this problem. Don't forget to insert your token in bot/main.py:12. 

Link: https://github.com/difhel/aps-mre-2. 

Note [bot/routers/admin/router.py:17-19](https://github.com/difhel/aps-mre-2/blob/master/bot/routers/admin/router.py#L17). 
This is an empty function that never triggers and does nothing. However, if you comment out this function, the error changes to another (see #872). This is very strange, I have no idea why this happens or how to fix it. Obviously it's a bug in either aiogram, aps, or pickle, but in any of the three cases I have absolutely no idea how to solve this further. It was already very hard to find, out of 5000 lines of code, **exactly which empty function breaks the code when deleted**.

By the way, thank you for your great work on this lib.

**Comment by agronholm** [comment]
So...how do I install and run this?

**Comment by agronholm** [comment]
I'm closing this due to the lack of responses. You need to provide me a MINIMUM workable example – that is, not something that requires a Discord token or something else. If this cannot be reproduced without the Discord Python library, then maybe that's the issue? Either way, it's your responsibility to figure out if APScheduler is really the problem, not mine. I'll reopen the issue if you work that out.

**Comment by magameda1337** [comment]
I got the same, but with RedisJobStore

**Comment by magameda1337** [comment]
![Image](https://github.com/user-attachments/assets/d7a5a01f-e479-4fb0-a124-da0c150e6099)
```
AsyncIOScheduler(jobstores = {
    "default": RedisJobStore(
        jobs_key="dispatched_trips_jobs", run_times_key="dispatched_trips_running",
        host="localhost", port=6379
    )
```

[sample.zip](https://github.com/user-attachments/files/20967509/sample.zip) There is an sample, that was build using alembic+sqlalchemy

**Comment by magameda1337** [comment]
I think that is my error, but idk where im done something wrong, pickle fails to dump my repositories, maybe you have some advices? Currently idk what job storage i shall set

**Comment by agronholm** [comment]
Please read the instructions on how to create a MWE: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by magameda1337** [comment]
> Also, are you sure you're using the latest APScheduler version? The latest version should emit a more informative error on a pickling failure.

   "apscheduler>=3.11.0",

**Comment by agronholm** [comment]
You probably shouldn't use the alpha, as it's not compatible with the v3.x series.

So tell me, what do I do with your sample code to get the error you described?

**Comment by magameda1337** [comment]
Well, firstly i installed it via uv add apscheduler, i thinked that 3.x was last version (i dont checked your git), currently im trying to get how i can use your scheduler (4.x version) 
from apscheduler import AsyncScheduler, Schedule


```
class SchedulerService:
    def __init__(self, scheduler: AsyncScheduler):
        self.scheduler = scheduler


    async def add_job(self, *args, **kwargs):
        async with self.scheduler as scheduler:
            await scheduler.start_in_background()
            await scheduler.add_schedule(*args, **kwargs)


    async def remove_job(self, job_id: str):
        async with self.scheduler as scheduler:

            await scheduler.remove_schedule(job_id)

```
```
2025-06-29 19:51:30,097 - apscheduler._schedulers.async_ - INFO - Scheduler started
2025-06-29 19:51:30,099 - apscheduler._schedulers.async_ - INFO - Added new schedule (task='app.windows.deposit:delete_invoice', trigger=DateTrigger('2025-06-29 19:52:09.684053+05:00')); next run time at 2025-06-29 19:52:09.684053+05:00
2025-06-29 19:51:30,099 - apscheduler._schedulers.async_ - INFO - Scheduler stopped
2025-06-29 19:51:31,105 - apscheduler._schedulers.async_ - INFO - Cleaned up expired job results and finished schedules
2025-06-29 19:51:31,106 - apscheduler._schedulers.async_ - INFO - Scheduler started
2025-06-29 19:51:31,112 - apscheduler._schedulers.async_ - INFO - Added new schedule (task='app.windows.deposit:check_deposit', trigger=IntervalTrigger(seconds=15.0, start_time='2025-06-29 19:51:31.101932+05:00')); next run time at 2025-06-29 19:51:31.101932+05:00
2025-06-29 19:51:31,113 - apscheduler._schedulers.async_ - INFO - Scheduler stopped
```, and it do nothing, how i can contact with it like in previus versions?

**Comment by agronholm** [comment]
Every time you enter and exit the context manager, the scheduler starts and then immediately stops. You don't want that.

**Comment by agronholm** [comment]
If you want help for your original pickling problem, you might want to figure out what you're actually trying to add as the job arguments. There may be associated data that isn't serializable, like file handles, threads, etc.
