### ISSUE TITLE
Create a Cron Trigger with month="*/12" does not work

### ISSUE THREAD

**Issue by JVGC** [agronholm/apscheduler#886]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.4

### What happened?

I'm trying to create a Cron Trigger that runs every 12 months. 

According to docs, the **month** parameter in the CronTrigger goes from 1-12, but I got an error saying it's higher than the total range of the expression

### How can we reproduce the bug?

Here is the error message I received:

`Error validating expression '*/12': the step value (12) is higher than the total range of the expression`

```python

from apscheduler.triggers.cron import CronTrigger
          
 trigger = CronTrigger(
       hour=0,
       minute=0,
       second=0,
       start_date="2024-04-05",
       month="*/12",
       day="1st mon",
)

**Comment by agronholm** [comment]
So which month do you want it to run on?

**Comment by JVGC** [comment]
So, I want it to run every 12 months starting from that start date. In this example, I would want it to run on April 2025

**Comment by JVGC** [comment]
The interval trigger does not support months, and in theory, I could something like this with the CronTrigger, right?
<img width="707" alt="image" src="https://github.com/agronholm/apscheduler/assets/35708958/23ad60ad-11c8-4e90-a4cc-18460f130457">

**Comment by agronholm** [comment]
The cron trigger, only supports firing when the specified conditions match the date/time. It does not have a concept of interval. That is, `*/2` for months would mean the same as `1,3,5,7,9,11`. That is, when the field value's offset from the minimum value is divisible by 2.

APScheduler 4.0 (currently in alpha) comes with a `CalendarIntervalTrigger` that does support firing every X months. But even that doesn't have any way to specify that it should trigger on a specific day of month. Your best bet is therefore to create a custom trigger.

**Comment by agronholm** [comment]
If there is no requirement to run it on a specific day of the month, but rather just on X months intervals, then `CalendarIntervalTrigger` from v4.0 should be perfect for your use case.
