### ISSUE TITLE
background cron job getting stopped after time run 

### ISSUE THREAD

**Issue by Dhiru** [agronholm/apscheduler#904]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

apscheduler-3.10.4 

### What happened?

scheduler.add_job(func=abfunc, trigger='cron', year='\*', month='\*', day=\'*', week='\*', hour='5,10,15,20',minute='20,30')
Job getting stop after two runs (ie. 5.20, 5.30)
i have add background job, it is running on 5hours and 20mins and but for next other hours (ie. 10hours 20mins, 15hours 20)  is not running  and even on next day also it is not running .

### How can we reproduce the bug?

for reproduce set this times
scheduler.add_job(func=abfunc, trigger='cron', year='\*', month='\*', day='*', week='\*', hour='5,10,15,20',minute='20,30')

**Comment by agronholm** [comment]
Have you followed the t[roubleshooting instructions](https://apscheduler.readthedocs.io/en/3.x/userguide.html#troubleshooting) to figure out what could be wrong? Can you reproduce this problem with a more frequently occurring schedule (like changing hours into minutes and minutes into seconds)?
