### ISSUE TITLE
Save results of scheduler jobs, version: 4.0.0a5

### ISSUE THREAD

**Issue by HK-Mattew** [agronholm/apscheduler#927]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

**This is a suggestion for the new version: 4.0.0a5**

I saw that you can save the results of individual jobs in apscheduler. However, it doesn't have or I didn't find the option to save the results of jobs from a scheduler added with Scheduler.add_schedule. (I looked through all the documentation and couldn't find it).

I believe it would be worth adding this feature to Scheduler.add_schedule to be able to save the results of all jobs executed by the scheduler.

_That's my suggestion. I apologize if this doesn't make sense to you._

### Use case

I believe it is essential to be able to have the results of the scheduler's work, as this would be useful for several occasions.

As this is not yet supported, I would have to add a scheduler to create jobs with the option to save job results (I believe this is not very interesting).

**Comment by agronholm** [comment]
You say this is essential, but you provide no reasoning of *why* it would be essential. I left out this possibility precisely because I figured it *wouldn't* be essential. I see it as a big footgun, as it would continuously add more data to the database automatically.

**Comment by HK-Mattew** [comment]
> You say this is essential, but you provide no reasoning of _why_ it would be essential. I left out this possibility precisely because I figured it _wouldn't_ be essential. I see it as a big footgun, as it would continuously add more data to the database automatically.

Specifically in my use case it would be: A scheduler that generates reports with website statistics on certain days/months (and others). And the preference for saving the results of the scheduler's jobs is that I could always use the apscheduler instance itself to get the results of my results for a certain type of report and among others.


You said you see it as a firearm. I don't believe it is, as activating the option to save the results of work would be up to whoever is using it and this option would be disabled by default. And of course, whoever activated this knows the possibilities (And I also believe that the result_expiration_time of the job could be specified, so it wouldn't cause so much confusion).

**Comment by WillDaSilva** [comment]
@HK-Mattew have you considered having your scheduled jobs explicitly save their results to a persistent data store at the end of their execution?

**Comment by agronholm** [comment]
I guess this could be supported as an opt-in feature, by adding a `result_expiration_time` parameter to schedules which defaults to 0.

**Comment by HK-Mattew** [comment]
> I guess this could be supported as an opt-in feature, by adding a `result_expiration_time` parameter to schedules which defaults to 0.

Hi @agronholm

Exactly, this should be an optional feature. This would not be a good idea to be active by default, as this could cause unwanted problems.
