### ISSUE TITLE
Is typo in _context.py?

### ISSUE THREAD

**Issue by mywaiting** [agronholm/apscheduler#956]
### Things to check first

- [x] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

master/v4.0-pre-release

### What happened?

when I read the source in this repo **master branch**, I found the code in `src/apscheduler/_context.py` 

```python

if TYPE_CHECKING:
    from ._structures import Job
    from .schedulers.async_ import AsyncScheduler
    from .schedulers.sync import Scheduler

```

Is typo here? maybe as follow:

```python

if TYPE_CHECKING:
    from ._structures import Job
    from ._schedulers.async_ import AsyncScheduler
    from ._schedulers.sync import Scheduler

```

If there is typo here, I will pull request and fix this.

thanks for creating this awesome tool that make things easier

### How can we reproduce the bug?

Just typo maybe, no need further code to reproduce the bug

**Comment by agronholm** [comment]
Fixed it, thanks for the heads up.
