### ISSUE TITLE
AsyncioExecutor not truly async

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#96]
Originally reported by: **Lennart Bastian (Bitbucket: [bastianl](http://bitbucket.org/bastianl), GitHub: [bastianl](http://github.com/bastianl))**

----------------------------------------

I have been using the `AsyncioScheduler` with the `APScheduler` to schedule tasks asynchronously. However, I want to schedule jobs (coroutines) in the same event loop that the scheduler is running in. 
It looks like the `AsyncioExectutor` is running tasks in a [separate thread](https://bitbucket.org/agronholm/apscheduler/src/f312c39b161011b6c6372960b6985434854fab84/apscheduler/executors/asyncio.py?at=master#cl-27), and not as coroutines but rather regular functions. In fact, it doesn't seem like you can schedule any kind of asynchronous functions. Is this the intended behavior? What's the point of calling it an `asyncio` executor? 

To solve this I modified the function `run_job` to work asynchronously, and tweaked the executor to run jobs as `asyncio.Tasks` which are automatically inserted into the eventloop.
[See this](https://gist.github.com/bastianl/e7a1879f583e69f95c0e).

Maybe we can modularize the `run_job` function and split it into two functions, one of which works asynchronously. Let me know what you think, am happy to submit a pull request.

----------------------------------------
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/96

**Comment by TechBK** [comment]
in your example [asyncio_.py](https://github.com/agronholm/apscheduler/blob/master/examples/schedulers/asyncio_.py)

i try declare function `tick` like:
```
@asyncio.coroutine
def tick()
```
, although, no error was raised, it not done.

How i work with AsyncioScheduler?

**Comment by agronholm** [comment]
Scheduling of coroutine functions is marked to be implemented in the 3.3 milestone. Meanwhile, you can use the event loop's `call_later_threadsafe()` function to make your code run in the event loop thread.

**Comment by TechBK** [comment]
Plzzz, illustrate example how to use `call_soon_threadsafe()` with AsyncioScheduler?

**Comment by txomon** [comment]
@agronholm Does it have any blocking issues that should be taken care of?

**Comment by agronholm** [comment]
This particular thing doesn't. However, the next step is to get 3.2.0 out which will fix the use case 3.1.0 broke -- adjusting jobs in job stores before the scheduler starts processing the jobs. The code is done, the tests are just unfinished. I expect to make a release this weekend.

The biggest problem with async execution is that I have to duplicate pretty much all of run_job() for use with scheduled coroutines and I don't want to do that. So I'm still looking for elegant solutions to that.

**Comment by txomon** [comment]
@TechBK  I am now using asyncio executor as the following. being execute() the function used on add_job()

```
import asyncio

async def _coroutine_execute(args):
    print('Executing through coroutine')

def execute(*args):
    try:
        el = asyncio.get_event_loop()
    except RuntimeError:
        el = asyncio.new_event_loop()
        asyncio.set_event_loop(el)

    try:
        el.run_until_complete(_coroutine_execute(args))
    except AttributeError:
        print('Something is going on in the tasks')
```

@agronholm I don't see what you mean. AFA I see, you would just need run a check on the job func and if it's a coroutine, and await from it if so, no?

**Comment by agronholm** [comment]
How would that work with Python 2?

**Comment by txomon** [comment]
Following this?
https://www.python.org/dev/peps/pep-0492/#backwards-compatibility

Other option is to define execute_job() as a function where just the execution of the job is handled, and still have run_job() globally defined, leaving room to each executor implement it's own.

That way, you could reimplement execute_job() in each Executor, making sure that it does what it says (the actual function, is executed in a thread, in a coroutine, in an eventlet, etc.)

The good part of this one is that you wouldn't run into any problems importing asyncio in the AsyncIOExecutor. You would need to move any logic you may have already created to overcome these limitations for other modules (spawning a thread etc.) to the execute_job() function of each executor.

**Comment by agronholm** [comment]
Ok @txomon , can you show me how to write run_job() in a way that work for both coroutine callables and regular functions in a manner that doesn't duplicate all the code?

**Comment by txomon** [comment]
@agronholm check #134

**Comment by TechBK** [comment]
i am waiting for solution of issue :(

**Comment by agronholm** [comment]
And you'll remain waiting for a while. The next release will not fix this -- 3.3 at the earliest will. Meanwhile you can try hacks involving `call_soon_threadsafe()`, `create_task()` and `ensure_future()`.

**Comment by TechBK** [comment]
@txomon i try to run ur code, but when job done, el stop directly.

**Comment by agronholm** [comment]
What are you talking about? What code?

**Comment by agronholm** [comment]
@txomon's code won't work. You can't just add new event loops whenever you feel like it.

**Comment by agronholm** [comment]
You have to pass the **existing** event loop to the scheduled callable and then use `call_soon_threadsafe()`.

**Comment by TechBK** [comment]
`call_soon_threadsafe()` not accept coroutine parameter :-1: 
`BaseEventLoop.call_soon_threadsafe(callback, *args)`
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.call_soon_threadsafe

**Comment by agronholm** [comment]
I know that. You have to pass it a callable which then calls `get_event_loop().create_task(your_coroutine_function())`.

**Comment by agronholm** [comment]
But to enable the runner to properly detect exceptions and such, you need to then have a `concurrent.futures.Future` object. In the event loop thread you do `future.set_result()` or `future.set_exception()` and in the wrapper function (that runs in the thread pool) you do `return future.result()`. I know, it gets hairy. That's why I didn't want to instruct people to do this.

**Comment by TechBK** [comment]
Super thank :+1:

**Comment by evilaliv3** [comment]
@agronholm: we are evaluating to re-adopt apscheduler in GlobaLeaks: https://github.com/globaleaks/GlobaLeaks/issues/1769

What i'm failing to understand is if this functionality is functional in twisted since previous version packaged in Debian/Ubuntu, or if its only available now in relation to python 3.5.

Is there any way to handle this behaviour with twisted and python 2.7 by using the twisted inlineCallbacks?

**Comment by agronholm** [comment]
There is no way to detect `@inlineCallbacks`, so it will not be supported before 4.0. Native coroutines would be doable before that but there is no working test harness for pytest and twisted (pytest-twisted is really old and does not work with native coroutines).

**Comment by evilaliv3** [comment]
i see thank you for the explanation

**Comment by agronholm** [comment]
The fundamental problem here is that currently all those executors default to running the jobs in worker threads. If I change this default behavior, it will break things for a lot of people. I was able to add native coroutine support because they're detectable and didn't work before anyway so I was able to add code that takes a different code path when a coroutine function is detected.

**Comment by evilaliv3** [comment]
understood;
do not worry, we were looking forward to the possibility of integrating apsscheduler given the great work you are doing and the need of being able of monitoring the job from failures.

sadly we will have still to go for a custom implementation because we will be stuck with python 2.7 for some time and in general we can use eventually use only the apscheduler packaged in ubuntu trusty/xenial.

**Comment by agronholm** [comment]
You could easily implement a custom executor that runs jobs directly in the reactor thread. In fact, that makes me wonder why I'm not doing that – providing an alternate executor that does this, even if it's not the default one.

**Comment by agronholm** [comment]
Thinking more about it, I'm not really sure if it's easy but it's far less work than implementing all those monitoring etc. features all by yourselves.

**Comment by evilaliv3** [comment]
the basic custom implementation that we use is the following: https://github.com/globaleaks/GlobaLeaks/blob/master/backend/globaleaks/jobs/base.py

the main issue is not be able to stop something that maybe can be stuck into the reactor, but this is mostly an issue with twisted that i think is not solvable in any way.

**Comment by agronholm** [comment]
So is your problem that the reactor could be stuck running code that's blocking everything else and you can't stop it?

**Comment by agronholm** [comment]
I didn't realize Ubuntu had such an ancient version of APScheduler. Why do you restrict yourselves to OS provided packages?
