### ISSUE TITLE
Using TornadoScheduler and Motor

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#98]
Originally reported by: **Dmitry Zhukov (Bitbucket: [dzhukov89](http://bitbucket.org/dzhukov89), GitHub: [dzhukov89](http://github.com/dzhukov89))**

----------------------------------------

Hi all!

This using TornadoScheduler below doesn't work

```
#!python

import motor
import tornado
class MyClass(object):

    def __init__(self):
        self.db = motor.MotorClient()['my_db']
        self.my_col = self.db['my_collection']

    @tornado.gen.coroutine
    def doSmthng1(self):
        print('start1')
        yield self.my_col.insert({'test': '1'})
        print('finish1')

def main():
    my_class_item = MyClass()
    ioloop = tornado.ioloop.IOLoop.instance()
    scheduler = TornadoScheduler()

    job2 = scheduler.add_job(my_class_item.doSmthng1, 'cron', second='*/5', id="cron_job")
    scheduler.start()
    ioloop.start()

if __name__ == "__main__":
    main()
```

When the job is start, I get an error:
```
#!python

ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f4c5eb35d08>, <tornado.concurrent.Future object at 0x7f4c5eb31f28>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
greenlet.error: cannot switch to a different thread
```
It stops at the line:

```
#!python
yield self.my_col.insert({'test': '1'})
```
What's wrong?

----------------------------------------
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/98

**Comment by agronholm** [comment]
A proper workaround for running a coroutine function from a worker thread would be to decorate the function with this:
```
from functools import wraps
from concurrent.futures import Future

from tornado.ioloop import IOLoop

def run_from_thread(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        return IOLoop.current().run_sync(func(*args, **kwargs))
    return wrapper
```

Disclaimer: I did not test this code.

**Comment by agronholm** [comment]
Hm, it looks like run_sync() will not work. It was designed for a different purpose. I'm looking for an alternative.

**Comment by anirbanroydas** [comment]
@agronholm `IOLoop.run_sync()` starts a loop, runs the coroutine, and stops the loop.
It will not work which you already mentioned.

What if I am using `GeventExecuter`? Will it work? 

Also, if you come with an alternative, or if there would be any, will it work with `GeventExecuter` or do we have to use the `ThreadPoolExecuter`?

**Comment by agronholm** [comment]
Are you able to choose any executor you like? Your application code doesn't run on top of Tornado then?

**Comment by anirbanroydas** [comment]
@agronholm No No. It does run on Tornado. What I am asking is if suppose I change my `tornado coroutines` to normal function with basic blocking calls, since tornado can have both coroutine style non-blocking methods and a general methods without any `gen.coroutine` decorator. 

So what I am asking is will `GeventExecuter` be okay in that case? Since `Gevent` can spawn **green threads** for each blocking methods in general.

And if suppose `GeventExecuter` is not a better alternative to `coroutines`, then do let me know of the  **_coroutine alternative_**, since the above code will not work because of `run_sync()`.

**Comment by agronholm** [comment]
Gevent and Tornado don't mix. You can try but you'll fail.

I am writing an alternate solution now. With asyncio I could almost write one blindfolded but it's been a while since I've used Tornado.

**Comment by agronholm** [comment]
I updated the snippet above. Hope it works for you.

**Comment by anirbanroydas** [comment]
Thanks a lot @agronholm . I will check it now and intimate about the same.

**Comment by agronholm** [comment]
Adding native coroutine support is as far as I'm willing to go for this. I tried to support generator based coros too but it was too painful.
